# -*- coding: cp1254 -*-
from header_common import *
from header_operations import *
from module_constants import *
from header_parties import *
from header_skills import *
from header_mission_templates import *
from header_items import *
from header_triggers import *
from header_terrain_types import *
from header_music import *
from header_map_icons import *
from ID_animations import *

get_imod_name_string_scripts = [
("get_imod_name_string",
    [
      (store_script_param, ":imod", 1),
      (assign, ":str_id", "@imod_plain"),
      (try_begin),
        (eq, ":imod", imod_cracked), (assign, ":str_id", "@imod_cracked"),
      (else_try),
        (eq, ":imod", imod_rusty), (assign, ":str_id", "@imod_rusty"),
      (else_try),
        (eq, ":imod", imod_bent), (assign, ":str_id", "@imod_bent"),
      (else_try),
        (eq, ":imod", imod_chipped), (assign, ":str_id", "@imod_chipped"),
      (else_try),
        (eq, ":imod", imod_battered), (assign, ":str_id", "@imod_battered"),
      (else_try),
        (eq, ":imod", imod_poor), (assign, ":str_id", "@imod_poor"),
      (else_try),
        (eq, ":imod", imod_crude), (assign, ":str_id", "@imod_crude"),
      (else_try),
        (eq, ":imod", imod_old), (assign, ":str_id", "@imod_old"),
      (else_try),
        (eq, ":imod", imod_cheap), (assign, ":str_id", "@imod_cheap"),
      (else_try),
        (eq, ":imod", imod_fine), (assign, ":str_id", "@imod_fine"),
      (else_try),
        (eq, ":imod", imod_well_made), (assign, ":str_id", "@imod_well_made"),
      (else_try),
        (eq, ":imod", imod_sharp), (assign, ":str_id", "@imod_sharp"),
      (else_try),
        (eq, ":imod", imod_balanced), (assign, ":str_id", "@imod_balanced"),
      (else_try),
        (eq, ":imod", imod_tempered), (assign, ":str_id", "@imod_tempered"),
      (else_try),
        (eq, ":imod", imod_deadly), (assign, ":str_id", "@imod_deadly"),
      (else_try),
        (eq, ":imod", imod_exquisite), (assign, ":str_id", "@imod_exquisite"),
      (else_try),
        (eq, ":imod", imod_masterwork), (assign, ":str_id", "@imod_masterwork"),
      (else_try),
        (eq, ":imod", imod_heavy), (assign, ":str_id", "@imod_heavy"),
      (else_try),
        (eq, ":imod", imod_strong), (assign, ":str_id", "@imod_strong"),
      (else_try),
        (eq, ":imod", imod_powerful), (assign, ":str_id", "@imod_powerful"),
      (else_try),
        (eq, ":imod", imod_tattered), (assign, ":str_id", "@imod_tattered"),
      (else_try),
        (eq, ":imod", imod_ragged), (assign, ":str_id", "@imod_ragged"),
      (else_try),
        (eq, ":imod", imod_rough), (assign, ":str_id", "@imod_rough"),
      (else_try),
        (eq, ":imod", imod_sturdy), (assign, ":str_id", "@imod_sturdy"),
      (else_try),
        (eq, ":imod", imod_thick), (assign, ":str_id", "@imod_thick"),
      (else_try),
        (eq, ":imod", imod_hardened), (assign, ":str_id", "@imod_hardened"),
      (else_try),
        (eq, ":imod", imod_reinforced), (assign, ":str_id", "@imod_reinforced"),
      (else_try),
        (eq, ":imod", imod_superb), (assign, ":str_id", "@imod_superb"),
      (else_try),
        (eq, ":imod", imod_lordly), (assign, ":str_id", "@imod_lordly"),
      (else_try),
        (eq, ":imod", imod_lame), (assign, ":str_id", "@imod_lame"),
      (else_try),
        (eq, ":imod", imod_swaybacked), (assign, ":str_id", "@imod_swaybacked"),
      (else_try),
        (eq, ":imod", imod_stubborn), (assign, ":str_id", "@imod_stubborn"),
      (else_try),
        (eq, ":imod", imod_timid), (assign, ":str_id", "@imod_timid"),
      (else_try),
        (eq, ":imod", imod_meek), (assign, ":str_id", "@imod_meek"),
      (else_try),
        (eq, ":imod", imod_spirited), (assign, ":str_id", "@imod_spirited"),
      (else_try),
        (eq, ":imod", imod_champion), (assign, ":str_id", "@imod_champion"),
      (else_try),
        (eq, ":imod", imod_fresh), (assign, ":str_id", "@imod_fresh"),
      (else_try),
        (eq, ":imod", imod_day_old), (assign, ":str_id", "@imod_day_old"),
      (else_try),
        (eq, ":imod", imod_two_day_old), (assign, ":str_id", "@imod_two_day_old"),
      (else_try),
        (eq, ":imod", imod_smelling), (assign, ":str_id", "@imod_smelling"),
      (else_try),
        (eq, ":imod", imod_rotten), (assign, ":str_id", "@imod_rotten"),
      (else_try),
        (eq, ":imod", imod_large_bag), (assign, ":str_id", "@imod_large_bag"),
      (try_end),
      (try_begin),
        (eq, ":imod", imod_plain),
        (str_store_string, s0, "@imod_plain_label"),
      (else_try),
        (str_store_string, s0, ":str_id"),
      (try_end),
      (assign, reg0, ":str_id"),
    ])
]
