# -*- coding: cp1254 -*-
import string
from header_common import *
from header_presentations import *
from header_mission_templates import *
from ID_meshes import *
from header_operations import *
from header_triggers import *
#SB: import skills from ID_skills import *
from module_constants import *
##diplomacy start+ Import for use with terrain advantage
from header_terrain_types import *
from module_items import *
#SB : import colors
from module_factions import *
from header_items import *
##diplomacy end
from compiler import *

all_items = ("all_items", 0, 0, [
    (ti_on_presentation_load,
      [
        (presentation_set_duration, 999999),
        (set_fixed_point_multiplier, 1000),

        (create_mesh_overlay, reg1, "mesh_note_window"),
        (position_set_x, pos1, 0),
        (position_set_y, pos1, 0),
        (overlay_set_position, reg1, pos1),

        (create_text_overlay, reg1, "@Category:", tf_left_align),
        (position_set_x, pos1, 20),
        (position_set_y, pos1, 670),
        (overlay_set_position, reg1, pos1),
        (create_combo_label_overlay, "$g_presentation_obj_1"),
        (position_set_x, pos1, 300),
        (position_set_y, pos1, 670),
        (overlay_set_position, "$g_presentation_obj_1", pos1),
        (overlay_add_item, "$g_presentation_obj_1", "@One-Handed"),
        (overlay_add_item, "$g_presentation_obj_1", "@Two-Handed"),
        (overlay_add_item, "$g_presentation_obj_1", "@Polearms"),
        (overlay_add_item, "$g_presentation_obj_1", "@Ranged"),
        (overlay_add_item, "$g_presentation_obj_1", "@Throwables"),
        (overlay_add_item, "$g_presentation_obj_1", "@Shields"),
        (overlay_add_item, "$g_presentation_obj_1", "@Head Armor"),
        (overlay_add_item, "$g_presentation_obj_1", "@Body Armor"),
        (overlay_add_item, "$g_presentation_obj_1", "@Foot Armor"),
        (overlay_add_item, "$g_presentation_obj_1", "@Hand Armor"),
        (overlay_add_item, "$g_presentation_obj_1", "@Horses"),
        (overlay_add_item, "$g_presentation_obj_1", "@Goods"),
        (overlay_add_item, "$g_presentation_obj_1", "@Other"),
        (overlay_set_val, "$g_presentation_obj_1", "$temp"),

        ## back
        (create_game_button_overlay, "$g_presentation_obj_5", "@Done"),
        (position_set_x, pos1, 910),
        (position_set_y, pos1, 12),
        (overlay_set_position, "$g_presentation_obj_5", pos1),

        # item 0, preview
        ## item slot
        (create_image_button_overlay, reg1, "mesh_mp_inventory_choose", "mesh_mp_inventory_choose"),
        (position_set_x, pos1, 2240),
        (position_set_y, pos1, 2240),
        (overlay_set_size, reg1, pos1),
        ## item frame position
        (position_set_x, pos1, 690),
        (position_set_y, pos1, 305),
        (overlay_set_position, reg1, pos1),
        (troop_set_slot, "trp_temp_array_a", 0, reg1),
        ## item
        (create_mesh_overlay_with_item_id, reg1, 0),
        (position_set_x, pos1, 2800),
        (position_set_y, pos1, 2800),
        (overlay_set_size, reg1, pos1),
        ## item position
        (position_set_x, pos1, 690+140),
        (position_set_y, pos1, 305+140),
        (overlay_set_position, reg1, pos1),
        (troop_set_slot, "trp_temp_array_b", 0, reg1),
        (troop_set_slot, "trp_temp_array_c", 0, 0),
        ## txt
        (create_text_overlay, reg1, "@Preview: ", tf_left_align),
        (position_set_x, pos1, 720),
        (position_set_y, pos1, 600),
        (overlay_set_position, reg1, pos1),

        ## items @items
        (str_clear, s0),
        (create_text_overlay, "$g_presentation_obj_6", s0, tf_scrollable),
        (position_set_x, pos1, 20),
        (position_set_y, pos1, 100),
        (overlay_set_position, "$g_presentation_obj_6", pos1),
        (position_set_x, pos1, 645),
        (position_set_y, pos1, 562),
        (overlay_set_area_size, "$g_presentation_obj_6", pos1),
        (set_container_overlay, "$g_presentation_obj_6"),

        (assign, ":num_items", len(items)),
        (assign, "$temp_2", 0),
        ## types
        (try_for_range, ":item_no", 1, ":num_items"),
          (item_get_type, ":type", ":item_no"),
          (assign, ":cat", 12),
          (try_begin),
            (eq, ":type", itp_type_one_handed_wpn), (assign, ":cat", 0),
          (else_try),
            (eq, ":type", itp_type_two_handed_wpn), (assign, ":cat", 1),
          (else_try),
            (eq, ":type", itp_type_polearm), (assign, ":cat", 2),
          (else_try),
            (this_or_next|eq, ":type", itp_type_bow),
            (this_or_next|eq, ":type", itp_type_crossbow),
            (this_or_next|eq, ":type", itp_type_arrows),
            (this_or_next|eq, ":type", itp_type_bolts),
            (this_or_next|eq, ":type", itp_type_bullets),
            (this_or_next|eq, ":type", itp_type_pistol),
            (eq, ":type", itp_type_musket), (assign, ":cat", 3),
          (else_try),
            (eq, ":type", itp_type_thrown), (assign, ":cat", 4),
          (else_try),
            (eq, ":type", itp_type_shield), (assign, ":cat", 5),
          (else_try),
            (eq, ":type", itp_type_head_armor), (assign, ":cat", 6),
          (else_try),
            (eq, ":type", itp_type_body_armor), (assign, ":cat", 7),
          (else_try),
            (eq, ":type", itp_type_foot_armor), (assign, ":cat", 8),
          (else_try),
            (eq, ":type", itp_type_hand_armor), (assign, ":cat", 9),
          (else_try),
            (eq, ":type", itp_type_horse), (assign, ":cat", 10),
          (else_try),
            (eq, ":type", itp_type_goods), (assign, ":cat", 11),
          (try_end),
          ## manual reclassification overrides (display only; cosmetic other-mod items -> Other)
          (try_begin),
            (eq, ":item_no", "itm_banner_background1"), (assign, ":cat", 12),
          (else_try),
            (eq, ":item_no", "itm_banner_background2"), (assign, ":cat", 12),
          (else_try),
            (eq, ":item_no", "itm_torch"), (assign, ":cat", 12),
          (else_try),
            (eq, ":item_no", "itm_offhand_dagger"), (assign, ":cat", 12),
          (else_try),
            (eq, ":item_no", "itm_untitled"), (assign, ":cat", 12), # invishead
          (else_try),
            (eq, ":item_no", "itm_nothing_head"), (assign, ":cat", 12),
          (else_try),
            (eq, ":item_no", "itm_facial"), (assign, ":cat", 12),
          (else_try),
            (call_script, "script_get_item_capability_with_imod", ":item_no", -1),
            (assign, ":cap", reg0),
            (le, ":cap", 0),
            (neq, ":type", itp_type_goods), (assign, ":cat", 12), # non-goods cosmetics (capability <=0) -> Other
           (else_try),
            (eq, ":type", itp_type_goods),
            (is_between, ":item_no", "itm_ca1_skin_0", "itm_future_gauntlets01"), (assign, ":cat", 12), # cosmetic goods (ca* block) -> Other
          (try_end),
          (eq, ":cat", "$temp"),
          (val_add, "$temp_2", 1),
        (try_end),

        # items
        (store_div, ":height", "$temp_2", 8),
        (store_mod, ":offset", "$temp_2", 8),
        (val_min, ":offset", 1),
        (val_add, ":height", ":offset"),
        (store_mul, ":pos_y", ":height", 80),
        (val_sub, ":pos_y", 80),
        (assign, ":pos_x", 0),
        (assign, ":slot_no", 1),
        (assign, ":first_item", 0),
        (try_for_range, ":item_no", 1, ":num_items"),
          (item_get_type, ":type", ":item_no"),
          (assign, ":cat", 12),
          (try_begin),
            (eq, ":type", itp_type_one_handed_wpn), (assign, ":cat", 0),
          (else_try),
            (eq, ":type", itp_type_two_handed_wpn), (assign, ":cat", 1),
          (else_try),
            (eq, ":type", itp_type_polearm), (assign, ":cat", 2),
          (else_try),
            (this_or_next|eq, ":type", itp_type_bow),
            (this_or_next|eq, ":type", itp_type_crossbow),
            (this_or_next|eq, ":type", itp_type_arrows),
            (this_or_next|eq, ":type", itp_type_bolts),
            (this_or_next|eq, ":type", itp_type_bullets),
            (this_or_next|eq, ":type", itp_type_pistol),
            (eq, ":type", itp_type_musket), (assign, ":cat", 3),
          (else_try),
            (eq, ":type", itp_type_thrown), (assign, ":cat", 4),
          (else_try),
            (eq, ":type", itp_type_shield), (assign, ":cat", 5),
          (else_try),
            (eq, ":type", itp_type_head_armor), (assign, ":cat", 6),
          (else_try),
            (eq, ":type", itp_type_body_armor), (assign, ":cat", 7),
          (else_try),
            (eq, ":type", itp_type_foot_armor), (assign, ":cat", 8),
          (else_try),
            (eq, ":type", itp_type_hand_armor), (assign, ":cat", 9),
          (else_try),
            (eq, ":type", itp_type_horse), (assign, ":cat", 10),
          (else_try),
            (eq, ":type", itp_type_goods), (assign, ":cat", 11),
          (try_end),
          ## manual reclassification overrides (display only; cosmetic other-mod items -> Other)
          (try_begin),
            (eq, ":item_no", "itm_banner_background1"), (assign, ":cat", 12),
          (else_try),
            (eq, ":item_no", "itm_banner_background2"), (assign, ":cat", 12),
          (else_try),
            (eq, ":item_no", "itm_torch"), (assign, ":cat", 12),
          (else_try),
            (eq, ":item_no", "itm_offhand_dagger"), (assign, ":cat", 12),
          (else_try),
            (eq, ":item_no", "itm_untitled"), (assign, ":cat", 12), # invishead
          (else_try),
            (eq, ":item_no", "itm_nothing_head"), (assign, ":cat", 12),
          (else_try),
            (eq, ":item_no", "itm_facial"), (assign, ":cat", 12),
          (else_try),
            (call_script, "script_get_item_capability_with_imod", ":item_no", -1),
            (assign, ":cap", reg0),
            (le, ":cap", 0),
            (neq, ":type", itp_type_goods), (assign, ":cat", 12), # non-goods cosmetics (capability <=0) -> Other
           (else_try),
            (eq, ":type", itp_type_goods),
            (is_between, ":item_no", "itm_ca1_skin_0", "itm_future_gauntlets01"), (assign, ":cat", 12), # cosmetic goods (ca* block) -> Other
          (try_end),
          (eq, ":cat", "$temp"),
          (try_begin),
            (eq, ":first_item", 0),
            (assign, ":first_item", ":item_no"),
          (try_end),
          ## item slot
          (create_image_button_overlay, reg1, "mesh_mp_inventory_choose", "mesh_mp_inventory_choose"),
          (position_set_x, pos1, 640),
          (position_set_y, pos1, 640),
          (overlay_set_size, reg1, pos1),
          (position_set_x, pos1, ":pos_x"),
          (position_set_y, pos1, ":pos_y"),
          (overlay_set_position, reg1, pos1),
          (troop_set_slot, "trp_temp_array_a", ":slot_no", reg1),
          ## item
          (create_mesh_overlay_with_item_id, reg1, ":item_no"),
          (position_set_x, pos1, 800),
          (position_set_y, pos1, 800),
          (overlay_set_size, reg1, pos1),
          (store_add, ":item_x", ":pos_x", 40),
          (store_add, ":item_y", ":pos_y", 40),
          (position_set_x, pos1, ":item_x"),
          (position_set_y, pos1, ":item_y"),
          (overlay_set_position, reg1, pos1),
          (troop_set_slot, "trp_temp_array_b", ":slot_no", reg1),
          (troop_set_slot, "trp_temp_array_c", ":slot_no", ":item_no"),
          (val_add, ":pos_x", 80),
          (val_add, ":slot_no", 1),
          (try_begin),
            (ge, ":pos_x", 640),
            (assign, ":pos_x", 0),
            (val_sub, ":pos_y", 80),
          (try_end),
        (try_end),

        (set_container_overlay, -1),

        ## cheat panel: category / quantity / modifier selects + get button (only when cheat menu enabled)
        (try_begin),
          (ge, "$cheat_mode", 1),
          (assign, "$g_all_items_imod", imod_plain),
          (assign, "$g_all_items_qty", 1),
          (assign, "$g_presentation_obj_8", -1),
          (assign, "$g_modifier_idx", 0),
          (assign, "$g_modifier_count", 0),
          (assign, "$g_last_sel_item", -1),

        ## quantity select (click to cycle 1..25) -- bottom of preview
          (assign, reg0, "$g_all_items_qty"),
          (str_store_string, s0, "@Quantity: {reg0}"),
          (create_game_button_overlay, "$g_presentation_obj_2", "@Quantity: 1"),
          (position_set_x, pos1, 840), # single cycling button -- move freely
          (position_set_y, pos1, 160),
          (overlay_set_position, "$g_presentation_obj_2", pos1),
          (overlay_set_text, "$g_presentation_obj_2", s0),
  
          ## get button -- bottom of preview
          (create_game_button_overlay, "$g_presentation_obj_4", "@Get"),
          (position_set_x, pos1, 840),
          (position_set_y, pos1, 100),
          (overlay_set_position, "$g_presentation_obj_4", pos1),

          ## modifier select (click to cycle through valid modifiers for the current item)
          (assign, ":m_idx", 0),
          ## plain (no modifier) is always available as the first entry
          (troop_set_slot, "trp_temp_array_d", 0, imod_plain),
          (val_add, ":m_idx", 1),
          (try_for_range, ":imod", 1, 43),
            (call_script, "script_item_has_modifier", ":first_item", ":imod"),
            (eq, reg0, 1),
            (troop_set_slot, "trp_temp_array_d", ":m_idx", ":imod"),
            (val_add, ":m_idx", 1),
          (try_end),
          (assign, "$g_modifier_count", ":m_idx"),
          (assign, "$g_modifier_idx", 0),
          (troop_get_slot, ":imod", "trp_temp_array_d", 0),
          (assign, "$g_all_items_imod", ":imod"),
          (create_game_button_overlay, "$g_presentation_obj_8", "@Get"),
          (position_set_x, pos1, 790),
          (position_set_y, pos1, 230),
          (overlay_set_position, "$g_presentation_obj_8", pos1),
          (position_set_x, pos1, 240),
          (position_set_y, pos1, 40),
          (overlay_set_size, "$g_presentation_obj_8", pos1),
          (str_store_string, s0, "@Plain"),
          (str_store_string, s0, "@Quality: {s0}"),
          (overlay_set_text, "$g_presentation_obj_8", s0),
        (try_end),

        ## items
        ]),

    (ti_on_presentation_mouse_enter_leave,
      [
      (store_trigger_param_1, ":object"),
      (store_trigger_param_2, ":enter_leave"),

      (store_add, ":upper_bound", "$temp_2", 1),
      (try_begin),
        (eq, ":enter_leave", 0),
        (try_for_range, ":slot_no", 0, ":upper_bound"),
          (troop_slot_eq, "trp_temp_array_a", ":slot_no", ":object"),
          (troop_get_slot, ":item_no", "trp_temp_array_c", ":slot_no"),
          (neq, ":item_no", 0),
          (close_item_details),
          (troop_get_slot, ":target_obj", "trp_temp_array_b", ":slot_no"),
          (overlay_get_position, pos0, ":target_obj"),
          (show_item_details, ":item_no", pos0, 100),
          (assign, "$g_current_opened_item_details", ":slot_no"),
        (try_end),
      (else_try),
        (try_for_range, ":slot_no", 0, ":upper_bound"),
          (troop_slot_eq, "trp_temp_array_a", ":slot_no", ":object"),
          (try_begin),
            (eq, "$g_current_opened_item_details", ":slot_no"),
            (close_item_details),
          (try_end),
        (try_end),
      (try_end),
    ]),

    (ti_on_presentation_event_state_change,
      [
        (store_trigger_param_1, ":object"),
        (store_trigger_param_2, ":value"),

        (set_fixed_point_multiplier, 1000),
        # create new item overlay to cover item in slot_0
        (store_add, ":upper_bound", "$temp_2", 1),
        (try_for_range, ":slot_no", 0, ":upper_bound"),
          (neq, ":slot_no", 0),
          (troop_slot_eq, "trp_temp_array_a", ":slot_no", ":object"),
          (troop_get_slot, ":item_no", "trp_temp_array_c", ":slot_no"),
          (troop_get_slot, ":target_obj", "trp_temp_array_b", 0),
          (overlay_set_display, ":target_obj", 0),
          ## new item overlay
          (create_mesh_overlay_with_item_id, reg1, ":item_no"),
          (position_set_x, pos1, 2800),
          (position_set_y, pos1, 2800),
          (overlay_set_size, reg1, pos1),
          (position_set_x, pos1, 690+140),
          (position_set_y, pos1, 305+140),
          (overlay_set_position, reg1, pos1),
          (troop_set_slot, "trp_temp_array_b", 0, reg1),
          (troop_set_slot, "trp_temp_array_c", 0, ":item_no"),
        (try_end),

        ## rebuild modifier select for the selected item (only when it changes)
        (try_begin),
          (ge, "$cheat_mode", 1),
          (troop_get_slot, ":sel_item", "trp_temp_array_c", 0),
          (neq, ":sel_item", "$g_last_sel_item"),
            (assign, "$g_last_sel_item", ":sel_item"),
            (assign, ":m_idx", 0),
          ## plain (no modifier) is always available as the first entry
          (troop_set_slot, "trp_temp_array_d", 0, imod_plain),
          (val_add, ":m_idx", 1),
          (try_for_range, ":imod", 1, 43),
            (call_script, "script_item_has_modifier", ":sel_item", ":imod"),
            (eq, reg0, 1),
            (troop_set_slot, "trp_temp_array_d", ":m_idx", ":imod"),
            (val_add, ":m_idx", 1),
          (try_end),
          (assign, "$g_modifier_count", ":m_idx"),
          (assign, "$g_modifier_idx", 0),
          (troop_get_slot, ":imod", "trp_temp_array_d", 0),
          (assign, "$g_all_items_imod", ":imod"),
          (str_store_string, s0, "@Plain"),
          (str_store_string, s0, "@Quality: {s0}"),
          (overlay_set_text, "$g_presentation_obj_8", s0),
        (try_end),

        (try_begin),
          (eq, ":object", "$g_presentation_obj_1"),
          (assign, "$temp", ":value"),
          (start_presentation, "prsnt_all_items"),
        (else_try),
          (eq, ":object", "$g_presentation_obj_5"),
          (presentation_set_duration, 0),
        (else_try),
          (eq, ":object", "$g_presentation_obj_2"),
          (val_add, "$g_all_items_qty", 1),
          (try_begin),
            (gt, "$g_all_items_qty", 25),
            (assign, "$g_all_items_qty", 1),
          (try_end),
          (assign, reg0, "$g_all_items_qty"),
          (str_store_string, s0, "@Quantity: {reg0}"),
          (overlay_set_text, "$g_presentation_obj_2", s0),
        (else_try),
          (eq, ":object", "$g_presentation_obj_4"),
          (troop_get_slot, ":get_item", "trp_temp_array_c", 0),
          (try_begin),
            (neq, ":get_item", 0),
            (try_for_range, ":k", 0, "$g_all_items_qty"),
              (troop_add_item, "trp_player", ":get_item", "$g_all_items_imod"),
            (try_end),
          (try_end),
        (else_try),
          (try_begin),
            (ge, "$cheat_mode", 1),
            (eq, ":object", "$g_presentation_obj_8"),
            (val_add, "$g_modifier_idx", 1),
            (try_begin),
              (ge, "$g_modifier_idx", "$g_modifier_count"),
              (assign, "$g_modifier_idx", 0),
            (try_end),
            (troop_get_slot, ":imod", "trp_temp_array_d", "$g_modifier_idx"),
            (assign, "$g_all_items_imod", ":imod"),
            (try_begin),
              (eq, ":imod", imod_plain), (str_store_string, s0, "@Plain"),
            (else_try),
              (eq, ":imod", imod_cracked), (str_store_string, s0, "@Cracked"),
            (else_try),
              (eq, ":imod", imod_rusty), (str_store_string, s0, "@Rusty"),
            (else_try),
              (eq, ":imod", imod_bent), (str_store_string, s0, "@Bent"),
            (else_try),
              (eq, ":imod", imod_chipped), (str_store_string, s0, "@Chipped"),
            (else_try),
              (eq, ":imod", imod_battered), (str_store_string, s0, "@Battered"),
            (else_try),
              (eq, ":imod", imod_poor), (str_store_string, s0, "@Poor"),
            (else_try),
              (eq, ":imod", imod_crude), (str_store_string, s0, "@Crude"),
            (else_try),
              (eq, ":imod", imod_old), (str_store_string, s0, "@Old"),
            (else_try),
              (eq, ":imod", imod_cheap), (str_store_string, s0, "@Cheap"),
            (else_try),
              (eq, ":imod", imod_fine), (str_store_string, s0, "@Fine"),
            (else_try),
              (eq, ":imod", imod_well_made), (str_store_string, s0, "@Well Made"),
            (else_try),
              (eq, ":imod", imod_sharp), (str_store_string, s0, "@Sharp"),
            (else_try),
              (eq, ":imod", imod_balanced), (str_store_string, s0, "@Balanced"),
            (else_try),
              (eq, ":imod", imod_tempered), (str_store_string, s0, "@Tempered"),
            (else_try),
              (eq, ":imod", imod_deadly), (str_store_string, s0, "@Deadly"),
            (else_try),
              (eq, ":imod", imod_exquisite), (str_store_string, s0, "@Exquisite"),
            (else_try),
              (eq, ":imod", imod_masterwork), (str_store_string, s0, "@Masterwork"),
            (else_try),
              (eq, ":imod", imod_heavy), (str_store_string, s0, "@Heavy"),
            (else_try),
              (eq, ":imod", imod_strong), (str_store_string, s0, "@Strong"),
            (else_try),
              (eq, ":imod", imod_powerful), (str_store_string, s0, "@Powerful"),
            (else_try),
              (eq, ":imod", imod_tattered), (str_store_string, s0, "@Tattered"),
            (else_try),
              (eq, ":imod", imod_ragged), (str_store_string, s0, "@Ragged"),
            (else_try),
              (eq, ":imod", imod_rough), (str_store_string, s0, "@Rough"),
            (else_try),
              (eq, ":imod", imod_sturdy), (str_store_string, s0, "@Sturdy"),
            (else_try),
              (eq, ":imod", imod_thick), (str_store_string, s0, "@Thick"),
            (else_try),
              (eq, ":imod", imod_hardened), (str_store_string, s0, "@Hardened"),
            (else_try),
              (eq, ":imod", imod_reinforced), (str_store_string, s0, "@Reinforced"),
            (else_try),
              (eq, ":imod", imod_superb), (str_store_string, s0, "@Superb"),
            (else_try),
              (eq, ":imod", imod_lordly), (str_store_string, s0, "@Lordly"),
            (else_try),
              (eq, ":imod", imod_lame), (str_store_string, s0, "@Lame"),
            (else_try),
              (eq, ":imod", imod_swaybacked), (str_store_string, s0, "@Swaybacked"),
            (else_try),
              (eq, ":imod", imod_stubborn), (str_store_string, s0, "@Stubborn"),
            (else_try),
              (eq, ":imod", imod_timid), (str_store_string, s0, "@Timid"),
            (else_try),
              (eq, ":imod", imod_meek), (str_store_string, s0, "@Meek"),
            (else_try),
              (eq, ":imod", imod_spirited), (str_store_string, s0, "@Spirited"),
            (else_try),
              (eq, ":imod", imod_champion), (str_store_string, s0, "@Champion"),
            (else_try),
              (eq, ":imod", imod_fresh), (str_store_string, s0, "@Fresh"),
            (else_try),
              (eq, ":imod", imod_day_old), (str_store_string, s0, "@Day-old"),
            (else_try),
              (eq, ":imod", imod_two_day_old), (str_store_string, s0, "@Two Days-old"),
            (else_try),
              (eq, ":imod", imod_smelling), (str_store_string, s0, "@Smelling"),
            (else_try),
              (eq, ":imod", imod_rotten), (str_store_string, s0, "@Rotten"),
            (else_try),
              (eq, ":imod", imod_large_bag), (str_store_string, s0, "@Large Bag of"),
            (try_end),
            (str_store_string, s0, "@Quality: {s0}"),
            (overlay_set_text, "$g_presentation_obj_8", s0),
          (try_end),
        (try_end),
    ]),
  ])
