# -*- coding: cp1254 -*-
# Auto-generated - do not edit

from presentations.reports.prsnt_all_items import all_items
from presentations.prsnt_arena_training import arena_training
from presentations.prsnt_auto_trade_options import auto_trade_options
from presentations.prsnt_bank import bank
from presentations.reports.prsnt_bank_quickview import bank_quickview
from presentations.prsnt_banner_background_selection import banner_background_selection
from presentations.prsnt_banner_charge_positioning import banner_charge_positioning
from presentations.prsnt_banner_charge_selection import banner_charge_selection
from presentations.prsnt_banner_flag_map_type_selection import banner_flag_map_type_selection
from presentations.prsnt_banner_flag_type_selection import banner_flag_type_selection
from presentations.prsnt_banner_selection import banner_selection
from presentations.prsnt_battle import battle
from presentations.minigames.prsnt_blackjack import blackjack
from presentations.reports.prsnt_budget_report import budget_report
from presentations.prsnt_change_color import change_color
from presentations.prsnt_color_selection import color_selection
from presentations.reports.prsnt_companion_overview import companion_overview
from presentations.prsnt_custom_banner import custom_banner
from presentations.prsnt_customize_armor import customize_armor
from presentations.prsnt_deposit_withdraw_money import deposit_withdraw_money
from presentations.minigames.prsnt_dices_game import dices_game
from presentations.prsnt_dplmc_auto_sell_options import dplmc_auto_sell_options
from presentations.prsnt_dplmc_autoloot_upgrade_management import dplmc_autoloot_upgrade_management
from presentations.prsnt_dplmc_peace_terms import dplmc_peace_terms
from presentations.prsnt_dplmc_policy_management import dplmc_policy_management
from presentations.prsnt_dplmc_set_vassal_title import dplmc_set_vassal_title
from presentations.prsnt_dplmc_shopping_list_of_food import dplmc_shopping_list_of_food
from presentations.camp.prsnt_food_options import food_options
from presentations.camp.prsnt_formation_mod_option import formation_mod_option
from presentations.prsnt_game_before_quit import game_before_quit
from presentations.prsnt_game_credits import game_credits
from presentations.prsnt_game_custom_battle_designer import game_custom_battle_designer
from presentations.multiplayer.prsnt_game_multiplayer_admin_panel import game_multiplayer_admin_panel
from presentations.prsnt_game_profile_banner_selection import game_profile_banner_selection
from presentations.reports.prsnt_jrider_character_relation_report import jrider_character_relation_report
from presentations.reports.prsnt_jrider_faction_relations_report import jrider_faction_relations_report
from presentations.prsnt_manage_inventory import manage_inventory
from presentations.prsnt_marshall_selection import marshall_selection
from presentations.prsnt_mini_map import mini_map
from presentations.prsnt_mini_map_bar import mini_map_bar
from presentations.prsnt_modify_slots import modify_slots
from presentations.multiplayer.prsnt_multiplayer_destructible_targets_display import multiplayer_destructible_targets_display
from presentations.multiplayer.prsnt_multiplayer_duel_start_counter import multiplayer_duel_start_counter
from presentations.multiplayer.prsnt_multiplayer_escape_menu import multiplayer_escape_menu
from presentations.multiplayer.prsnt_multiplayer_flag_projection_display import multiplayer_flag_projection_display
from presentations.multiplayer.prsnt_multiplayer_flag_projection_display_bt import multiplayer_flag_projection_display_bt
from presentations.multiplayer.prsnt_multiplayer_item_select import multiplayer_item_select
from presentations.multiplayer.prsnt_multiplayer_message_1 import multiplayer_message_1
from presentations.multiplayer.prsnt_multiplayer_message_2 import multiplayer_message_2
from presentations.multiplayer.prsnt_multiplayer_message_3 import multiplayer_message_3
from presentations.multiplayer.prsnt_multiplayer_poll import multiplayer_poll
from presentations.multiplayer.prsnt_multiplayer_poll_menu import multiplayer_poll_menu
from presentations.multiplayer.prsnt_multiplayer_respawn_time_counter import multiplayer_respawn_time_counter
from presentations.multiplayer.prsnt_multiplayer_round_time_counter import multiplayer_round_time_counter
from presentations.multiplayer.prsnt_multiplayer_show_factions_list import multiplayer_show_factions_list
from presentations.multiplayer.prsnt_multiplayer_show_maps_list import multiplayer_show_maps_list
from presentations.multiplayer.prsnt_multiplayer_show_number_of_bots_list import multiplayer_show_number_of_bots_list
from presentations.multiplayer.prsnt_multiplayer_show_players_list import multiplayer_show_players_list
from presentations.multiplayer.prsnt_multiplayer_stats_chart import multiplayer_stats_chart
from presentations.multiplayer.prsnt_multiplayer_stats_chart_deathmatch import multiplayer_stats_chart_deathmatch
from presentations.multiplayer.prsnt_multiplayer_team_score_display import multiplayer_team_score_display
from presentations.multiplayer.prsnt_multiplayer_team_select import multiplayer_team_select
from presentations.multiplayer.prsnt_multiplayer_troop_select import multiplayer_troop_select
from presentations.multiplayer.prsnt_multiplayer_welcome_message import multiplayer_welcome_message
from presentations.prsnt_name_kingdom import name_kingdom
from presentations.camp.prsnt_order_display import order_display
from presentations.prsnt_redefine_keys import redefine_keys
from presentations.camp.prsnt_retirement import retirement
from presentations.prsnt_sliders import sliders
from presentations.reports.prsnt_spawn_diagnostics import spawn_diagnostics
from presentations.minigames.prsnt_three_card import three_card
from presentations.prsnt_troop_ratio_bar import troop_ratio_bar
from presentations.prsnt_tutorial_show_mouse_movement import tutorial_show_mouse_movement
from presentations.prsnt_world_map import world_map

presentations = [
  all_items,
  arena_training,
  auto_trade_options,
  bank,
  bank_quickview,
  banner_background_selection,
  banner_charge_positioning,
  banner_charge_selection,
  banner_flag_map_type_selection,
  banner_flag_type_selection,
  banner_selection,
  battle,
  blackjack,
  budget_report,
  change_color,
  color_selection,
  companion_overview,
  custom_banner,
  customize_armor,
  deposit_withdraw_money,
  dices_game,
  dplmc_auto_sell_options,
  dplmc_autoloot_upgrade_management,
  dplmc_peace_terms,
  dplmc_policy_management,
  dplmc_set_vassal_title,
  dplmc_shopping_list_of_food,
  food_options,
  formation_mod_option,
  game_before_quit,
  game_credits,
  game_custom_battle_designer,
  game_multiplayer_admin_panel,
  game_profile_banner_selection,
  jrider_character_relation_report,
  jrider_faction_relations_report,
  manage_inventory,
  marshall_selection,
  mini_map,
  mini_map_bar,
  modify_slots,
  multiplayer_destructible_targets_display,
  multiplayer_duel_start_counter,
  multiplayer_escape_menu,
  multiplayer_flag_projection_display,
  multiplayer_flag_projection_display_bt,
  multiplayer_item_select,
  multiplayer_message_1,
  multiplayer_message_2,
  multiplayer_message_3,
  multiplayer_poll,
  multiplayer_poll_menu,
  multiplayer_respawn_time_counter,
  multiplayer_round_time_counter,
  multiplayer_show_factions_list,
  multiplayer_show_maps_list,
  multiplayer_show_number_of_bots_list,
  multiplayer_show_players_list,
  multiplayer_stats_chart,
  multiplayer_stats_chart_deathmatch,
  multiplayer_team_score_display,
  multiplayer_team_select,
  multiplayer_troop_select,
  multiplayer_welcome_message,
  name_kingdom,
  order_display,
  redefine_keys,
  retirement,
  sliders,
  spawn_diagnostics,
  three_card,
  troop_ratio_bar,
  tutorial_show_mouse_movement,
  world_map,
]

