# -*- coding: cp1254 -*-
import string
from header_common import *
from header_presentations import *
from header_mission_templates import *
from ID_meshes import *
from header_operations import *
from header_triggers import *
#SB: import skills from ID_skills import *
from module_constants import *
##diplomacy start+ Import for use with terrain advantage
from header_terrain_types import *
from module_items import *
#SB : import colors
from module_factions import *
from header_items import *
##diplomacy end
from compiler import *

change_color = ("change_color", 0, mesh_load_window, [
    (ti_on_presentation_load,
      [
        (presentation_set_duration, 999999),
        (set_fixed_point_multiplier, 1000),

        (create_combo_button_overlay, "$g_presentation_obj_1"),
        (position_set_x, pos1, 500),
        (position_set_y, pos1, 680),
        (overlay_set_position, "$g_presentation_obj_1", pos1),

        # (try_for_range, ":cur_slot", 0, 9),
          # (troop_get_slot, ":cur_faction", "trp_temp_array_a", ":cur_slot"),
          # (str_store_faction_name, s0, ":cur_faction"),
          # (overlay_add_item, "$g_presentation_obj_1", s0),
        # (try_end),
        # (overlay_set_val, "$g_presentation_obj_1", "$temp"),

        ## name and color
        (try_begin),
          (eq, "$g_presentation_state", recolor_kingdom),

          #maybe not
          (faction_get_slot, ":mesh", "$players_kingdom", slot_faction_banner),
          (create_mesh_overlay, reg0, ":mesh"),
          (overlay_set_position, reg0, pos1),

          # faction list
          (assign, ":slot_no", 0),
          (try_for_range, ":faction", "fac_commoners", "fac_innocents"),
            (troop_set_slot, "trp_temp_array_a", ":slot_no", ":faction"),
            (str_store_faction_name, s0, ":faction"),
            (overlay_add_item, "$g_presentation_obj_1", s0),
            (val_add, ":slot_no", 1),
          (try_end),
          (try_for_range_backwards, ":faction", kingdoms_begin, kingdoms_end),
            (troop_set_slot, "trp_temp_array_a", ":slot_no", ":faction"),
            (str_store_faction_name, s0, ":faction"),
            (overlay_add_item, "$g_presentation_obj_1", s0),
            (val_add, ":slot_no", 1),
          (try_end),

          # default color list
          # (troop_set_slot, "trp_temp_array_b", 0, factions[fac_deserters][6]),
          (troop_set_slot, "trp_temp_array_b", 0, 0xAAAAAA), #commoners doesn't have a default value
          (troop_set_slot, "trp_temp_array_b", 1, factions[fac_outlaws][6]),
          (troop_set_slot, "trp_temp_array_b", 2, factions[fac_neutral][6]),
          # (troop_set_slot, "trp_temp_array_b", 0, 0x444444), #common
          # (troop_set_slot, "trp_temp_array_b", 1, 0x888888), #outlaw
          # (troop_set_slot, "trp_temp_array_b", 2, 0xFFFFFF), #neutral
          (troop_set_slot, "trp_temp_array_b", 3, factions[fac_kingdom_6][6]),
          (troop_set_slot, "trp_temp_array_b", 4, factions[fac_kingdom_5][6]),
          (troop_set_slot, "trp_temp_array_b", 5, factions[fac_kingdom_4][6]),
          (troop_set_slot, "trp_temp_array_b", 6, factions[fac_kingdom_3][6]),
          (troop_set_slot, "trp_temp_array_b", 7, factions[fac_kingdom_2][6]),
          (troop_set_slot, "trp_temp_array_b", 8, factions[fac_kingdom_1][6]),
          (troop_set_slot, "trp_temp_array_b", 9, factions[fac_player_supporters_faction][6]),
          # (troop_set_slot, "trp_temp_array_b", 3, 0xCCCC66),
          # (troop_set_slot, "trp_temp_array_b", 4, 0x669999),
          # (troop_set_slot, "trp_temp_array_b", 5, 0x0066FF),
          # (troop_set_slot, "trp_temp_array_b", 6, 0x9999CC),
          # (troop_set_slot, "trp_temp_array_b", 7, 0xFF3300),
          # (troop_set_slot, "trp_temp_array_b", 8, 0xCC6600),
          # (troop_set_slot, "trp_temp_array_b", 9, 0x33DD33),
          # (troop_set_slot, "trp_temp_array_b", 10, 0xFFCC33),

          # (troop_set_slot, "trp_temp_array_b", 11, 0xFF4433), #plyr

          ## name and color
          (troop_get_slot, ":faction", "trp_temp_array_a", "$temp"),
          (str_store_faction_name, s0, ":faction"),
          (faction_get_color, ":faction_color", ":faction"),
        (else_try),
          (eq, "$g_presentation_state", recolor_groups),
          # (assign, "$temp", grc_infantry),
          (overlay_add_item, "$g_presentation_obj_1", "str_allies_"),
          (overlay_add_item, "$g_presentation_obj_1", "str_enemies_"),
          (try_for_range_backwards, ":class", grc_infantry, grc_everyone),
            # (troop_get_slot, ":faction_color", "trp_mercenaries_end", ":class"),
            # (troop_set_slot, "trp_temp_array_b", ":class", ":faction_color"), #unnecessary?
            (str_store_class_name, s0, ":class"),
            (overlay_add_item, "$g_presentation_obj_1", s0),
          (try_end),
          (troop_get_slot, ":class", "trp_temp_array_a", "$temp"),
          (str_store_class_name, s0, ":class"),
        (else_try),
          (eq, "$g_presentation_state", recolor_heraldic),
          (overlay_set_display, "$g_presentation_obj_1", 0),
          (troop_get_slot, ":banner", "$g_player_troop", slot_troop_banner_scene_prop),
          (val_sub, ":banner", banner_scene_props_begin),
          (troop_get_slot, ":faction_color", "trp_banner_background_color_array", ":banner"),
          (assign, "$temp", ":banner"), #store offset
          (val_add, ":banner", banner_meshes_begin),
          (create_mesh_overlay, reg0),
          (overlay_set_position, reg0, pos1),
        (try_end),
        (store_add, ":string", "$g_presentation_state", "str_color_of"),
        (str_store_string, s0, ":string"),
        (create_text_overlay, reg1, "str_color_of", tf_center_justify),
        (position_set_x, pos1, 500),
        (position_set_y, pos1, 600),
        (overlay_set_position, reg1, pos1),
        (create_mesh_overlay, "$g_presentation_obj_2", "mesh_white_plane"),
        (position_set_x, pos1, 450),
        (position_set_y, pos1, 480),
        (overlay_set_position, "$g_presentation_obj_2", pos1),
        (position_set_x, pos1, 5000),
        (position_set_y, pos1, 5000),
        (overlay_set_size, "$g_presentation_obj_2", pos1),
        # (faction_get_color, ":faction_color", ":cur_faction"),
        (overlay_set_color, "$g_presentation_obj_2", ":faction_color"),

        ## sliders
        (position_set_x, pos1, 500),
        (create_slider_overlay, "$g_presentation_obj_3", 0, 255),
        (position_set_y, pos1, 400),
        (overlay_set_position, "$g_presentation_obj_3", pos1),
        (create_slider_overlay, "$g_presentation_obj_4", 0, 255),
        (position_set_y, pos1, 350),
        (overlay_set_position, "$g_presentation_obj_4", pos1),
        (create_slider_overlay, "$g_presentation_obj_5", 0, 255),
        (position_set_y, pos1, 300),
        (overlay_set_position, "$g_presentation_obj_5", pos1),
        (store_mod, ":blue", ":faction_color", 0x100),
        (val_div, ":faction_color", 0x100),
        (store_mod, ":green", ":faction_color", 0x100),
        (val_div, ":faction_color", 0x100),
        (store_mod, ":red", ":faction_color", 0x100),
        (overlay_set_val, "$g_presentation_obj_3", ":red"),
        (overlay_set_val, "$g_presentation_obj_4", ":green"),
        (overlay_set_val, "$g_presentation_obj_5", ":blue"),
        ## num boxes
        (position_set_x, pos1, 650),
        (create_number_box_overlay, "$g_presentation_obj_6", 0, 256),
        (position_set_y, pos1, 400),
        (overlay_set_position, "$g_presentation_obj_6", pos1),
        (create_number_box_overlay, "$g_presentation_obj_7", 0, 256),
        (position_set_y, pos1, 350),
        (overlay_set_position, "$g_presentation_obj_7", pos1),
        (create_number_box_overlay, "$g_presentation_obj_8", 0, 256),
        (position_set_y, pos1, 300),
        (overlay_set_position, "$g_presentation_obj_8", pos1),
        (overlay_set_val, "$g_presentation_obj_6", ":red"),
        (overlay_set_val, "$g_presentation_obj_7", ":green"),
        (overlay_set_val, "$g_presentation_obj_8", ":blue"),
        (assign, reg2, ":red"),
        (assign, reg3, ":green"),
        (assign, reg4, ":blue"),
        ## text: r g b
        (position_set_x, pos1, 330),
        (create_text_overlay, reg1, "@Red:", tf_center_justify),
        (position_set_y, pos1, 400),
        (overlay_set_position, reg1, pos1),
        (create_text_overlay, reg1, "@Green:", tf_center_justify),
        (position_set_y, pos1, 350),
        (overlay_set_position, reg1, pos1),
        (create_text_overlay, reg1, "@Blue:", tf_center_justify),
        (position_set_y, pos1, 300),
        (overlay_set_position, reg1, pos1),

        ## HTML code
        (str_store_string, s0, "str_dplmc_none"),
        (create_text_overlay, "$g_presentation_obj_9", "str_html", tf_center_justify),
        (position_set_x, pos1, 500),
        (position_set_y, pos1, 450),
        (overlay_set_position, "$g_presentation_obj_9", pos1),
        (call_script, "script_convert_rgb_code_to_html_code", reg2, reg3, reg4),
        (overlay_set_text, "$g_presentation_obj_9", "str_html"),

        ## default and random
        (create_game_button_overlay, "$g_presentation_obj_11", "str_reset_to_default"),
        (position_set_x, pos1, 420),
        (position_set_y, pos1, 230),
        (overlay_set_position, "$g_presentation_obj_11", pos1),
        (create_game_button_overlay, "$g_presentation_obj_12", "str_randomize"),
        (position_set_x, pos1, 580),
        (position_set_y, pos1, 230),
        (overlay_set_position, "$g_presentation_obj_12", pos1),

        ## color picker
        (create_mesh_overlay, reg1, "mesh_white_plane"),
        (position_set_x, pos1, 138),
        (position_set_y, pos1, 78),
        (overlay_set_position, reg1, pos1),
        (position_set_x, pos1, 36100),
        (position_set_y, pos1, 6100),
        (overlay_set_size, reg1, pos1),
        (overlay_set_color, reg1, 0),

        (assign, ":pos_x", 140),
        (assign, ":pos_y", 80),
        (try_for_range, ":cur_slot", 0, 216),
          (create_image_button_overlay, reg1, "mesh_white_plane", "mesh_white_plane"),
          (position_set_x, pos1, ":pos_x"),
          (position_set_y, pos1, ":pos_y"),
          (overlay_set_position, reg1, pos1),
          (position_set_x, pos1, 900),
          (position_set_y, pos1, 900),
          (overlay_set_size, reg1, pos1),
          (assign, ":cur_color", ":cur_slot"),
          (call_script, "script_convert_slot_no_to_color", ":cur_color"),
          (assign, ":dest_color", reg0),
          (overlay_set_color, reg1, ":dest_color"),
          (val_add, ":pos_x", 20),
          (try_begin),
            (eq, ":pos_x", 860),
            (assign, ":pos_x", 140),
            (val_add, ":pos_y", 20),
          (try_end),
          (troop_set_slot, "trp_temp_array_c", ":cur_slot", reg1),
        (try_end),

        ## done
        (create_game_button_overlay, "$g_presentation_obj_10", "str_done"),
        (position_set_x, pos1, 900),
        (position_set_y, pos1, 25),
        (overlay_set_position, "$g_presentation_obj_10", pos1),
        ####### mouse fix pos system #######
        #(call_script, "script_mouse_fix_pos_ready"),
        ####### mouse fix pos system #######
      ]),

      #(ti_on_presentation_run,
        #[
        ####### mouse fix pos system #######
        #(call_script, "script_mouse_fix_pos_run"),
        ####### mouse fix pos system #######
      #]),

    (ti_on_presentation_event_state_change,
      [
        (store_trigger_param_1, ":object"),
        (store_trigger_param_2, ":value"),

        (try_begin),
          (eq, ":object", "$g_presentation_obj_1"),
          (assign, "$temp", ":value"),
          (start_presentation, "prsnt_change_color"),
        (else_try),
          (this_or_next|eq, ":object", "$g_presentation_obj_3"),
          (eq, ":object", "$g_presentation_obj_6"),
          (overlay_set_val, "$g_presentation_obj_3", ":value"),
          (overlay_set_val, "$g_presentation_obj_6", ":value"),
          (assign, reg2, ":value"),
          (call_script, "script_get_dest_color_from_rgb", reg2, reg3, reg4),
          (assign, ":cur_color", reg0),
          (overlay_set_color, "$g_presentation_obj_2", ":cur_color"),

          (troop_get_slot, ":cur_faction", "trp_temp_array_a", "$temp"),
          (faction_set_color, ":cur_faction", ":cur_color"),
          (call_script, "script_convert_rgb_code_to_html_code", reg2, reg3, reg4),
          (overlay_set_text, "$g_presentation_obj_9", "str_html"),
        (else_try),
          (this_or_next|eq, ":object", "$g_presentation_obj_4"),
          (eq, ":object", "$g_presentation_obj_7"),
          (overlay_set_val, "$g_presentation_obj_4", ":value"),
          (overlay_set_val, "$g_presentation_obj_7", ":value"),
          (assign, reg3, ":value"),
          (call_script, "script_get_dest_color_from_rgb", reg2, reg3, reg4),
          (assign, ":cur_color", reg0),
          (overlay_set_color, "$g_presentation_obj_2", ":cur_color"),
          (troop_get_slot, ":cur_faction", "trp_temp_array_a", "$temp"),
          (faction_set_color, ":cur_faction", ":cur_color"),
          (call_script, "script_convert_rgb_code_to_html_code", reg2, reg3, reg4),
          (overlay_set_text, "$g_presentation_obj_9", "str_html"),
        (else_try),
          (this_or_next|eq, ":object", "$g_presentation_obj_5"),
          (eq, ":object", "$g_presentation_obj_8"),
          (overlay_set_val, "$g_presentation_obj_5", ":value"),
          (overlay_set_val, "$g_presentation_obj_8", ":value"),
          (assign, reg4, ":value"),
          (call_script, "script_change_color"),
          # (call_script, "script_get_dest_color_from_rgb", reg2, reg3, reg4),
          # (assign, ":cur_color", reg0),
          # (overlay_set_color, "$g_presentation_obj_2", ":cur_color"),
          # (troop_get_slot, ":cur_faction", "trp_temp_array_a", "$temp"),
          # (faction_set_color, ":cur_faction", ":cur_color"),
          # (call_script, "script_convert_rgb_code_to_html_code", reg2, reg3, reg4),
          # (overlay_set_text, "$g_presentation_obj_9", "str_html"),
        (else_try),
          (eq, ":object", "$g_presentation_obj_11"),
          (troop_get_slot, ":cur_faction", "trp_temp_array_a", "$temp"),
          (troop_get_slot, ":default_color", "trp_temp_array_b", "$temp"),
          (try_begin),
            (eq, "$g_presentation_state", recolor_kingdom),
            (faction_set_color, ":cur_faction", ":default_color"),
          (else_try),
            (eq, "$g_presentation_state", recolor_groups),
            (troop_set_slot, "trp_mercenaries_end", "$temp", ":default_color"),
          (else_try),
            (eq, "$g_presentation_state", recolor_heraldic),
            (troop_set_slot, "trp_banner_background_color_array", "$temp", ":default_color"),
          (try_end),
          (overlay_set_color, "$g_presentation_obj_2", ":default_color"),
          (store_mod, ":blue", ":default_color", 0x100),
          (val_div, ":default_color", 0x100),
          (store_mod, ":green", ":default_color", 0x100),
          (val_div, ":default_color", 0x100),
          (store_mod, ":red", ":default_color", 0x100),
          (overlay_set_val, "$g_presentation_obj_3", ":red"),
          (overlay_set_val, "$g_presentation_obj_4", ":green"),
          (overlay_set_val, "$g_presentation_obj_5", ":blue"),
          (overlay_set_val, "$g_presentation_obj_6", ":red"),
          (overlay_set_val, "$g_presentation_obj_7", ":green"),
          (overlay_set_val, "$g_presentation_obj_8", ":blue"),
          (assign, reg2, ":red"),
          (assign, reg3, ":green"),
          (assign, reg4, ":blue"),
          (call_script, "script_convert_rgb_code_to_html_code", reg2, reg3, reg4),
          (overlay_set_text, "$g_presentation_obj_9", "str_html"),
        (else_try),
          (eq, ":object", "$g_presentation_obj_12"),
          (store_random_in_range, reg2, 0, 256),
          (store_random_in_range, reg3, 0, 256),
          (store_random_in_range, reg4, 0, 256),
          (overlay_set_val, "$g_presentation_obj_3", reg2),
          (overlay_set_val, "$g_presentation_obj_4", reg3),
          (overlay_set_val, "$g_presentation_obj_5", reg4),
          (overlay_set_val, "$g_presentation_obj_6", reg2),
          (overlay_set_val, "$g_presentation_obj_7", reg3),
          (overlay_set_val, "$g_presentation_obj_8", reg4),
          (call_script, "script_change_color"),
          # (call_script, "script_get_dest_color_from_rgb", reg2, reg3, reg4),
          # (assign, ":cur_color", reg0),
          # (overlay_set_color, "$g_presentation_obj_2", ":cur_color"),
          # (troop_get_slot, ":cur_faction", "trp_temp_array_a", "$temp"),
          # (faction_set_color, ":cur_faction", ":cur_color"),
          # (call_script, "script_convert_rgb_code_to_html_code", reg2, reg3, reg4),
          # (overlay_set_text, "$g_presentation_obj_9", "str_html"),
        (else_try),
          (eq, ":object", "$g_presentation_obj_10"),
          (try_begin),
            (gt, "$g_presentation_next_presentation", 0),
            (start_presentation, "$g_presentation_next_presentation"),
          (else_try),
            (presentation_set_duration, 0),
          (try_end),
        (else_try),
          (try_for_range, ":cur_slot", 0, 216),
            (troop_slot_eq, "trp_temp_array_c", ":cur_slot", ":object"),
            (assign, ":cur_color", ":cur_slot"),
            (call_script, "script_convert_slot_no_to_color", ":cur_color"),
            (assign, ":dest_color", reg0),
            (troop_get_slot, ":cur_faction", "trp_temp_array_a", "$temp"),
            #(str_store_faction_name,s0, ":cur_faction"),
            #(display_message, "@color {reg0}, {s0}"),
            (faction_set_color, ":cur_faction", ":dest_color"),
            #(faction_set_color, "fac_player_supporters_faction", ":dest_color"),
            (overlay_set_color, "$g_presentation_obj_2", ":dest_color"),
            (store_mod, ":blue", ":dest_color", 0x100),
            (val_div, ":dest_color", 0x100),
            (store_mod, ":green", ":dest_color", 0x100),
            (val_div, ":dest_color", 0x100),
            (store_mod, ":red", ":dest_color", 0x100),
            (overlay_set_val, "$g_presentation_obj_3", ":red"),
            (overlay_set_val, "$g_presentation_obj_4", ":green"),
            (overlay_set_val, "$g_presentation_obj_5", ":blue"),
            (overlay_set_val, "$g_presentation_obj_6", ":red"),
            (overlay_set_val, "$g_presentation_obj_7", ":green"),
            (overlay_set_val, "$g_presentation_obj_8", ":blue"),
            (assign, reg2, ":red"),
            (assign, reg3, ":green"),
            (assign, reg4, ":blue"),
            (call_script, "script_convert_rgb_code_to_html_code", reg2, reg3, reg4),
            (overlay_set_text, "$g_presentation_obj_9", "str_html"),
          (try_end),
        (try_end),
    ]),
  ])
