# -*- coding: cp1254 -*-
import string
from header_common import *
from header_presentations import *
from header_mission_templates import *
from ID_meshes import *
from header_operations import *
from header_triggers import *
from module_constants import *
from header_terrain_types import *
from module_items import *
from module_factions import *
from header_items import *
from compiler import *

cc_color_editor = ("cc_color_editor", 0, mesh_load_window, [
    (ti_on_presentation_load,
      [
        (presentation_set_duration, 999999),
        (set_fixed_point_multiplier, 1000),

        (create_combo_button_overlay, "$g_cc_color_obj_1"),
        (position_set_x, pos1, 500),
        (position_set_y, pos1, 680),
        (overlay_set_position, "$g_cc_color_obj_1", pos1),

        (troop_set_slot, "trp_temp_array_a", 0, "fac_commoners"),
        (troop_set_slot, "trp_temp_array_a", 1, "fac_outlaws"),
        (troop_set_slot, "trp_temp_array_a", 2, "fac_neutral"),
        (troop_set_slot, "trp_temp_array_a", 3, "fac_dark_knights"),
        (troop_set_slot, "trp_temp_array_a", 4, "fac_player_supporters_faction"),
        (troop_set_slot, "trp_temp_array_a", 5, "fac_kingdom_1"),
        (troop_set_slot, "trp_temp_array_a", 6, "fac_kingdom_2"),
        (troop_set_slot, "trp_temp_array_a", 7, "fac_kingdom_3"),
        (troop_set_slot, "trp_temp_array_a", 8, "fac_kingdom_4"),
        (troop_set_slot, "trp_temp_array_a", 9, "fac_kingdom_5"),
        (troop_set_slot, "trp_temp_array_a", 10, "fac_kingdom_6"),

        (troop_set_slot, "trp_temp_array_b", 0, 0x444444),
        (troop_set_slot, "trp_temp_array_b", 1, 0x888888),
        (troop_set_slot, "trp_temp_array_b", 2, 0xFFFFFF),
        (troop_set_slot, "trp_temp_array_b", 3, 0x383838),
        (troop_set_slot, "trp_temp_array_b", 4, 0xFF4433),
        (troop_set_slot, "trp_temp_array_b", 5, 0xEE7744),
        (troop_set_slot, "trp_temp_array_b", 6, 0xCCBB99),
        (troop_set_slot, "trp_temp_array_b", 7, 0xCC99FF),
        (troop_set_slot, "trp_temp_array_b", 8, 0x33DDDD),
        (troop_set_slot, "trp_temp_array_b", 9, 0x33DD33),
        (troop_set_slot, "trp_temp_array_b", 10, 0xDDDD33),

        (try_for_range, ":cur_slot", 0, 11),
          (troop_get_slot, ":cur_faction", "trp_temp_array_a", ":cur_slot"),
          (str_store_faction_name, s0, ":cur_faction"),
          (overlay_add_item, "$g_cc_color_obj_1", s0),
        (try_end),
        (overlay_set_val, "$g_cc_color_obj_1", "$temp"),

        (troop_get_slot, ":cur_faction", "trp_temp_array_a", "$temp"),
        (str_store_faction_name, s0, ":cur_faction"),
        (create_text_overlay, reg1, "@Faction color of {s0}:", tf_center_justify),
        (position_set_x, pos1, 500),
        (position_set_y, pos1, 600),
        (overlay_set_position, reg1, pos1),
        (create_mesh_overlay, "$g_cc_color_obj_2", "mesh_white_plane"),
        (position_set_x, pos1, 450),
        (position_set_y, pos1, 480),
        (overlay_set_position, "$g_cc_color_obj_2", pos1),
        (position_set_x, pos1, 5000),
        (position_set_y, pos1, 5000),
        (overlay_set_size, "$g_cc_color_obj_2", pos1),
        (faction_get_color, ":faction_color", ":cur_faction"),
        (overlay_set_color, "$g_cc_color_obj_2", ":faction_color"),

        (position_set_x, pos1, 500),
        (create_slider_overlay, "$g_cc_color_obj_3", 0, 255),
        (position_set_y, pos1, 400),
        (overlay_set_position, "$g_cc_color_obj_3", pos1),
        (create_slider_overlay, "$g_cc_color_obj_4", 0, 255),
        (position_set_y, pos1, 350),
        (overlay_set_position, "$g_cc_color_obj_4", pos1),
        (create_slider_overlay, "$g_cc_color_obj_5", 0, 255),
        (position_set_y, pos1, 300),
        (overlay_set_position, "$g_cc_color_obj_5", pos1),
        (store_mod, ":blue", ":faction_color", 0x100),
        (val_div, ":faction_color", 0x100),
        (store_mod, ":green", ":faction_color", 0x100),
        (val_div, ":faction_color", 0x100),
        (store_mod, ":red", ":faction_color", 0x100),
        (overlay_set_val, "$g_cc_color_obj_3", ":red"),
        (overlay_set_val, "$g_cc_color_obj_4", ":green"),
        (overlay_set_val, "$g_cc_color_obj_5", ":blue"),
        (position_set_x, pos1, 1000),
        (position_set_y, pos1, 500),
        (overlay_set_size, "$g_cc_color_obj_3", pos1),
        (overlay_set_size, "$g_cc_color_obj_4", pos1),
        (overlay_set_size, "$g_cc_color_obj_5", pos1),
        (position_set_x, pos1, 650),
        (create_number_box_overlay, "$g_cc_color_obj_6", 0, 256),
        (position_set_y, pos1, 400),
        (overlay_set_position, "$g_cc_color_obj_6", pos1),
        (create_number_box_overlay, "$g_cc_color_obj_7", 0, 256),
        (position_set_y, pos1, 350),
        (overlay_set_position, "$g_cc_color_obj_7", pos1),
        (create_number_box_overlay, "$g_cc_color_obj_8", 0, 256),
        (position_set_y, pos1, 300),
        (overlay_set_position, "$g_cc_color_obj_8", pos1),
        (overlay_set_val, "$g_cc_color_obj_6", ":red"),
        (overlay_set_val, "$g_cc_color_obj_7", ":green"),
        (overlay_set_val, "$g_cc_color_obj_8", ":blue"),
        (assign, reg2, ":red"),
        (assign, reg3, ":green"),
        (assign, reg4, ":blue"),
        (position_set_x, pos1, 330),
        (create_text_overlay, reg1, "@Red:", tf_center_justify),
        (position_set_y, pos1, 400),
        (overlay_set_position, reg1, pos1),
        (create_text_overlay, reg1, "@Green:", tf_center_justify),
        (position_set_y, pos1, 350),
        (overlay_set_position, reg1, pos1),
        (create_text_overlay, reg1, "@Blue:", tf_center_justify),
        (position_set_y, pos1, 300),
        (overlay_set_position, reg1, pos1),

        (create_text_overlay, "$g_cc_color_obj_9", "@ ", tf_center_justify),
        (position_set_x, pos1, 500),
        (position_set_y, pos1, 450),
        (overlay_set_position, "$g_cc_color_obj_9", pos1),
        (call_script, "script_convert_rgb_code_to_html_code", reg2, reg3, reg4),
        (overlay_set_text, "$g_cc_color_obj_9", "@HTML code: {s0}"),

        (create_game_button_overlay, "$g_cc_color_obj_11", "@Default"),
        (position_set_x, pos1, 420),
        (position_set_y, pos1, 230),
        (overlay_set_position, "$g_cc_color_obj_11", pos1),
        (create_game_button_overlay, "$g_cc_color_obj_12", "@Randomize"),
        (position_set_x, pos1, 580),
        (position_set_y, pos1, 230),
        (overlay_set_position, "$g_cc_color_obj_12", pos1),

        (create_mesh_overlay, reg1, "mesh_white_plane"),
        (position_set_x, pos1, 138),
        (position_set_y, pos1, 78),
        (overlay_set_position, reg1, pos1),
        (position_set_x, pos1, 36100),
        (position_set_y, pos1, 6100),
        (overlay_set_size, reg1, pos1),
        (overlay_set_color, reg1, 0),

        (assign, ":pos_x", 140),
        (assign, ":pos_y", 80),
        (try_for_range, ":cur_slot", 0, 216),
          (create_image_button_overlay, reg1, "mesh_white_plane", "mesh_white_plane"),
          (position_set_x, pos1, ":pos_x"),
          (position_set_y, pos1, ":pos_y"),
          (overlay_set_position, reg1, pos1),
          (position_set_x, pos1, 900),
          (position_set_y, pos1, 900),
          (overlay_set_size, reg1, pos1),
          (assign, ":cur_color", ":cur_slot"),
          (call_script, "script_convert_slot_no_to_color", ":cur_color"),
          (assign, ":dest_color", reg0),
          (overlay_set_color, reg1, ":dest_color"),
          (val_add, ":pos_x", 20),
          (try_begin),
            (eq, ":pos_x", 860),
            (assign, ":pos_x", 140),
            (val_add, ":pos_y", 20),
          (try_end),
          (troop_set_slot, "trp_temp_array_c", ":cur_slot", reg1),
        (try_end),

        (create_game_button_overlay, "$g_cc_color_obj_10", "@Done"),
        (position_set_x, pos1, 900),
        (position_set_y, pos1, 25),
        (overlay_set_position, "$g_cc_color_obj_10", pos1),
      ]),

    (ti_on_presentation_event_state_change,
      [
        (store_trigger_param_1, ":object"),
        (store_trigger_param_2, ":value"),

        (try_for_range, ":cur_slot", 0, 216),
          (troop_slot_eq, "trp_temp_array_c", ":cur_slot", ":object"),
          (assign, ":cur_color", ":cur_slot"),
          (call_script, "script_convert_slot_no_to_color", ":cur_color"),
          (assign, ":dest_color", reg0),
          (troop_get_slot, ":cur_faction", "trp_temp_array_a", "$temp"),
          (faction_set_color, ":cur_faction", ":dest_color"),
          (overlay_set_color, "$g_cc_color_obj_2", ":dest_color"),
          (store_mod, ":blue", ":dest_color", 0x100),
          (val_div, ":dest_color", 0x100),
          (store_mod, ":green", ":dest_color", 0x100),
          (val_div, ":dest_color", 0x100),
          (store_mod, ":red", ":dest_color", 0x100),
          (overlay_set_val, "$g_cc_color_obj_3", ":red"),
          (overlay_set_val, "$g_cc_color_obj_4", ":green"),
          (overlay_set_val, "$g_cc_color_obj_5", ":blue"),
          (overlay_set_val, "$g_cc_color_obj_6", ":red"),
          (overlay_set_val, "$g_cc_color_obj_7", ":green"),
          (overlay_set_val, "$g_cc_color_obj_8", ":blue"),
          (assign, reg2, ":red"),
          (assign, reg3, ":green"),
          (assign, reg4, ":blue"),
          (call_script, "script_convert_rgb_code_to_html_code", reg2, reg3, reg4),
          (overlay_set_text, "$g_cc_color_obj_9", "@HTML code: {s0}"),
        (try_end),

        (try_begin),
          (eq, ":object", "$g_cc_color_obj_1"),
          (assign, "$temp", ":value"),
          (start_presentation, "prsnt_cc_color_editor"),
        (else_try),
          (this_or_next|eq, ":object", "$g_cc_color_obj_3"),
          (eq, ":object", "$g_cc_color_obj_6"),
          (overlay_set_val, "$g_cc_color_obj_3", ":value"),
          (overlay_set_val, "$g_cc_color_obj_6", ":value"),
          (assign, reg2, ":value"),
          (call_script, "script_get_dest_color_from_rgb", reg2, reg3, reg4),
          (assign, ":cur_color", reg0),
          (overlay_set_color, "$g_cc_color_obj_2", ":cur_color"),
          (troop_get_slot, ":cur_faction", "trp_temp_array_a", "$temp"),
          (faction_set_color, ":cur_faction", ":cur_color"),
          (call_script, "script_convert_rgb_code_to_html_code", reg2, reg3, reg4),
          (overlay_set_text, "$g_cc_color_obj_9", "@HTML code: {s0}"),
        (else_try),
          (this_or_next|eq, ":object", "$g_cc_color_obj_4"),
          (eq, ":object", "$g_cc_color_obj_7"),
          (overlay_set_val, "$g_cc_color_obj_4", ":value"),
          (overlay_set_val, "$g_cc_color_obj_7", ":value"),
          (assign, reg3, ":value"),
          (call_script, "script_get_dest_color_from_rgb", reg2, reg3, reg4),
          (assign, ":cur_color", reg0),
          (overlay_set_color, "$g_cc_color_obj_2", ":cur_color"),
          (troop_get_slot, ":cur_faction", "trp_temp_array_a", "$temp"),
          (faction_set_color, ":cur_faction", ":cur_color"),
          (call_script, "script_convert_rgb_code_to_html_code", reg2, reg3, reg4),
          (overlay_set_text, "$g_cc_color_obj_9", "@HTML code: {s0}"),
        (else_try),
          (this_or_next|eq, ":object", "$g_cc_color_obj_5"),
          (eq, ":object", "$g_cc_color_obj_8"),
          (overlay_set_val, "$g_cc_color_obj_5", ":value"),
          (overlay_set_val, "$g_cc_color_obj_8", ":value"),
          (assign, reg4, ":value"),
          (call_script, "script_get_dest_color_from_rgb", reg2, reg3, reg4),
          (assign, ":cur_color", reg0),
          (overlay_set_color, "$g_cc_color_obj_2", ":cur_color"),
          (troop_get_slot, ":cur_faction", "trp_temp_array_a", "$temp"),
          (faction_set_color, ":cur_faction", ":cur_color"),
          (call_script, "script_convert_rgb_code_to_html_code", reg2, reg3, reg4),
          (overlay_set_text, "$g_cc_color_obj_9", "@HTML code: {s0}"),
        (else_try),
          (eq, ":object", "$g_cc_color_obj_11"),
          (troop_get_slot, ":cur_faction", "trp_temp_array_a", "$temp"),
          (troop_get_slot, ":default_color", "trp_temp_array_b", "$temp"),
          (faction_set_color, ":cur_faction", ":default_color"),
          (overlay_set_color, "$g_cc_color_obj_2", ":default_color"),
          (store_mod, ":blue", ":default_color", 0x100),
          (val_div, ":default_color", 0x100),
          (store_mod, ":green", ":default_color", 0x100),
          (val_div, ":default_color", 0x100),
          (store_mod, ":red", ":default_color", 0x100),
          (overlay_set_val, "$g_cc_color_obj_3", ":red"),
          (overlay_set_val, "$g_cc_color_obj_4", ":green"),
          (overlay_set_val, "$g_cc_color_obj_5", ":blue"),
          (overlay_set_val, "$g_cc_color_obj_6", ":red"),
          (overlay_set_val, "$g_cc_color_obj_7", ":green"),
          (overlay_set_val, "$g_cc_color_obj_8", ":blue"),
          (assign, reg2, ":red"),
          (assign, reg3, ":green"),
          (assign, reg4, ":blue"),
          (call_script, "script_convert_rgb_code_to_html_code", reg2, reg3, reg4),
          (overlay_set_text, "$g_cc_color_obj_9", "@HTML code: {s0}"),
        (else_try),
          (eq, ":object", "$g_cc_color_obj_12"),
          (store_random_in_range, reg2, 0, 256),
          (store_random_in_range, reg3, 0, 256),
          (store_random_in_range, reg4, 0, 256),
          (overlay_set_val, "$g_cc_color_obj_3", reg2),
          (overlay_set_val, "$g_cc_color_obj_4", reg3),
          (overlay_set_val, "$g_cc_color_obj_5", reg4),
          (overlay_set_val, "$g_cc_color_obj_6", reg2),
          (overlay_set_val, "$g_cc_color_obj_7", reg3),
          (overlay_set_val, "$g_cc_color_obj_8", reg4),
          (call_script, "script_get_dest_color_from_rgb", reg2, reg3, reg4),
          (assign, ":cur_color", reg0),
          (overlay_set_color, "$g_cc_color_obj_2", ":cur_color"),
          (troop_get_slot, ":cur_faction", "trp_temp_array_a", "$temp"),
          (faction_set_color, ":cur_faction", ":cur_color"),
          (call_script, "script_convert_rgb_code_to_html_code", reg2, reg3, reg4),
          (overlay_set_text, "$g_cc_color_obj_9", "@HTML code: {s0}"),
        (else_try),
          (eq, ":object", "$g_cc_color_obj_10"),
          (presentation_set_duration, 0),
        (try_end),
    ]),
  ])
