# -*- coding: cp1254 -*-
import string
from header_common import *
from header_presentations import *
from header_mission_templates import *
from ID_meshes import *
from header_operations import *
from header_triggers import *
from module_constants import *
from header_terrain_types import *
from module_items import *
from module_factions import *
from header_items import *
from compiler import *

equip_npcs = ("equip_npcs", 0, mesh_load_window, [
    (ti_on_presentation_load,
      [
        (set_fixed_point_multiplier, 1000),
        (presentation_set_duration, 999999),

        (create_mesh_overlay, reg1, "mesh_load_window"),
        (position_set_x, pos1, 0),
        (position_set_y, pos1, 0),
        (overlay_set_position, reg1, pos1),

        (assign, "$g_cur_selected_item_slot", -1),
        (try_begin),
          (neg|is_between, "$g_autoloot_mass_action_mode", 0, 4),
          (assign, "$g_autoloot_mass_action_mode", 0),
        (try_end),
        (try_begin),
          (neg|ge, "$cheat_mode", 1),
          (eq, "$g_autoloot_mass_action_mode", 3),
          (assign, "$g_autoloot_mass_action_mode", 0),
        (try_end),

        # [DONE BUTTON] x=870 y=10
        (create_game_button_overlay, "$g_presentation_obj_admin_panel_2", "@Done"),
        (position_set_x, pos1, 870),
        (position_set_y, pos1, 10),
        (overlay_set_position, "$g_presentation_obj_admin_panel_2", pos1),

        (troop_get_inventory_capacity, ":inv_cap", "trp_player"),
        (store_sub, ":num_items", ":inv_cap", 10),
        (store_add, ":num_pages", ":num_items", 47),
        (val_div, ":num_pages", 48),
        (val_max, ":num_pages", 1),
        (val_min, ":num_pages", 10),

        # [PAGE COMBO] x=740 y=15
        (create_combo_label_overlay, "$g_presentation_obj_admin_panel_3"),
        (position_set_x, pos1, 740),
        (position_set_y, pos1, 15),
        (overlay_set_position, "$g_presentation_obj_admin_panel_3", pos1),
        (position_set_x, pos1, 500),
        (position_set_y, pos1, 800),
        (overlay_set_size, "$g_presentation_obj_admin_panel_3", pos1),
        (try_for_range, ":page", 0, ":num_pages"),
          (store_add, reg1, ":page", 1),
          (str_store_string, s1, "@Page {reg1}"),
          (overlay_add_item, "$g_presentation_obj_admin_panel_3", s1),
        (try_end),
        (overlay_set_val, "$g_presentation_obj_admin_panel_3", "$g_cur_page_of_loot_pool"),

        # [RE-SORT BUTTON] x=440 y=10
        (create_game_button_overlay, "$g_presentation_obj_admin_panel_4", "@Re-sort"),
        (position_set_x, pos1, 440),
        (position_set_y, pos1, 10),
        (overlay_set_position, "$g_presentation_obj_admin_panel_4", pos1),

        (try_begin),
          (neg|is_between, "$g_autoloot_mass_action_mode", 0, 4),
          (assign, "$g_autoloot_mass_action_mode", 0),
        (try_end),
        (try_begin),
          (neg|ge, "$cheat_mode", 1),
          (eq, "$g_autoloot_mass_action_mode", 3),
          (assign, "$g_autoloot_mass_action_mode", 0),
        (try_end),

        # [MASS ACTION COMBO] x=180 y=20
        (create_combo_label_overlay, "$g_presentation_obj_admin_panel_15"),
        (position_set_x, pos1, 180),
        (position_set_y, pos1, 20),
        (overlay_set_position, "$g_presentation_obj_admin_panel_15", pos1),
        (position_set_x, pos1, 500),
        (position_set_y, pos1, 800),
        (overlay_set_size, "$g_presentation_obj_admin_panel_15", pos1),
        (overlay_add_item, "$g_presentation_obj_admin_panel_15", "@Upgrade all"),
        (overlay_add_item, "$g_presentation_obj_admin_panel_15", "@Remove all"),
        (overlay_add_item, "$g_presentation_obj_admin_panel_15", "@Copy all"),
        (try_begin),
          (ge, "$cheat_mode", 1),
          (overlay_add_item, "$g_presentation_obj_admin_panel_15", "@Cheat: Copy all"),
        (try_end),
        (overlay_set_val, "$g_presentation_obj_admin_panel_15", "$g_autoloot_mass_action_mode"),

        # [APPLY BUTTON] x=210 y=30
        (create_button_overlay, "$g_presentation_obj_admin_panel_19", "@Apply"),
        (position_set_x, pos1, 210),
        (position_set_y, pos1, 30),
        (overlay_set_position, "$g_presentation_obj_admin_panel_19", pos1),

        (assign, ":pos_y", 270),
        (position_set_x, pos2, 900),
        (position_set_y, pos2, 900),

        (create_check_box_overlay, "$g_presentation_obj_admin_panel_9", "mesh_checkbox_off", "mesh_checkbox_on"),
        (position_set_x, pos1, 200),
        (position_set_y, pos1, ":pos_y"),
        (overlay_set_position, "$g_presentation_obj_admin_panel_9", pos1),
        (troop_get_slot, ":upg_weapon", "$g_selected_troop", dplmc_slot_upgrade_wpn_0),
        (overlay_set_val, "$g_presentation_obj_admin_panel_9", ":upg_weapon"),
        (create_text_overlay, reg1, "@Weapon 1", tf_left_align),
        (position_set_x, pos1, 220),
        (position_set_y, pos1, ":pos_y"),
        (overlay_set_position, reg1, pos1),
        (overlay_set_size, reg1, pos2),
        (val_sub, ":pos_y", 35),

        (create_check_box_overlay, "$g_presentation_obj_admin_panel_10", "mesh_checkbox_off", "mesh_checkbox_on"),
        (position_set_x, pos1, 200),
        (position_set_y, pos1, ":pos_y"),
        (overlay_set_position, "$g_presentation_obj_admin_panel_10", pos1),
        (troop_get_slot, ":upg_weapon", "$g_selected_troop", dplmc_slot_upgrade_wpn_1),
        (overlay_set_val, "$g_presentation_obj_admin_panel_10", ":upg_weapon"),
        (create_text_overlay, reg1, "@Weapon 2", tf_left_align),
        (position_set_x, pos1, 220),
        (position_set_y, pos1, ":pos_y"),
        (overlay_set_position, reg1, pos1),
        (overlay_set_size, reg1, pos2),
        (val_sub, ":pos_y", 35),

        (create_check_box_overlay, "$g_presentation_obj_admin_panel_11", "mesh_checkbox_off", "mesh_checkbox_on"),
        (position_set_x, pos1, 200),
        (position_set_y, pos1, ":pos_y"),
        (overlay_set_position, "$g_presentation_obj_admin_panel_11", pos1),
        (troop_get_slot, ":upg_weapon", "$g_selected_troop", dplmc_slot_upgrade_wpn_2),
        (overlay_set_val, "$g_presentation_obj_admin_panel_11", ":upg_weapon"),
        (create_text_overlay, reg1, "@Weapon 3", tf_left_align),
        (position_set_x, pos1, 220),
        (position_set_y, pos1, ":pos_y"),
        (overlay_set_position, reg1, pos1),
        (overlay_set_size, reg1, pos2),
        (val_sub, ":pos_y", 35),

        (create_check_box_overlay, "$g_presentation_obj_admin_panel_12", "mesh_checkbox_off", "mesh_checkbox_on"),
        (position_set_x, pos1, 200),
        (position_set_y, pos1, ":pos_y"),
        (overlay_set_position, "$g_presentation_obj_admin_panel_12", pos1),
        (troop_get_slot, ":upg_weapon", "$g_selected_troop", dplmc_slot_upgrade_wpn_3),
        (overlay_set_val, "$g_presentation_obj_admin_panel_12", ":upg_weapon"),
        (create_text_overlay, reg1, "@Weapon 4", tf_left_align),
        (position_set_x, pos1, 220),
        (position_set_y, pos1, ":pos_y"),
        (overlay_set_position, reg1, pos1),
        (overlay_set_size, reg1, pos2),
        (val_sub, ":pos_y", 40),

        (create_check_box_overlay, "$g_presentation_obj_admin_panel_7", "mesh_checkbox_off", "mesh_checkbox_on"),
        (position_set_x, pos1, 200),
        (position_set_y, pos1, ":pos_y"),
        (overlay_set_position, "$g_presentation_obj_admin_panel_7", pos1),
        (troop_get_slot, ":upg_armor", "$g_selected_troop", dplmc_slot_upgrade_armor),
        (overlay_set_val, "$g_presentation_obj_admin_panel_7", ":upg_armor"),
        (create_text_overlay, reg1, "@Armors", tf_left_align),
        (position_set_x, pos1, 220),
        (position_set_y, pos1, ":pos_y"),
        (overlay_set_position, reg1, pos1),
        (overlay_set_size, reg1, pos2),
        (val_sub, ":pos_y", 35),

        (create_check_box_overlay, "$g_presentation_obj_admin_panel_8", "mesh_checkbox_off", "mesh_checkbox_on"),
        (position_set_x, pos1, 200),
        (position_set_y, pos1, ":pos_y"),
        (overlay_set_position, "$g_presentation_obj_admin_panel_8", pos1),
        (troop_get_slot, ":upg_horse", "$g_selected_troop", dplmc_slot_upgrade_horse),
        (overlay_set_val, "$g_presentation_obj_admin_panel_8", ":upg_horse"),
        (create_text_overlay, reg1, "@Horse", tf_left_align),
        (position_set_x, pos1, 220),
        (position_set_y, pos1, ":pos_y"),
        (overlay_set_position, reg1, pos1),
        (overlay_set_size, reg1, pos2),
        (val_sub, ":pos_y", 45),

        # (assign, ":head_armor", 0),
        # (assign, ":body_armor", 0),
        # (assign, ":leg_armor", 0),
        # (try_for_range, ":inv_slot_no", 4, 8),
        #   (troop_get_inventory_slot, ":item", "$g_selected_troop", ":inv_slot_no"),
        #   (gt, ":item", -1),
        #   (troop_get_inventory_slot_modifier, ":imod", "$g_selected_troop", ":inv_slot_no"),
        #   (call_script, "script_imod_effect_armor", ":imod"),
        #   (assign, ":imod_effect", reg0),
        #   (item_get_head_armor, ":cur_head_armor", ":item"),
        #   (try_begin),
        #     (gt, ":cur_head_armor", 0),
        #     (val_add, ":cur_head_armor", ":imod_effect"),
        #     (val_max, ":cur_head_armor", 0),
        #     (val_add, ":head_armor", ":cur_head_armor"),
        #   (try_end),
        #   (item_get_body_armor, ":cur_body_armor", ":item"),
        #   (try_begin),
        #     (gt, ":cur_body_armor", 0),
        #     (val_add, ":cur_body_armor", ":imod_effect"),
        #     (val_max, ":cur_body_armor", 0),
        #     (val_add, ":body_armor", ":cur_body_armor"),
        #   (try_end),
        #   (item_get_leg_armor, ":cur_leg_armor", ":item"),
        #   (try_begin),
        #     (gt, ":cur_leg_armor", 0),
        #     (val_add, ":cur_leg_armor", ":imod_effect"),
        #     (val_max, ":cur_leg_armor", 0),
        #     (val_add, ":leg_armor", ":cur_leg_armor"),
        #   (try_end),
        # (try_end),

        # (assign, reg0, ":head_armor"),
        # (str_store_string, s1, "@Head Armor: {reg0}"),
        # (str_store_string, s2, s1),
        # (assign, reg0, ":body_armor"),
        # (str_store_string, s1, "@Body Armor: {reg0}"),
        # (str_store_string, s2, "@{s2}^^{s1}"),
        # (assign, reg0, ":leg_armor"),
        # (str_store_string, s1, "@Leg Armor: {reg0}"),
        # (str_store_string, s2, "@{s2}^^{s1}"),

        # (create_text_overlay, "$g_presentation_obj_admin_panel_14", s2, tf_center_justify),
        # (position_set_x, pos1, 900),
        # (position_set_y, pos1, 900),
        # (overlay_set_size, "$g_presentation_obj_admin_panel_14", pos1),
        # (position_set_x, pos1, 160),
        # (position_set_y, pos1, ":pos_y"),
        # (overlay_set_position, "$g_presentation_obj_admin_panel_14", pos1),

        (create_button_overlay, "$g_presentation_obj_admin_panel_5", "@Tips", tf_center_justify),
        (overlay_set_color, "$g_presentation_obj_admin_panel_5", 0x00FF00),
        (position_set_x, pos1, 910),
        (position_set_y, pos1, 60),
        (overlay_set_position, "$g_presentation_obj_admin_panel_5", pos1),

        (str_clear, s0),
        (assign, ":area_size_x", 130),
        (assign, ":area_size_y", 600),
        (assign, ":offset_y", 30),
        (create_text_overlay, reg1, s0, tf_scrollable),
        (position_set_x, pos1, 850),
        (position_set_y, pos1, 100),
        (overlay_set_position, reg1, pos1),
        (position_set_x, pos1, ":area_size_x"),
        (position_set_y, pos1, ":area_size_y"),
        (overlay_set_area_size, reg1, pos1),
        (set_container_overlay, reg1),

        (call_script, "script_get_num_heroes_of_party", "p_main_party", 0),
        (assign, ":num_of_heroes", reg0),
        (store_mul, ":pos_y", ":num_of_heroes", ":offset_y"),
        (val_max, ":pos_y", ":area_size_y"),
        (val_sub, ":pos_y", ":offset_y"),
        (store_div, ":pos_x", ":area_size_x", 2),

        (assign, ":trp_slot_prsnt_no", 0),
        (party_get_num_companion_stacks, ":num_stacks", "p_main_party"),
        (try_for_range, ":i_stack", 0, ":num_stacks"),
          (party_stack_get_troop_id, ":stack_troop", "p_main_party", ":i_stack"),
          (troop_is_hero, ":stack_troop"),
          (str_store_troop_name, s1, ":stack_troop"),
          (position_set_x, pos1, ":pos_x"),
          (position_set_y, pos1, ":pos_y"),
          (val_sub, ":pos_y", ":offset_y"),
          (create_button_overlay, reg1, "@{s1}", tf_center_justify),
          (overlay_set_position, reg1, pos1),
          (try_begin),
            (eq, ":stack_troop", "$g_selected_troop"),
            (overlay_set_color, reg1, 0xFFD700),
          (try_end),
          (troop_set_slot, "trp_temp_array_e", ":trp_slot_prsnt_no", reg1),
          (troop_set_slot, "trp_temp_array_a", ":trp_slot_prsnt_no", ":stack_troop"),
          (val_add, ":trp_slot_prsnt_no", 1),
        (try_end),

        (set_container_overlay, -1),

        (str_store_troop_name, s1, "$g_selected_troop"),

        # [TROOP NAME] x=50 y=280 size=900x900
        (create_text_overlay, reg1, s1, tf_double_space|tf_center_justify),
        (position_set_x, pos1, 900),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
        (position_set_x, pos1, 50),
        (position_set_y, pos1, 260),
        (overlay_set_position, reg1, pos1),

        # [CHARACTER MESH] x=-5 y=50 size=675x900
        (store_mul, ":cur_troop", "$g_selected_troop", 2),
        (create_mesh_overlay_with_tableau_material, reg1, -1, "tableau_game_party_window", ":cur_troop"),
        (position_set_x, pos1, 675),
        (position_set_y, pos1, 900),
        (overlay_set_size, reg1, pos1),
        (position_set_x, pos1, -5),
        (position_set_y, pos1, 50),
        (overlay_set_position, reg1, pos1),

        (create_mesh_overlay, "$g_presentation_obj_admin_panel_13", "mesh_inventory_equipment_panel"),
        (position_set_x, pos1, 960),
        (position_set_y, pos1, 960),
        (overlay_set_size, "$g_presentation_obj_admin_panel_13", pos1),
        (position_set_x, pos1, 10),
        (position_set_y, pos1, 15),
        (overlay_set_position, "$g_presentation_obj_admin_panel_13", pos1),
        (overlay_set_alpha, "$g_presentation_obj_admin_panel_13", 0xFF),

        (assign, ":init_pos_x", 219),
        (assign, ":init_pos_y", 683),
        (assign, ":cur_troop", "$g_selected_troop"),

        (create_combo_label_overlay, "$g_presentation_obj_admin_panel_1"),
        (store_add, ":pos_x", ":init_pos_x", 140),
        (store_add, ":pos_y", ":init_pos_y", 2),
        (position_set_x, pos1, ":pos_x"),
        (position_set_y, pos1, ":pos_y"),
        (overlay_set_position, "$g_presentation_obj_admin_panel_1", pos1),
        (position_set_x, pos1, 400),
        (position_set_y, pos1, 750),
        (overlay_set_size, "$g_presentation_obj_admin_panel_1", pos1),
        (overlay_add_item, "$g_presentation_obj_admin_panel_1", "@Arms 1"),
        (overlay_add_item, "$g_presentation_obj_admin_panel_1", "@Arms 2"),
        (overlay_set_val, "$g_presentation_obj_admin_panel_1", "$g_weapons_set_no"),

        (create_text_overlay, reg1, "@Outfit", tf_center_justify),
        (store_add, ":pos_x", ":init_pos_x", -98),
        (store_add, ":pos_y", ":init_pos_y", 2),
        (position_set_x, pos1, ":pos_x"),
        (position_set_y, pos1, ":pos_y"),
        (overlay_set_position, reg1, pos1),
        (create_text_overlay, reg1, "@Horse", tf_center_justify),
        (store_add, ":pos_x", ":init_pos_x", -140),
        (store_add, ":pos_y", ":init_pos_y", -278),
        (position_set_x, pos1, ":pos_x"),
        (position_set_y, pos1, ":pos_y"),
        (overlay_set_position, reg1, pos1),

        (assign, "$g_current_opened_item_details", -1),

        (assign, ":pos_x", ":init_pos_x"),
        (assign, ":pos_y", ":init_pos_y"),
        (try_for_range, ":slot_no", 0, 9),
          (try_begin),
            (eq, ":slot_no", 4),
            (val_sub, ":pos_x", 96),
            (assign, ":pos_y", ":init_pos_y"),
          (else_try),
            (eq, ":slot_no", 7),
            (val_sub, ":pos_x", 84),
            (store_sub, ":pos_y", ":init_pos_y", 85),
          (else_try),
            (eq, ":slot_no", 8),
            (val_sub, ":pos_y", 108),
          (try_end),
          (val_sub, ":pos_y", 85),

          (troop_get_inventory_slot, ":cur_item", ":cur_troop", ":slot_no"),
          (create_mesh_overlay, reg1, "mesh_white_plane"),
          (position_set_x, pos1, 4150),
          (position_set_y, pos1, 4150),
          (overlay_set_size, reg1, pos1),
          (position_set_x, pos1, ":pos_x"),
          (position_set_y, pos1, ":pos_y"),
          (overlay_set_position, reg1, pos1),
          (overlay_set_color, reg1, 0x000000),
          (try_begin),
            (lt, ":cur_item", 0),
            (overlay_set_alpha, reg1, 0x00),
          (else_try),
            (overlay_set_alpha, reg1, 0xFF),
          (try_end),

          (try_begin),
            (lt, ":cur_item", 0),
            (assign, ":cur_item", 0),
          (try_end),
          (create_mesh_overlay_with_item_id, reg1, ":cur_item"),
          (position_set_x, pos1, 850),
          (position_set_y, pos1, 850),
          (overlay_set_size, reg1, pos1),
          (store_add, ":item_x", ":pos_x", 42),
          (store_add, ":item_y", ":pos_y", 42),
          (position_set_x, pos1, ":item_x"),
          (position_set_y, pos1, ":item_y"),
          (overlay_set_position, reg1, pos1),
          (troop_set_slot, "trp_temp_array_d", ":slot_no", reg1),
          (troop_set_slot, "trp_temp_array_c", ":slot_no", 1),

          (create_mesh_overlay, reg1, "mesh_white_plane"),
          (position_set_x, pos1, 4150),
          (position_set_y, pos1, 4150),
          (overlay_set_size, reg1, pos1),
          (position_set_x, pos1, ":pos_x"),
          (position_set_y, pos1, ":pos_y"),
          (overlay_set_position, reg1, pos1),
          (overlay_set_alpha, reg1, 0x00),
          (troop_set_slot, "trp_temp_array_b", ":slot_no", reg1),

          (try_begin),
            (ge, ":cur_item", 0),
            (create_check_box_overlay, reg1, "mesh_checkbox_lock_off", "mesh_checkbox_lock_on"),
            (store_add, ":lock_x", ":pos_x", 62),
            (store_add, ":lock_y", ":pos_y", 1),
            (position_set_x, pos1, ":lock_x"),
            (position_set_y, pos1, ":lock_y"),
            (overlay_set_position, reg1, pos1),
            (troop_get_slot, ":locked", "trp_temp_array_lock", ":slot_no"),
            (overlay_set_val, reg1, ":locked"),
            (troop_set_slot, "trp_temp_array_f", ":slot_no", reg1),
          (else_try),
            (troop_set_slot, "trp_temp_array_f", ":slot_no", -1),
          (try_end),
        (try_end),

        (troop_set_slot, "trp_temp_array_d", 9, -1),
        (troop_set_slot, "trp_temp_array_b", 9, -1),
        (troop_set_slot, "trp_temp_array_c", 9, 0),
        (troop_set_slot, "trp_temp_array_f", 9, -1),

        (assign, ":pos_x", 327),
        (assign, ":pos_y", 647),
        (assign, ":slot_no", 10),
        (troop_get_inventory_capacity, ":inv_cap", "trp_player"),
        (try_for_range, ":unused_height", 0, 8),
          (try_for_range, ":unused_width", 0, 6),
            (create_mesh_overlay, reg1, "mesh_inventory_slot"),
            (position_set_x, pos1, 920),
            (position_set_y, pos1, 920),
            (overlay_set_size, reg1, pos1),
            (position_set_x, pos1, ":pos_x"),
            (position_set_y, pos1, ":pos_y"),
            (overlay_set_position, reg1, pos1),
            (store_mul, ":item_slot_no", "$g_cur_page_of_loot_pool", 48),
            (val_add, ":item_slot_no", ":slot_no"),
            (try_begin),
              (lt, ":item_slot_no", ":inv_cap"),
              (troop_get_inventory_slot, ":item_no", "trp_player", ":item_slot_no"),
              (troop_get_inventory_slot_modifier, ":item_imod", "trp_player", ":item_slot_no"),
            (else_try),
              (assign, ":item_no", -1),
              (assign, ":item_imod", 0),
            (try_end),
            (try_begin),
              (lt, ":item_no", 0),
              (assign, ":item_no", 0),
              (troop_set_slot, "trp_temp_array_c", ":slot_no", 1),
            (else_try),
              (gt, ":item_no", 0),
              (call_script, "script_dplmc_troop_can_use_item", "$g_selected_troop", ":item_no", ":item_imod"),
              (assign, ":can_use", reg0),
              (troop_set_slot, "trp_temp_array_c", ":slot_no", ":can_use"),
            (try_end),
            (create_mesh_overlay_with_item_id, reg1, ":item_no"),
            (position_set_x, pos1, 850),
            (position_set_y, pos1, 850),
            (overlay_set_size, reg1, pos1),
            (store_add, ":item_x", ":pos_x", 42),
            (store_add, ":item_y", ":pos_y", 42),
            (position_set_x, pos1, ":item_x"),
            (position_set_y, pos1, ":item_y"),
            (overlay_set_position, reg1, pos1),
            (troop_set_slot, "trp_temp_array_d", ":slot_no", reg1),

            (create_mesh_overlay, reg1, "mesh_white_plane"),
            (position_set_x, pos1, 4250),
            (position_set_y, pos1, 4250),
            (overlay_set_size, reg1, pos1),
            (position_set_x, pos1, ":pos_x"),
            (position_set_y, pos1, ":pos_y"),
            (overlay_set_position, reg1, pos1),
            (overlay_set_color, reg1, 0xFF0000),
            (overlay_set_alpha, reg1, 0x00),
            (try_begin),
              (troop_slot_eq, "trp_temp_array_c", ":slot_no", 0),
              (overlay_set_alpha, reg1, 0x40),
            (try_end),
            (troop_set_slot, "trp_temp_array_b", ":slot_no", reg1),

            (try_begin),
              (gt, ":item_no", 0),
              (create_check_box_overlay, reg1, "mesh_checkbox_lock_off", "mesh_checkbox_lock_on"),
              (store_add, ":lock_x", ":pos_x", 66),
              (store_add, ":lock_y", ":pos_y", 2),
              (position_set_x, pos1, ":lock_x"),
              (position_set_y, pos1, ":lock_y"),
              (overlay_set_position, reg1, pos1),
              (troop_get_slot, ":locked", "trp_temp_array_lock", ":item_slot_no"),
              (overlay_set_val, reg1, ":locked"),
              (troop_set_slot, "trp_temp_array_f", ":slot_no", reg1),
            (else_try),
              (troop_set_slot, "trp_temp_array_f", ":slot_no", -1),
            (try_end),

            (val_add, ":pos_x", 85),
            (val_add, ":slot_no", 1),
          (try_end),
          (assign, ":pos_x", 327),
          (val_sub, ":pos_y", 85),
        (try_end),
      ]),

    (ti_on_presentation_run,
      [
        (set_fixed_point_multiplier, 1000),

        (try_begin),
          (key_clicked, key_escape),
          (assign, "$g_selected_troop", "trp_player"),
          (call_script, "script_all_toggle_weapons_set", 0),
          (presentation_set_duration, 0),
        (try_end),

        (call_script, "script_get_num_heroes_of_party", "p_main_party", 0),
        (assign, ":num_of_heroes", reg0),
        (assign, ":dest_prsnt_slot", 0),
        (try_for_range, ":trp_slot_prsnt_no", 0, ":num_of_heroes"),
          (troop_slot_eq, "trp_temp_array_a", ":trp_slot_prsnt_no", "$g_selected_troop"),
          (assign, ":dest_prsnt_slot", ":trp_slot_prsnt_no"),
        (try_end),

        (assign, ":value_change", 0),
        (try_begin),
          (this_or_next|key_clicked, key_up),
          (game_key_clicked, gk_move_forward),
          (assign, ":value_change", -1),
        (else_try),
          (this_or_next|key_clicked, key_down),
          (game_key_clicked, gk_move_backward),
          (assign, ":value_change", 1),
        (else_try),
          (this_or_next|key_clicked, key_left),
          (game_key_clicked, gk_move_left),
          (store_sub, ":value_change", 0, ":num_of_heroes"),
        (else_try),
          (this_or_next|key_clicked, key_right),
          (game_key_clicked, gk_move_right),
          (assign, ":value_change", ":num_of_heroes"),
        (try_end),
        (try_begin),
          (store_add, ":new_prsnt_slot", ":dest_prsnt_slot", ":value_change"),
          (val_clamp, ":new_prsnt_slot", 0, ":num_of_heroes"),
          (troop_get_slot, ":new_troop", "trp_temp_array_a", ":new_prsnt_slot"),
          (neq, ":new_troop", "$g_selected_troop"),
          (assign, "$g_selected_troop", ":new_troop"),
          (start_presentation, "prsnt_equip_npcs"),
        (try_end),

        (try_begin),
          (key_clicked, key_f),
          (val_add, "$g_weapons_set_no", 1),
          (val_mod, "$g_weapons_set_no", 2),
          (call_script, "script_all_toggle_weapons_set", 1),
          (start_presentation, "prsnt_equip_npcs"),
        (try_end),

        (try_begin),
          (gt, "$g_cur_selected_item_slot", -1),
          (troop_get_slot, ":object", "trp_temp_array_d", "$g_cur_selected_item_slot"),
          (mouse_get_position, pos1),
          (overlay_set_position, ":object", pos1),
          (position_set_x, pos2, 1700),
          (position_set_y, pos2, 1700),
          (overlay_set_size, ":object", pos2),
        (try_end),
      ]),

    (ti_on_presentation_mouse_press,
     [(store_trigger_param_1, ":object"),
      (store_trigger_param_2, ":mouse_state"),

      (try_for_range, ":slot_no", 0, 58),
        (troop_slot_eq, "trp_temp_array_b", ":slot_no", ":object"),
        (troop_slot_eq, "trp_temp_array_c", ":slot_no", 1),
        (try_begin),
          (is_between, ":slot_no", 0, 9),
          (assign, ":item_slot_no", ":slot_no"),
          (troop_get_inventory_slot, ":cur_item", "$g_selected_troop", ":item_slot_no"),
        (else_try),
          (is_between, ":slot_no", 10, 58),
          (store_mul, ":item_slot_no", "$g_cur_page_of_loot_pool", 48),
          (val_add, ":item_slot_no", ":slot_no"),
          (troop_get_inventory_slot, ":cur_item", "trp_player", ":item_slot_no"),
        (try_end),

        (try_begin),
          (eq, ":mouse_state", 0),
          (try_begin),
            (eq, "$g_cur_selected_item_slot", -1),
            (try_begin),
              (gt, ":cur_item", -1),
              (assign, "$g_cur_selected_item_slot", ":slot_no"),
              (close_item_details),
            (try_end),
          (else_try),
            (try_begin),
              (assign, ":old_slot", "$g_cur_selected_item_slot"),
              (assign, ":new_slot", ":slot_no"),
              (call_script, "script_exchange_two_items_of_slots", ":old_slot", ":new_slot"),
            (try_end),
          (try_end),
        (else_try),
          (eq, ":mouse_state", 1),
          (try_begin),
            (eq, "$g_cur_selected_item_slot", -1),
            (is_between, ":slot_no", 10, 58),
            (gt, ":cur_item", -1),
            (assign, ":old_slot", ":slot_no"),
            (item_get_type, ":old_slot_type", ":cur_item"),
            (try_begin),
              (this_or_next|is_between, ":old_slot_type", itp_type_one_handed_wpn, itp_type_goods),
              (is_between, ":old_slot_type", itp_type_pistol, itp_type_animal),
              (assign, ":old_slot_type", itp_type_one_handed_wpn),
            (try_end),
            (assign, ":end_cond", 9),
            (try_for_range, ":new_slot", 0, ":end_cond"),
              (try_begin),
                (is_between, ":new_slot", 0, 4),
                (assign, ":new_slot_type", itp_type_one_handed_wpn),
                (troop_get_inventory_slot, ":new_item", "$g_selected_troop", ":new_slot"),
                (try_begin),
                  (gt, ":new_item", -1),
                  (assign, ":new_slot_type", -1),
                (try_end),
              (else_try),
                (is_between, ":new_slot", 4, 8),
                (store_add, ":new_slot_type", ":new_slot", 8),
              (else_try),
                (eq, ":new_slot", 8),
                (assign, ":new_slot_type", itp_type_horse),
              (try_end),
              (eq, ":new_slot_type", ":old_slot_type"),
              (assign, ":end_cond", 0),
              (call_script, "script_exchange_two_items_of_slots", ":old_slot", ":new_slot"),
            (try_end),
          (try_end),
        (try_end),
      (try_end),
    ]),

    (ti_on_presentation_mouse_enter_leave,
      [
      (store_trigger_param_1, ":object"),
      (store_trigger_param_2, ":enter_leave"),

      (try_begin),
        (eq, ":enter_leave", 0),
        (try_for_range, ":slot_no", 0, 58),
          (troop_slot_eq, "trp_temp_array_b", ":slot_no", ":object"),
          (troop_get_slot, ":item_object", "trp_temp_array_d", ":slot_no"),
          (overlay_get_position, pos0, ":item_object"),
          (try_begin),
            (is_between, ":slot_no", 0, 9),
            (troop_get_inventory_slot, ":cur_item", "$g_selected_troop", ":slot_no"),
            (troop_get_inventory_slot_modifier, ":cur_imod", "$g_selected_troop", ":slot_no"),
          (else_try),
            (is_between, ":slot_no", 10, 58),
            (store_mul, ":item_slot_no", "$g_cur_page_of_loot_pool", 48),
            (val_add, ":item_slot_no", ":slot_no"),
            (troop_get_inventory_slot, ":cur_item", "trp_player", ":item_slot_no"),
            (troop_get_inventory_slot_modifier, ":cur_imod", "trp_player", ":item_slot_no"),
          (try_end),
          (eq, "$g_cur_selected_item_slot", -1),
          (gt, ":cur_item", -1),
          (try_begin),
            (gt, ":cur_imod", 0),
            (show_item_details_with_modifier, ":cur_item", ":cur_imod", pos0, 100),
          (else_try),
            (show_item_details, ":cur_item", pos0, 100),
          (try_end),
          (assign, "$g_current_opened_item_details", ":slot_no"),
        (try_end),
      (else_try),
        (try_for_range, ":slot_no", 0, 58),
          (troop_slot_eq, "trp_temp_array_b", ":slot_no", ":object"),
          (try_begin),
            (eq, "$g_current_opened_item_details", ":slot_no"),
            (close_item_details),
          (try_end),
        (try_end),
      (try_end),
    ]),

    (ti_on_presentation_event_state_change,
      [
        (store_trigger_param_1, ":object"),
        (store_trigger_param_2, ":value"),

        (try_begin),
          (eq, ":object", "$g_presentation_obj_admin_panel_12"),
          (troop_set_slot, "$g_selected_troop", dplmc_slot_upgrade_wpn_3, ":value"),
        (else_try),
          (eq, ":object", "$g_presentation_obj_admin_panel_11"),
          (troop_set_slot, "$g_selected_troop", dplmc_slot_upgrade_wpn_2, ":value"),
        (else_try),
          (eq, ":object", "$g_presentation_obj_admin_panel_10"),
          (troop_set_slot, "$g_selected_troop", dplmc_slot_upgrade_wpn_1, ":value"),
        (else_try),
          (eq, ":object", "$g_presentation_obj_admin_panel_9"),
          (troop_set_slot, "$g_selected_troop", dplmc_slot_upgrade_wpn_0, ":value"),
        (else_try),
          (eq, ":object", "$g_presentation_obj_admin_panel_7"),
          (troop_set_slot, "$g_selected_troop", dplmc_slot_upgrade_armor, ":value"),
        (else_try),
          (eq, ":object", "$g_presentation_obj_admin_panel_8"),
          (troop_set_slot, "$g_selected_troop", dplmc_slot_upgrade_horse, ":value"),
        (else_try),
          (eq, ":object", "$g_presentation_obj_admin_panel_15"),
          (assign, "$g_autoloot_mass_action_mode", ":value"),
          (start_presentation, "prsnt_equip_npcs"),
        (else_try),
          (eq, ":object", "$g_presentation_obj_admin_panel_19"),
          (try_begin),
            (eq, "$g_autoloot_mass_action_mode", 0),
            (party_get_num_companion_stacks, ":num_stacks", "p_main_party"),
            (try_for_range, ":i_stack", 0, ":num_stacks"),
              (party_stack_get_troop_id, ":stack_troop", "p_main_party", ":i_stack"),
              (troop_is_hero, ":stack_troop"),
              (try_for_range, ":slot_no", 0, 9),
                (troop_get_slot, ":locked", "trp_temp_array_lock", ":slot_no"),
                (store_add, ":backup_slot", ":slot_no", 100),
                (troop_set_slot, "trp_temp_array_lock", ":backup_slot", ":locked"),
                (try_begin),
                  (eq, ":slot_no", 0),
                  (troop_get_slot, ":do_upgrade", "$g_selected_troop", dplmc_slot_upgrade_wpn_0),
                (else_try),
                  (eq, ":slot_no", 1),
                  (troop_get_slot, ":do_upgrade", "$g_selected_troop", dplmc_slot_upgrade_wpn_1),
                (else_try),
                  (eq, ":slot_no", 2),
                  (troop_get_slot, ":do_upgrade", "$g_selected_troop", dplmc_slot_upgrade_wpn_2),
                (else_try),
                  (eq, ":slot_no", 3),
                  (troop_get_slot, ":do_upgrade", "$g_selected_troop", dplmc_slot_upgrade_wpn_3),
                (else_try),
                  (is_between, ":slot_no", 4, 8),
                  (troop_get_slot, ":do_upgrade", "$g_selected_troop", dplmc_slot_upgrade_armor),
                (else_try),
                  (eq, ":slot_no", 8),
                  (troop_get_slot, ":do_upgrade", "$g_selected_troop", dplmc_slot_upgrade_horse),
                (try_end),
                (eq, ":do_upgrade", 0),
                (troop_set_slot, "trp_temp_array_lock", ":slot_no", 1),
              (try_end),
              (call_script, "script_upgrade_armors_and_horse_for_troop", ":stack_troop"),
              (call_script, "script_upgrade_weapons_for_troop", ":stack_troop"),
              (try_for_range, ":slot_no", 0, 9),
                (store_add, ":backup_slot", ":slot_no", 100),
                (troop_get_slot, ":locked", "trp_temp_array_lock", ":backup_slot"),
                (troop_set_slot, "trp_temp_array_lock", ":slot_no", ":locked"),
              (try_end),
            (try_end),
           (else_try),
             (eq, "$g_autoloot_mass_action_mode", 1),
             (party_get_num_companion_stacks, ":num_stacks", "p_main_party"),
             (try_for_range, ":i_stack", 0, ":num_stacks"),
               (party_stack_get_troop_id, ":stack_troop", "p_main_party", ":i_stack"),
               (troop_is_hero, ":stack_troop"),
               (neq, ":stack_troop", "trp_player"),
               (try_for_range, ":slot_no", 0, 9),
                 (try_begin),
                   (eq, ":slot_no", 0),
                   (troop_get_slot, ":do_upgrade", "$g_selected_troop", dplmc_slot_upgrade_wpn_0),
                 (else_try),
                   (eq, ":slot_no", 1),
                   (troop_get_slot, ":do_upgrade", "$g_selected_troop", dplmc_slot_upgrade_wpn_1),
                 (else_try),
                   (eq, ":slot_no", 2),
                   (troop_get_slot, ":do_upgrade", "$g_selected_troop", dplmc_slot_upgrade_wpn_2),
                 (else_try),
                   (eq, ":slot_no", 3),
                   (troop_get_slot, ":do_upgrade", "$g_selected_troop", dplmc_slot_upgrade_wpn_3),
                 (else_try),
                   (is_between, ":slot_no", 4, 8),
                   (troop_get_slot, ":do_upgrade", "$g_selected_troop", dplmc_slot_upgrade_armor),
                 (else_try),
                   (eq, ":slot_no", 8),
                   (troop_get_slot, ":do_upgrade", "$g_selected_troop", dplmc_slot_upgrade_horse),
                 (try_end),
                 (eq, ":do_upgrade", 1),
                 (troop_get_inventory_slot, ":cur_item", ":stack_troop", ":slot_no"),
                 (gt, ":cur_item", -1),
                 (troop_get_inventory_slot_modifier, ":cur_imod", ":stack_troop", ":slot_no"),
                 (troop_set_inventory_slot, ":stack_troop", ":slot_no", -1),
                 (troop_set_inventory_slot_modifier, ":stack_troop", ":slot_no", 0),
                 (troop_get_inventory_capacity, ":inv_cap", "trp_player"),
                 (assign, ":end", ":inv_cap"),
                 (try_for_range, ":i_slot", 10, ":end"),
                   (troop_get_inventory_slot, ":empty_item", "trp_player", ":i_slot"),
                   (eq, ":empty_item", -1),
                   (troop_set_inventory_slot, "trp_player", ":i_slot", ":cur_item"),
                   (troop_set_inventory_slot_modifier, "trp_player", ":i_slot", ":cur_imod"),
                   (assign, ":end", 0),
                 (try_end),
                 (try_begin),
                   (eq, ":end", ":inv_cap"),
                   (troop_add_item, "trp_player", ":cur_item"),
                   (try_for_range, ":i_slot", 10, ":inv_cap"),
                     (troop_get_inventory_slot, ":check_item", "trp_player", ":i_slot"),
                     (eq, ":check_item", ":cur_item"),
                     (troop_get_inventory_slot_modifier, ":check_imod", "trp_player", ":i_slot"),
                     (eq, ":check_imod", 0),
                     (neq, ":cur_imod", 0),
                     (troop_set_inventory_slot_modifier, "trp_player", ":i_slot", ":cur_imod"),
                     (assign, ":inv_cap", 0),
                   (try_end),
                 (try_end),
               (try_end),
             (try_end),
           (else_try),
             (eq, "$g_autoloot_mass_action_mode", 2),
             (party_get_num_companion_stacks, ":num_stacks", "p_main_party"),
             (try_for_range, ":i_stack", 0, ":num_stacks"),
               (party_stack_get_troop_id, ":stack_troop", "p_main_party", ":i_stack"),
               (troop_is_hero, ":stack_troop"),
               (neq, ":stack_troop", "trp_player"),
               (neq, ":stack_troop", "$g_selected_troop"),
               (try_for_range, ":slot_no", 0, 9),
                 (try_begin),
                   (eq, ":slot_no", 0),
                   (troop_get_slot, ":do_upgrade", "$g_selected_troop", dplmc_slot_upgrade_wpn_0),
                 (else_try),
                   (eq, ":slot_no", 1),
                   (troop_get_slot, ":do_upgrade", "$g_selected_troop", dplmc_slot_upgrade_wpn_1),
                 (else_try),
                   (eq, ":slot_no", 2),
                   (troop_get_slot, ":do_upgrade", "$g_selected_troop", dplmc_slot_upgrade_wpn_2),
                 (else_try),
                   (eq, ":slot_no", 3),
                   (troop_get_slot, ":do_upgrade", "$g_selected_troop", dplmc_slot_upgrade_wpn_3),
                 (else_try),
                   (is_between, ":slot_no", 4, 8),
                   (troop_get_slot, ":do_upgrade", "$g_selected_troop", dplmc_slot_upgrade_armor),
                 (else_try),
                   (eq, ":slot_no", 8),
                   (troop_get_slot, ":do_upgrade", "$g_selected_troop", dplmc_slot_upgrade_horse),
                 (try_end),
                 (eq, ":do_upgrade", 1),
                 (troop_get_inventory_slot, ":source_item", "$g_selected_troop", ":slot_no"),
                 (gt, ":source_item", -1),
                 (troop_get_inventory_slot_modifier, ":source_imod", "$g_selected_troop", ":slot_no"),
                 (troop_get_inventory_capacity, ":inv_cap", "trp_player"),
                 (assign, ":found_slot", -1),
                 (try_for_range, ":p_slot", 10, ":inv_cap"),
                   (eq, ":found_slot", -1),
                   (troop_get_inventory_slot, ":p_item", "trp_player", ":p_slot"),
                   (eq, ":p_item", ":source_item"),
                   (troop_get_inventory_slot_modifier, ":p_imod", "trp_player", ":p_slot"),
                   (eq, ":p_imod", ":source_imod"),
                   (assign, ":found_slot", ":p_slot"),
                 (try_end),
                 (neq, ":found_slot", -1),
                 (troop_set_inventory_slot, "trp_player", ":found_slot", -1),
                 (troop_set_inventory_slot_modifier, "trp_player", ":found_slot", 0),
                 (troop_get_inventory_slot, ":target_item", ":stack_troop", ":slot_no"),
                 (troop_get_inventory_slot_modifier, ":target_imod", ":stack_troop", ":slot_no"),
                 (try_begin),
                   (gt, ":target_item", -1),
                   (this_or_next|neq, ":target_item", ":source_item"),
                   (neq, ":target_imod", ":source_imod"),
                   (assign, ":end", ":inv_cap"),
                   (try_for_range, ":p_slot2", 10, ":end"),
                     (troop_get_inventory_slot, ":empty", "trp_player", ":p_slot2"),
                     (eq, ":empty", -1),
                     (troop_set_inventory_slot, "trp_player", ":p_slot2", ":target_item"),
                     (troop_set_inventory_slot_modifier, "trp_player", ":p_slot2", ":target_imod"),
                     (assign, ":end", 0),
                   (try_end),
                   (try_begin),
                     (eq, ":end", ":inv_cap"),
                     (troop_add_item, "trp_player", ":target_item"),
                     (neq, ":target_imod", 0),
                     (try_for_range, ":p_slot2", 10, ":inv_cap"),
                       (troop_get_inventory_slot, ":chk", "trp_player", ":p_slot2"),
                       (eq, ":chk", ":target_item"),
                       (troop_get_inventory_slot_modifier, ":chk_imod", "trp_player", ":p_slot2"),
                       (eq, ":chk_imod", 0),
                       (troop_set_inventory_slot_modifier, "trp_player", ":p_slot2", ":target_imod"),
                       (assign, ":inv_cap", 0),
                     (try_end),
                   (try_end),
                 (try_end),
                  (troop_set_inventory_slot, ":stack_troop", ":slot_no", ":source_item"),
                  (troop_set_inventory_slot_modifier, ":stack_troop", ":slot_no", ":source_imod"),
                (try_end),
              (try_end),
          (else_try),
            (eq, "$g_autoloot_mass_action_mode", 3),
            (ge, "$cheat_mode", 1),
            (party_get_num_companion_stacks, ":num_stacks", "p_main_party"),
            (try_for_range, ":i_stack", 0, ":num_stacks"),
              (party_stack_get_troop_id, ":stack_troop", "p_main_party", ":i_stack"),
              (troop_is_hero, ":stack_troop"),
              (neq, ":stack_troop", "trp_player"),
              (neq, ":stack_troop", "$g_selected_troop"),
              (try_for_range, ":slot_no", 0, 9),
                (try_begin),
                  (eq, ":slot_no", 0),
                  (troop_get_slot, ":do_upgrade", "$g_selected_troop", dplmc_slot_upgrade_wpn_0),
                (else_try),
                  (eq, ":slot_no", 1),
                  (troop_get_slot, ":do_upgrade", "$g_selected_troop", dplmc_slot_upgrade_wpn_1),
                (else_try),
                  (eq, ":slot_no", 2),
                  (troop_get_slot, ":do_upgrade", "$g_selected_troop", dplmc_slot_upgrade_wpn_2),
                (else_try),
                  (eq, ":slot_no", 3),
                  (troop_get_slot, ":do_upgrade", "$g_selected_troop", dplmc_slot_upgrade_wpn_3),
                (else_try),
                  (is_between, ":slot_no", 4, 8),
                  (troop_get_slot, ":do_upgrade", "$g_selected_troop", dplmc_slot_upgrade_armor),
                (else_try),
                  (eq, ":slot_no", 8),
                  (troop_get_slot, ":do_upgrade", "$g_selected_troop", dplmc_slot_upgrade_horse),
                (try_end),
                (eq, ":do_upgrade", 1),
                (troop_get_inventory_slot, ":source_item", "$g_selected_troop", ":slot_no"),
                (gt, ":source_item", -1),
                (troop_get_inventory_slot_modifier, ":source_imod", "$g_selected_troop", ":slot_no"),
                (troop_get_inventory_slot, ":target_item", ":stack_troop", ":slot_no"),
                (try_begin),
                  (gt, ":target_item", -1),
                  (neq, ":target_item", ":source_item"),
                  (troop_add_item, "trp_player", ":target_item"),
                (try_end),
                (troop_set_inventory_slot, ":stack_troop", ":slot_no", ":source_item"),
                (troop_set_inventory_slot_modifier, ":stack_troop", ":slot_no", ":source_imod"),
              (try_end),
            (try_end),
           (try_end),
           (start_presentation, "prsnt_equip_npcs"),
         (else_try),
           (eq, ":object", "$g_presentation_obj_admin_panel_5"),
          (tutorial_box, "@Left - drag: exchange items manually^Right - click: auto-stow item into matching equipment slot\
^^Up/Down Arrow: switch hero^Left/Right Arrow: jump to first/last hero^Key F: toggle weapon set^Key Escape: close^^Lock items to prevent auto-sort and auto-upgrade.", "@Tips"),
        (else_try),
          (eq, ":object", "$g_presentation_obj_admin_panel_4"),
          (call_script, "script_sort_player_inventory_by_item_type"),
          (start_presentation, "prsnt_equip_npcs"),
        (else_try),
          (eq, ":object", "$g_presentation_obj_admin_panel_1"),
          (assign, "$g_weapons_set_no", ":value"),
          (call_script, "script_all_toggle_weapons_set", 1),
          (start_presentation, "prsnt_equip_npcs"),
        (else_try),
          (eq, ":object", "$g_presentation_obj_admin_panel_3"),
          (assign, "$g_cur_page_of_loot_pool", ":value"),
          (start_presentation, "prsnt_equip_npcs"),
        (else_try),
          (eq, ":object", "$g_presentation_obj_admin_panel_2"),
          (assign, "$g_selected_troop", "trp_player"),
          (call_script, "script_all_toggle_weapons_set", 0),
          (presentation_set_duration, 0),
        (try_end),

        (call_script, "script_get_num_heroes_of_party", "p_main_party", 0),
        (assign, ":num_of_heroes", reg0),
        (try_for_range, ":trp_slot_prsnt_no", 0, ":num_of_heroes"),
          (troop_slot_eq, "trp_temp_array_e", ":trp_slot_prsnt_no", ":object"),
          (troop_get_slot, ":cur_troop", "trp_temp_array_a", ":trp_slot_prsnt_no"),
          (assign, "$g_selected_troop", ":cur_troop"),
          (start_presentation, "prsnt_equip_npcs"),
        (try_end),

        (assign, ":upper_bound", 58),
        (try_for_range, ":slot_no", 0, ":upper_bound"),
          (troop_slot_eq, "trp_temp_array_f", ":slot_no", ":object"),
          (try_begin),
            (is_between, ":slot_no", 0, 9),
            (troop_set_slot, "trp_temp_array_lock", ":slot_no", ":value"),
          (else_try),
            (is_between, ":slot_no", 10, 58),
            (store_mul, ":item_slot_no", "$g_cur_page_of_loot_pool", 48),
            (val_add, ":item_slot_no", ":slot_no"),
            (troop_set_slot, "trp_temp_array_lock", ":item_slot_no", ":value"),
          (try_end),
          (assign, ":upper_bound", 0),
        (try_end),
      ]),
])
