# -*- coding: cp1254 -*-
import string
from header_common import *
from header_presentations import *
from header_mission_templates import *
from ID_meshes import *
from header_operations import *
from header_triggers import *
from module_constants import *
from header_terrain_types import *
from module_items import *
from module_factions import *
from header_items import *
from compiler import *

party_size_and_morale = ("party_size_and_morale", 0, mesh_load_window, [
    (ti_on_presentation_load,
      [
        (presentation_set_duration, 999999),
        (set_fixed_point_multiplier, 1000),

        (create_text_overlay, reg1, "@Party Morale", tf_center_justify),
        (position_set_x, pos1, 1500),
        (position_set_y, pos1, 1500),
        (overlay_set_size, reg1, pos1),
        (position_set_x, pos1, 260),
        (position_set_y, pos1, 650),
        (overlay_set_position, reg1, pos1),

        (position_set_x, pos3, 900),
        (position_set_y, pos3, 900),
        (position_set_x, pos1, 80),
        (position_set_x, pos2, 440),
        (assign, ":cur_y", 600),
        (assign, ":y_offset", 30),

        (call_script, "script_get_player_party_morale_values"),
        (assign, ":ideal_morale", reg1),

        (create_text_overlay, reg1, "@Base morale", tf_left_align),
        (position_set_y, pos1, ":cur_y"),
        (overlay_set_position, reg1, pos1),
        (overlay_set_size, reg1, pos3),
        (create_text_overlay, reg1, "@+50", tf_right_align),
        (position_set_y, pos2, ":cur_y"),
        (overlay_set_position, reg1, pos2),
        (overlay_set_color, reg1, 0x00AA00),
        (overlay_set_size, reg1, pos3),
        (val_sub, ":cur_y", ":y_offset"),

        (assign, reg0, "$g_player_party_morale_modifier_party_size"),
        (create_text_overlay, reg1, "@Party size", tf_left_align),
        (position_set_y, pos1, ":cur_y"),
        (overlay_set_position, reg1, pos1),
        (overlay_set_size, reg1, pos3),
        (try_begin),
          (gt, reg0, 0),
          (str_store_string, s1, "@-{reg0}"),
          (assign, ":dest_color", 0xAA0000),
        (else_try),
          (eq, reg0, 0),
          (str_store_string, s1, "@{reg0}"),
          (assign, ":dest_color", 0x000000),
        (try_end),
        (create_text_overlay, reg1, s1, tf_right_align),
        (position_set_y, pos2, ":cur_y"),
        (overlay_set_position, reg1, pos2),
        (overlay_set_color, reg1, ":dest_color"),
        (overlay_set_size, reg1, pos3),
        (val_sub, ":cur_y", ":y_offset"),

        (assign, reg0, "$g_player_party_morale_modifier_leadership"),
        (create_text_overlay, reg1, "@Leadership", tf_left_align),
        (position_set_y, pos1, ":cur_y"),
        (overlay_set_position, reg1, pos1),
        (overlay_set_size, reg1, pos3),
        (try_begin),
          (gt, reg0, 0),
          (str_store_string, s1, "@+{reg0}"),
          (assign, ":dest_color", 0x00AA00),
        (else_try),
          (eq, reg0, 0),
          (str_store_string, s1, "@{reg0}"),
          (assign, ":dest_color", 0x000000),
        (try_end),
        (create_text_overlay, reg1, s1, tf_right_align),
        (position_set_y, pos2, ":cur_y"),
        (overlay_set_position, reg1, pos2),
        (overlay_set_color, reg1, ":dest_color"),
        (overlay_set_size, reg1, pos3),
        (val_sub, ":cur_y", ":y_offset"),

        (store_character_level, ":player_level", "trp_player"),
        (val_mul, ":player_level", 3),
        (assign, reg0, ":player_level"),
        (create_text_overlay, reg1, "@Player's level", tf_left_align),
        (position_set_y, pos1, ":cur_y"),
        (overlay_set_position, reg1, pos1),
        (overlay_set_size, reg1, pos3),
        (create_text_overlay, reg1, "@+{reg0}", tf_right_align),
        (position_set_y, pos2, ":cur_y"),
        (overlay_set_position, reg1, pos2),
        (overlay_set_color, reg1, 0x00AA00),
        (overlay_set_size, reg1, pos3),
        (val_sub, ":cur_y", ":y_offset"),

        (try_begin),
          (eq, "$g_player_party_morale_modifier_food", 0),
          (str_store_string, s1, "@No food"),
          (assign, reg0, "$g_player_party_morale_modifier_no_food"),
          (str_store_string, s2, "@-{reg0}"),
          (assign, ":dest_color", 0xAA0000),
        (else_try),
          (str_store_string, s1, "@Food variety"),
          (assign, reg0, "$g_player_party_morale_modifier_food"),
          (str_store_string, s2, "@+{reg0}"),
          (assign, ":dest_color", 0x00AA00),
        (try_end),
        (create_text_overlay, reg1, s1, tf_left_align),
        (position_set_y, pos1, ":cur_y"),
        (overlay_set_position, reg1, pos1),
        (overlay_set_size, reg1, pos3),
        (create_text_overlay, reg1, s2, tf_right_align),
        (position_set_y, pos2, ":cur_y"),
        (overlay_set_position, reg1, pos2),
        (overlay_set_color, reg1, ":dest_color"),
        (overlay_set_size, reg1, pos3),
        (val_sub, ":cur_y", ":y_offset"),

        (try_begin),
          (gt, "$g_player_party_morale_modifier_debt", 0),
          (assign, reg0, "$g_player_party_morale_modifier_debt"),
          (create_text_overlay, reg1, "@Wage debt", tf_left_align),
          (position_set_y, pos1, ":cur_y"),
          (overlay_set_position, reg1, pos1),
          (overlay_set_size, reg1, pos3),
          (create_text_overlay, reg1, "@-{reg0}", tf_right_align),
          (position_set_y, pos2, ":cur_y"),
          (overlay_set_position, reg1, pos2),
          (overlay_set_color, reg1, 0xAA0000),
          (overlay_set_size, reg1, pos3),
          (val_sub, ":cur_y", ":y_offset"),
        (try_end),

        (create_text_overlay, reg1, "@Recent events", tf_left_align),
        (position_set_y, pos1, ":cur_y"),
        (overlay_set_position, reg1, pos1),
        (overlay_set_size, reg1, pos3),
        (party_get_morale, ":cur_morale", "p_main_party"),
        (store_sub, reg0, ":cur_morale", ":ideal_morale"),
        (try_begin),
          (gt, reg0, 0),
          (str_store_string, s1, "@+{reg0}"),
          (assign, ":dest_color", 0x00AA00),
        (else_try),
          (eq, reg0, 0),
          (str_store_string, s1, "@{reg0}"),
          (assign, ":dest_color", 0x000000),
        (else_try),
          (str_store_string, s1, "@{reg0}"),
          (assign, ":dest_color", 0xAA0000),
        (try_end),
        (create_text_overlay, reg1, s1, tf_right_align),
        (position_set_y, pos2, ":cur_y"),
        (overlay_set_position, reg1, pos2),
        (overlay_set_color, reg1, ":dest_color"),
        (overlay_set_size, reg1, pos3),
        (val_sub, ":cur_y", ":y_offset"),

        (store_mul, ":line_offset", ":y_offset", 75),
        (val_div, ":line_offset", 100),
        (store_add, ":line_pos_y", ":cur_y", ":line_offset"),
        (call_script, "script_prsnt_line", 360, 1, 80, ":line_pos_y", 0),

        (create_text_overlay, reg1, "@Total", tf_left_align),
        (position_set_y, pos1, ":cur_y"),
        (overlay_set_position, reg1, pos1),
        (party_get_morale, reg0, "p_main_party"),
        (overlay_set_size, reg1, pos3),
        (create_text_overlay, reg1, "@{reg0}", tf_right_align),
        (position_set_y, pos2, ":cur_y"),
        (overlay_set_position, reg1, pos2),
        (overlay_set_size, reg1, pos3),
        (val_sub, ":cur_y", ":y_offset"),

        (party_get_morale, ":cur_morale", "p_main_party"),
        (store_sub, ":dif", ":ideal_morale", ":cur_morale"),
        (store_skill_level, ":skill", "skl_leadership", "trp_player"),
        (try_begin),
          (gt, ":dif", 0),
          (store_add, ":morale_change_factor", 20, ":skill"),
        (else_try),
          (store_sub, ":morale_change_factor", 20, ":skill"),
        (try_end),
        (store_mul, ":dif_to_add", ":dif", ":morale_change_factor"),
        (val_div, ":dif_to_add", 100),
        (store_mul, ":dif_to_add_correction", ":dif_to_add", 100),
        (val_div, ":dif_to_add_correction", ":morale_change_factor"),
        (try_begin),
          (neq, ":dif_to_add_correction", ":dif"),
          (try_begin),
            (gt, ":dif", 0),
            (val_add, ":dif_to_add", 1),
          (else_try),
            (val_sub, ":dif_to_add", 1),
          (try_end),
        (try_end),
        (store_add, ":dest_morale", ":cur_morale", ":dif_to_add"),
        (val_clamp, ":dest_morale", 0, 100),
        (store_sub, ":morale_to_change", ":dest_morale", ":cur_morale"),
        (create_text_overlay, reg1, "@Morale value to change", tf_left_align),
        (position_set_y, pos1, ":cur_y"),
        (overlay_set_position, reg1, pos1),
        (overlay_set_size, reg1, pos3),
        (assign, reg0, ":morale_to_change"),
        (try_begin),
          (gt, reg0, 0),
          (str_store_string, s1, "@+{reg0}"),
          (assign, ":dest_color", 0x00AA00),
        (else_try),
          (eq, reg0, 0),
          (str_store_string, s1, "@{reg0}"),
          (assign, ":dest_color", 0x000000),
        (else_try),
          (str_store_string, s1, "@{reg0}"),
          (assign, ":dest_color", 0xAA0000),
        (try_end),
        (create_text_overlay, reg1, s1, tf_right_align),
        (position_set_y, pos2, ":cur_y"),
        (overlay_set_position, reg1, pos2),
        (overlay_set_color, reg1, ":dest_color"),
        (overlay_set_size, reg1, pos3),
        (val_sub, ":cur_y", ":y_offset"),
        (create_text_overlay, reg1, "@Prospective party morale", tf_left_align),
        (position_set_y, pos1, ":cur_y"),
        (overlay_set_position, reg1, pos1),
        (assign, reg0, ":dest_morale"),
        (overlay_set_size, reg1, pos3),
        (create_text_overlay, reg1, "@{reg0}", tf_right_align),
        (position_set_y, pos2, ":cur_y"),
        (overlay_set_position, reg1, pos2),
        (overlay_set_size, reg1, pos3),
        (val_sub, ":cur_y", ":y_offset"),

        (val_sub, ":cur_y", ":y_offset"),
        (val_sub, ":cur_y", ":y_offset"),
        (try_for_range, ":kingdom_no", npc_kingdoms_begin, npc_kingdoms_end),
          (faction_get_slot, ":faction_morale", ":kingdom_no", slot_faction_morale_of_player_troops),
          (val_div, ":faction_morale", 100),
          (neq, ":faction_morale", 0),
          (assign, reg0, ":faction_morale"),
          (str_store_faction_name, s1, ":kingdom_no"),
          (create_text_overlay, reg1, "@Extra morale for {s1} troops", tf_left_align),
          (position_set_y, pos1, ":cur_y"),
          (overlay_set_position, reg1, pos1),
          (overlay_set_size, reg1, pos3),
          (try_begin),
            (gt, reg0, 0),
            (str_store_string, s1, "@+{reg0}"),
            (assign, ":dest_color", 0x00AA00),
          (else_try),
            (str_store_string, s1, "@{reg0}"),
            (assign, ":dest_color", 0xAA0000),
          (try_end),
          (create_text_overlay, reg1, s1, tf_right_align),
          (position_set_y, pos2, ":cur_y"),
          (overlay_set_position, reg1, pos2),
          (overlay_set_color, reg1, ":dest_color"),
          (overlay_set_size, reg1, pos3),
          (val_sub, ":cur_y", ":y_offset"),
        (try_end),

        (create_text_overlay, reg1, "@Party Size", tf_center_justify),
        (position_set_x, pos1, 1500),
        (position_set_y, pos1, 1500),
        (overlay_set_size, reg1, pos1),
        (position_set_x, pos1, 740),
        (position_set_y, pos1, 650),
        (overlay_set_position, reg1, pos1),

        (position_set_x, pos1, 560),
        (position_set_x, pos2, 920),
        (assign, ":cur_y", 600),
        (assign, ":y_offset", 30),

        (create_text_overlay, reg1, "@Base size", tf_left_align),
        (position_set_y, pos1, ":cur_y"),
        (overlay_set_position, reg1, pos1),
        (overlay_set_size, reg1, pos3),
        (create_text_overlay, reg1, "@+30", tf_right_align),
        (position_set_y, pos2, ":cur_y"),
        (overlay_set_position, reg1, pos2),
        (overlay_set_size, reg1, pos3),
        (val_sub, ":cur_y", ":y_offset"),

        (create_text_overlay, reg1, "@Player's level", tf_left_align),
        (position_set_y, pos1, ":cur_y"),
        (overlay_set_position, reg1, pos1),
        (overlay_set_size, reg1, pos3),
        (store_character_level, ":troop_level", "trp_player"),
        (store_mul, reg0, ":troop_level", 2),
        (create_text_overlay, reg1, "@+{reg0}", tf_right_align),
        (position_set_y, pos2, ":cur_y"),
        (overlay_set_position, reg1, pos2),
        (overlay_set_size, reg1, pos3),
        (val_sub, ":cur_y", ":y_offset"),

        (create_text_overlay, reg1, "@Leadership", tf_left_align),
        (position_set_y, pos1, ":cur_y"),
        (overlay_set_position, reg1, pos1),
        (overlay_set_size, reg1, pos3),
        (store_skill_level, ":leadership", "skl_leadership", "trp_player"),
        (store_mul, reg0, ":leadership", 10),
        (try_begin),
          (gt, reg0, 0),
          (str_store_string, s1, "@+{reg0}"),
        (else_try),
          (str_store_string, s1, "@{reg0}"),
        (try_end),
        (create_text_overlay, reg1, s1, tf_right_align),
        (position_set_y, pos2, ":cur_y"),
        (overlay_set_position, reg1, pos2),
        (overlay_set_size, reg1, pos3),
        (val_sub, ":cur_y", ":y_offset"),

        (create_text_overlay, reg1, "@Charisma", tf_left_align),
        (position_set_y, pos1, ":cur_y"),
        (overlay_set_position, reg1, pos1),
        (overlay_set_size, reg1, pos3),
        (store_attribute_level, reg0, "trp_player", ca_charisma),
        (try_begin),
          (gt, reg0, 0),
          (str_store_string, s1, "@+{reg0}"),
        (else_try),
          (str_store_string, s1, "@{reg0}"),
        (try_end),
        (create_text_overlay, reg1, s1, tf_right_align),
        (position_set_y, pos2, ":cur_y"),
        (overlay_set_position, reg1, pos2),
        (overlay_set_size, reg1, pos3),
        (val_sub, ":cur_y", ":y_offset"),

        (create_text_overlay, reg1, "@Renown", tf_left_align),
        (position_set_y, pos1, ":cur_y"),
        (overlay_set_position, reg1, pos1),
        (overlay_set_size, reg1, pos3),
        (troop_get_slot, ":renown", "trp_player", slot_troop_renown),
        (store_div, reg0, ":renown", 25),
        (try_begin),
          (gt, reg0, 0),
          (str_store_string, s1, "@+{reg0}"),
        (else_try),
          (str_store_string, s1, "@{reg0}"),
        (try_end),
        (create_text_overlay, reg1, s1, tf_right_align),
        (position_set_y, pos2, ":cur_y"),
        (overlay_set_position, reg1, pos2),
        (overlay_set_size, reg1, pos3),
        (val_sub, ":cur_y", ":y_offset"),

        (create_text_overlay, reg1, "@Castles", tf_left_align),
        (position_set_y, pos1, ":cur_y"),
        (overlay_set_position, reg1, pos1),
        (overlay_set_size, reg1, pos3),
        (assign, ":center_bonus", 0),
        (try_for_range, ":cur_center", castles_begin, castles_end),
          (party_slot_eq, ":cur_center", slot_town_lord, "trp_player"),
          (val_add, ":center_bonus", 20),
        (try_end),
        (assign, reg0, ":center_bonus"),
        (try_begin),
          (gt, reg0, 0),
          (str_store_string, s1, "@+{reg0}"),
        (else_try),
          (str_store_string, s1, "@{reg0}"),
        (try_end),
        (create_text_overlay, reg1, s1, tf_right_align),
        (position_set_y, pos2, ":cur_y"),
        (overlay_set_position, reg1, pos2),
        (overlay_set_size, reg1, pos3),
        (val_sub, ":cur_y", ":y_offset"),

        (store_mul, ":line_offset", ":y_offset", 75),
        (val_div, ":line_offset", 100),
        (store_add, ":line_pos_y", ":cur_y", ":line_offset"),
        (call_script, "script_prsnt_line", 360, 1, 560, ":line_pos_y", 0),

        (create_text_overlay, reg1, "@Total", tf_left_align),
        (position_set_y, pos1, ":cur_y"),
        (overlay_set_position, reg1, pos1),
        (overlay_set_size, reg1, pos3),
        (call_script, "script_game_get_party_companion_limit"),
        (create_text_overlay, reg1, "@{reg0}", tf_right_align),
        (position_set_y, pos2, ":cur_y"),
        (overlay_set_position, reg1, pos2),
        (overlay_set_size, reg1, pos3),
        (val_sub, ":cur_y", ":y_offset"),

        (create_game_button_overlay, "$g_presentation_obj_5", "@Done"),
        (position_set_x, pos1, 900),
        (position_set_y, pos1, 25),
        (overlay_set_position, "$g_presentation_obj_5", pos1),
      ]),

    (ti_on_presentation_event_state_change,
      [
        (store_trigger_param_1, ":object"),

        (try_begin),
          (eq, ":object", "$g_presentation_obj_5"),
          (presentation_set_duration, 0),
        (try_end),
    ]),
  ])
