# -*- coding: cp1254 -*-
from header_common import *
from header_presentations import *
from header_mission_templates import *
from ID_meshes import *
from header_operations import *
from header_triggers import *
from module_constants import *
from header_terrain_types import *
from header_items import *
from module_factions import *
from compiler import *

spawn_diagnostics = ("spawn_diagnostics", 0, mesh_load_window,
    [(ti_on_presentation_load,
      [
       (presentation_set_duration, 999999),
       (set_fixed_point_multiplier, 1000),

       (create_text_overlay, reg1, "@Bandit & Spawn Report", tf_center_justify),
       (position_set_x, pos1, 1500),
       (position_set_y, pos1, 1500),
       (overlay_set_size, reg1, pos1),
       (position_set_x, pos1, 260),
       (position_set_y, pos1, 650),
       (overlay_set_position, reg1, pos1),

       (position_set_x, pos3, 900),
       (position_set_y, pos3, 900),
       (position_set_x, pos1, 25),
       (position_set_x, pos2, 380),
       (assign, ":cur_y", 600),
       (assign, ":y_offset", 24),

       (create_text_overlay, reg1, "@Land Bandits", 0),
       (overlay_set_color, reg1, 0x880000),
       (position_set_y, pos1, ":cur_y"),
       (overlay_set_position, reg1, pos1),
       (overlay_set_size, reg1, pos3),
       (val_sub, ":cur_y", ":y_offset"),

       (str_store_string, s1, "@Mountain Bandits"),
       (call_script, "script_get_spawn_report_line", "pt_mountain_bandits", 18, 1),
       (create_text_overlay, reg1, s1, 0),
       (position_set_y, pos1, ":cur_y"),
       (overlay_set_position, reg1, pos1),
       (overlay_set_size, reg1, pos3),
       (create_text_overlay, reg1, s0, 0),
       (position_set_y, pos2, ":cur_y"),
       (overlay_set_position, reg1, pos2),
       (overlay_set_size, reg1, pos3),
       (val_sub, ":cur_y", ":y_offset"),

       (str_store_string, s1, "@Forest Bandits"),
       (call_script, "script_get_spawn_report_line", "pt_forest_bandits", 18, 1),
       (create_text_overlay, reg1, s1, 0),
       (position_set_y, pos1, ":cur_y"),
       (overlay_set_position, reg1, pos1),
       (overlay_set_size, reg1, pos3),
       (create_text_overlay, reg1, s0, 0),
       (position_set_y, pos2, ":cur_y"),
       (overlay_set_position, reg1, pos2),
       (overlay_set_size, reg1, pos3),
       (val_sub, ":cur_y", ":y_offset"),

       (str_store_string, s1, "@Sea Raiders"),
       (call_script, "script_get_spawn_report_line", "pt_sea_raiders", 18, 1),
       (create_text_overlay, reg1, s1, 0),
       (position_set_y, pos1, ":cur_y"),
       (overlay_set_position, reg1, pos1),
       (overlay_set_size, reg1, pos3),
       (create_text_overlay, reg1, s0, 0),
       (position_set_y, pos2, ":cur_y"),
       (overlay_set_position, reg1, pos2),
       (overlay_set_size, reg1, pos3),
       (val_sub, ":cur_y", ":y_offset"),

       (str_store_string, s1, "@Steppe Bandits"),
       (call_script, "script_get_spawn_report_line", "pt_steppe_bandits", 18, 1),
       (create_text_overlay, reg1, s1, 0),
       (position_set_y, pos1, ":cur_y"),
       (overlay_set_position, reg1, pos1),
       (overlay_set_size, reg1, pos3),
       (create_text_overlay, reg1, s0, 0),
       (position_set_y, pos2, ":cur_y"),
       (overlay_set_position, reg1, pos2),
       (overlay_set_size, reg1, pos3),
       (val_sub, ":cur_y", ":y_offset"),

       (str_store_string, s1, "@Taiga Bandits"),
       (call_script, "script_get_spawn_report_line", "pt_taiga_bandits", 18, 1),
       (create_text_overlay, reg1, s1, 0),
       (position_set_y, pos1, ":cur_y"),
       (overlay_set_position, reg1, pos1),
       (overlay_set_size, reg1, pos3),
       (create_text_overlay, reg1, s0, 0),
       (position_set_y, pos2, ":cur_y"),
       (overlay_set_position, reg1, pos2),
       (overlay_set_size, reg1, pos3),
       (val_sub, ":cur_y", ":y_offset"),

       (str_store_string, s1, "@Desert Bandits"),
       (call_script, "script_get_spawn_report_line", "pt_desert_bandits", 18, 1),
       (create_text_overlay, reg1, s1, 0),
       (position_set_y, pos1, ":cur_y"),
       (overlay_set_position, reg1, pos1),
       (overlay_set_size, reg1, pos3),
       (create_text_overlay, reg1, s0, 0),
       (position_set_y, pos2, ":cur_y"),
       (overlay_set_position, reg1, pos2),
       (overlay_set_size, reg1, pos3),
       (val_sub, ":cur_y", ":y_offset"),

       (store_mul, ":line_offset", ":y_offset", 60),
       (val_div, ":line_offset", 100),
       (store_add, ":line_pos_y", ":cur_y", ":line_offset"),
       (call_script, "script_prsnt_line", 500, 1, 25, ":line_pos_y", 0),

       (str_store_string, s1, "@Looters"),
       (call_script, "script_get_spawn_report_line", "pt_looters", 18, 0),
       (create_text_overlay, reg1, s1, 0),
       (position_set_y, pos1, ":cur_y"),
       (overlay_set_position, reg1, pos1),
       (overlay_set_size, reg1, pos3),
       (create_text_overlay, reg1, s0, 0),
       (position_set_y, pos2, ":cur_y"),
       (overlay_set_position, reg1, pos2),
       (overlay_set_size, reg1, pos3),
       (val_sub, ":cur_y", ":y_offset"),

       (store_mul, ":line_offset", ":y_offset", 60),
       (val_div, ":line_offset", 100),
       (store_add, ":line_pos_y", ":cur_y", ":line_offset"),
       (call_script, "script_prsnt_line", 500, 1, 25, ":line_pos_y", 0),

       (create_text_overlay, reg1, "@Pirate Ships", 0),
       (overlay_set_color, reg1, 0x880000),
       (position_set_y, pos1, ":cur_y"),
       (overlay_set_position, reg1, pos1),
       (overlay_set_size, reg1, pos3),
       (val_sub, ":cur_y", ":y_offset"),

       (store_num_parties_of_template, ":ns1", "pt_sea_raiders_ship"),
       (store_num_parties_of_template, ":ns2", "pt_corsair_ship"),
       (store_num_parties_of_template, ":ns3", "pt_pirate_ship"),
       (store_add, ":ns_total", ":ns1", ":ns2"),
       (val_add, ":ns_total", ":ns3"),
       (assign, reg1, ":ns_total"),
       (assign, reg2, 5),
       (assign, reg3, ":ns1"),
       (assign, reg4, ":ns2"),
       (assign, reg5, ":ns3"),
       (str_store_string, s0, "@{reg1}/{reg2}   raider {reg3} / corsair {reg4} / pirate {reg5}"),
       (create_text_overlay, reg1, "@Ships total", 0),
       (position_set_y, pos1, ":cur_y"),
       (overlay_set_position, reg1, pos1),
       (overlay_set_size, reg1, pos3),
       (create_text_overlay, reg1, s0, 0),
       (position_set_y, pos2, ":cur_y"),
       (overlay_set_position, reg1, pos2),
       (overlay_set_size, reg1, pos3),
       (val_sub, ":cur_y", ":y_offset"),

       (store_mul, ":line_offset", ":y_offset", 60),
       (val_div, ":line_offset", 100),
       (store_add, ":line_pos_y", ":cur_y", ":line_offset"),
       (call_script, "script_prsnt_line", 500, 1, 25, ":line_pos_y", 0),

       (store_num_parties_of_template, ":num_mh", "pt_manhunters"),
       (assign, ":num_bandits", 0),
       (try_for_range, ":bt", bandit_party_templates_begin, bandit_party_templates_end),
         (store_num_parties_of_template, ":n", ":bt"),
         (val_add, ":num_bandits", ":n"),
       (try_end),
       (store_div, ":mh_cap", ":num_bandits", manhunter_bandits_per_manhunter),
       (val_max, ":mh_cap", 4),
       (val_min, ":mh_cap", num_max_manhunters),

       (create_text_overlay, reg1, "@Manhunters", 0),
       (overlay_set_color, reg1, 0x880000),
       (position_set_y, pos1, ":cur_y"),
       (overlay_set_position, reg1, pos1),
       (overlay_set_size, reg1, pos3),
       (val_sub, ":cur_y", ":y_offset"),

       (assign, reg1, ":num_mh"),
       (assign, reg2, ":mh_cap"),
       (str_store_string, s0, "@{reg1}/{reg2}"),
       (create_text_overlay, reg1, "@Active patrols", 0),
       (position_set_y, pos1, ":cur_y"),
       (overlay_set_position, reg1, pos1),
       (overlay_set_size, reg1, pos3),
       (create_text_overlay, reg1, s0, 0),
       (position_set_y, pos2, ":cur_y"),
       (overlay_set_position, reg1, pos2),
       (overlay_set_size, reg1, pos3),
       (val_sub, ":cur_y", ":y_offset"),

       (assign, reg1, ":num_bandits"),
       (str_store_string, s0, "@{reg1} roaming bandits"),
       (create_text_overlay, reg1, "@Bandits tracked", 0),
       (position_set_y, pos1, ":cur_y"),
       (overlay_set_position, reg1, pos1),
       (overlay_set_size, reg1, pos3),
       (create_text_overlay, reg1, s0, 0),
       (position_set_y, pos2, ":cur_y"),
       (overlay_set_position, reg1, pos2),
       (overlay_set_size, reg1, pos3),
       (val_sub, ":cur_y", ":y_offset"),

       (store_mul, ":line_offset", ":y_offset", 60),
       (val_div, ":line_offset", 100),
       (store_add, ":line_pos_y", ":cur_y", ":line_offset"),
       (call_script, "script_prsnt_line", 500, 1, 25, ":line_pos_y", 0),

       (store_num_parties_of_template, ":num_des", "pt_deserters"),
       (create_text_overlay, reg1, "@Deserters", 0),
       (overlay_set_color, reg1, 0x880000),
       (position_set_y, pos1, ":cur_y"),
       (overlay_set_position, reg1, pos1),
       (overlay_set_size, reg1, pos3),
       (val_sub, ":cur_y", ":y_offset"),

       (assign, reg1, ":num_des"),
       (str_store_string, s0, "@{reg1}"),
       (create_text_overlay, reg1, "@Active patrols", 0),
       (position_set_y, pos1, ":cur_y"),
       (overlay_set_position, reg1, pos1),
       (overlay_set_size, reg1, pos3),
       (create_text_overlay, reg1, s0, 0),
       (position_set_y, pos2, ":cur_y"),
       (overlay_set_position, reg1, pos2),
       (overlay_set_size, reg1, pos3),
       (val_sub, ":cur_y", ":y_offset"),

       (str_store_string, s0, "@max 15, 20 troops each"),
       (create_text_overlay, reg1, "@Limit", 0),
       (position_set_y, pos1, ":cur_y"),
       (overlay_set_position, reg1, pos1),
       (overlay_set_size, reg1, pos3),
       (create_text_overlay, reg1, s0, 0),
       (position_set_y, pos2, ":cur_y"),
       (overlay_set_position, reg1, pos2),
       (overlay_set_size, reg1, pos3),

       (create_game_button_overlay, "$g_presentation_obj_spawn_diag_close", "@Done"),
       (position_set_x, pos1, 900),
       (position_set_y, pos1, 25),
       (overlay_set_position, "$g_presentation_obj_spawn_diag_close", pos1),
      ]),
     (ti_on_presentation_event_state_change,
      [(store_trigger_param_1, ":object"),
       (try_begin),
         (eq, ":object", "$g_presentation_obj_spawn_diag_close"),
         (presentation_set_duration, 0),
       (try_end),
       ]),
     ])
