# -*- coding: cp1254 -*-
import string
from header_common import *
from header_presentations import *
from header_mission_templates import *
from ID_meshes import *
from header_operations import *
from header_triggers import *
from module_constants import *
from header_terrain_types import *
from module_items import *
from module_factions import *
from header_items import *
from compiler import *

cc_relations_with_factions = ("cc_relations_with_factions", 0, mesh_load_window, [
    (ti_on_presentation_load,
      [
        (presentation_set_duration, 999999),
        (set_fixed_point_multiplier, 1000),

        (create_text_overlay, reg1, "@Relation with the factions", tf_center_justify),
        (position_set_x, pos1, 500),
        (position_set_y, pos1, 670),
        (overlay_set_position, reg1, pos1),
        (position_set_x, pos1, 1500),
        (position_set_y, pos1, 1500),
        (overlay_set_size, reg1, pos1),

        (create_text_overlay, reg1, "@Click the totems to view relation with the lords", tf_center_justify),
        (position_set_x, pos1, 500),
        (position_set_y, pos1, 50),
        (overlay_set_position, reg1, pos1),
        (position_set_x, pos1, 800),
        (position_set_y, pos1, 800),
        (overlay_set_size, reg1, pos1),

        (str_clear, s0),
        (create_text_overlay, "$g_presentation_obj_6", s0, tf_scrollable),
        (position_set_x, pos1, 15),
        (position_set_y, pos1, 80),
        (overlay_set_position, "$g_presentation_obj_6", pos1),
        (position_set_x, pos1, 950),
        (position_set_y, pos1, 570),
        (overlay_set_area_size, "$g_presentation_obj_6", pos1),
        (set_container_overlay, "$g_presentation_obj_6"),

        (assign, ":num_active_factions", 0),
        (try_for_range, ":cur_kingdom", kingdoms_begin, kingdoms_end),
          (faction_slot_eq, ":cur_kingdom", slot_faction_state, sfs_active),
          (val_add, ":num_active_factions", 1),
        (try_end),

        (store_mod, ":mod_value", ":num_active_factions", 2),
        (try_begin),
          (eq, ":mod_value", 0),
          (assign, ":cur_x", 470),
        (else_try),
          (assign, ":cur_x", -30),
        (try_end),

        (try_begin),
          (is_between, ":num_active_factions", 1, 3),
          (assign, ":cur_y", 400),
        (else_try),
          (is_between, ":num_active_factions", 3, 5),
          (assign, ":cur_y", 200),
        (else_try),
          (is_between, ":num_active_factions", 5, 7),
          (assign, ":cur_y", 0),
        (else_try),
          (assign, ":cur_y", 20),
        (try_end),

        (assign, ":x_offset", 500),
        (assign, ":y_offset", 200),

        (assign, ":slot_no", 0),
        (try_for_range_backwards, ":cur_kingdom", kingdoms_begin, kingdoms_end),
          (faction_slot_eq, ":cur_kingdom", slot_faction_state, sfs_active),
          (try_begin),
            (is_between, ":cur_kingdom", "fac_kingdom_1", kingdoms_end),
            (create_image_button_overlay_with_tableau_material, reg1, -1, "tableau_faction_note_mesh", ":cur_kingdom"),
            (assign, ":totem_x", ":cur_x"),
          (else_try), # use banner instead
            (create_image_button_overlay_with_tableau_material, reg1, -1, "tableau_faction_note_mesh_banner", ":cur_kingdom"),
            (store_add, ":totem_x", ":cur_x", 90),
          (try_end),
          (position_set_x, pos1, 600),
          (position_set_y, pos1, 600),
          (overlay_set_size, reg1, pos1),
          (position_set_x, pos1, ":totem_x"),
          (position_set_y, pos1, ":cur_y"),
          (overlay_set_position, reg1, pos1),
          (troop_set_slot, "trp_temp_array_a", ":slot_no", reg1),
          (troop_set_slot, "trp_temp_array_b", ":slot_no", ":cur_kingdom"),
          (val_add, ":slot_no", 1),

          # bar
          (store_add, ":relation_bar_x", ":cur_x", 270),
          (store_add, ":relation_bar_y", ":cur_y", 10),
          (create_mesh_overlay, reg1, "mesh_relation_bar"),
          (position_set_x, pos1, ":relation_bar_x"),
          (position_set_y, pos1, ":relation_bar_y"),
          (overlay_set_position, reg1, pos1),
          # pointer
          (try_begin),
            (eq, ":cur_kingdom", "fac_player_supporters_faction"),
            (assign, ":cur_relation", 100),
          (else_try),
            (store_relation, ":cur_relation", "fac_player_supporters_faction", ":cur_kingdom"),
          (try_end),
          (store_sub, ":pointer_x", ":cur_relation", -100),
          (val_add, ":pointer_x", 270),
          (val_add, ":pointer_x", ":cur_x"),
          (create_mesh_overlay, reg1, "mesh_reln_pointer"),
          (position_set_x, pos1, ":pointer_x"),
          (position_set_y, pos1, ":relation_bar_y"),
          (overlay_set_position, reg1, pos1),
          # text
          (store_add, ":text_x", ":cur_x", 370),
          (store_add, ":text_y", ":relation_bar_y", 45),
          (assign, reg0, ":cur_relation"),
          (str_store_faction_name, s1, ":cur_kingdom"),

          (try_begin),
            (ge, ":cur_relation", 90),
            (str_store_string, s3, "@Loyal"),
          (else_try),
            (ge, ":cur_relation", 80),
            (str_store_string, s3, "@Devoted"),
          (else_try),
            (ge, ":cur_relation", 70),
            (str_store_string, s3, "@Fond"),
          (else_try),
            (ge, ":cur_relation", 60),
            (str_store_string, s3, "@Gracious"),
          (else_try),
            (ge, ":cur_relation", 50),
            (str_store_string, s3, "@Friendly"),
          (else_try),
            (ge, ":cur_relation", 40),
            (str_store_string, s3, "@Supportive"),
          (else_try),
            (ge, ":cur_relation", 30),
            (str_store_string, s3, "@Favorable"),
          (else_try),
            (ge, ":cur_relation", 20),
            (str_store_string, s3, "@Cooperative"),
          (else_try),
            (ge, ":cur_relation", 10),
            (str_store_string, s3, "@Accepting"),
          (else_try),
            (ge, ":cur_relation", 0),
            (str_store_string, s3, "@Indifferent"),
          (else_try),
            (ge, ":cur_relation", -10),
            (str_store_string, s3, "@Suspicious"),
          (else_try),
            (ge, ":cur_relation", -20),
            (str_store_string, s3, "@Grumbling"),
          (else_try),
            (ge, ":cur_relation", -30),
            (str_store_string, s3, "@Hostile"),
          (else_try),
            (ge, ":cur_relation", -40),
            (str_store_string, s3, "@Resentful"),
          (else_try),
            (ge, ":cur_relation", -50),
            (str_store_string, s3, "@Angry"),
          (else_try),
            (ge, ":cur_relation", -60),
            (str_store_string, s3, "@Hateful"),
          (else_try),
            (ge, ":cur_relation", -70),
            (str_store_string, s3, "@Revengeful"),
          (else_try),
            (str_store_string, s3, "@Vengeful"),
          (try_end),

          (create_text_overlay, reg1, "@{s1}^^{reg0} ({s3})", tf_center_justify),
          (position_set_x, pos1, ":text_x"),
          (position_set_y, pos1, ":text_y"),
          (overlay_set_position, reg1, pos1),

          (val_sub, ":cur_x", ":x_offset"),
          (try_begin),
            (eq, ":cur_x", -530),
            (assign, ":cur_x", 470),
            (val_add, ":cur_y", ":y_offset"),
          (try_end),
        (try_end),
        (set_container_overlay, -1),

        # Done
        (create_game_button_overlay, "$g_presentation_obj_5", "@Done"),
        (position_set_x, pos1, 900),
        (position_set_y, pos1, 25),
        (overlay_set_position, "$g_presentation_obj_5", pos1),
      ]),

    (ti_on_presentation_event_state_change,
      [
        (store_trigger_param_1, ":object"),

        (assign, ":num_active_factions", 0),
        (try_for_range, ":cur_kingdom", kingdoms_begin, kingdoms_end),
          (faction_slot_eq, ":cur_kingdom", slot_faction_state, sfs_active),
          (val_add, ":num_active_factions", 1),
        (try_end),
        (try_for_range, ":slot_no", 0, ":num_active_factions"),
          (troop_slot_eq, "trp_temp_array_a", ":slot_no", ":object"),
          (troop_get_slot, "$temp", "trp_temp_array_b", ":slot_no"),
          (start_presentation, "prsnt_cc_relations_with_lords_by_faction"),
        (try_end),

        (try_begin),
          (eq, ":object", "$g_presentation_obj_5"),
          (presentation_set_duration, 0),
        (try_end),
    ]),
  ])
