# -*- coding: cp1254 -*-
import string
from header_common import *
from header_presentations import *
from header_mission_templates import *
from ID_meshes import *
from header_operations import *
from header_triggers import *
#SB: import skills from ID_skills import *
from module_constants import *
##diplomacy start+ Import for use with terrain advantage
from header_terrain_types import *
from module_items import *
#SB : import colors
from module_factions import *
from header_items import *
##diplomacy end
from compiler import *

manage_inventory = ("manage_inventory", 0, mesh_inventory_window, [
    (ti_on_presentation_load, [
      (presentation_set_duration, 999999),
      (set_fixed_point_multiplier, 1000),

      (assign, "$g_cur_selected_item_slot", -1),
      (assign, "$g_current_opened_item_details", -1),
      (call_script, "script_all_toggle_weapons_set", 1),
      (assign, ":selected_troop", "$g_prsnt_param_1"),
      (assign, ":num_heros", 0),
      (party_get_num_companion_stacks, ":num_stacks","p_main_party"),
      (try_for_range, ":stack_no", 0, ":num_stacks"),
        (party_stack_get_troop_id,":stack_troop","p_main_party",":stack_no"),
        (troop_is_hero, ":stack_troop"),
        (troop_set_slot, ":stack_troop", slot_troop_not_auto_equip, 1),
      (try_end),
      (assign, ":num_heros", 0),
      (party_get_num_companion_stacks, ":num_stacks","p_main_party"),
      (try_for_range, ":stack_no", 0, ":num_stacks"),
        (party_stack_get_troop_id,":stack_troop","p_main_party",":stack_no"),
        (troop_is_hero, ":stack_troop"),
        (this_or_next|eq, ":stack_troop", "trp_player"),
        (troop_slot_eq, ":stack_troop", slot_troop_not_auto_equip, 1),
        (troop_set_slot, "trp_temp_array_sort", ":num_heros", ":stack_troop"),
        (val_add, ":num_heros", 1),
      (try_end),
      (assign, "$g_manage_inventory_num_heros", ":num_heros"),

      # hero list
      (create_text_overlay, reg1, "@Equip Companions", tf_center_justify),
      (position_set_x, pos1, 835),
      (position_set_y, pos1, 700),
      (overlay_set_position, reg1, pos1),

      (str_clear, s0),
      (create_text_overlay, reg1, s0, tf_scrollable_style_2),
      (position_set_x, pos1, 710),
      (position_set_y, pos1, 150),
      (overlay_set_position, reg1, pos1),
      (assign, ":area_size_x", 250),
      (assign, ":area_size_y", 485),
      (assign, ":offset_y", 30),
      (position_set_x, pos1, ":area_size_x"),
      (position_set_y, pos1, ":area_size_y"),
      (overlay_set_area_size, reg1, pos1),
      (set_container_overlay, reg1),

      (store_mul, ":pos_y", ":num_heros", ":offset_y"),
      (val_max, ":pos_y", ":area_size_y"),
      (val_sub, ":pos_y", ":offset_y"),
      (store_div, ":pos_x", ":area_size_x", 2),

      (assign, ":hero_obj_slot_no", 0),
      (try_for_range, ":stack_no", 0, ":num_heros"),
        (troop_get_slot,":stack_troop","trp_temp_array_sort",":stack_no"),
        (str_store_troop_name, s1, ":stack_troop"),
        (create_button_overlay, reg1, s1, tf_center_justify),
        (position_set_x, pos1, ":pos_x"),
        (position_set_y, pos1, ":pos_y"),
        (overlay_set_position, reg1, pos1),
        (try_begin),
          (eq, ":stack_troop", ":selected_troop"),
          (overlay_set_color, reg1, 0x333333),
        (try_end),
        (troop_set_slot, "trp_temp_array_a", ":hero_obj_slot_no", reg1),
        (val_add, ":hero_obj_slot_no", 1),
        (val_sub, ":pos_y", ":offset_y"),
      (try_end),

      (set_container_overlay, -1),

      # Auto-upgrade equipments
      (create_in_game_button_overlay, "$g_presentation_obj_admin_panel_6", "@Upgrade for All"),
      (overlay_set_color, "$g_presentation_obj_admin_panel_6", 0xFFFFFF),
      (position_set_x, pos1, 835),
      (position_set_y, pos1, 645),
      (overlay_set_position, "$g_presentation_obj_admin_panel_6", pos1),

      # done
      (create_game_button_overlay, "$g_presentation_obj_admin_panel_2", "@Done", tf_center_justify),
      (position_set_x, pos1, 835),
      (position_set_y, pos1, 25),
      (overlay_set_position, "$g_presentation_obj_admin_panel_2", pos1),

      # sort
      (create_game_button_overlay, "$g_presentation_obj_admin_panel_4", "@Sort", tf_center_justify),
      (position_set_x, pos1, 165),
      (position_set_y, pos1, 25),
      (overlay_set_position, "$g_presentation_obj_admin_panel_4", pos1),

      # your inventory
      (create_text_overlay, reg1, "@Your Inventory", tf_center_justify),
      (position_set_x, pos1, 165),
      (position_set_y, pos1, 700),
      (overlay_set_position, reg1, pos1),

      (str_clear, s0),
      (create_text_overlay, "$g_presentation_obj_admin_panel_3", s0, tf_scrollable_style_2),
      (position_set_x, pos1, 20),
      (position_set_y, pos1, 100),
      (overlay_set_position, "$g_presentation_obj_admin_panel_3", pos1),
      (assign, ":area_size_x", 270),
      (assign, ":area_size_y", 600),
      (position_set_x, pos1, ":area_size_x"),
      (position_set_y, pos1, ":area_size_y"),
      (overlay_set_area_size, "$g_presentation_obj_admin_panel_3", pos1),
      (set_container_overlay, "$g_presentation_obj_admin_panel_3"),

      (assign, ":offset_xy", 90),
      (store_div, ":item_pos_offset", ":offset_xy", 2),

      (troop_get_inventory_capacity, ":inv_cap", "trp_player"),
      (store_sub, ":num_inventory_slots", ":inv_cap", 10),
      (store_div, ":height", ":num_inventory_slots", 3),
      (store_mod, ":offset", ":num_inventory_slots", 3),
      (val_min, ":offset", 1),
      (val_add, ":height", ":offset"),
      (store_mul, ":pos_y", ":height", ":offset_xy"),
      (val_sub, ":pos_y", ":offset_xy"),
      (assign, ":pos_x", 0),

      ## inventory slots
      (try_for_range, ":slot_no", 10, ":inv_cap"),
        (troop_get_inventory_slot, ":item_no", "trp_player", ":slot_no"),
        (troop_get_inventory_slot_modifier, ":item_imod", "trp_player", ":slot_no"),
        (try_begin),
          (lt, ":item_no", 0),
          (assign, ":item_no", 0),
          (assign, ":can_use", 1),
          (troop_set_slot, "trp_temp_array_c", ":slot_no", ":can_use"),
        (else_try),
          (gt, ":item_no", 0),
          (call_script, "script_troop_can_use_item", ":selected_troop", ":item_no", ":item_imod"),
          (assign, ":can_use", reg0),
          (troop_set_slot, "trp_temp_array_c", ":slot_no", ":can_use"),
        (try_end),

        (create_mesh_overlay, reg1, "mesh_inventory_slot"), # inventory slot
        (position_set_x, pos1, 920),
        (position_set_y, pos1, 920),
        (overlay_set_size, reg1, pos1),
        (position_set_x, pos1, ":pos_x"),
        (position_set_y, pos1, ":pos_y"),
        (overlay_set_position, reg1, pos1),
        (troop_set_slot, "trp_temp_array_b", ":slot_no", reg1),

        (create_mesh_overlay_with_item_id, reg1, ":item_no"), # item
        (position_set_x, pos3, 960),
        (position_set_y, pos3, 960),
        (overlay_set_size, reg1, pos3),
        (store_add, ":item_x", ":pos_x", ":item_pos_offset"),
        (store_add, ":item_y", ":pos_y", ":item_pos_offset"),
        (position_set_x, pos1, ":item_x"),
        (position_set_y, pos1, ":item_y"),
        (overlay_set_position, reg1, pos1),
        (troop_set_slot, "trp_temp_array_d", ":slot_no", reg1),
        (troop_set_slot, "trp_temp_array_x", ":slot_no", ":item_x"),
        (troop_set_slot, "trp_temp_array_y", ":slot_no", ":item_y"),

        (create_check_box_overlay, reg1, "mesh_checkbox_lock_off", "mesh_checkbox_lock_on"), # sort setting
        (store_add, ":lock_x", ":pos_x", 66),
        (store_add, ":lock_y", ":pos_y", 2),
        (position_set_x, pos1, ":lock_x"),
        (position_set_y, pos1, ":lock_y"),
        (overlay_set_position, reg1, pos1),
        (troop_get_slot, ":locked", "trp_temp_array_lock", ":slot_no"),
        (overlay_set_val, reg1, ":locked"),
        (troop_set_slot, "trp_temp_array_e", ":slot_no", reg1),

        (val_add, ":slot_no", 1),
        (val_add, ":pos_x", ":offset_xy"),
        (try_begin),
          (ge, ":pos_x", ":area_size_x"),
          (assign, ":pos_x", 0),
          (val_sub, ":pos_y", ":offset_xy"),
        (try_end),
      (try_end),

      (set_container_overlay, -1),

      # selected troop
      (str_store_troop_name, s1, ":selected_troop"),
      (create_text_overlay, reg1, s1, tf_center_justify),
      (position_set_x, pos1, 500),
      (position_set_y, pos1, 270),
      (overlay_set_position, reg1, pos1),

      (store_mul, ":troop_with_weapons", ":selected_troop", 2),
      (create_mesh_overlay_with_tableau_material, "$g_presentation_obj_admin_panel_7", -1, "tableau_game_party_window", ":troop_with_weapons"),
      (position_set_x, pos1, 800),
      (position_set_y, pos1, 960),
      (overlay_set_size, "$g_presentation_obj_admin_panel_7", pos1),
      (position_set_x, pos1, 300),
      (position_set_y, pos1, 15),
      (overlay_set_position, "$g_presentation_obj_admin_panel_7", pos1),

      (assign, ":head_armor", 0),
      (assign, ":body_armor", 0),
      (assign, ":leg_armor", 0),
      (try_for_range, ":inv_slot_no", 4, 8),
        (troop_get_inventory_slot, ":item", ":selected_troop", ":inv_slot_no"),
        (gt, ":item", -1),
          (troop_get_inventory_slot_modifier, ":imod", ":selected_troop", ":inv_slot_no"),
          (call_script, "script_imod_effect_armor", ":imod"),
          (assign, ":imod_effect", reg0),
          (item_get_head_armor, ":cur_head_armor", ":item"), # head_armor
          (try_begin), 
            (gt, ":cur_head_armor", 0),
            (val_add, ":cur_head_armor", ":imod_effect"), 
            (val_max, ":cur_head_armor", 0),
            (val_add, ":head_armor", ":cur_head_armor"),
          (try_end),
          (item_get_body_armor, ":cur_body_armor", ":item"), # body_armor
          (try_begin), 
            (gt, ":cur_body_armor", 0),
            (val_add, ":cur_body_armor", ":imod_effect"), 
            (val_max, ":cur_body_armor", 0),
            (val_add, ":body_armor", ":cur_body_armor"),
          (try_end),
          (item_get_leg_armor, ":cur_leg_armor", ":item"), # leg_armor
          (try_begin),
            (gt, ":cur_leg_armor", 0),
            (val_add, ":cur_leg_armor", ":imod_effect"), 
            (val_max, ":cur_leg_armor", 0),
            (val_add, ":leg_armor", ":cur_leg_armor"),
          (try_end),
      (try_end),

      (assign, reg0, ":head_armor"),
      (str_store_string, s1, "@Head Armor: {reg0}"),
      (str_store_string, s2, s1),
      (assign, reg0, ":body_armor"),
      (str_store_string, s1, "@Body Armor: {reg0}"),
      (str_store_string, s2, "@{s2}^^{s1}"),
      (assign, reg0, ":leg_armor"),
      (str_store_string, s1, "@Leg Armor: {reg0}"),
      (str_store_string, s2, "@{s2}^^{s1}"),

      (create_text_overlay, "$g_presentation_obj_admin_panel_8", s2, tf_center_justify),
      (position_set_x, pos1, 950),
      (position_set_y, pos1, 950),
      (overlay_set_size, "$g_presentation_obj_admin_panel_8", pos1),
      (position_set_x, pos1, 580),
      (position_set_y, pos1, 100),
      (overlay_set_position, "$g_presentation_obj_admin_panel_8", pos1),

      ## equipments
      (assign, ":init_pos_x", 554),
      (assign, ":init_pos_y", 695),
      (create_combo_label_overlay, "$g_presentation_obj_admin_panel_1"), # weapons set
      (position_set_x, pos1, 400),
      (position_set_y, pos1, 750),
      (overlay_set_size, "$g_presentation_obj_admin_panel_1", pos1),
      (position_set_x, pos1, 655),
      (position_set_y, pos1, ":init_pos_y"),
      (overlay_set_position, "$g_presentation_obj_admin_panel_1", pos1),
      (overlay_add_item, "$g_presentation_obj_admin_panel_1", "@Arms 1"),
      (overlay_add_item, "$g_presentation_obj_admin_panel_1", "@Arms 2"),
      (overlay_set_val, "$g_presentation_obj_admin_panel_1", "$g_weapons_set_no"),

      (create_text_overlay, reg1, "@Outfit", tf_center_justify),
      (position_set_x, pos1, 455),
      (position_set_y, pos1, ":init_pos_y"),
      (overlay_set_position, reg1, pos1),
      (create_text_overlay, reg1, "@Horse", tf_center_justify),
      (position_set_x, pos1, 405),
      (position_set_y, pos1, 405),
      (overlay_set_position, reg1, pos1),

      (assign, ":pos_x", ":init_pos_x"),
      (assign, ":pos_y", ":init_pos_y"),
      (assign, ":offset_xy", 88),
      (store_div, ":item_pos_offset", ":offset_xy", 2),
      (try_for_range, ":slot_no", 0, 9),
        (try_begin),
          (eq, ":slot_no", 4),
          (assign, ":pos_x", 453),
          (assign, ":pos_y", ":init_pos_y"),
        (else_try),
          (eq, ":slot_no", 7),
          (val_sub, ":pos_x", ":offset_xy"),
          (store_sub, ":pos_y", ":init_pos_y", ":offset_xy"),
        (else_try),
          (eq, ":slot_no", 8),
          (assign, ":pos_y", 405),
        (try_end),
        (val_sub, ":pos_y", ":offset_xy"),

        (troop_get_inventory_slot, ":item_no", ":selected_troop", ":slot_no"),
        (try_begin),
          (lt, ":item_no", 0),
          (assign, ":item_no", 0),
        (try_end),
        (troop_set_slot, "trp_temp_array_c", ":slot_no", 1), # can use

        (create_mesh_overlay, reg1, "mesh_inventory_slot"), # inventory slot
        (position_set_x, pos1, 860),
        (position_set_y, pos1, 860),
        (overlay_set_size, reg1, pos1),
        (position_set_x, pos1, ":pos_x"),
        (position_set_y, pos1, ":pos_y"),
        (overlay_set_position, reg1, pos1),
        (overlay_set_color, reg1, 0x000000),
        (overlay_set_alpha, reg1, 0x00),
        (try_begin),
          (gt, ":item_no", 0),
          (overlay_set_alpha, reg1, 0xFF),
        (try_end),
        (troop_set_slot, "trp_temp_array_b", ":slot_no", reg1),

        (create_mesh_overlay_with_item_id, reg1, ":item_no"), # item
        (position_set_x, pos4, 950),
        (position_set_y, pos4, 950),
        (overlay_set_size, reg1, pos4),
        (store_add, ":item_x", ":pos_x", ":item_pos_offset"),
        (store_add, ":item_y", ":pos_y", ":item_pos_offset"),
        (position_set_x, pos1, ":item_x"),
        (position_set_y, pos1, ":item_y"),
        (overlay_set_position, reg1, pos1),
        (troop_set_slot, "trp_temp_array_d", ":slot_no", reg1),

        (create_check_box_overlay, reg1, "mesh_checkbox_lock_off", "mesh_checkbox_lock_on"), # upgrade setting
        (store_add, ":lock_x", ":pos_x", 62),
        (store_add, ":lock_y", ":pos_y", 1),
        (position_set_x, pos1, ":lock_x"),
        (position_set_y, pos1, ":lock_y"),
        (overlay_set_position, reg1, pos1),
        (troop_get_slot, ":locked", "trp_temp_array_lock", ":slot_no"),
        (overlay_set_val, reg1, ":locked"),
        (troop_set_slot, "trp_temp_array_e", ":slot_no", reg1),
      (try_end),
    ]),

    (ti_on_presentation_mouse_enter_leave,[
      (store_trigger_param_1, ":object"),
      (store_trigger_param_2, ":enter_leave"),

      (assign, ":selected_troop", "$g_prsnt_param_1"),
      (troop_get_inventory_capacity, ":inv_cap", "trp_player"),
      (try_begin),
        (eq, ":enter_leave", 0),
        (try_for_range, ":slot_no", 0, ":inv_cap"),
          (neq, ":slot_no", 9),
          (troop_slot_eq, "trp_temp_array_b", ":slot_no", ":object"),
          (troop_get_slot, ":item_object", "trp_temp_array_d", ":slot_no"),
          (overlay_get_position, pos0, ":item_object"),
          (try_begin),
            (is_between, ":slot_no", 0, 9),
            (troop_get_inventory_slot, ":cur_item", ":selected_troop", ":slot_no"),
            (troop_get_inventory_slot_modifier, ":cur_imod", ":selected_troop", ":slot_no"),
          (else_try),
            (is_between, ":slot_no", 10, ":inv_cap"),
            (troop_get_inventory_slot, ":cur_item", "trp_player", ":slot_no"),
            (troop_get_inventory_slot_modifier, ":cur_imod", "trp_player", ":slot_no"),
          (try_end),
          (eq, "$g_cur_selected_item_slot", -1),
          (gt, ":cur_item", -1),
          (show_item_details_with_modifier, ":cur_item", ":cur_imod", pos0, 100),
          (assign, "$g_current_opened_item_details", ":slot_no"),
        (try_end),
      (else_try),
        (try_for_range, ":slot_no", 0, ":inv_cap"),
          (troop_slot_eq, "trp_temp_array_b", ":slot_no", ":object"),
          (try_begin),
            (eq, "$g_current_opened_item_details", ":slot_no"),
            (close_item_details),
          (try_end),
        (try_end),
      (try_end),
    ]),

    (ti_on_presentation_mouse_press,[
      (store_trigger_param_1, ":object"),
      (store_trigger_param_2, ":mouse_state"),
      
      (assign, ":selected_troop", "$g_prsnt_param_1"),
      (assign, ":exchange", -1),
      (try_begin), 
        (gt, "$g_cur_selected_item_slot", -1),
        (eq, ":mouse_state", 1), # right-click
        (assign, ":exchange", 0),
      (try_end),

      (try_begin),
        (eq, ":exchange", -1),
        (troop_get_inventory_capacity, ":inv_cap", "trp_player"),
        (try_for_range, ":slot_no", 0, ":inv_cap"),
          (neq, ":slot_no", 9),
          (troop_slot_eq, "trp_temp_array_b", ":slot_no", ":object"),
          (try_begin),
            (is_between, ":slot_no", 0, 9),
            (troop_get_inventory_slot, ":cur_item", ":selected_troop", ":slot_no"),
          (else_try),
            (is_between, ":slot_no", 10, ":inv_cap"),
            (troop_get_inventory_slot, ":cur_item", "trp_player", ":slot_no"),
          (try_end),
          
          (try_begin),
            (eq, ":mouse_state", 0), # left-click
            (try_begin),
              (eq, "$g_cur_selected_item_slot", -1),
              (try_begin),
                (gt, ":cur_item", -1),
                (try_begin),
                  (ge, ":slot_no", 10),
                  (troop_get_slot, ":item_x", "trp_temp_array_x", ":slot_no"),
                  (troop_get_slot, ":item_y", "trp_temp_array_y", ":slot_no"),
                  (position_set_x, pos5, ":item_x"),
                  (position_set_y, pos5, ":item_y"),
                (else_try),
                  (troop_get_slot, ":cur_selected_object", "trp_temp_array_d", ":slot_no"),
                  (overlay_get_position, pos5, ":cur_selected_object"),
                  (troop_get_slot, ":cur_selected_slot_obj", "trp_temp_array_b", ":slot_no"),
                  (overlay_set_alpha, ":cur_selected_slot_obj", 0x00),
                (try_end),

                (assign, "$g_cur_selected_item_slot", ":slot_no"),
                (close_item_details),
              (try_end),

            (else_try),
              (assign, ":old_slot", "$g_cur_selected_item_slot"),
              (try_begin),
                (ge, ":old_slot", 10),
                (troop_get_inventory_slot, ":old_item", "trp_player", ":old_slot"),
              (else_try),
                (troop_get_inventory_slot, ":old_item", ":selected_troop", ":old_slot"),
              (try_end),
              (assign, ":new_slot", ":slot_no"),
              (assign, ":new_item", ":cur_item"),

              (try_begin),
                (eq, ":new_slot", ":old_slot"),
                (assign, ":exchange", 0),
              (else_try),
                (is_between, ":new_slot", 0, 4),
                (is_between, ":old_slot", 0, 4),
                (assign, ":exchange", 2),
              (else_try),
                (ge, ":new_slot", 10),
                (ge, ":old_slot", 10),
                (assign, ":exchange", 1),
              (else_try),
                (ge, ":old_slot", 10),
                (try_begin),
                  (troop_slot_eq, "trp_temp_array_c", ":old_slot", 1),
                  (item_get_type, ":old_slot_type", ":old_item"),
                  (try_begin), # weapons
                    (this_or_next|is_between, ":old_slot_type", itp_type_one_handed_wpn, itp_type_goods),
                    (is_between, ":old_slot_type", itp_type_pistol, itp_type_animal),
                    (assign, ":old_slot_type", itp_type_one_handed_wpn),
                  (try_end),
                  (call_script, "script_get_inventory_slot_type", ":new_slot"),
                  (assign, ":new_slot_type", reg0),
                  (try_begin),
                    (eq, ":new_slot_type", ":old_slot_type"),
                    (assign, ":exchange", 3),
                    (eq, ":new_slot", 8),
                    (assign, ":exchange", 2),
                  (try_end),
                (else_try),
                  (display_message, "@Troop can't use this item.", 0xFF0000),
                (try_end),
              (else_try),
                (ge, ":new_slot", 10),
                (try_begin),
                  (troop_slot_eq, "trp_temp_array_c", ":new_slot", 1),
                  (try_begin),
                    (gt, ":new_item", -1),
                    (item_get_type, ":new_slot_type", ":new_item"),
                    (try_begin), # weapons
                      (this_or_next|is_between, ":new_slot_type", itp_type_one_handed_wpn, itp_type_goods),
                      (is_between, ":new_slot_type", itp_type_pistol, itp_type_animal),
                      (assign, ":new_slot_type", itp_type_one_handed_wpn),
                    (try_end),
                    (call_script, "script_get_inventory_slot_type", ":old_slot"),
                    (assign, ":old_slot_type", reg0),
                  (try_end),
                  (try_begin),
                    (this_or_next|eq, ":new_item", -1),
                    (eq, ":old_slot_type", ":new_slot_type"),
                    (assign, ":exchange", 3),
                    (eq, ":old_slot", 8),
                    (assign, ":exchange", 2),
                  (try_end),
                (else_try),
                  (display_message, "@Troop can't use this item.", 0xFF0000),
                (try_end),
              (try_end),
            (try_end),

          (else_try),
            (eq, ":mouse_state", 1), # right-click
            (gt, ":cur_item", -1),
            (eq, "$g_cur_selected_item_slot", -1),
            (try_begin),
              (ge, ":slot_no", 10),
              (try_begin),
                (troop_slot_eq, "trp_temp_array_c", ":slot_no", 1),
                (assign, ":old_slot", ":slot_no"),
                (assign, ":old_item", ":cur_item"),
                (item_get_type, ":old_slot_type", ":old_item"),
                (try_begin), # weapons
                  (this_or_next|is_between, ":old_slot_type", itp_type_one_handed_wpn, itp_type_goods),
                  (is_between, ":old_slot_type", itp_type_pistol, itp_type_animal),
                  (assign, ":old_slot_type", itp_type_one_handed_wpn),
                (try_end),

                (assign, ":end_cond", 9),
                (try_for_range, ":new_slot", 0, ":end_cond"),
                  (call_script, "script_get_inventory_slot_type", ":new_slot"),
                  (assign, ":new_slot_type", reg0),
                  (try_begin),
                    (eq, ":new_slot_type", itp_type_one_handed_wpn),
                    (troop_get_inventory_slot, ":new_item", ":selected_troop", ":new_slot"),
                    (gt, ":new_item", -1),
                    (assign, ":new_slot_type", -1),
                  (try_end),
                  (eq, ":new_slot_type", ":old_slot_type"),
                  (assign, ":end_cond", 0),
                  (assign, ":exchange", 3),
                  (try_begin),
                    (eq, ":new_slot", 8),
                    (assign, ":exchange", 2),
                  (try_end),
                  (troop_get_slot, ":item_x", "trp_temp_array_x", ":old_slot"),
                  (troop_get_slot, ":item_y", "trp_temp_array_y", ":old_slot"),
                  (position_set_x, pos5, ":item_x"),
                  (position_set_y, pos5, ":item_y"),
                (try_end),
              (else_try),
                (display_message, "@Troop can't use this item.", 0xFF0000),
              (try_end),

            (else_try),
              (assign, ":old_slot", ":slot_no"),
              (assign, ":end_cond", ":inv_cap"),
              (try_for_range, ":new_slot", 10, ":end_cond"),
                (troop_slot_eq, "trp_temp_array_lock", ":new_slot", 0),
                (troop_get_inventory_slot, ":new_item", "trp_player", ":new_slot"),
                (eq, ":new_item", -1),
                (assign, ":end_cond", 0),
                (assign, ":exchange", 3),
                (try_begin),
                  (eq, ":old_slot", 8),
                  (assign, ":exchange", 2),
                (try_end),
                (troop_get_slot, ":old_object", "trp_temp_array_d", ":old_slot"),
                (overlay_get_position, pos5, ":old_object"),
              (try_end),
            (try_end),
          (try_end),

          (try_begin),
            (ge, ":exchange", 1),
            (troop_get_slot, ":old_object", "trp_temp_array_d", ":old_slot"),
            (troop_get_slot, ":can_use_old_item", "trp_temp_array_c", ":old_slot"),
            (troop_get_slot, ":new_object", "trp_temp_array_d", ":new_slot"),
            (troop_get_slot, ":can_use_new_item", "trp_temp_array_c", ":new_slot"),

            ## put old_object in new_slot
            (try_begin),
              (ge, ":new_slot", 10),
              (troop_get_inventory_slot, ":new_item", "trp_player", ":new_slot"),
              (troop_get_slot, ":item_x", "trp_temp_array_x", ":new_slot"),
              (troop_get_slot, ":item_y", "trp_temp_array_y", ":new_slot"),
              (position_set_x, pos6, ":item_x"),
              (position_set_y, pos6, ":item_y"),
              (position_set_x, pos3, 960),
              (position_set_y, pos3, 960),
              (overlay_set_size, ":old_object", pos3),
              (overlay_set_container_overlay, ":old_object", "$g_presentation_obj_admin_panel_3"),
            (else_try),
              (troop_get_inventory_slot, ":new_item", ":selected_troop", ":new_slot"),
              (overlay_get_position, pos6, ":new_object"),
              (position_set_x, pos4, 950),
              (position_set_y, pos4, 950),
              (overlay_set_size, ":old_object", pos4),
              (overlay_set_container_overlay, ":old_object", -1),
              (troop_get_slot, ":new_slot_obj", "trp_temp_array_b", ":new_slot"),
              (overlay_set_alpha, ":new_slot_obj", 0xFF),
            (try_end),
            (overlay_set_position, ":old_object", pos6),
            (troop_set_slot, "trp_temp_array_d", ":new_slot", ":old_object"),
            (troop_set_slot, "trp_temp_array_c", ":new_slot", ":can_use_old_item"),

            ## put new_object in old_slot
            (try_begin),
              (ge, ":old_slot", 10),
              (position_set_x, pos3, 960),
              (position_set_y, pos3, 960),
              (overlay_set_size, ":new_object", pos3),
              (overlay_set_container_overlay, ":new_object", "$g_presentation_obj_admin_panel_3"),
            (else_try),
              (position_set_x, pos4, 950),
              (position_set_y, pos4, 950),
              (overlay_set_size, ":new_object", pos4),
              (overlay_set_container_overlay, ":new_object", -1),
              (troop_get_slot, ":old_slot_obj", "trp_temp_array_b", ":old_slot"),
              (overlay_set_alpha, ":old_slot_obj", 0xFF),
              (eq, ":new_item", -1),
              (overlay_set_alpha, ":old_slot_obj", 0x00),
            (try_end),
            (overlay_set_position, ":new_object", pos5),
            (troop_set_slot, "trp_temp_array_d", ":old_slot", ":new_object"),
            (troop_set_slot, "trp_temp_array_c", ":old_slot", ":can_use_new_item"),

            (call_script, "script_exchange_two_items_of_slots", ":old_slot", ":new_slot", ":selected_troop"),
            (assign, "$g_cur_selected_item_slot", -1),

            # troop
            (ge, ":exchange", 2),
            (overlay_set_display, "$g_presentation_obj_admin_panel_7", 0),
            (store_mul, ":troop_with_weapons", ":selected_troop", 2),
            (create_mesh_overlay_with_tableau_material, "$g_presentation_obj_admin_panel_7", -1, "tableau_game_party_window", ":troop_with_weapons"),
            (position_set_x, pos1, 800),
            (position_set_y, pos1, 960),
            (overlay_set_size, "$g_presentation_obj_admin_panel_7", pos1),
            (position_set_x, pos1, 300),
            (position_set_y, pos1, 15),
            (overlay_set_position, "$g_presentation_obj_admin_panel_7", pos1),

            (eq, ":exchange", 3),
            (assign, ":head_armor", 0),
            (assign, ":body_armor", 0),
            (assign, ":leg_armor", 0),
            (try_for_range, ":inv_slot_no", 4, 8),
              (troop_get_inventory_slot, ":item", ":selected_troop", ":inv_slot_no"),
              (gt, ":item", -1),
                (troop_get_inventory_slot_modifier, ":imod", ":selected_troop", ":inv_slot_no"),
                (call_script, "script_imod_effect_armor", ":imod"),
                (assign, ":imod_effect", reg0),
                (item_get_head_armor, ":cur_head_armor", ":item"),
                (try_begin), 
                  (gt, ":cur_head_armor", 0),
                  (val_add, ":cur_head_armor", ":imod_effect"), 
                  (val_max, ":cur_head_armor", 0),
                  (val_add, ":head_armor", ":cur_head_armor"),
                (try_end),
                (item_get_body_armor, ":cur_body_armor", ":item"),
                (try_begin), 
                  (gt, ":cur_body_armor", 0),
                  (val_add, ":cur_body_armor", ":imod_effect"), 
                  (val_max, ":cur_body_armor", 0),
                  (val_add, ":body_armor", ":cur_body_armor"),
                (try_end),
                (item_get_leg_armor, ":cur_leg_armor", ":item"),
                (try_begin),
                  (gt, ":cur_leg_armor", 0),
                  (val_add, ":cur_leg_armor", ":imod_effect"), 
                  (val_max, ":cur_leg_armor", 0),
                  (val_add, ":leg_armor", ":cur_leg_armor"),
                (try_end),
            (try_end),

            (assign, reg0, ":head_armor"),
            (str_store_string, s1, "@Head Armor: {reg0}"),
            (str_store_string, s2, s1),
            (assign, reg0, ":body_armor"),
            (str_store_string, s1, "@Body Armor: {reg0}"),
            (str_store_string, s2, "@{s2}^^{s1}"),
            (assign, reg0, ":leg_armor"),
            (str_store_string, s1, "@Leg Armor: {reg0}"),
            (str_store_string, s2, "@{s2}^^{s1}"),
            (overlay_set_text, "$g_presentation_obj_admin_panel_8", s2),
          (try_end),
        (try_end),
      (try_end),

      (try_begin),
        (eq, ":exchange", 0),
        (troop_get_slot, ":cur_selected_object", "trp_temp_array_d", "$g_cur_selected_item_slot"),
        (try_begin),
          (ge, "$g_cur_selected_item_slot", 10),
          (position_set_x, pos3, 960),
          (position_set_y, pos3, 960),
          (overlay_set_size, ":cur_selected_object", pos3),
          (overlay_set_container_overlay, ":cur_selected_object", "$g_presentation_obj_admin_panel_3"),
        (else_try),
          (position_set_x, pos4, 950),
          (position_set_y, pos4, 950),
          (overlay_set_size, ":cur_selected_object", pos4),
          (troop_get_slot, ":cur_selected_slot_obj", "trp_temp_array_b", "$g_cur_selected_item_slot"),
          (overlay_set_alpha, ":cur_selected_slot_obj", 0xFF),
        (try_end),
        (overlay_set_position, ":cur_selected_object", pos5),
        (assign, "$g_cur_selected_item_slot", -1),
      (try_end),
    ]),

    (ti_on_presentation_run, [
      (set_fixed_point_multiplier, 1000),

      (try_begin),
        (gt, "$g_cur_selected_item_slot", -1),
        (troop_get_slot, ":cur_selected_object", "trp_temp_array_d", "$g_cur_selected_item_slot"),
        (mouse_get_position, pos1),
        (try_begin),
          (ge, "$g_cur_selected_item_slot", 10),
          (overlay_set_container_overlay, ":cur_selected_object", -1),
        (try_end),
        (overlay_set_position, ":cur_selected_object", pos1),
        (position_set_x, pos2, 1600),
        (position_set_y, pos2, 1600),
        (overlay_set_size, ":cur_selected_object", pos2),
      (try_end),

      (assign, ":selected_troop", "$g_prsnt_param_1"),
      (assign, ":num_heros", "$g_manage_inventory_num_heros"),
      (try_for_range, ":stack_no", 0, ":num_heros"),
        (troop_get_slot, ":stack_troop", "trp_temp_array_sort", ":stack_no"),
        (eq, ":stack_troop", ":selected_troop"),
        (assign, ":cur_stack_no", ":stack_no"),
      (try_end),
      (assign, ":value_change", 0),
      (try_begin),
        (this_or_next|key_clicked, key_up),
        (game_key_clicked, gk_move_forward),
        (assign, ":value_change", -1),
      (else_try),
        (this_or_next|key_clicked, key_down),
        (game_key_clicked, gk_move_backward),
        (assign, ":value_change", 1),
      (else_try),
        (this_or_next|key_clicked, key_left),
        (game_key_clicked, gk_move_left),
        (store_sub, ":value_change", 0, ":num_heros"),
      (else_try),
        (this_or_next|key_clicked, key_right),
        (game_key_clicked, gk_move_right),
        (assign, ":value_change", ":num_heros"),
      (try_end),
      (try_begin),
        (store_add, ":new_stack_no", ":cur_stack_no", ":value_change"),
        (val_clamp, ":new_stack_no", 0, ":num_heros"),
        (troop_get_slot, ":new_troop", "trp_temp_array_sort", ":new_stack_no"),
        (neq, ":new_troop", ":selected_troop"),
        (assign, ":selected_troop", ":new_troop"),
        (assign, "$g_prsnt_param_1", ":selected_troop"),
        (start_presentation, "prsnt_manage_inventory"),
      (try_end),

      (try_begin),
        (this_or_next|key_clicked, key_space),
        (game_key_clicked, gk_action),
        (val_add, "$g_weapons_set_no", 1),
        (val_mod, "$g_weapons_set_no", 2),
        (call_script, "script_all_toggle_weapons_set", 1),
        (start_presentation, "prsnt_manage_inventory"),
      (try_end),

      (try_begin),
        (key_clicked, key_escape),
        (presentation_set_duration, 0),
      (try_end),
    ]),

    (ti_on_presentation_event_state_change,[
      (store_trigger_param_1, ":object"),
      (store_trigger_param_2, ":value"),

      (assign, ":continue", 1),
      (assign, ":selected_troop", "$g_prsnt_param_1"),
      (troop_get_inventory_capacity, ":inv_cap", "trp_player"),
      (assign, ":num_heros", "$g_manage_inventory_num_heros"),

      (try_begin), # toggle weapon set for all
        (eq, ":object", "$g_presentation_obj_admin_panel_1"),
        (assign, "$g_weapons_set_no", ":value"),
        (call_script, "script_all_toggle_weapons_set", 1),
        (start_presentation, "prsnt_manage_inventory"),

      (else_try), # done
        (eq, ":object", "$g_presentation_obj_admin_panel_2"),
        (assign, ":selected_troop", "trp_player"),
        (assign, "$g_prsnt_param_1", ":selected_troop"),
        (call_script, "script_all_toggle_weapons_set", 0),
        (presentation_set_duration, 0),

      (else_try), # sort
        (eq, ":object", "$g_presentation_obj_admin_panel_4"),
        (call_script, "script_sort_player_inventory_by_item_type"),
        (start_presentation, "prsnt_manage_inventory"),

      (else_try), # upgrade all
        (eq, ":object", "$g_presentation_obj_admin_panel_6"),
        (try_for_range, ":stack_no", 0, ":num_heros"),
          (troop_get_slot, ":stack_troop", "trp_temp_array_sort", ":stack_no"),
          (call_script, "script_upgrade_armors_and_horse_for_troop", ":stack_troop"),
          (call_script, "script_upgrade_weapons_for_troop", ":stack_troop"),
        (try_end),
        (start_presentation, "prsnt_manage_inventory"),

      (try_end),

      (eq, ":continue", 1),
      # heros
      (try_for_range, ":hero_obj_slot_no", 0, ":num_heros"),
        (troop_slot_eq, "trp_temp_array_a", ":hero_obj_slot_no", ":object"),
          (troop_get_slot, ":selected_troop", "trp_temp_array_sort", ":hero_obj_slot_no"),
        (assign, "$g_prsnt_param_1", ":selected_troop"),
        (start_presentation, "prsnt_manage_inventory"),
      (try_end),

      # lock
      (assign, ":upper_bound", ":inv_cap"),
      (try_for_range, ":slot_no", 0, ":upper_bound"),
        (neq, ":slot_no", 9),
        (troop_slot_eq, "trp_temp_array_e", ":slot_no", ":object"),
        (troop_set_slot, "trp_temp_array_lock", ":slot_no", ":value"),
        (assign, ":upper_bound", 0),
      (try_end),
    ]),
  ])
