# -*- coding: cp1254 -*-
from header_troops import *

tf_guarantee_all = tf_guarantee_boots|tf_guarantee_armor|tf_guarantee_gloves|tf_guarantee_helmet|tf_guarantee_horse|tf_guarantee_shield|tf_guarantee_ranged

man_face_younger_1 = 0x0000000000000001124000000020000000000000001c00800000000000000000
man_face_younger_2 = 0x000000003f0052064deeffffffffffff00000000001efff90000000000000000
woman_face_1 = 0x0000000000000001000000000000000000000000001c00000000000000000000
woman_face_2 = 0x00000003bf0030067ff7fbffefff6dff00000000001f6dbf0000000000000000

# KCTT-only custom presets. Presets 1-3 come from the base custom_troops mod;
# these additional graph presets are generated by KCTT. They are neutral shapes,
# inspired by common native upgrade structures, not native faction imports.
#
# Each unit entry: (unit label, troop level, [upgrade target labels]).
PRESET_4_UNITS = [
	("A",  4,  ["B1", "B2"]),
	("B1", 10, ["C1", "C2"]),
	("B2", 10, ["C3", "C4"]),
	("C1", 18, ["D1"]),
	("C2", 18, ["D2"]),
	("C3", 18, ["D3", "D4"]),
	("C4", 18, ["D5", "D6"]),
	("D1", 26, ["E1"]),
	("D2", 26, ["E2"]),
	("D3", 26, ["E3"]),
	("D4", 26, ["E4"]),
	("D5", 26, ["E5"]),
	("D6", 26, ["E6"]),
	("E1", 34, ["F1"]),
	("E2", 34, []),
	("E3", 34, ["F2"]),
	("E4", 34, []),
	("E5", 34, []),
	("E6", 34, ["F3"]),
	("F1", 40, []),
	("F2", 40, []),
	("F3", 40, []),
]

PRESET_5_UNITS = [
	("A1", 4, ["B1"]),
	("B1", 10, ["C1", "C2"]),
	("C1", 18, ["D1"]),
	("C2", 18, ["D2", "D3"]),
	("D1", 26, ["E1"]),
	("D2", 26, ["E2"]),
	("D3", 26, ["E3"]),
	("E1", 34, []),
	("E2", 34, []),
	("E3", 34, []),
]

PRESET_6_UNITS = [
	("A1", 4, ["B1"]),
	("B1", 10, ["C1", "C2"]),
	("C1", 18, ["D1"]),
	("C2", 18, ["D2"]),
	("D1", 26, []),
	("D2", 26, []),
]

PRESET_7_UNITS = [
	("A", 4, ["B1", "B2"]),
	("B1", 10, ["C1"]),
	("B2", 10, ["C2"]),
	("C1", 18, ["D1"]),
	("C2", 18, ["D2"]),
	("D1", 26, ["E1"]),
	("D2", 26, []),
	("E1", 34, ["F1"]),
	("F1", 40, []),
]

PRESET_8_UNITS = [
	("A1", 4, ["B1", "B2"]),
	("B1", 10, ["C1"]),
	("B2", 10, ["C2"]),
	("C1", 18, ["D1"]),
	("C2", 18, ["D2"]),
	("D1", 26, ["E1"]),
	("D2", 26, ["E2"]),
	("E1", 34, []),
	("E2", 34, []),
]

KCT_CUSTOM_PRESETS = [
	(4, "Preset 4 - 12 branches, 6 tiers", PRESET_4_UNITS),
	(5, "Preset 5 - 5 branches, 5 tiers", PRESET_5_UNITS),
	(6, "Preset 6 - 3 branches, 4 tiers", PRESET_6_UNITS),
	(7, "Preset 7 - 3 branches, 6 tiers", PRESET_7_UNITS),
	(8, "Preset 8 - 3 branches, 5 tiers", PRESET_8_UNITS),
]

def kct_custom_preset_units(tree_index):
	for index, _, units in KCT_CUSTOM_PRESETS:
		if index == tree_index:
			return units
	return PRESET_4_UNITS

def kct_custom_preset_troop_id(tree_index, skin_id, node_index):
	return "cstm_custom_troop_%d_%d_%d_0" % (tree_index, skin_id, node_index)

def preset_4_troop_id(skin_id, node_index):
	return kct_custom_preset_troop_id(4, skin_id, node_index)

def average_face(face_1, face_2):
	age_and_skin_mask = 0xfffffffffffffffff00000000000000000000000000000000000000000000000
	average_features  = 0x000000000000000006db6db6db6db6db00000000000db6db0000000000000000
	return (((face_1 + face_2) / 2) & age_and_skin_mask) + average_features

# Troop slots used to link a real custom troop to its dummy. These MUST match the
# values in the base mod's custom_troops_constants (NEW_TROOP_SLOTS_BEGIN = 500)
# because the dummies for presets 1-3 are linked by the base mod at game start
# using those exact slot numbers.
cstm_slot_troop_dummy = 500
cstm_slot_troop_custom_troop = 501

# Marks a real troop as configured (its store Save pressed). Used by the bottom-up
# editing restriction (CSTM_TROOP_TREES_SPEC.md §7): a node's customise entry
# unlocks only after its upgrade parent has been configured. The base mod's
# allocator ends at 519, so 520 is free.
cstm_slot_troop_configured = 520

# Proficiency inheritance (bottom-up A -> B -> ... -> F):
# 531 = design lock: set on a troop when its first child is saved; while set,
#       only the equipment and name of that troop may be edited (stat boxes
#       are frozen). Persisted on the real troop.
# 532 = proficiency bonus: the parent's unspent proficiency points inherited
#       by this troop (rollover); added to the pool in kct_get_proficiency_points.
#       Persisted on the real troop (and mirrored on the dummy at store open).
cstm_slot_troop_design_lock = 531
cstm_slot_troop_proficiency_bonus = 532

# 528 = first-open marker for the proficiency inheritance snapshot: set on a
#      child the first time its store opens (parent configured, itself not yet
#      configured). Guarantees the inherited baseline is baked exactly once, so
#      Save/Reset only reflect real user edits and the snapshot never wipes them.
cstm_slot_troop_inherited = 528

# 533 = troop class override chosen in the store's Class selector
#      (0 = Auto / game-derived, 1 = grc_infantry, 2 = grc_cavalry, 3 = grc_archers).
#      Persisted on the real troop so the class survives game loads (re-applied
#      by the KCT start ops) and template export/import. Slot 533 is free: the
#      base mod's allocator ends at 519 and the KCT slots above use 520/528/531/532.
cstm_slot_troop_class_override = 533

# 521-527 = per-tree equipment budget for the Kingdom custom troop store. The
# slots live on the SHARED prefix troop (cstm_troop_tree_prefix), one per tree
# index 0-6. Values: 0 Balanced / 1 Boosted / 2 Cheater / 3 Auto. Slots 521-527
# are free: the base mod's allocator ends at 519 and the next KCT slot is 528.
cstm_slot_tree_budget_begin = 521

# The troop whose name is used to store the custom troop tree prefix string
# (mirrors cstm_troop_tree_prefix in custom_troops_constants).
cstm_troop_tree_prefix = "trp_cstm_custom_troops_end"

# Vanilla savegame-backed KCTT template bank. Each slot has one metadata troop
# plus kct_template_nodes_per_slot hero troops. The node width matches preset 4,
# the largest current tree, while smaller presets use only the first N nodes.
kct_template_slot_count = 12
kct_import_preview_backup_slot = kct_template_slot_count
kct_template_storage_slot_count = kct_template_slot_count + 1
kct_template_nodes_per_slot = max([len(units) for _, _, units in KCT_CUSTOM_PRESETS])

# Metadata slots on trp_kct_template_slot_<n>_meta.
kct_slot_template_occupied = 0
kct_slot_template_tree = 1
kct_slot_template_gender = 2
kct_slot_template_count = 3
kct_slot_template_budget = 4
kct_slot_template_version = 5

kct_template_version = 1
kct_seeded_template_slot_count = 8

def kct_template_meta_troop_id(slot_index):
	return "kct_template_slot_%d_meta" % (slot_index)

def kct_template_node_troop_id(slot_index, node_index):
	return "kct_template_slot_%d_node_%02d" % (slot_index, node_index)
