# -*- coding: cp1254 -*-
from header_common import *
from header_operations import *
from module_constants import *
from module_constants import *
from header_parties import *
from header_skills import *
from header_mission_templates import *
from header_items import *
from header_triggers import *
from header_terrain_types import *
from header_music import *
from header_map_icons import *
from ID_animations import *

initialize_banner_info_scripts = [
("initialize_banner_info",
	[
	  #Banners
      (try_for_range, ":cur_troop", active_npcs_begin, kingdom_ladies_end),
        (troop_set_slot, ":cur_troop", slot_troop_custom_banner_flag_type, -1),
        (troop_set_slot, ":cur_troop", slot_troop_custom_banner_map_flag_type, -1),
      (try_end),
      (troop_set_slot, "trp_player", slot_troop_custom_banner_flag_type, -1),
      (troop_set_slot, "trp_player", slot_troop_custom_banner_map_flag_type, -1),
      #(store_random_in_range, "$g_election_date", 0, 45), #setting a random election date
      (assign, "$g_election_date", 45),
      #Assigning global constant
      #(call_script, "script_store_average_center_value_per_faction"),

      (troop_set_slot, "trp_player", slot_troop_custom_banner_bg_color_1, 0xFFFFFFFF),
      (troop_set_slot, "trp_player", slot_troop_custom_banner_bg_color_2, 0xFFFFFFFF),
      (troop_set_slot, "trp_player", slot_troop_custom_banner_charge_color_1, 0xFFFFFFFF),
      (troop_set_slot, "trp_player", slot_troop_custom_banner_charge_color_2, 0xFFFFFFFF),
      (troop_set_slot, "trp_player", slot_troop_custom_banner_charge_color_3, 0xFFFFFFFF),
      (troop_set_slot, "trp_player", slot_troop_custom_banner_charge_color_4, 0xFFFFFFFF),

      #Setting background colors for banners
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_relations_begin, 4287579441),
        (troop_set_slot, "trp_banner_background_color_array", 1, 4292466641),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_occupation, 4281808694),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_state, 4288973608),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_last_talk_time, 4283004725),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_met, 4286723629),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_party_template, 4286133033),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_renown, 4280689953),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_prisoner_of_party, 4292467409),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_present_at_event, 4283581795),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_leaded_party, 4287705388),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_wealth, 4289700401),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_cur_center, 4285558076),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_banner_scene_prop, 4292269006),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_original_faction, 4283571208),
        (troop_set_slot, "trp_banner_background_color_array", 15, 4281943428),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_player_order_state, 4282541614),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_player_order_object, 4292861654),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_age, 4280887076),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_age_appearance, 4283982107),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_does_not_give_quest, 4281416295),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_player_debt, 4288451146),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_player_relation, 4289437989),
        (troop_set_slot, "trp_banner_background_color_array", 23, 4281749864),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_last_quest, 4292269006),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_last_quest_betrayed, 4287931970),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_last_persuasion_time, 4287906097),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_last_comment_time, 4287183668),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_spawned_before, 4282537232),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_last_comment_slot, 4287907118),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_spouse, 4282866324),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_father, 4291932721),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_mother, 4292993759),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_guardian, 4288248862),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_betrothed, 4291213133),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_love_interest_1, 4289567256),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_love_interest_2, 4280362017),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_love_interest_3, 4289083444),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_love_interests_end, 4283265334),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_betrothal_time, 4281949572),
        (troop_set_slot, "trp_banner_background_color_array", slot_lady_used_tournament, 4283594041),
        (troop_set_slot, "trp_banner_background_color_array", 41, 4288429113),
        (troop_set_slot, "trp_banner_background_color_array", 42, 4282536332),
        (troop_set_slot, "trp_banner_background_color_array", 43, 4288965164),
        (troop_set_slot, "trp_banner_background_color_array", 44, 4288631105),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_current_rumor, 4281098633),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_temp_slot, 4283786273),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_promised_fief, 4288504350),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_set_decision_seed, 4292796118),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_temp_decision_seed, 4285417617),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_recruitment_random, 4287728456),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_intrigue_impatience, 4292796377),
        (troop_set_slot, "trp_banner_background_color_array", slot_lord_reputation_type, 4283060097),
        (troop_set_slot, "trp_banner_background_color_array", slot_lord_recruitment_argument, 4287379489),
        (troop_set_slot, "trp_banner_background_color_array", slot_lord_recruitment_candidate, 4283646580),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_change_to_faction, 4293387230),
        (troop_set_slot, "trp_banner_background_color_array", 56, 4288032313),
        (troop_set_slot, "trp_banner_background_color_array", 57, 4281883011),
        (troop_set_slot, "trp_banner_background_color_array", 58, 4292270038),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_first_encountered, 4288515353),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_home, 4292072403),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_morality_state, 4281947524),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_morality_type, 4281413681),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_morality_value, 4286463790),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_2ary_morality_type, 4281611316),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_2ary_morality_state, 4282141035),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_2ary_morality_value, 4292466897),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_town_with_contacts, 4288250428),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_town_contact_type, 4288643630),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_morality_penalties, 4281940025),
        (troop_set_slot, "trp_banner_background_color_array", 70, 4289022257),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_personalityclash_object, 4292861142),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_personalityclash_state, 4288629302),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_personalityclash2_object, 4287395105),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_personalityclash2_state, 4288628273),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_personalitymatch_object, 4286133028),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_personalitymatch_state, 4281946230),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_personalityclash_penalties, 4281084716),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_home_speech_delivered, 4284838177),
        (troop_set_slot, "trp_banner_background_color_array", 79, 4286460193),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_met_previously, 4285944110),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_turned_down_twice, 4293387230),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_playerparty_history, 4287920417),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_playerparty_history_string, 4283267964),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_return_renown, 4281611057),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_custom_banner_bg_color_1, 4289154358),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_custom_banner_bg_color_2, 4293387230),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_custom_banner_charge_color_1, 4292270286),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_custom_banner_charge_color_2, 4282273127),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_custom_banner_charge_color_3, 4288644142),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_custom_banner_charge_color_4, 4283263380),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_custom_banner_bg_type, 4283064600),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_custom_banner_charge_type_1, 4287904809),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_custom_banner_charge_type_2, 4281943161),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_custom_banner_charge_type_3, 4281611057),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_custom_banner_charge_type_4, 4282338653),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_custom_banner_flag_type, 4283065481),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_custom_banner_num_charges, 4281413681),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_custom_banner_positioning, 4292270030),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_custom_banner_map_flag_type, 4291206656),
        (troop_set_slot, "trp_banner_background_color_array", 100, 4284714578),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_intro, 4292664275),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_intro_response_1, 4292598995),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_intro_response_2, 4286855217),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_backstory_a, 4291743686),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_backstory_b, 4291009841),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_backstory_c, 4291540592),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_backstory_delayed, 4281944600),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_backstory_response_1, 4281804552),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_backstory_response_2, 4288309264),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_signup, 4289886480),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_signup_2, 4287399457),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_signup_response_1, 4288109059),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_signup_response_2, 4281084196),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_mentions_payment, 4289369644),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_payment_response, 4288840238),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_morality_speech, 4286286476),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_2ary_morality_speech, 4282124552),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_personalityclash_speech, 4294902015),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_personalityclash_speech_b, 4284947988),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_personalityclash2_speech, 4279251010),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_personalityclash2_speech_b, 4283057408),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_personalitymatch_speech, 4285543204),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_personalitymatch_speech_b, 4280559932),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_retirement_speech, 4284311910),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_rehire_speech, 4287250991),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_home_intro, 4284492071),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_home_description, 4291809222),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_home_description_2, 4292467153),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_home_recap, 4284444459),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_honorific, 4287913033),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_kingsupport_string_1, 4292072651),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_kingsupport_string_2, 4281479729),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_kingsupport_string_2a, 4292401361),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_kingsupport_string_2b, 4283451237),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_kingsupport_string_3, 4280634471),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_kingsupport_objection_string, 4289241485),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_intel_gathering_string, 4283639858),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_fief_acceptance_string, 4281553956),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_woman_to_woman_string, 4289170496),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_turn_against_string, 4283112728),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_strings_end, 4287443504),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_kingsupport_state, 4280361505),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_kingsupport_argument, 4280361505),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_kingsupport_opponent, 4281219856),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_kingsupport_objection_state, 4282539387),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_player_routed_agents, 4281943560), #146
      # (troop_set_slot, "trp_banner_background_color_array", 128, 0xFF212221),
      # (troop_set_slot, "trp_banner_background_color_array", 129, 0xFF212221),
      # (troop_set_slot, "trp_banner_background_color_array", 130, 0xFF2E3B10),
      # (troop_set_slot, "trp_banner_background_color_array", 131, 0xFF425D7B),
      # (troop_set_slot, "trp_banner_background_color_array", 132, 0xFF394608),

	  ])
]
