# -*- coding: cp1254 -*-
from header_common import *
from header_operations import *
from module_constants import *
from module_constants import *
from header_parties import *
from header_skills import *
from header_mission_templates import *
from header_items import *
from header_triggers import *
from header_terrain_types import *
from header_music import *
from header_map_icons import *
from ID_animations import *

####################################################################################################################
# HERALDRY & BANNER SCRIPTS
# 
# This file contains scripts that manage banners, heraldry, and shield customization.
# It handles the placement and assignment of custom banners to troops and lords.
####################################################################################################################

heraldry_scripts = [
("initialize_banner_info",
	[
	  #Banners
      (try_for_range, ":cur_troop", active_npcs_begin, kingdom_ladies_end),
        (troop_set_slot, ":cur_troop", slot_troop_custom_banner_flag_type, -1),
        (troop_set_slot, ":cur_troop", slot_troop_custom_banner_map_flag_type, -1),
      (try_end),
      (troop_set_slot, "trp_player", slot_troop_custom_banner_flag_type, -1),
      (troop_set_slot, "trp_player", slot_troop_custom_banner_map_flag_type, -1),
      #(store_random_in_range, "$g_election_date", 0, 45), #setting a random election date
      (assign, "$g_election_date", 45),
      #Assigning global constant
      #(call_script, "script_store_average_center_value_per_faction"),

      (troop_set_slot, "trp_player", slot_troop_custom_banner_bg_color_1, 0xFFFFFFFF),
      (troop_set_slot, "trp_player", slot_troop_custom_banner_bg_color_2, 0xFFFFFFFF),
      (troop_set_slot, "trp_player", slot_troop_custom_banner_charge_color_1, 0xFFFFFFFF),
      (troop_set_slot, "trp_player", slot_troop_custom_banner_charge_color_2, 0xFFFFFFFF),
      (troop_set_slot, "trp_player", slot_troop_custom_banner_charge_color_3, 0xFFFFFFFF),
      (troop_set_slot, "trp_player", slot_troop_custom_banner_charge_color_4, 0xFFFFFFFF),

      #Setting background colors for banners
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_relations_begin, 4287579441),
        (troop_set_slot, "trp_banner_background_color_array", 1, 4292466641),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_occupation, 4281808694),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_state, 4288973608),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_last_talk_time, 4283004725),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_met, 4286723629),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_party_template, 4286133033),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_renown, 4280689953),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_prisoner_of_party, 4292467409),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_present_at_event, 4283581795),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_leaded_party, 4287705388),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_wealth, 4289700401),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_cur_center, 4285558076),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_banner_scene_prop, 4292269006),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_original_faction, 4283571208),
        (troop_set_slot, "trp_banner_background_color_array", 15, 4281943428),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_player_order_state, 4282541614),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_player_order_object, 4292861654),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_age, 4280887076),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_age_appearance, 4283982107),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_does_not_give_quest, 4281416295),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_player_debt, 4288451146),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_player_relation, 4289437989),
        (troop_set_slot, "trp_banner_background_color_array", 23, 4281749864),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_last_quest, 4292269006),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_last_quest_betrayed, 4287931970),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_last_persuasion_time, 4287906097),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_last_comment_time, 4287183668),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_spawned_before, 4282537232),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_last_comment_slot, 4287907118),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_spouse, 4282866324),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_father, 4291932721),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_mother, 4292993759),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_guardian, 4288248862),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_betrothed, 4291213133),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_love_interest_1, 4289567256),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_love_interest_2, 4280362017),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_love_interest_3, 4289083444),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_love_interests_end, 4283265334),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_betrothal_time, 4281949572),
        (troop_set_slot, "trp_banner_background_color_array", slot_lady_used_tournament, 4283594041),
        (troop_set_slot, "trp_banner_background_color_array", 41, 4288429113),
        (troop_set_slot, "trp_banner_background_color_array", 42, 4282536332),
        (troop_set_slot, "trp_banner_background_color_array", 43, 4288965164),
        (troop_set_slot, "trp_banner_background_color_array", 44, 4288631105),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_current_rumor, 4281098633),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_temp_slot, 4283786273),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_promised_fief, 4288504350),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_set_decision_seed, 4292796118),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_temp_decision_seed, 4285417617),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_recruitment_random, 4287728456),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_intrigue_impatience, 4292796377),
        (troop_set_slot, "trp_banner_background_color_array", slot_lord_reputation_type, 4283060097),
        (troop_set_slot, "trp_banner_background_color_array", slot_lord_recruitment_argument, 4287379489),
        (troop_set_slot, "trp_banner_background_color_array", slot_lord_recruitment_candidate, 4283646580),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_change_to_faction, 4293387230),
        (troop_set_slot, "trp_banner_background_color_array", 56, 4288032313),
        (troop_set_slot, "trp_banner_background_color_array", 57, 4281883011),
        (troop_set_slot, "trp_banner_background_color_array", 58, 4292270038),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_first_encountered, 4288515353),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_home, 4292072403),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_morality_state, 4281947524),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_morality_type, 4281413681),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_morality_value, 4286463790),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_2ary_morality_type, 4281611316),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_2ary_morality_state, 4282141035),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_2ary_morality_value, 4292466897),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_town_with_contacts, 4288250428),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_town_contact_type, 4288643630),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_morality_penalties, 4281940025),
        (troop_set_slot, "trp_banner_background_color_array", 70, 4289022257),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_personalityclash_object, 4292861142),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_personalityclash_state, 4288629302),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_personalityclash2_object, 4287395105),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_personalityclash2_state, 4288628273),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_personalitymatch_object, 4286133028),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_personalitymatch_state, 4281946230),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_personalityclash_penalties, 4281084716),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_home_speech_delivered, 4284838177),
        (troop_set_slot, "trp_banner_background_color_array", 79, 4286460193),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_met_previously, 4285944110),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_turned_down_twice, 4293387230),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_playerparty_history, 4287920417),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_playerparty_history_string, 4283267964),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_return_renown, 4281611057),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_custom_banner_bg_color_1, 4289154358),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_custom_banner_bg_color_2, 4293387230),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_custom_banner_charge_color_1, 4292270286),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_custom_banner_charge_color_2, 4282273127),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_custom_banner_charge_color_3, 4288644142),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_custom_banner_charge_color_4, 4283263380),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_custom_banner_bg_type, 4283064600),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_custom_banner_charge_type_1, 4287904809),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_custom_banner_charge_type_2, 4281943161),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_custom_banner_charge_type_3, 4281611057),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_custom_banner_charge_type_4, 4282338653),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_custom_banner_flag_type, 4283065481),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_custom_banner_num_charges, 4281413681),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_custom_banner_positioning, 4292270030),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_custom_banner_map_flag_type, 4291206656),
        (troop_set_slot, "trp_banner_background_color_array", 100, 4284714578),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_intro, 4292664275),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_intro_response_1, 4292598995),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_intro_response_2, 4286855217),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_backstory_a, 4291743686),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_backstory_b, 4291009841),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_backstory_c, 4291540592),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_backstory_delayed, 4281944600),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_backstory_response_1, 4281804552),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_backstory_response_2, 4288309264),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_signup, 4289886480),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_signup_2, 4287399457),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_signup_response_1, 4288109059),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_signup_response_2, 4281084196),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_mentions_payment, 4289369644),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_payment_response, 4288840238),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_morality_speech, 4286286476),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_2ary_morality_speech, 4282124552),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_personalityclash_speech, 4294902015),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_personalityclash_speech_b, 4284947988),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_personalityclash2_speech, 4279251010),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_personalityclash2_speech_b, 4283057408),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_personalitymatch_speech, 4285543204),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_personalitymatch_speech_b, 4280559932),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_retirement_speech, 4284311910),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_rehire_speech, 4287250991),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_home_intro, 4284492071),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_home_description, 4291809222),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_home_description_2, 4292467153),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_home_recap, 4284444459),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_honorific, 4287913033),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_kingsupport_string_1, 4292072651),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_kingsupport_string_2, 4281479729),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_kingsupport_string_2a, 4292401361),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_kingsupport_string_2b, 4283451237),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_kingsupport_string_3, 4280634471),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_kingsupport_objection_string, 4289241485),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_intel_gathering_string, 4283639858),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_fief_acceptance_string, 4281553956),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_woman_to_woman_string, 4289170496),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_turn_against_string, 4283112728),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_strings_end, 4287443504),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_kingsupport_state, 4280361505),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_kingsupport_argument, 4280361505),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_kingsupport_opponent, 4281219856),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_kingsupport_objection_state, 4282539387),
        (troop_set_slot, "trp_banner_background_color_array", slot_troop_player_routed_agents, 4281943560), #146
      # (troop_set_slot, "trp_banner_background_color_array", 128, 0xFF212221),
      # (troop_set_slot, "trp_banner_background_color_array", 129, 0xFF212221),
      # (troop_set_slot, "trp_banner_background_color_array", 130, 0xFF2E3B10),
      # (troop_set_slot, "trp_banner_background_color_array", 131, 0xFF425D7B),
      # (troop_set_slot, "trp_banner_background_color_array", 132, 0xFF394608),

	  ]),


      # Input: none
  # Output: none
  ("change_banners_and_chest",
    [(party_get_slot, ":cur_leader", "$g_encountered_party", slot_town_lord),
     (try_begin),
       (ge, ":cur_leader", 0),
#normal_banner_begin
       (troop_get_slot, ":troop_banner_object", ":cur_leader", slot_troop_banner_scene_prop),
       (try_begin),
           (gt, ":troop_banner_object", 0),
           (replace_scene_props, banner_scene_props_begin, ":troop_banner_object"),
       (else_try),
           (eq, ":troop_banner_object", -1),
           (troop_get_slot, ":troop_custom_banner_object", ":cur_leader", slot_troop_custom_banner_flag_type),
           (ge, ":troop_custom_banner_object", 0),
           (val_add, ":troop_custom_banner_object", "spr_custom_banner_01"),
           (replace_scene_props, "spr_banner_a", ":troop_custom_banner_object"),
       (try_end),
     (else_try),
       (replace_scene_props, banner_scene_props_begin, "spr_empty"),
     (try_end),
     (try_begin),
       (neq, ":cur_leader", "trp_player"),
       (replace_scene_props, "spr_player_chest", "spr_locked_player_chest"),
     (try_end),
     ]),


  # script_remove_siege_objects
  # INPUT: agent_no, troop_no
  # OUTPUT: banner_mesh
  ("agent_troop_get_banner_mesh",
    [
       (store_script_param, ":troop_no", 2),
       (assign, ":banner_mesh", "mesh_banners_default_b"),

        (try_begin),
            (eq, "$g_is_quick_battle", 1),
            (try_begin),
                (eq, ":troop_no", -2),
                (assign, ":banner_mesh", "$g_quick_battle_team_0_banner"),
                (val_sub, ":banner_mesh", banner_meshes_begin),
                (val_add, ":banner_mesh", arms_meshes_begin),
            (else_try),
                (eq, ":troop_no", -3),
                (assign, ":banner_mesh", "$g_quick_battle_team_1_banner"),
                (val_sub, ":banner_mesh", banner_meshes_begin),
                (val_add, ":banner_mesh", arms_meshes_begin),
            (try_end),
        (else_try),
            (game_in_multiplayer_mode),
            (ge, ":troop_no", 0),
            (try_begin),
                (is_between, ":troop_no", arms_meshes_begin, arms_meshes_end_minus_one),
                (assign, ":banner_mesh", ":troop_no"),
            (try_end),
            # (store_faction_of_troop, ":faction_of_troop_script_param_1", ":troop_no"),
            # (is_between, ":faction_of_troop_script_param_1", "fac_kingdom_1", "fac_kingdoms_end"),
            # (faction_get_slot, ":banner_mesh", ":faction_of_troop_script_param_1", slot_faction_banner),
            # (val_sub, ":banner_mesh", banner_meshes_begin),
            # (val_add, ":banner_mesh", arms_meshes_begin),
        (else_try),
            (ge, ":troop_no", 0),
            (try_begin),
               (troop_slot_ge, ":troop_no", slot_troop_banner_scene_prop, 1),
               (troop_get_slot, ":banner_spr", ":troop_no", slot_troop_banner_scene_prop),
               (store_add, ":banner_scene_props_end", banner_scene_props_end_minus_one, 1),
               (is_between, ":banner_spr", banner_scene_props_begin, ":banner_scene_props_end"),
               (val_sub, ":banner_spr", banner_scene_props_begin),
               (store_add, ":banner_mesh", ":banner_spr", arms_meshes_begin),
            (try_end),
        (else_try),
            (eq, ":troop_no", -1),
            (assign, ":banner_mesh", "mesh_banners_default_a"),
        (else_try),
            (eq, ":troop_no", -2),
            (assign, ":banner_mesh", "mesh_banners_default_b"),
        (else_try),
            (eq, ":troop_no", -3),
            (assign, ":banner_mesh", "mesh_banners_default_c"),
        (else_try),
            (eq, ":troop_no", -4),
            (assign, ":banner_mesh", "mesh_banners_default_d"),
        (else_try),
            (eq, ":troop_no", -5),
            (assign, ":banner_mesh", "mesh_banners_default_e"),
        (try_end),
        (assign, reg0, ":banner_mesh"),
        #(display_message, "@banner mesh: {reg0}"),


       # (try_begin),
         # (lt, ":agent_no", 0),
         # (try_begin),
           # (ge, ":troop_no", 0),
           # (this_or_next|troop_slot_ge, ":troop_no", slot_troop_banner_scene_prop, 1),
           # (eq, ":troop_no", "trp_player"),
           # (assign, ":banner_troop", ":troop_no"),
         # (else_try),
           # (is_between, ":troop_no", companions_begin, companions_end),
           # (assign, ":banner_troop", "trp_player"),
         # (else_try),
           # (assign, ":banner_mesh", "mesh_banners_default_a"),
         # (try_end),
       # (else_try),
         # (eq, "$g_is_quick_battle", 1),
         # (agent_get_team, ":agent_team", ":agent_no"),
         # (try_begin),
           # (eq, ":agent_team", 0),
           # (assign, ":banner_mesh", "$g_quick_battle_team_0_banner"),
         # (else_try),
           # (assign, ":banner_mesh", "$g_quick_battle_team_1_banner"),
         # (try_end),
         # (try_begin),
            # (is_between, ":banner_mesh", banner_meshes_begin, arms_meshes_begin), #dckplmc - back colors
            # (store_sub, ":banner_offset", ":banner_mesh", banner_meshes_begin),
            # (store_add, ":banner_mesh", ":banner_offset", arms_meshes_begin),
         # (try_end),
       # (else_try),
         # (game_in_multiplayer_mode),
         # (agent_get_group, ":agent_group", ":agent_no"),
         # (try_begin),
           # (neg|player_is_active, ":agent_group"),
           # (agent_get_player_id, ":agent_group", ":agent_no"),
         # (try_end),
         # (try_begin),
           # #if player banners are not allowed, use the default banner mesh
           # (eq, "$g_multiplayer_allow_player_banners", 1),
           # (player_is_active, ":agent_group"),
           # (player_get_banner_id, ":player_banner", ":agent_group"),
           # (ge, ":player_banner", 0),
           # (store_add, ":banner_mesh", ":player_banner", arms_meshes_begin),
           # (assign, ":already_used", 0),
           # (try_for_range, ":cur_faction", npc_kingdoms_begin, npc_kingdoms_end), #wrong client data check
             # (faction_slot_eq, ":cur_faction", slot_faction_banner, ":banner_mesh"),
             # (assign, ":already_used", 1),
           # (try_end),
           # (eq, ":already_used", 0), #otherwise use the default banner mesh
         # (else_try),
           # (agent_get_team, ":agent_team", ":agent_no"),
           # (team_get_faction, ":team_faction_no", ":agent_team"),

           # (try_begin),
             # (agent_is_human, ":agent_no"),
             # (faction_get_slot, ":banner_mesh", ":team_faction_no", slot_faction_banner),
           # (else_try),
             # (agent_get_rider, ":rider_agent_no", ":agent_no"),
             # #(agent_get_position, pos1, ":agent_no"),
             # #(position_get_x, ":pos_x", pos1),
             # #(position_get_y, ":pos_y", pos1),
             # #(assign, reg0, ":pos_x"),
             # #(assign, reg1, ":pos_y"),
             # #(assign, reg2, ":agent_no"),
             # #(display_message, "@{!}agent_no:{reg2}, pos_x:{reg0} , posy:{reg1}"),
             # (try_begin),
               # (ge, ":rider_agent_no", 0),
               # (agent_is_active, ":rider_agent_no"),
               # (agent_get_team, ":rider_agent_team", ":rider_agent_no"),
               # (team_get_faction, ":rider_team_faction_no", ":rider_agent_team"),
               # (faction_get_slot, ":banner_mesh", ":rider_team_faction_no", slot_faction_banner),
             # (else_try),
               # (assign, ":banner_mesh", "mesh_banners_default_c"),
             # (try_end),
           # (try_end),
         # (try_end),
       # (else_try),
         # #(agent_get_troop_id, ":troop_id", ":agent_no"),
         # #(this_or_next|troop_slot_ge,  ":troop_id", slot_troop_banner_scene_prop, 1),
         # (this_or_next|troop_slot_ge,  ":troop_no", slot_troop_banner_scene_prop, 1),
         # (eq, ":troop_no", "trp_player"),
         # (assign, ":banner_troop", ":troop_no"),

       # (else_try),
         # (agent_get_troop_id, ":troop_id", ":agent_no"),
         # (agent_get_party_id, ":agent_party", ":agent_no"),
         # (try_begin),
           # (lt, ":agent_party", 0),
           # (is_between, ":troop_id", companions_begin, companions_end),
           # (main_party_has_troop, ":troop_id"),
           # (assign, ":agent_party", "p_main_party"),
         # (try_end),
         # (ge, ":agent_party", 0),
         # (party_get_template_id, ":party_template", ":agent_party"),
         # (try_begin),
           # (eq, ":party_template", "pt_deserters"),
           # (assign, ":banner_mesh", "mesh_banners_default_c"),
         # (else_try),
           # (is_between, ":agent_party", centers_begin, centers_end),
           # (is_between, ":troop_id", companions_begin, companions_end),
           # (neg|troop_slot_eq, ":troop_no", slot_troop_occupation, slto_kingdom_hero), #dckplmc
           # (neq, "$talk_context", tc_tavern_talk),
           # #this should be a captured companion in prison
           # (assign, ":banner_troop", "trp_player"),
         # (else_try),
           # (is_between, ":agent_party", centers_begin, centers_end),
           # (party_get_slot, ":town_lord", "$g_encountered_party", slot_town_lord),
           # (ge, ":town_lord", 0),
           # (assign, ":banner_troop", ":town_lord"),
         # (else_try),
           # (this_or_next|party_slot_eq, ":agent_party", slot_party_type, spt_kingdom_hero_party),
           # (eq, ":agent_party", "p_main_party"),
           # (party_get_num_companion_stacks, ":num_stacks", ":agent_party"),
           # (gt, ":num_stacks", 0),
           # (party_stack_get_troop_id, ":leader_troop_id", ":agent_party", 0),
           # (this_or_next|troop_slot_ge,  ":leader_troop_id", slot_troop_banner_scene_prop, 1),
           # (eq, ":leader_troop_id", "trp_player"),
           # (assign, ":banner_troop", ":leader_troop_id"),
         # (try_end),
       # (else_try), #Check if we are in a tavern
         # (eq, "$talk_context", tc_tavern_talk),
         # (neq, ":troop_no", "trp_player"),
         # (assign, ":banner_mesh", "mesh_banners_default_d"),
       # (else_try), #camp
         # (eq, "$talk_context", tc_camp_talk),
         # (assign, ":banner_troop", "trp_player"),
       # (else_try), #can't find party, this can be a town guard
         # (neq, ":troop_no", "trp_player"),
         # (is_between, "$g_encountered_party", walled_centers_begin, walled_centers_end),
         # (party_get_slot, ":town_lord", "$g_encountered_party", slot_town_lord),
         # (ge, ":town_lord", 0),
         # (assign, ":banner_troop", ":town_lord"),
       # (try_end),
       # (try_begin),
         # (ge, ":banner_troop", 0),
         # (try_begin),
           # (neg|troop_slot_ge, ":banner_troop", slot_troop_banner_scene_prop, 1),
           # (assign, ":banner_mesh", "mesh_banners_default_b"),
         # (else_try),
           # (troop_get_slot, ":banner_spr", ":banner_troop", slot_troop_banner_scene_prop),
           # (store_add, ":banner_scene_props_end", banner_scene_props_end_minus_one, 1),
           # (is_between, ":banner_spr", banner_scene_props_begin, ":banner_scene_props_end"),
           # (val_sub, ":banner_spr", banner_scene_props_begin),
           # (store_add, ":banner_mesh", ":banner_spr", arms_meshes_begin),
         # (try_end),
       # (try_end),

       # (assign, reg0, ":banner_mesh"),
       # (display_message, "@banner mesh: {reg0}")
     ]),
  #script_shield_item_set_banner
  # INPUT: agent_no
  # OUTPUT: none
  ("shield_item_set_banner",
    [
       (store_script_param, ":tableau_no",1),
       (store_script_param, ":agent_no", 2),
       (store_script_param, ":troop_no", 3),
       #(call_script, "script_agent_troop_get_banner_mesh", ":agent_no", ":troop_no"),
       #(cur_item_set_tableau_material, ":tableau_no", reg0),

       (assign, ":banner_troop", -1),
       #(assign, ":banner_mesh", 0),

       (try_begin),
           (agent_is_active, ":agent_no"),
           (agent_get_rider, ":rider_agent_no", ":agent_no"),
           (gt, ":rider_agent_no", -1),
           (assign, ":agent_no", ":rider_agent_no"),
           (agent_get_troop_id, ":troop_no", ":rider_agent_no"),
       (try_end),

       (try_begin),
         (lt, ":agent_no", 0),
         (try_begin),
           (ge, ":troop_no", 0),
           (this_or_next|troop_slot_ge, ":troop_no", slot_troop_banner_scene_prop, 1),
           (eq, ":troop_no", "trp_player"),
           (assign, ":banner_troop", ":troop_no"),
         (else_try),
           (ge, ":troop_no", 0),
           (troop_slot_eq, ":troop_no", slot_troop_banner_scene_prop, -1),
           (troop_slot_ge, ":troop_no", slot_troop_custom_banner_map_flag_type, 0),
           (assign, ":banner_troop", ":troop_no"),
         (else_try),
           (is_between, ":troop_no", companions_begin, companions_end),
           (assign, ":banner_troop", "trp_player"),
         (else_try),
           (is_between, ":troop_no", kingdom_ladies_begin, kingdom_ladies_end),
           (neg|troop_slot_eq, ":troop_no", slot_troop_occupation, slto_kingdom_hero),
           (troop_slot_eq, ":troop_no", slot_troop_spouse, "trp_player"),
           (assign, ":banner_troop", "trp_player"),
         (else_try),
           (assign, ":banner_troop", -2),
         (try_end),
       (else_try),
         (eq, "$g_is_quick_battle", 1),
         (agent_get_team, ":agent_team", ":agent_no"),
         (try_begin),
           (eq, ":agent_team", 0),
           (assign, ":banner_troop", -2),
         (else_try),
           (assign, ":banner_troop", -3),
         (try_end),
         # (try_begin),
            # (is_between, ":banner_mesh", banner_meshes_begin, arms_meshes_begin), #dckplmc - back colors
            # (store_sub, ":banner_offset", ":banner_mesh", banner_meshes_begin),
            # (store_add, ":banner_mesh", ":banner_offset", arms_meshes_begin),
         # (try_end),
       (else_try),
         (game_in_multiplayer_mode),
         (agent_get_group, ":agent_group", ":agent_no"),
         (try_begin),
           (neg|player_is_active, ":agent_group"),
           (agent_get_player_id, ":agent_group", ":agent_no"),
         (try_end),
         (try_begin),
           #if player banners are not allowed, use the default banner mesh
           (eq, "$g_multiplayer_allow_player_banners", 1),
           (player_is_active, ":agent_group"),
           (player_get_banner_id, ":player_banner", ":agent_group"),
           (ge, ":player_banner", 0),
           (store_add, ":banner_troop", ":player_banner", arms_meshes_begin),
           (assign, ":already_used", 0),
           (try_for_range, ":cur_faction", npc_kingdoms_begin, npc_kingdoms_end), #wrong client data check
             (faction_slot_eq, ":cur_faction", slot_faction_banner, ":banner_troop"),
             (assign, ":already_used", 1),
           (try_end),
           (eq, ":already_used", 0), #otherwise use the default banner mesh
         (else_try),
           (agent_get_team, ":agent_team", ":agent_no"),
           (team_get_faction, ":team_faction_no", ":agent_team"),

           (try_begin),
             (agent_is_human, ":agent_no"),
             (faction_get_slot, ":banner_troop", ":team_faction_no", slot_faction_banner),
           (else_try),
             (agent_get_rider, ":rider_agent_no", ":agent_no"),
             #(agent_get_position, pos1, ":agent_no"),
             #(position_get_x, ":pos_x", pos1),
             #(position_get_y, ":pos_y", pos1),
             #(assign, reg0, ":pos_x"),
             #(assign, reg1, ":pos_y"),
             #(assign, reg2, ":agent_no"),
             #(display_message, "@{!}agent_no:{reg2}, pos_x:{reg0} , posy:{reg1}"),
             (try_begin),
               (ge, ":rider_agent_no", 0),
               (agent_is_active, ":rider_agent_no"),
               (agent_get_team, ":rider_agent_team", ":rider_agent_no"),
               (team_get_faction, ":rider_team_faction_no", ":rider_agent_team"),
               (faction_get_slot, ":banner_troop", ":rider_team_faction_no", slot_faction_banner),
             (else_try),
               (assign, ":banner_troop", -4),
             (try_end),
           (try_end),
         (try_end),
       (else_try),
         #(agent_get_troop_id, ":troop_id", ":agent_no"),
         #(this_or_next|troop_slot_ge,  ":troop_id", slot_troop_banner_scene_prop, 1),
         (this_or_next|troop_slot_ge,  ":troop_no", slot_troop_banner_scene_prop, 1),
         (eq, ":troop_no", "trp_player"),
         (assign, ":banner_troop", ":troop_no"),
       (else_try),
         (troop_slot_eq,  ":troop_no", slot_troop_banner_scene_prop, -1),
         (troop_slot_ge, ":troop_no", slot_troop_custom_banner_map_flag_type, 0),
         (assign, ":banner_troop", ":troop_no"),

       (else_try),
         (agent_get_troop_id, ":troop_id", ":agent_no"),
         (agent_get_party_id, ":agent_party", ":agent_no"),
         (try_begin),
           (lt, ":agent_party", 0),
           (is_between, ":troop_id", companions_begin, companions_end),
           (main_party_has_troop, ":troop_id"),
           (assign, ":agent_party", "p_main_party"),
         (try_end),
         (ge, ":agent_party", 0),
         (party_get_template_id, ":party_template", ":agent_party"),
         (try_begin),
           (eq, ":party_template", "pt_deserters"),
           (assign, ":banner_troop", -3),
         (else_try),
           (is_between, ":agent_party", centers_begin, centers_end),
           (is_between, ":troop_id", companions_begin, companions_end),
           (neg|troop_slot_eq, ":troop_no", slot_troop_occupation, slto_kingdom_hero), #dckplmc
           (neq, "$talk_context", tc_tavern_talk),
           #this should be a captured companion in prison
           (assign, ":banner_troop", "trp_player"),
         (else_try),
           (is_between, ":agent_party", centers_begin, centers_end),
           (party_get_slot, ":town_lord", "$g_encountered_party", slot_town_lord),
           (ge, ":town_lord", 0),
           (assign, ":banner_troop", ":town_lord"),
         (else_try),
           (this_or_next|party_slot_eq, ":agent_party", slot_party_type, spt_kingdom_hero_party),
           (eq, ":agent_party", "p_main_party"),
           (party_get_num_companion_stacks, ":num_stacks", ":agent_party"),
           (gt, ":num_stacks", 0),
           (party_stack_get_troop_id, ":leader_troop_id", ":agent_party", 0),
           (this_or_next|troop_slot_ge,  ":leader_troop_id", slot_troop_banner_scene_prop, 1),
           (eq, ":leader_troop_id", "trp_player"),
           (assign, ":banner_troop", ":leader_troop_id"),
         (else_try),
           (party_slot_eq, ":agent_party", slot_party_type, spt_kingdom_hero_party),
           (party_get_num_companion_stacks, ":num_stacks", ":agent_party"),
           (gt, ":num_stacks", 0),
           (party_stack_get_troop_id, ":leader_troop_id", ":agent_party", 0),
           (troop_slot_eq,  ":leader_troop_id", slot_troop_banner_scene_prop, -1),
           (troop_slot_ge, ":leader_troop_id", slot_troop_custom_banner_map_flag_type, 0),
           (assign, ":banner_troop", ":leader_troop_id"),
         (try_end),
       (else_try), #Check if we are in a tavern
         (eq, "$talk_context", tc_tavern_talk),
         (neq, ":troop_no", "trp_player"),
         (assign, ":banner_troop", -4),
       (else_try), #camp
         (eq, "$talk_context", tc_camp_talk),
         (assign, ":banner_troop", "trp_player"),
       (else_try), #can't find party, this can be a town guard
         (neq, ":troop_no", "trp_player"),
         (is_between, "$g_encountered_party", walled_centers_begin, walled_centers_end),
         (party_get_slot, ":town_lord", "$g_encountered_party", slot_town_lord),
         (ge, ":town_lord", 0),
         (assign, ":banner_troop", ":town_lord"),
       (try_end),

       # (str_store_troop_name, s0, ":troop_no"),
       # (display_message, s0),
       #(cur_item_set_banner_tableau_material, ":tableau_no", ":troop_no"),
       (cur_item_set_tableau_material, ":tableau_no", ":banner_troop"),
     ]),


  #script_troop_agent_set_banner
  # INPUT: agent_no
  # OUTPUT: none
  ("troop_agent_set_banner",
    [
       (store_script_param, ":tableau_no",1),
       (store_script_param, ":agent_no", 2),
       (store_script_param, ":troop_no", 3),
       # (call_script, "script_agent_troop_get_banner_mesh", ":agent_no", ":troop_no"),
       # (cur_agent_set_banner_tableau_material, ":tableau_no", reg0),

       (assign, ":banner_troop", -1),
       #(assign, ":banner_mesh", 0),

       (try_begin),
         (lt, ":agent_no", 0),
         (try_begin),
           (ge, ":troop_no", 0),
           (this_or_next|troop_slot_ge, ":troop_no", slot_troop_banner_scene_prop, 1),
           (eq, ":troop_no", "trp_player"),
           (assign, ":banner_troop", ":troop_no"),
         (else_try),
           (ge, ":troop_no", 0),
           (troop_slot_eq, ":troop_no", slot_troop_banner_scene_prop, -1),
           (troop_slot_ge, ":troop_no", slot_troop_custom_banner_map_flag_type, 0),
           (assign, ":banner_troop", ":troop_no"),
         (else_try),
           (is_between, ":troop_no", companions_begin, companions_end),
           (assign, ":banner_troop", "trp_player"),
         (else_try),
           (is_between, ":troop_no", kingdom_ladies_begin, kingdom_ladies_end),
           (neg|troop_slot_eq, ":troop_no", slot_troop_occupation, slto_kingdom_hero),
           (troop_slot_eq, ":troop_no", slot_troop_spouse, "trp_player"),
           (assign, ":banner_troop", "trp_player"),
         (else_try),
           (assign, ":banner_troop", -2),
         (try_end),
       (else_try),
         (eq, "$g_is_quick_battle", 1),
         (agent_get_team, ":agent_team", ":agent_no"),
         (try_begin),
           (eq, ":agent_team", 0),
           (assign, ":banner_troop", -2),
         (else_try),
           (assign, ":banner_troop", -3),
         (try_end),
         # (try_begin),
            # (is_between, ":banner_mesh", banner_meshes_begin, arms_meshes_begin), #dckplmc - back colors
            # (store_sub, ":banner_offset", ":banner_mesh", banner_meshes_begin),
            # (store_add, ":banner_mesh", ":banner_offset", arms_meshes_begin),
         # (try_end),
       (else_try),
         (game_in_multiplayer_mode),
         (agent_get_group, ":agent_group", ":agent_no"),
         (try_begin),
           (neg|player_is_active, ":agent_group"),
           (agent_get_player_id, ":agent_group", ":agent_no"),
         (try_end),
         (try_begin),
           #if player banners are not allowed, use the default banner mesh
           (eq, "$g_multiplayer_allow_player_banners", 1),
           (player_is_active, ":agent_group"),
           (player_get_banner_id, ":player_banner", ":agent_group"),
           (ge, ":player_banner", 0),
           (store_add, ":banner_troop", ":player_banner", arms_meshes_begin),
           (assign, ":already_used", 0),
           (try_for_range, ":cur_faction", npc_kingdoms_begin, npc_kingdoms_end), #wrong client data check
             (faction_slot_eq, ":cur_faction", slot_faction_banner, ":banner_troop"),
             (assign, ":already_used", 1),
           (try_end),
           (eq, ":already_used", 0), #otherwise use the default banner mesh
         (else_try),
           (agent_get_team, ":agent_team", ":agent_no"),
           (team_get_faction, ":team_faction_no", ":agent_team"),

           (try_begin),
             (agent_is_human, ":agent_no"),
             (faction_get_slot, ":banner_troop", ":team_faction_no", slot_faction_banner),
           (else_try),
             (agent_get_rider, ":rider_agent_no", ":agent_no"),
             #(agent_get_position, pos1, ":agent_no"),
             #(position_get_x, ":pos_x", pos1),
             #(position_get_y, ":pos_y", pos1),
             #(assign, reg0, ":pos_x"),
             #(assign, reg1, ":pos_y"),
             #(assign, reg2, ":agent_no"),
             #(display_message, "@{!}agent_no:{reg2}, pos_x:{reg0} , posy:{reg1}"),
             (try_begin),
               (ge, ":rider_agent_no", 0),
               (agent_is_active, ":rider_agent_no"),
               (agent_get_team, ":rider_agent_team", ":rider_agent_no"),
               (team_get_faction, ":rider_team_faction_no", ":rider_agent_team"),
               (faction_get_slot, ":banner_troop", ":rider_team_faction_no", slot_faction_banner),
             (else_try),
               (assign, ":banner_troop", -4),
             (try_end),
           (try_end),
         (try_end),
       (else_try),
         #(agent_get_troop_id, ":troop_id", ":agent_no"),
         #(this_or_next|troop_slot_ge,  ":troop_id", slot_troop_banner_scene_prop, 1),
         (this_or_next|troop_slot_ge,  ":troop_no", slot_troop_banner_scene_prop, 1),
         (eq, ":troop_no", "trp_player"),
         (assign, ":banner_troop", ":troop_no"),
       (else_try),
         (troop_slot_eq,  ":troop_no", slot_troop_banner_scene_prop, -1),
         (troop_slot_ge, ":troop_no", slot_troop_custom_banner_map_flag_type, 0),
         (assign, ":banner_troop", ":troop_no"),

       (else_try),
         (agent_get_troop_id, ":troop_id", ":agent_no"),
         (agent_get_party_id, ":agent_party", ":agent_no"),
         (try_begin),
           (lt, ":agent_party", 0),
           (is_between, ":troop_id", companions_begin, companions_end),
           (main_party_has_troop, ":troop_id"),
           (assign, ":agent_party", "p_main_party"),
         (try_end),
         (ge, ":agent_party", 0),
         (party_get_template_id, ":party_template", ":agent_party"),
         (try_begin),
           (eq, ":party_template", "pt_deserters"),
           (assign, ":banner_troop", -3),
         (else_try),
           (is_between, ":agent_party", centers_begin, centers_end),
           (is_between, ":troop_id", companions_begin, companions_end),
           (neg|troop_slot_eq, ":troop_no", slot_troop_occupation, slto_kingdom_hero), #dckplmc
           (neq, "$talk_context", tc_tavern_talk),
           #this should be a captured companion in prison
           (assign, ":banner_troop", "trp_player"),
         (else_try),
           (is_between, ":agent_party", centers_begin, centers_end),
           (party_get_slot, ":town_lord", "$g_encountered_party", slot_town_lord),
           (ge, ":town_lord", 0),
           (assign, ":banner_troop", ":town_lord"),
         (else_try),
           (this_or_next|party_slot_eq, ":agent_party", slot_party_type, spt_kingdom_hero_party),
           (eq, ":agent_party", "p_main_party"),
           (party_get_num_companion_stacks, ":num_stacks", ":agent_party"),
           (gt, ":num_stacks", 0),
           (party_stack_get_troop_id, ":leader_troop_id", ":agent_party", 0),
           (this_or_next|troop_slot_ge,  ":leader_troop_id", slot_troop_banner_scene_prop, 1),
           (eq, ":leader_troop_id", "trp_player"),
           (assign, ":banner_troop", ":leader_troop_id"),
         (else_try),
           (party_slot_eq, ":agent_party", slot_party_type, spt_kingdom_hero_party),
           (party_get_num_companion_stacks, ":num_stacks", ":agent_party"),
           (gt, ":num_stacks", 0),
           (party_stack_get_troop_id, ":leader_troop_id", ":agent_party", 0),
           (troop_slot_eq,  ":leader_troop_id", slot_troop_banner_scene_prop, -1),
           (troop_slot_ge, ":leader_troop_id", slot_troop_custom_banner_map_flag_type, 0),
           (assign, ":banner_troop", ":leader_troop_id"),
         (try_end),
       (else_try), #Check if we are in a tavern
         (eq, "$talk_context", tc_tavern_talk),
         (neq, ":troop_no", "trp_player"),
         (assign, ":banner_troop", -4),
       (else_try), #camp
         (eq, "$talk_context", tc_camp_talk),
         (assign, ":banner_troop", "trp_player"),
       (else_try), #can't find party, this can be a town guard
         (neq, ":troop_no", "trp_player"),
         (is_between, "$g_encountered_party", walled_centers_begin, walled_centers_end),
         (party_get_slot, ":town_lord", "$g_encountered_party", slot_town_lord),
         (ge, ":town_lord", 0),
         (assign, ":banner_troop", ":town_lord"),
       (try_end),

       # (str_store_troop_name, s0, ":troop_no"),
       # (display_message, s0),
       #(cur_agent_set_banner_tableau_material, ":tableau_no", ":troop_no"),
       (cur_agent_set_banner_tableau_material, ":tableau_no", ":banner_troop"),

     ]),

##  #script_shield_item_set_banner
  # Input: none
  # Output: none
  ("place_player_banner_near_inventory",
    [
    	#normal_banner_begin
    	(troop_get_slot, ":troop_banner_object", "trp_player", slot_troop_banner_scene_prop),
    	#custom_banner_begin
    	(troop_get_slot, ":flag_spr", "trp_player", slot_troop_custom_banner_flag_type),

     (try_begin),
       (assign, ":flag_object", -1),
       (try_begin),
    	#normal_banner_begin
           (gt, ":troop_banner_object", 0),
           (scene_prop_get_instance, ":flag_object", ":troop_banner_object", 0),
    	#custom_banner_begin
       (else_try),
           (eq, ":troop_banner_object", -1),
           (ge, ":flag_spr", 0),
           (val_add, ":flag_spr", custom_banner_flag_scene_props_begin),
           (scene_prop_get_instance, ":flag_object", ":flag_spr", 0),
       (try_end),
       (try_begin),
         (ge, ":flag_object", 0),
         (get_player_agent_no, ":player_agent"),
         (agent_get_look_position, pos1, ":player_agent"),
         (position_move_y, pos1, -500),
         (position_rotate_z, pos1, 180),
         (position_set_z_to_ground_level, pos1),
         (position_move_z, pos1, 300),
         (prop_instance_set_position, ":flag_object", pos1),
       (try_end),
       (scene_prop_get_instance, ":pole_object", "spr_banner_pole", 0),
       (try_begin),
         (ge, ":pole_object", 0),
         (position_move_z, pos1, -320),
         (prop_instance_set_position, ":pole_object", pos1),
       (try_end),
     (else_try),
       (init_position, pos1),
       (position_move_z, pos1, -1000000),
       (scene_prop_get_instance, ":flag_object", banner_scene_props_begin, 0),
       (try_begin),
         (ge, ":flag_object", 0),
         (prop_instance_set_position, ":flag_object", pos1),
       (try_end),
       (scene_prop_get_instance, ":pole_object", "spr_banner_pole", 0),
       (try_begin),
         (ge, ":pole_object", 0),
         (prop_instance_set_position, ":pole_object", pos1),
       (try_end),
     (try_end),
     ]),

  # script_place_player_banner_near_inventory_bms
  # Input: none
  # Output: none
  ("place_player_banner_near_inventory_bms",
    [
    	    	#normal_banner_begin
    	(troop_get_slot, ":troop_banner_object", "trp_player", slot_troop_banner_scene_prop),
    	    	#custom_banner_begin
      (troop_get_slot, ":flag_spr", "trp_player", slot_troop_custom_banner_flag_type),
     (try_begin),
       (try_begin),
    	    	#normal_banner_begin
           (gt, ":troop_banner_object", 0),
           (replace_scene_props, banner_scene_props_begin, ":troop_banner_object"),
       (else_try),
    	    	#custom_banner_begin
           (eq, ":troop_banner_object", -1),
           (ge, ":flag_spr", 0),
           (val_add, ":flag_spr", custom_banner_flag_scene_props_begin),
           (replace_scene_props, banner_scene_props_begin, ":flag_spr"),
       (try_end),
     (try_end),
     ]),

  # script_stay_captive_for_hours
  # Input: arg1 = troop_no, arg2 = center_pos_x, arg3 = center_pos_y, arg4 = width, arg5 = height, arg6 = stretch_width, arg7 = stretch_height, arg8 = default_scale, arg9 = max_charge_scale, arg10 = drawn_item_type
  # drawn_item_type is 0 for banners, 1 for shields, 2 for heater shield, 3 for armor
  # arguments will be used as fixed point values
  # Output: none
  ("draw_banner_to_region",
    [
      (store_script_param, ":troop_no", 1),
      (store_script_param, ":center_pos_x", 2),
      (store_script_param, ":center_pos_y", 3),
      (store_script_param, ":width", 4),
      (store_script_param, ":height", 5),
      (store_script_param, ":stretch_width", 6),
      (store_script_param, ":stretch_height", 7),
      (store_script_param, ":default_scale", 8),
      (store_script_param, ":max_charge_scale", 9),
      (store_script_param, ":drawn_item_type", 10),

      (troop_get_slot, ":bg_type", ":troop_no", slot_troop_custom_banner_bg_type),
      (val_add, ":bg_type", custom_banner_backgrounds_begin),
      (troop_get_slot, ":bg_color_1", ":troop_no", slot_troop_custom_banner_bg_color_1),
      (troop_get_slot, ":bg_color_2", ":troop_no", slot_troop_custom_banner_bg_color_2),
      (troop_get_slot, ":num_charges", ":troop_no", slot_troop_custom_banner_num_charges),
      (troop_get_slot, ":positioning", ":troop_no", slot_troop_custom_banner_positioning),
      (call_script, "script_get_troop_custom_banner_num_positionings", ":troop_no"),
      (assign, ":num_positionings", reg0),
      (val_mod, ":positioning", ":num_positionings"),

      (init_position, pos2),
      (position_set_x, pos2, ":width"),
      (position_set_y, pos2, ":height"),
      (assign, ":default_value", 1),
      (convert_to_fixed_point, ":default_value"),
      (position_set_z, pos2, ":default_value"),

      (init_position, pos1),
      (position_set_x, pos1, ":center_pos_x"),
      (position_set_y, pos1, ":center_pos_y"),
      (position_move_z, pos1, -20),

      (init_position, pos3),
      (position_set_x, pos3, ":default_scale"),
      (position_set_y, pos3, ":default_scale"),
      (position_set_z, pos3, ":default_value"),

      (try_begin),
        (this_or_next|eq, ":bg_type", "mesh_custom_banner_bg"),
        (this_or_next|eq, ":bg_type", "mesh_custom_banner_fg01"),
        (this_or_next|eq, ":bg_type", "mesh_custom_banner_fg02"),
        (this_or_next|eq, ":bg_type", "mesh_custom_banner_fg03"),
        (this_or_next|eq, ":bg_type", "mesh_custom_banner_fg08"),
        (this_or_next|eq, ":bg_type", "mesh_custom_banner_fg09"),
        (this_or_next|eq, ":bg_type", "mesh_custom_banner_fg10"),
        (this_or_next|eq, ":bg_type", "mesh_custom_banner_fg11"),
        (this_or_next|eq, ":bg_type", "mesh_custom_banner_fg12"),
        (this_or_next|eq, ":bg_type", "mesh_custom_banner_fg13"),
        (this_or_next|eq, ":bg_type", "mesh_custom_banner_fg16"),
        (eq, ":bg_type", "mesh_custom_banner_fg17"),
        (cur_tableau_add_mesh_with_scale_and_vertex_color, ":bg_type", pos1, pos2, 0, ":bg_color_1"),
      (else_try),
        (cur_tableau_add_mesh_with_scale_and_vertex_color, ":bg_type", pos1, pos3, 0, ":bg_color_1"),
      (try_end),
      (position_move_z, pos1, -20),
      (position_move_x, pos2, ":width"),
      (position_move_y, pos2, ":height"),
      (cur_tableau_add_mesh_with_scale_and_vertex_color, "mesh_custom_banner_bg", pos1, pos2, 0, ":bg_color_2"),

      (assign, ":charge_stretch", ":stretch_width"),
      (val_min, ":charge_stretch", ":stretch_height"),
      (val_min, ":charge_stretch", ":max_charge_scale"),
      (call_script, "script_get_custom_banner_charge_type_position_scale_color", "trp_player", ":positioning"),

      (try_begin),
        (this_or_next|eq, ":drawn_item_type", 2), #heater shield
        (eq, ":drawn_item_type", 3), #armor
        (assign, ":change_center_pos", 0),
        (try_begin),
          (eq, ":num_charges", 1),
          (assign, ":change_center_pos", 1),
        (else_try),
          (eq, ":num_charges", 2),
          (eq, ":positioning", 1),
          (assign, ":change_center_pos", 1),
        (else_try),
          (eq, ":num_charges", 3),
          (eq, ":positioning", 1),
          (assign, ":change_center_pos", 1),
        (try_end),
        (try_begin),
          (eq, ":change_center_pos", 1),
          (val_add, ":center_pos_y", 30),
        (try_end),
      (try_end),

      (try_begin),
        (ge, ":num_charges", 1),
        (val_mul, reg1, ":charge_stretch"),
        (val_div, reg1, 10000),
        (position_get_x, ":x", pos0),
        (position_get_y, ":y", pos0),
        (val_mul, ":x", ":stretch_width"),
        (val_mul, ":y", ":stretch_height"),
        (val_div, ":x", 10000),
        (val_div, ":y", 10000),
        (val_add, ":x", ":center_pos_x"),
        (val_add, ":y", ":center_pos_y"),
        (position_set_x, pos0, ":x"),
        (position_set_y, pos0, ":y"),
        (assign, ":scale_value", reg1),
        (convert_to_fixed_point, ":scale_value"),
        (store_mul, ":scale_value_inverse", ":scale_value", -1),
        (init_position, pos4),
        (position_set_x, pos4, ":scale_value"),
        (position_set_y, pos4, ":scale_value"),
        (position_set_z, pos4, ":scale_value"),
        (store_div, ":orientation", reg0, 256), #orientation flags
        (try_begin),
          (this_or_next|eq, ":orientation", 1),
          (eq, ":orientation", 3),
          (position_set_x, pos4, ":scale_value_inverse"),
        (try_end),
        (try_begin),
          (this_or_next|eq, ":orientation", 2),
          (eq, ":orientation", 3),
          (position_set_y, pos4, ":scale_value_inverse"),
        (try_end),
        (val_mod, reg0, 256), #remove orientation flags
        (cur_tableau_add_mesh_with_scale_and_vertex_color, reg0, pos0, pos4, 0, reg2),
      (try_end),
      (try_begin),
        (ge, ":num_charges", 2),
        (val_mul, reg4, ":charge_stretch"),
        (val_div, reg4, 10000),
        (position_get_x, ":x", pos1),
        (position_get_y, ":y", pos1),
        (val_mul, ":x", ":stretch_width"),
        (val_mul, ":y", ":stretch_height"),
        (val_div, ":x", 10000),
        (val_div, ":y", 10000),
        (val_add, ":x", ":center_pos_x"),
        (val_add, ":y", ":center_pos_y"),
        (position_set_x, pos1, ":x"),
        (position_set_y, pos1, ":y"),

        (assign, ":scale_value", reg4),
        (convert_to_fixed_point, ":scale_value"),
        (store_mul, ":scale_value_inverse", ":scale_value", -1),
        (init_position, pos4),
        (position_set_x, pos4, ":scale_value"),
        (position_set_y, pos4, ":scale_value"),
        (position_set_z, pos4, ":scale_value"),
        (store_div, ":orientation", reg3, 256), #orientation flags
        (try_begin),
          (this_or_next|eq, ":orientation", 1),
          (eq, ":orientation", 3),
          (position_set_x, pos4, ":scale_value_inverse"),
        (try_end),
        (try_begin),
          (this_or_next|eq, ":orientation", 2),
          (eq, ":orientation", 3),
          (position_set_y, pos4, ":scale_value_inverse"),
        (try_end),
        (val_mod, reg3, 256), #remove orientation flags

        (cur_tableau_add_mesh_with_scale_and_vertex_color, reg3, pos1, pos4, 0, reg5),
      (try_end),
      (try_begin),
        (ge, ":num_charges", 3),
        (val_mul, reg7, ":charge_stretch"),
        (val_div, reg7, 10000),
        (position_get_x, ":x", pos2),
        (position_get_y, ":y", pos2),
        (val_mul, ":x", ":stretch_width"),
        (val_mul, ":y", ":stretch_height"),
        (val_div, ":x", 10000),
        (val_div, ":y", 10000),
        (val_add, ":x", ":center_pos_x"),
        (val_add, ":y", ":center_pos_y"),
        (position_set_x, pos2, ":x"),
        (position_set_y, pos2, ":y"),

        (assign, ":scale_value", reg7),
        (convert_to_fixed_point, ":scale_value"),
        (store_mul, ":scale_value_inverse", ":scale_value", -1),
        (init_position, pos4),
        (position_set_x, pos4, ":scale_value"),
        (position_set_y, pos4, ":scale_value"),
        (position_set_z, pos4, ":scale_value"),
        (store_div, ":orientation", reg6, 256), #orientation flags
        (try_begin),
          (this_or_next|eq, ":orientation", 1),
          (eq, ":orientation", 3),
          (position_set_x, pos4, ":scale_value_inverse"),
        (try_end),
        (try_begin),
          (this_or_next|eq, ":orientation", 2),
          (eq, ":orientation", 3),
          (position_set_y, pos4, ":scale_value_inverse"),
        (try_end),
        (val_mod, reg6, 256), #remove orientation flags

        (cur_tableau_add_mesh_with_scale_and_vertex_color, reg6, pos2, pos4, 0, reg8),
      (try_end),
      (try_begin),
        (ge, ":num_charges", 4),
        (val_mul, reg10, ":charge_stretch"),
        (val_div, reg10, 10000),
        (position_get_x, ":x", pos3),
        (position_get_y, ":y", pos3),
        (val_mul, ":x", ":stretch_width"),
        (val_mul, ":y", ":stretch_height"),
        (val_div, ":x", 10000),
        (val_div, ":y", 10000),
        (val_add, ":x", ":center_pos_x"),
        (val_add, ":y", ":center_pos_y"),
        (position_set_x, pos3, ":x"),
        (position_set_y, pos3, ":y"),

        (assign, ":scale_value", reg10),
        (convert_to_fixed_point, ":scale_value"),
        (store_mul, ":scale_value_inverse", ":scale_value", -1),
        (init_position, pos4),
        (position_set_x, pos4, ":scale_value"),
        (position_set_y, pos4, ":scale_value"),
        (position_set_z, pos4, ":scale_value"),
        (store_div, ":orientation", reg9, 256), #orientation flags
        (try_begin),
          (this_or_next|eq, ":orientation", 1),
          (eq, ":orientation", 3),
          (position_set_x, pos4, ":scale_value_inverse"),
        (try_end),
        (try_begin),
          (this_or_next|eq, ":orientation", 2),
          (eq, ":orientation", 3),
          (position_set_y, pos4, ":scale_value_inverse"),
        (try_end),
        (val_mod, reg9, 256), #remove orientation flags

        (cur_tableau_add_mesh_with_scale_and_vertex_color, reg9, pos3, pos4, 0, reg11),
      (try_end),
     ]),

  # script_get_troop_custom_banner_num_positionings
  # Input: arg1 = troop_no
  # Output: reg0 = num_positionings
  ("get_troop_custom_banner_num_positionings",
    [
      (store_script_param, ":troop_no", 1),
      (troop_get_slot, ":num_charges", ":troop_no", slot_troop_custom_banner_num_charges),
      (try_begin),
        (eq, ":num_charges", 1),
        (assign, ":num_positionings", 2),
      (else_try),
        (eq, ":num_charges", 2),
        (assign, ":num_positionings", 4),
      (else_try),
        (eq, ":num_charges", 3),
        (assign, ":num_positionings", 6),
      (else_try),
        (assign, ":num_positionings", 2),
      (try_end),
      (assign, reg0, ":num_positionings"),
     ]),

  # script_get_custom_banner_charge_type_position_scale_color
  # Input: arg1 = troop_no, arg2 = positioning_index
  # Output: reg0 = type_1
  #         reg1 = scale_1
  #         reg2 = color_1
  #         reg3 = type_2
  #         reg4 = scale_2
  #         reg5 = color_2
  #         reg6 = type_3
  #         reg7 = scale_3
  #         reg8 = color_3
  #         reg9 = type_4
  #         reg10 = scale_4
  #         reg11 = color_4
  ("get_custom_banner_charge_type_position_scale_color",
    [
      (store_script_param, ":troop_no", 1),
      (store_script_param, ":positioning", 2),
      (troop_get_slot, ":num_charges", ":troop_no", slot_troop_custom_banner_num_charges),
      (init_position, pos0),
      (init_position, pos1),
      (init_position, pos2),
      (init_position, pos3),

      (troop_get_slot, reg0, ":troop_no", slot_troop_custom_banner_charge_type_1),
      (val_add, reg0, custom_banner_charges_begin),
      (troop_get_slot, reg2, ":troop_no", slot_troop_custom_banner_charge_color_1),
      (troop_get_slot, reg3, ":troop_no", slot_troop_custom_banner_charge_type_2),
      (val_add, reg3, custom_banner_charges_begin),
      (troop_get_slot, reg5, ":troop_no", slot_troop_custom_banner_charge_color_2),
      (troop_get_slot, reg6, ":troop_no", slot_troop_custom_banner_charge_type_3),
      (val_add, reg6, custom_banner_charges_begin),
      (troop_get_slot, reg8, ":troop_no", slot_troop_custom_banner_charge_color_3),
      (troop_get_slot, reg9, ":troop_no", slot_troop_custom_banner_charge_type_4),
      (val_add, reg9, custom_banner_charges_begin),
      (troop_get_slot, reg11, ":troop_no", slot_troop_custom_banner_charge_color_4),

      (try_begin),
        (eq, ":num_charges", 1),
        (try_begin),
          (eq, ":positioning", 0),
          (assign, reg1, 100),
        (else_try),
          (assign, reg1, 50),
        (try_end),
      (else_try),
        (eq, ":num_charges", 2),
        (try_begin),
          (eq, ":positioning", 0),
          (position_set_y, pos0, 25),
          (position_set_y, pos1, -25),
          (assign, reg1, 40),
          (assign, reg4, 40),
        (else_try),
          (eq, ":positioning", 1),
          (position_set_x, pos0, -25),
          (position_set_x, pos1, 25),
          (assign, reg1, 40),
          (assign, reg4, 40),
        (else_try),
          (eq, ":positioning", 2),
          (position_set_x, pos0, -25),
          (position_set_y, pos0, 25),
          (position_set_x, pos1, 25),
          (position_set_y, pos1, -25),
          (assign, reg1, 50),
          (assign, reg4, 50),
        (else_try),
          (position_set_x, pos0, -25),
          (position_set_y, pos0, -25),
          (position_set_x, pos1, 25),
          (position_set_y, pos1, 25),
          (assign, reg1, 50),
          (assign, reg4, 50),
        (try_end),
      (else_try),
        (eq, ":num_charges", 3),
        (try_begin),
          (eq, ":positioning", 0),
          (position_set_y, pos0, 33),
          (position_set_y, pos2, -33),
          (assign, reg1, 30),
          (assign, reg4, 30),
          (assign, reg7, 30),
        (else_try),
          (eq, ":positioning", 1),
          (position_set_x, pos0, -33),
          (position_set_x, pos2, 33),
          (assign, reg1, 30),
          (assign, reg4, 30),
          (assign, reg7, 30),
        (else_try),
          (eq, ":positioning", 2),
          (position_set_x, pos0, -30),
          (position_set_y, pos0, 30),
          (position_set_x, pos2, 30),
          (position_set_y, pos2, -30),
          (assign, reg1, 35),
          (assign, reg4, 35),
          (assign, reg7, 35),
        (else_try),
          (eq, ":positioning", 3),
          (position_set_x, pos0, -30),
          (position_set_y, pos0, -30),
          (position_set_x, pos2, 30),
          (position_set_y, pos2, 30),
          (assign, reg1, 35),
          (assign, reg4, 35),
          (assign, reg7, 35),
        (else_try),
          (eq, ":positioning", 4),
          (position_set_x, pos0, -25),
          (position_set_y, pos0, -25),
          (position_set_y, pos1, 25),
          (position_set_x, pos2, 25),
          (position_set_y, pos2, -25),
          (assign, reg1, 50),
          (assign, reg4, 50),
          (assign, reg7, 50),
        (else_try),
          (position_set_x, pos0, -25),
          (position_set_y, pos0, 25),
          (position_set_y, pos1, -25),
          (position_set_x, pos2, 25),
          (position_set_y, pos2, 25),
          (assign, reg1, 50),
          (assign, reg4, 50),
          (assign, reg7, 50),
        (try_end),
      (else_try),
        (try_begin),
          (eq, ":positioning", 0),
          (position_set_x, pos0, -25),
          (position_set_y, pos0, 25),
          (position_set_x, pos1, 25),
          (position_set_y, pos1, 25),
          (position_set_x, pos2, -25),
          (position_set_y, pos2, -25),
          (position_set_x, pos3, 25),
          (position_set_y, pos3, -25),
          (assign, reg1, 50),
          (assign, reg4, 50),
          (assign, reg7, 50),
          (assign, reg10, 50),
        (else_try),
          (position_set_y, pos0, 30),
          (position_set_x, pos1, -30),
          (position_set_x, pos2, 30),
          (position_set_y, pos3, -30),
          (assign, reg1, 35),
          (assign, reg4, 35),
          (assign, reg7, 35),
          (assign, reg10, 35),
        (try_end),
      (try_end),
     ]),

  # script_get_random_custom_banner
  # Input: arg1 = troop_no
  # Output: none
  ("get_random_custom_banner",
    [
      (store_script_param, ":troop_no", 1),
      (store_random_in_range, ":num_charges", 1, 5),
      (troop_set_slot, ":troop_no", slot_troop_custom_banner_num_charges, ":num_charges"),
      (store_random_in_range, ":random_color_index", 0, 42),
      (call_script, "script_get_custom_banner_color_from_index", ":random_color_index"),
      (assign, ":color_1", reg0),
      (troop_set_slot, ":troop_no", slot_troop_custom_banner_bg_color_1, ":color_1"),
      (assign, ":end_cond", 1),
      (try_for_range, ":unused", 0, ":end_cond"),
        (store_random_in_range, ":random_color_index", 0, 42),
        (call_script, "script_get_custom_banner_color_from_index", ":random_color_index"),
        (assign, ":color_2", reg0),
        (try_begin),
          (call_script, "script_cf_check_color_visibility", ":color_1", ":color_2"),
          (troop_set_slot, ":troop_no", slot_troop_custom_banner_bg_color_2, ":color_2"),
        (else_try),
          (val_add, ":end_cond", 1),
        (try_end),
      (try_end),
      (assign, ":end_cond", 4),
      (assign, ":cur_charge", 0),
      (try_for_range, ":unused", 0, ":end_cond"),
        (store_random_in_range, ":random_color_index", 0, 42),
        (call_script, "script_get_custom_banner_color_from_index", ":random_color_index"),
        (assign, ":charge_color", reg0),
        (try_begin),
          (call_script, "script_cf_check_color_visibility", ":charge_color", ":color_1"),
          (call_script, "script_cf_check_color_visibility", ":charge_color", ":color_2"),
          (store_add, ":cur_slot", ":cur_charge", slot_troop_custom_banner_charge_color_1),
          (troop_set_slot, ":troop_no", ":cur_slot", ":charge_color"),
          (store_random_in_range, ":random_charge", custom_banner_charges_begin, custom_banner_charges_end),
          (val_sub, ":random_charge", custom_banner_charges_begin),
          (store_add, ":cur_slot", ":cur_charge", slot_troop_custom_banner_charge_type_1),
          (troop_set_slot, ":troop_no", ":cur_slot", ":random_charge"),
          (val_add, ":cur_charge", 1),
        (else_try),
          (val_add, ":end_cond", 1),
        (try_end),
      (try_end),
      (store_random_in_range, ":random_bg", custom_banner_backgrounds_begin, custom_banner_backgrounds_end),
      (val_sub, ":random_bg", custom_banner_backgrounds_begin),
      (troop_set_slot, ":troop_no", slot_troop_custom_banner_bg_type, ":random_bg"),
      (store_random_in_range, ":random_flag", custom_banner_flag_types_begin, custom_banner_flag_types_end),
      (val_sub, ":random_flag", custom_banner_flag_types_begin),
      (troop_set_slot, ":troop_no", slot_troop_custom_banner_flag_type, ":random_flag"),
      (store_random_in_range, ":random_positioning", 0, 4),
      (troop_set_slot, ":troop_no", slot_troop_custom_banner_positioning, ":random_positioning"),
     ]),

  # script_get_custom_banner_color_from_index
  # Input: arg1 = color_index
  # Output: reg0 = color
  ("get_custom_banner_color_from_index",
    [
      (store_script_param, ":color_index", 1),

      (assign, ":cur_color", 0xFF000000),
      (assign, ":red", 0x00),
      (assign, ":green", 0x00),
      (assign, ":blue", 0x00),
      (store_mod, ":mod_i_color", ":color_index", 7),
      (try_begin),
        (eq, ":mod_i_color", 0),
        (assign, ":blue", 0xFF),
      (else_try),
        (eq, ":mod_i_color", 1),
        (assign, ":red", 0xEE),
      (else_try),
        (eq, ":mod_i_color", 2),
        (assign, ":red", 0xFB),
        (assign, ":green", 0xAC),
      (else_try),
        (eq, ":mod_i_color", 3),
        (assign, ":red", 0x5F),
        (assign, ":blue", 0xFF),
      (else_try),
        (eq, ":mod_i_color", 4),
        (assign, ":red", 0x05),
        (assign, ":green", 0x44),
      (else_try),
        (eq, ":mod_i_color", 5),
        (assign, ":red", 0xEE),
        (assign, ":green", 0xEE),
        (assign, ":blue", 0xEE),
      (else_try),
        (assign, ":red", 0x22),
        (assign, ":green", 0x22),
        (assign, ":blue", 0x22),
      (try_end),
      (store_div, ":cur_tone", ":color_index", 7),
      (store_sub, ":cur_tone", 8, ":cur_tone"),
      (val_mul, ":red", ":cur_tone"),
      (val_div, ":red", 8),
      (val_mul, ":green", ":cur_tone"),
      (val_div, ":green", 8),
      (val_mul, ":blue", ":cur_tone"),
      (val_div, ":blue", 8),
      (val_mul, ":green", 0x100),
      (val_mul, ":red", 0x10000),
      (val_add, ":cur_color", ":blue"),
      (val_add, ":cur_color", ":green"),
      (val_add, ":cur_color", ":red"),
      (assign, reg0, ":cur_color"),
     ]),

  # script_cf_check_color_visibility
]
