# -*- coding: cp1254 -*-
# package initializer for taxes_training menus

from game_menus.taxes_training.mnu_collect_taxes import collect_taxes_menu
from game_menus.taxes_training.mnu_collect_taxes_complete import collect_taxes_complete_menu
from game_menus.taxes_training.mnu_collect_taxes_rebels_killed import collect_taxes_rebels_killed_menu
from game_menus.taxes_training.mnu_collect_taxes_failed import collect_taxes_failed_menu
from game_menus.taxes_training.mnu_collect_taxes_revolt_warning import collect_taxes_revolt_warning_menu
from game_menus.taxes_training.mnu_collect_taxes_revolt import collect_taxes_revolt_menu
from game_menus.taxes_training.mnu_train_peasants_against_bandits import train_peasants_against_bandits_menu
from game_menus.taxes_training.mnu_train_peasants_against_bandits_ready import train_peasants_against_bandits_ready_menu
from game_menus.taxes_training.mnu_train_peasants_against_bandits_training_result import train_peasants_against_bandits_training_result_menu
from game_menus.taxes_training.mnu_train_peasants_against_bandits_attack import train_peasants_against_bandits_attack_menu
from game_menus.taxes_training.mnu_train_peasants_against_bandits_attack_result import train_peasants_against_bandits_attack_result_menu
from game_menus.taxes_training.mnu_train_peasants_against_bandits_success import train_peasants_against_bandits_success_menu

taxes_training_menus = []
taxes_training_menus.extend(collect_taxes_menu)
taxes_training_menus.extend(collect_taxes_complete_menu)
taxes_training_menus.extend(collect_taxes_rebels_killed_menu)
taxes_training_menus.extend(collect_taxes_failed_menu)
taxes_training_menus.extend(collect_taxes_revolt_warning_menu)
taxes_training_menus.extend(collect_taxes_revolt_menu)
taxes_training_menus.extend(train_peasants_against_bandits_menu)
taxes_training_menus.extend(train_peasants_against_bandits_ready_menu)
taxes_training_menus.extend(train_peasants_against_bandits_training_result_menu)
taxes_training_menus.extend(train_peasants_against_bandits_attack_menu)
taxes_training_menus.extend(train_peasants_against_bandits_attack_result_menu)
taxes_training_menus.extend(train_peasants_against_bandits_success_menu)

