# -*- coding: cp1254 -*-
# package initializer for kingdom_management menus

from game_menus.kingdom_management.mnu_faction_orders import faction_orders_menu
from game_menus.kingdom_management.mnu_marshall_selection_candidate_ask import marshall_selection_candidate_ask_menu
from game_menus.kingdom_management.mnu_kingdom_army_quest_join_siege_order import kingdom_army_quest_join_siege_order_menu
from game_menus.kingdom_management.mnu_kingdom_army_follow_failed import kingdom_army_follow_failed_menu
from game_menus.kingdom_management.mnu_invite_player_to_faction_without_center import invite_player_to_faction_without_center_menu
from game_menus.kingdom_management.mnu_invite_player_to_faction import invite_player_to_faction_menu
from game_menus.kingdom_management.mnu_invite_player_to_faction_accepted import invite_player_to_faction_accepted_menu
from game_menus.kingdom_management.mnu_question_peace_offer import question_peace_offer_menu
from game_menus.kingdom_management.mnu_minister_confirm import minister_confirm_menu
from game_menus.kingdom_management.mnu_auto_return_to_map import auto_return_to_map_menu
from game_menus.kingdom_management.mnu_bandit_lair import bandit_lair_menu

kingdom_management_menus = []
kingdom_management_menus.extend(faction_orders_menu)
kingdom_management_menus.extend(marshall_selection_candidate_ask_menu)
kingdom_management_menus.extend(kingdom_army_quest_join_siege_order_menu)
kingdom_management_menus.extend(kingdom_army_follow_failed_menu)
kingdom_management_menus.extend(invite_player_to_faction_without_center_menu)
kingdom_management_menus.extend(invite_player_to_faction_menu)
kingdom_management_menus.extend(invite_player_to_faction_accepted_menu)
kingdom_management_menus.extend(question_peace_offer_menu)
kingdom_management_menus.extend(minister_confirm_menu)
kingdom_management_menus.extend(auto_return_to_map_menu)
kingdom_management_menus.extend(bandit_lair_menu)

