# -*- coding: cp1254 -*-
from header_common import *
from header_operations import *
from module_constants import *
from module_constants import *
from header_parties import *
from header_skills import *
from header_mission_templates import *
from header_items import *
from header_triggers import *
from header_terrain_types import *
from header_music import *
from header_map_icons import *
from ID_animations import *
from ID_strings import str_key_0
from module_factions import dplmc_factions_begin, dplmc_factions_end, dplmc_non_generic_factions_begin

cf_troop_debug_range_scripts = [
("cf_troop_debug_range",
    [
        (store_script_param, ":troop_no", 1),
        (store_script_param, ":sreg", 2),
        (store_script_param, ":direction", 3),
        (assign, ":result", ":troop_no"),
        (try_begin),
          (is_between, ":troop_no", heroes_begin, heroes_end),
          (str_store_string, ":sreg", "@hero"),
          (try_begin),
            (eq, ":direction", -1),
            (assign, ":result", heroes_begin),
          (else_try),
            (eq, ":direction", 1),
            (store_sub, ":result", heroes_end, ":direction"),
          (try_end),
          (try_begin),
            (is_between, ":troop_no", companions_begin, companions_end),
            (str_store_string, ":sreg", "@companion"),
            (try_begin),
              (eq, ":direction", -1),
              (assign, ":result", companions_begin),
            (else_try),
              (eq, ":direction", 1),
              (store_sub, ":result", companions_end, ":direction"),
            (try_end),
          (else_try),
            (is_between, ":troop_no", kings_begin, kings_end),
            (str_store_string, ":sreg", "@king"),
            (try_begin),
              (eq, ":direction", -1),
              (assign, ":result", kings_begin),
            (else_try),
              (eq, ":direction", 1),
              (store_sub, ":result", kings_end, ":direction"),
            (try_end),
          (else_try),
            (is_between, ":troop_no", lords_begin, lords_end),
            (str_store_string, ":sreg", "@lord"),
            (try_begin),
              (eq, ":direction", -1),
              (assign, ":result", lords_begin),
            (else_try),
              (eq, ":direction", 1),
              (store_sub, ":result", lords_end, ":direction"),
            (try_end),
          (else_try),
            (is_between, ":troop_no", pretenders_begin, pretenders_end),
            (str_store_string, ":sreg", "@pretender"),
            (try_begin),
              (eq, ":direction", -1),
              (assign, ":result", pretenders_begin),
            (else_try),
              (eq, ":direction", 1),
              (store_sub, ":result", pretenders_end, ":direction"),
            (try_end),
          (else_try),
            (is_between, ":troop_no", kingdom_ladies_begin, kingdom_ladies_end),
            (str_store_string, ":sreg", "@lady"),
            (try_begin),
              (eq, ":direction", -1),
              (assign, ":result", kingdom_ladies_begin),
            (else_try),
              (eq, ":direction", 1),
              (store_sub, ":result", kingdom_ladies_end, ":direction"),
            (try_end),
          (try_end),
        (else_try),
          (is_between, ":troop_no", bandits_begin, bandits_end),
          (str_store_string, ":sreg", "@bandit"),
          (try_begin),
            (eq, ":direction", -1),
            (assign, ":result", bandits_begin),
          (else_try),
            (eq, ":direction", 1),
            (store_sub, ":result", bandits_end, ":direction"),
          (try_end),
        (else_try),
          (is_between, ":troop_no", tavern_minstrels_begin, tavern_minstrels_end),
          (str_store_string, ":sreg", "@minstrel"),
          (try_begin),
            (eq, ":direction", -1),
            (assign, ":result", tavern_minstrels_begin),
          (else_try),
            (eq, ":direction", 1),
            (store_sub, ":result", tavern_minstrels_end, ":direction"),
          (try_end),
        (else_try),
          (is_between, ":troop_no", tavern_booksellers_begin, tavern_booksellers_end),
          (str_store_string, ":sreg", "@bookseller"),
          (try_begin),
            (eq, ":direction", -1),
            (assign, ":result", tavern_booksellers_begin),
          (else_try),
            (eq, ":direction", 1),
            (store_sub, ":result", tavern_booksellers_end, ":direction"),
          (try_end),
        (else_try),
          (is_between, ":troop_no", tavern_travelers_begin, tavern_travelers_end),
          (str_store_string, ":sreg", "@traveler"),
          (try_begin),
            (eq, ":direction", -1),
            (assign, ":result", tavern_travelers_begin),
          (else_try),
            (eq, ":direction", 1),
            (store_sub, ":result", tavern_travelers_end, ":direction"),
          (try_end),
        (else_try),
          (is_between, ":troop_no", ransom_brokers_begin, ransom_brokers_end),
          (str_store_string, ":sreg", "@ransom broker"),
          (try_begin),
            (eq, ":direction", -1),
            (assign, ":result", ransom_brokers_begin),
          (else_try),
            (eq, ":direction", 1),
            (store_sub, ":result", ransom_brokers_end, ":direction"),
          (try_end),
        (else_try),
          (is_between, ":troop_no", mercenary_troops_begin, mercenary_troops_end),
          (str_store_string, ":sreg", "@mercenary"),
          (try_begin),
            (eq, ":direction", -1),
            (assign, ":result", mercenary_troops_begin),
          (else_try),
            (eq, ":direction", 1),
            (store_sub, ":result", mercenary_troops_end, ":direction"),
          (try_end),
        (else_try),
          (is_between, ":troop_no", multiplayer_troops_begin, multiplayer_troops_end),
          (str_store_string, ":sreg", "@multiplayer troop"),
          (try_begin),
            (eq, ":direction", -1),
            (assign, ":result", multiplayer_troops_begin),
          (else_try),
            (eq, ":direction", 1),
            (store_sub, ":result", multiplayer_troops_end, ":direction"),
          (try_end),
        (else_try),
          (is_between, ":troop_no", quick_battle_troops_begin, quick_battle_troops_end),
          (str_store_string, ":sreg", "@quick battler"),
          (try_begin),
            (eq, ":direction", -1),
            (assign, ":result", quick_battle_troops_begin),
          (else_try),
            (eq, ":direction", 1),
            (store_sub, ":result", quick_battle_troops_end, ":direction"),
          (try_end),
        (else_try),
          (is_between, ":troop_no", training_ground_trainers_begin, training_ground_trainers_end),
          (str_store_string, ":sreg", "@trainer"),
          (try_begin),
            (eq, ":direction", -1),
            (assign, ":result", training_ground_trainers_begin),
          (else_try),
            (eq, ":direction", 1),
            (store_sub, ":result", training_ground_trainers_end, ":direction"),
          (try_end),
        (else_try),
          (is_between, ":troop_no", arena_masters_begin, arena_masters_end),
          (str_store_string, ":sreg", "@arena master"),
          (try_begin),
            (eq, ":direction", -1),
            (assign, ":result", arena_masters_begin),
          (else_try),
            (eq, ":direction", 1),
            (store_sub, ":result", arena_masters_end, ":direction"),
          (try_end),
        (else_try),
          (is_between, ":troop_no", walkers_begin, walkers_end),
          (str_store_string, ":sreg", "@walker"),
          (try_begin),
            (eq, ":direction", -1),
            (assign, ":result", walkers_begin),
          (else_try),
            (eq, ":direction", 1),
            (store_sub, ":result", walkers_end, ":direction"),
          (try_end),
        (else_try),
          (is_between, ":troop_no", merchants_begin, merchants_end),
          (str_store_string, ":sreg", "@merchant"),
          (try_begin),
            (eq, ":direction", -1),
            (assign, ":result", merchants_begin),
          (else_try),
            (eq, ":direction", 1),
            (store_sub, ":result", merchants_end, ":direction"),
          (try_end),
          (try_begin),
            (is_between, ":troop_no", armor_merchants_begin, armor_merchants_end),
            (str_store_string, ":sreg", "@armor merchant"),
            (try_begin),
              (eq, ":direction", -1),
              (assign, ":result", armor_merchants_begin),
            (else_try),
              (eq, ":direction", 1),
              (store_sub, ":result", armor_merchants_end, ":direction"),
            (try_end),
          (else_try),
            (is_between, ":troop_no", weapon_merchants_begin, weapon_merchants_end),
            (str_store_string, ":sreg", "@weapon merchant"),
            (try_begin),
              (eq, ":direction", -1),
              (assign, ":result", weapon_merchants_begin),
            (else_try),
              (eq, ":direction", 1),
              (store_sub, ":result", weapon_merchants_end, ":direction"),
            (try_end),
          (else_try),
            (is_between, ":troop_no", tavernkeepers_begin, tavernkeepers_end),
            (str_store_string, ":sreg", "@tavernkeeper"),
            (try_begin),
              (eq, ":direction", -1),
              (assign, ":result", tavernkeepers_begin),
            (else_try),
              (eq, ":direction", 1),
              (store_sub, ":result", tavernkeepers_end, ":direction"),
            (try_end),
          (else_try),
            (is_between, ":troop_no", goods_merchants_begin, goods_merchants_end),
            (str_store_string, ":sreg", "@goods merchant"),
            (try_begin),
              (eq, ":direction", -1),
              (assign, ":result", goods_merchants_begin),
            (else_try),
              (eq, ":direction", 1),
              (store_sub, ":result", goods_merchants_end, ":direction"),
            (try_end),
          (else_try),
            (is_between, ":troop_no", horse_merchants_begin, horse_merchants_end),
            (str_store_string, ":sreg", "@horse merchant"),
            (try_begin),
              (eq, ":direction", -1),
              (assign, ":result", horse_merchants_begin),
            (else_try),
              (eq, ":direction", 1),
              (store_sub, ":result", horse_merchants_end, ":direction"),
            (try_end),
          (else_try),
            (is_between, ":troop_no", mayors_begin, mayors_end),
            (str_store_string, ":sreg", "@guildmaster"),
            (try_begin),
              (eq, ":direction", -1),
              (assign, ":result", mayors_begin),
            (else_try),
              (eq, ":direction", 1),
              (store_sub, ":result", mayors_end, ":direction"),
            (try_end),
          (else_try),
            (is_between, ":troop_no", village_elders_begin, village_elders_end),
            (str_store_string, ":sreg", "@village elder"),
            (try_begin),
              (eq, ":direction", -1),
              (assign, ":result", village_elders_begin),
            (else_try),
              (eq, ":direction", 1),
              (store_sub, ":result", village_elders_end, ":direction"),
            (try_end),
          (try_end),
        (else_try),
          (is_between, ":troop_no", startup_merchants_begin, startup_merchants_end),
          (str_store_string, ":sreg", "@startup merchant"),
          (try_begin),
            (eq, ":direction", -1),
            (assign, ":result", startup_merchants_begin),
          (else_try),
            (eq, ":direction", 1),
            (store_sub, ":result", startup_merchants_end, ":direction"),
          (try_end),
        (else_try),
          (is_between, ":troop_no", tournament_champions_begin, tournament_champions_end),
          (str_store_string, ":sreg", "@tournament fighter"),
          (try_begin),
            (eq, ":direction", -1),
            (assign, ":result", tournament_champions_begin),
          (else_try),
            (eq, ":direction", 1),
            (store_sub, ":result", tournament_champions_end, ":direction"),
          (try_end),
        (else_try),
          (is_between, ":troop_no", dplmc_employees_begin, dplmc_employees_end),
          (str_store_string, ":sreg", "@court member"),
          (try_begin),
            (eq, ":direction", -1),
            (assign, ":result", dplmc_employees_begin),
          (else_try),
            (eq, ":direction", 1),
            (store_sub, ":result", dplmc_employees_end, ":direction"),
          (try_end),
        (else_try),
          (is_between, ":troop_no", fighters_begin, fighters_end),
          (str_store_string, ":sreg", "@fighter"),
          (try_begin),
            (eq, ":direction", -1),
            (assign, ":result", fighters_begin),
          (else_try),
            (eq, ":direction", 1),
            (store_sub, ":result", fighters_end, ":direction"),
          (try_end),
        (else_try), #sarranids
          (is_between, ":troop_no", "trp_sarranid_recruit", "trp_looter"),
          (str_store_string, ":sreg", "str_kingdom_6_adjective"),
          (try_begin),
            (eq, ":direction", -1),
            (assign, ":result", "trp_sarranid_recruit"),
          (else_try),
            (eq, ":direction", 1),
            (store_sub, ":result", "trp_looter", ":direction"),
          (try_end),
        (else_try), #rhodoks
          (is_between, ":troop_no", "trp_rhodok_tribesman", "trp_sarranid_recruit"),
          (str_store_string, ":sreg", "str_kingdom_5_adjective"),
          (try_begin),
            (eq, ":direction", -1),
            (assign, ":result", "trp_rhodok_tribesman"),
          (else_try),
            (eq, ":direction", 1),
            (store_sub, ":result", "trp_sarranid_recruit", ":direction"),
          (try_end),
        (else_try), #nords
          (is_between, ":troop_no", "trp_nord_recruit", "trp_rhodok_tribesman"),
          (str_store_string, ":sreg", "str_kingdom_4_adjective"),
          (try_begin),
            (eq, ":direction", -1),
            (assign, ":result", "trp_nord_recruit"),
          (else_try),
            (eq, ":direction", 1),
            (store_sub, ":result", "trp_rhodok_tribesman", ":direction"),
          (try_end),
        (else_try), #khergits
          (is_between, ":troop_no", "trp_khergit_tribesman", "trp_nord_recruit"),
          (str_store_string, ":sreg", "str_kingdom_3_adjective"),
          (try_begin),
            (eq, ":direction", -1),
            (assign, ":result", "trp_khergit_tribesman"),
          (else_try),
            (eq, ":direction", 1),
            (store_sub, ":result", "trp_nord_recruit", ":direction"),
          (try_end),
        (else_try), #vaegirs
          (is_between, ":troop_no", "trp_vaegir_recruit", "trp_khergit_tribesman"),
          (str_store_string, ":sreg", "str_kingdom_2_adjective"),
          (try_begin),
            (eq, ":direction", -1),
            (assign, ":result", "trp_vaegir_recruit"),
          (else_try),
            (eq, ":direction", 1),
            (store_sub, ":result", "trp_khergit_tribesman", ":direction"),
          (try_end),
        (else_try), #swadians
          (is_between, ":troop_no", "trp_swadian_recruit", "trp_vaegir_recruit"),
          (str_store_string, ":sreg", "str_kingdom_1_adjective"),
          (try_begin),
            (eq, ":direction", -1),
            (assign, ":result", "trp_swadian_recruit"),
          (else_try),
            (eq, ":direction", 1),
            (store_sub, ":result", "trp_vaegir_recruit", ":direction"),
          (try_end),
        (try_end),
        (this_or_next|eq, ":direction", 0),
        (neq, ":result", ":troop_no"),
        (assign, reg0, ":result"),

    ])
]
