# -*- coding: cp1254 -*-
from header_common import *
from header_operations import *
from module_constants import *
from module_constants import *
from header_parties import *
from header_skills import *
from header_mission_templates import *
from header_items import *
from header_triggers import *
from header_terrain_types import *
from header_music import *
from header_map_icons import *
from ID_animations import *

exchange_prisoners_between_factions_scripts = [
# script_randomly_start_war_peace
# Input: arg1 = initializing_war_peace_cond (1 = true, 0 = false)
# Output: none
#  ("randomly_start_war_peace",
#    [
#      (store_script_param_1, ":initializing_war_peace_cond"),
#      (assign, ":total_resources", 0),
#      (assign, ":total_active_kingdoms", 0),
#      (try_for_range, ":cur_kingdom", kingdoms_begin, kingdoms_end),
#        (faction_slot_eq, ":cur_kingdom", slot_faction_state, sfs_active),
#        (val_add, ":total_active_kingdoms", 1),
#        (faction_get_slot, ":num_towns", ":cur_kingdom", slot_faction_num_towns),
#        (store_mul, ":kingdom_resources_value", ":num_towns", 2),
#        (faction_get_slot, ":num_castles", ":cur_kingdom", slot_faction_num_castles),
#        (val_add, ":kingdom_resources_value", ":num_castles"),
#        (val_mul, ":kingdom_resources_value", 10),
#        (val_max, ":kingdom_resources_value", 1),
#        (val_mul, ":kingdom_resources_value", 1000),
#        (faction_get_slot, ":num_armies", ":cur_kingdom", slot_faction_num_armies),
#        (val_max, ":num_armies", 1),
#        (val_div, ":kingdom_resources_value", ":num_armies"),
#        (val_add, ":total_resources", ":kingdom_resources_value"),
#      (try_end),
#      (val_max, ":total_active_kingdoms", 1),
#      (store_div, ":average_resources", ":total_resources", ":total_active_kingdoms"),
#      (try_for_range, ":cur_kingdom", kingdoms_begin, kingdoms_end),
##       (neq, ":cur_kingdom", "fac_player_supporters_faction"),
#        (faction_slot_eq, ":cur_kingdom", slot_faction_state, sfs_active),
#        (assign, ":num_ongoing_wars", 0),
#        (try_for_range, ":other_kingdom", kingdoms_begin, kingdoms_end),
#          (faction_slot_eq, ":other_kingdom", slot_faction_state, sfs_active),
#          (store_relation, ":other_relation", ":cur_kingdom", ":other_kingdom"),
#          (lt, ":other_relation", 0),
#          (val_add, ":num_ongoing_wars", 1),
#        (try_end),
#        (faction_get_slot, ":num_towns", ":cur_kingdom", slot_faction_num_towns),
#        (store_mul, ":kingdom_1_resources_value", ":num_towns", 2),
#        (faction_get_slot, ":num_castles", ":cur_kingdom", slot_faction_num_castles),
#        (val_add, ":kingdom_1_resources_value", ":num_castles"),
#        (val_mul, ":kingdom_1_resources_value", 10),
#        (val_max, ":kingdom_1_resources_value", 1),
#        (val_mul, ":kingdom_1_resources_value", 1000),
#        (faction_get_slot, ":num_armies", ":cur_kingdom", slot_faction_num_armies),
#        (val_max, ":num_armies", 1),
#        (val_div, ":kingdom_1_resources_value", ":num_armies"),
#        (store_add, ":start_cond", ":cur_kingdom", 1),
#        (try_for_range, ":cur_kingdom_2", ":start_cond", kingdoms_end),
##         (neq, ":cur_kingdom", "fac_player_supporters_faction"),
#          (faction_slot_eq, ":cur_kingdom_2", slot_faction_state, sfs_active),
#          (assign, ":num_ongoing_wars_2", 0),
#          (try_for_range, ":other_kingdom", kingdoms_begin, kingdoms_end),
#            (faction_slot_eq, ":other_kingdom", slot_faction_state, sfs_active),
#            (store_relation, ":other_relation", ":cur_kingdom_2", ":other_kingdom"),
#            (lt, ":other_relation", 0),
#            (val_add, ":num_ongoing_wars_2", 1),
#          (try_end),
#          (store_add, ":total_ongoing_wars", ":num_ongoing_wars", ":num_ongoing_wars_2"),
#          (faction_get_slot, ":num_towns", ":cur_kingdom_2", slot_faction_num_towns),
#          (store_mul, ":kingdom_2_resources_value", ":num_towns", 2),
#          (faction_get_slot, ":num_castles", ":cur_kingdom_2", slot_faction_num_castles),
#          (val_add, ":kingdom_2_resources_value", ":num_castles"),
#          (val_mul, ":kingdom_2_resources_value", 10),
#          (val_max, ":kingdom_2_resources_value", 1),
#          (val_mul, ":kingdom_2_resources_value", 1000),
#          (faction_get_slot, ":num_armies", ":cur_kingdom_2", slot_faction_num_armies),
#          (val_max, ":num_armies", 1),
#          (val_div, ":kingdom_2_resources_value", ":num_armies"),
#          (assign, ":max_resources_value", ":kingdom_1_resources_value"),
#          (val_max, ":max_resources_value", ":kingdom_2_resources_value"),
#          (val_mul, ":max_resources_value", 100),
#          (val_div, ":max_resources_value", ":average_resources"),
#          (assign, ":cur_king", -1),
#          (try_begin),
#            (eq, ":cur_kingdom", "fac_player_supporters_faction"),
#            (faction_get_slot, ":cur_king", ":cur_kingdom_2", slot_faction_leader),
#            (assign, ":cur_relation", reg0),
#            (store_sub, ":relation_effect", 200, ":cur_relation"),
#            (val_mul, ":kingdom_1_resources_value", ":relation_effect"),
#            (val_div, ":kingdom_1_resources_value", 200),
#          (else_try),
#            (eq, ":cur_kingdom_2", "fac_player_supporters_faction"),
#            (faction_get_slot, ":cur_king", ":cur_kingdom", slot_faction_leader),
#          (try_end),
#          (try_begin),
#            (ge, ":cur_king", 0),
#            (call_script, "script_troop_get_player_relation", ":cur_king"),
#            (assign, ":cur_relation", reg0),
#            (store_sub, ":relation_effect", 200, ":cur_relation"),
#            (val_mul, ":max_resources_value", ":relation_effect"),
#            (val_div, ":max_resources_value", 200),
#          (try_end),
#max_resources_value is the obtained value that gives us how tempting the kingdom's values are
#average is 100
#         (val_clamp, ":max_resources_value", 20, 500),
#not letting more than 5 times higher chance of declaring war or peace
#        (store_random_in_range, ":random_no", 0, 10000),
#         (store_relation, ":cur_relation", ":cur_kingdom", ":cur_kingdom_2"),
#         (try_begin),
#           (lt, ":cur_relation", 0), #AT WAR
#           (store_mul, ":chance_to_make_peace", ":total_ongoing_wars", 50),
#           (val_mul, ":chance_to_make_peace", 100),
#           (val_div, ":chance_to_make_peace", ":max_resources_value"),
#           (try_begin),
#disable random peace for special conditions
#             (this_or_next|eq, ":cur_kingdom", "fac_player_supporters_faction"),
#             (eq, ":cur_kingdom_2", "fac_player_supporters_faction"),
#             (assign, ":continue", 0),
#    (try_begin),
#     (gt, "$supported_pretender", 0),
#    (this_or_next|eq, ":cur_kingdom", "$supported_pretender_old_faction"),
#     (eq, ":cur_kingdom_2", "$supported_pretender_old_faction"),
#      (assign, ":continue", 1),
#     (else_try),
#         (is_between, "$players_oath_renounced_against_kingdom", kingdoms_begin, kingdoms_end),
#          (this_or_next|eq, ":cur_kingdom", "$players_oath_renounced_against_kingdom"),
#           (eq, ":cur_kingdom_2", "$players_oath_renounced_against_kingdom"),
#            (assign, ":continue", 1),
#           (try_end),
#     (eq, ":continue", 1),
#      (assign, ":chance_to_make_peace", 0),
#     (try_end),
#      (try_begin),
#         (lt, ":random_no", ":chance_to_make_peace"),
#          (assign, ":continue", 1),
#           (try_begin),
#              (check_quest_active, "qst_persuade_lords_to_make_peace"),
#  (quest_get_slot, ":quest_target_faction", "qst_persuade_lords_to_make_peace", slot_quest_target_faction),
#   (quest_get_slot, ":quest_object_faction", "qst_persuade_lords_to_make_peace", slot_quest_object_faction),
#    (this_or_next|eq, ":cur_kingdom", ":quest_target_faction"),
#     (eq, ":cur_kingdom", ":quest_object_faction"),
#      (this_or_next|eq, ":cur_kingdom_2", ":quest_target_faction"),
#       (eq, ":cur_kingdom_2", ":quest_object_faction"),
#        (assign, ":continue", 0), #Do not declare war if the quest is active for the specific kingdoms
#       (try_end),
#        (eq, ":continue", 1),
#         (try_begin),
#            (eq, ":cur_kingdom", "fac_player_supporters_faction"),
#             (call_script, "script_add_notification_menu", "mnu_question_peace_offer", ":cur_kingdom_2", 0),
#            (else_try),
#    (eq, ":cur_kingdom_2", "fac_player_supporters_faction"),
#     (call_script, "script_add_notification_menu", "mnu_question_peace_offer", ":cur_kingdom", 0),
#    (else_try),
#       (call_script, "script_diplomacy_start_peace_between_kingdoms", ":cur_kingdom", ":cur_kingdom_2", ":initializing_war_peace_cond"),
#      (try_end),
#     (try_end),
#    (else_try), # AT PEACE
#       (assign, ":chance_to_declare_war", 6),
#        (val_sub, ":chance_to_declare_war", ":total_ongoing_wars"),
#         (val_mul, ":chance_to_declare_war", 50),
#  (val_mul, ":chance_to_declare_war", ":max_resources_value"),
#   (val_div, ":chance_to_declare_war", 100),
#    (try_begin),
#       (lt, ":random_no", ":chance_to_declare_war"),
#        (assign, ":continue", 1),
#         (try_begin),
#            (check_quest_active, "qst_raid_caravan_to_start_war"),
# (quest_get_slot, ":quest_target_faction", "qst_raid_caravan_to_start_war", slot_quest_target_faction),
#  (quest_get_slot, ":quest_object_faction", "qst_raid_caravan_to_start_war", slot_quest_object_faction),
#   (this_or_next|eq, ":cur_kingdom", ":quest_target_faction"),
#    (eq, ":cur_kingdom", ":quest_object_faction"),
#     (this_or_next|eq, ":cur_kingdom_2", ":quest_target_faction"),
#      (eq, ":cur_kingdom_2", ":quest_object_faction"),
#       (assign, ":continue", 0), #Do not declare war if the quest is active for the specific kingdoms
#      (try_end),
#       (eq, ":continue", 1),
#        (call_script, "script_diplomacy_start_war_between_kingdoms", ":cur_kingdom", ":cur_kingdom_2", ":initializing_war_peace_cond"),
#       (try_end),
#      (try_end),
#     (try_end),
#    (try_end),
#    ]),
# script_exchange_prisoners_between_factions
# Input: arg1 = faction_no_1, arg2 = faction_no_2
("exchange_prisoners_between_factions",
   [
       (store_script_param_1, ":faction_no_1"),
       (store_script_param_2, ":faction_no_2"),
       (assign, ":faction_no_3", -1),
       (assign, ":faction_no_4", -1),
       (assign, ":free_companions_too", 0),
       (try_begin),
         (this_or_next|eq, "$players_kingdom", ":faction_no_1"),
         (eq, "$players_kingdom", ":faction_no_2"),
         (assign, ":faction_no_3", "fac_player_faction"),
         (assign, ":faction_no_4", "fac_player_supporters_faction"),
         (assign, ":free_companions_too", 1),
       (try_end),

       (try_for_parties, ":party_no"),
         (store_faction_of_party, ":party_faction", ":party_no"),
         (this_or_next|eq, ":party_faction", ":faction_no_1"),
         (this_or_next|eq, ":party_faction", ":faction_no_2"),
         (this_or_next|eq, ":party_faction", ":faction_no_3"),
         (eq, ":party_faction", ":faction_no_4"),
         (party_get_num_prisoner_stacks, ":num_stacks", ":party_no"),
         (try_for_range_backwards, ":troop_iterator", 0, ":num_stacks"),
           (party_prisoner_stack_get_troop_id, ":cur_troop_id", ":party_no", ":troop_iterator"),

           (assign, ":continue", 0),
           (try_begin),
             (is_between, ":cur_troop_id", companions_begin, companions_end),
             (eq, ":free_companions_too", 1),
             (assign, ":continue", 1),
           (else_try),
             (neg|is_between, ":cur_troop_id", companions_begin, companions_end),
             (store_troop_faction, ":cur_faction", ":cur_troop_id"),
             (this_or_next|eq, ":cur_faction", ":faction_no_1"),
             (this_or_next|eq, ":cur_faction", ":faction_no_2"),
             (this_or_next|eq, ":cur_faction", ":faction_no_3"),
             (eq, ":cur_faction", ":faction_no_4"),
             (assign, ":continue", 1),
           (try_end),
           (eq, ":continue", 1),

           (try_begin),
             (troop_is_hero, ":cur_troop_id"),
             (call_script, "script_remove_troop_from_prison", ":cur_troop_id"),
           (try_end),
           (party_prisoner_stack_get_size, ":stack_size", ":party_no", ":troop_iterator"),
           (party_remove_prisoners, ":party_no", ":cur_troop_id", ":stack_size"),
         (try_end),
       (try_end),

    ])
]
