# -*- coding: cp1254 -*-
from header_common import *
from header_operations import *
from module_constants import *

exchange_two_items_of_slots_scripts = [
("exchange_two_items_of_slots",
  [
    (store_script_param_1, ":old_slot"),
    (store_script_param_2, ":new_slot"),

    (try_begin),
      (is_between, ":old_slot", 0, 9),
      (assign, ":old_item_slot_no", ":old_slot"),
      (troop_get_inventory_slot, ":old_item", "$g_selected_troop", ":old_item_slot_no"),
      (troop_get_inventory_slot_modifier, ":old_imod", "$g_selected_troop", ":old_item_slot_no"),
    (else_try),
      (is_between, ":old_slot", 10, 58),
      (store_mul, ":old_item_slot_no", "$g_cur_page_of_loot_pool", 48),
      (val_add, ":old_item_slot_no", ":old_slot"),
      (troop_get_inventory_slot, ":old_item", "trp_player", ":old_item_slot_no"),
      (troop_get_inventory_slot_modifier, ":old_imod", "trp_player", ":old_item_slot_no"),
    (try_end),
    (try_begin),
      (is_between, ":new_slot", 0, 9),
      (assign, ":new_item_slot_no", ":new_slot"),
      (troop_get_inventory_slot, ":new_item", "$g_selected_troop", ":new_item_slot_no"),
      (troop_get_inventory_slot_modifier, ":new_imod", "$g_selected_troop", ":new_item_slot_no"),
    (else_try),
      (is_between, ":new_slot", 10, 58),
      (store_mul, ":new_item_slot_no", "$g_cur_page_of_loot_pool", 48),
      (val_add, ":new_item_slot_no", ":new_slot"),
      (troop_get_inventory_slot, ":new_item", "trp_player", ":new_item_slot_no"),
      (troop_get_inventory_slot_modifier, ":new_imod", "trp_player", ":new_item_slot_no"),
    (try_end),

    (try_begin),
      (gt, ":old_item", -1),
      (item_get_type, ":old_slot_type", ":old_item"),
      (try_begin),
        (this_or_next|is_between, ":old_slot_type", itp_type_one_handed_wpn, itp_type_goods),
        (is_between, ":old_slot_type", itp_type_pistol, itp_type_animal),
        (assign, ":old_slot_type", itp_type_one_handed_wpn),
      (try_end),

      (try_begin),
        (is_between, ":new_slot", 0, 4),
        (assign, ":new_slot_type", itp_type_one_handed_wpn),
      (else_try),
        (is_between, ":new_slot", 4, 8),
        (store_add, ":new_slot_type", ":new_slot", 8),
      (else_try),
        (eq, ":new_slot", 8),
        (assign, ":new_slot_type", itp_type_horse),
      (else_try),
        (is_between, ":new_slot", 10, 58),
        (try_begin),
          (this_or_next|eq, ":new_item", -1),
          (is_between, ":old_slot", 10, 58),
          (assign, ":new_slot_type", -1),
        (else_try),
          (item_get_type, ":new_slot_type", ":new_item"),
          (try_begin),
            (this_or_next|is_between, ":new_slot_type", itp_type_one_handed_wpn, itp_type_goods),
            (is_between, ":new_slot_type", itp_type_pistol, itp_type_animal),
            (assign, ":new_slot_type", itp_type_one_handed_wpn),
          (try_end),
        (try_end),
      (try_end),

      (try_begin),
        (is_between, ":new_slot", 0, 10),
        (assign, ":new_troop", "$g_selected_troop"),
      (else_try),
        (is_between, ":new_slot", 10, 58),
        (assign, ":new_troop", "trp_player"),
      (try_end),
      (try_begin),
        (is_between, ":old_slot", 0, 10),
        (assign, ":old_troop", "$g_selected_troop"),
      (else_try),
        (is_between, ":old_slot", 10, 58),
        (assign, ":old_troop", "trp_player"),
      (try_end),

      (try_begin),
        (this_or_next|eq, ":new_slot_type", -1),
        (eq, ":new_slot_type", ":old_slot_type"),
        (try_begin),
          (eq, ":new_item", -1),
          (troop_set_inventory_slot, ":new_troop", ":new_item_slot_no", ":old_item"),
          (troop_set_inventory_slot_modifier, ":new_troop", ":new_item_slot_no", ":old_imod"),
          (troop_set_inventory_slot, ":old_troop", ":old_item_slot_no", -1),
          (start_presentation, "prsnt_equip_npcs"),
        (else_try),
          (troop_set_inventory_slot, ":new_troop", ":new_item_slot_no", ":old_item"),
          (troop_set_inventory_slot_modifier, ":new_troop", ":new_item_slot_no", ":old_imod"),
          (troop_set_inventory_slot, ":old_troop", ":old_item_slot_no", ":new_item"),
          (troop_set_inventory_slot_modifier, ":old_troop", ":old_item_slot_no", ":new_imod"),
          (start_presentation, "prsnt_equip_npcs"),
        (try_end),
      (try_end),
    (try_end),
]),
]
