# -*- coding: cp1254 -*-
from header_common import *
from header_operations import *
from module_constants import *
from header_parties import *
from header_skills import *
from header_mission_templates import *
from header_items import *
from header_triggers import *
from header_terrain_types import *
from header_music import *
from header_map_icons import *
from ID_animations import *

get_item_capability_with_imod_scripts = [
("get_item_capability_with_imod",
    [
      (store_script_param, ":item", 1),
      (store_script_param, ":imod", 2),
      
      (item_get_type, ":type", ":item"),
      (assign, ":item_capability", 0),
      (try_begin),
        (eq,  ":type", itp_type_horse),
        (item_get_hit_points, ":horse_hp", ":item"),
        (item_get_body_armor, ":horse_armor", ":item"),
        (item_get_horse_speed, ":horse_speed", ":item"),
        (item_get_horse_maneuver, ":horse_maneuver", ":item"),
        (item_get_horse_charge_damage, ":horse_charge", ":item"),
        (try_begin),
          (gt, ":imod", 0),
          (try_begin),
            (gt, ":horse_hp", 0),
            (call_script, "script_imod_effect_hp", ":imod"),
            (val_add, ":horse_hp", reg0),
            (val_max, ":horse_hp", 0),
          (try_end),
          (try_begin),
            (gt, ":horse_armor", 0),
            (call_script, "script_imod_effect_armor", ":imod"),
            (val_add, ":horse_armor", reg0),
            (val_max, ":horse_armor", 0),
          (try_end),
          (try_begin),
            (gt, ":horse_speed", 0),
            (call_script, "script_imod_effect_horse_speed", ":imod"),
            (val_add, ":horse_speed", reg0),
            (val_max, ":horse_speed", 0),
          (try_end),
          (try_begin),
            (gt, ":horse_maneuver", 0),
            (call_script, "script_imod_effect_horse_maneuver", ":imod"),
            (val_add, ":horse_maneuver", reg0),
            (val_max, ":horse_maneuver", 0),
          (try_end),
          (try_begin),
            (gt, ":horse_charge", 0),
            (call_script, "script_imod_effect_horse_charge", ":imod"),
            (val_add, ":horse_charge", reg0),
            (val_max, ":horse_charge", 0),
          (try_end),
        (try_end),
        (try_begin),
          (eq, ":imod", imod_lame),
        (else_try),
          (val_add, ":item_capability", ":horse_hp"),
          (val_mul, ":horse_armor", 3),
          (val_add, ":item_capability", ":horse_armor"),
          (val_mul, ":horse_speed", 5),
          (val_add, ":item_capability", ":horse_speed"),
          (val_mul, ":horse_maneuver", 4),
          (val_add, ":item_capability", ":horse_maneuver"),
          (val_add, ":item_capability", ":horse_charge"),
        (try_end),

      (else_try),
        (is_between, ":type", itp_type_head_armor, itp_type_hand_armor+1),
        (item_get_head_armor, ":head_armor", ":item"),
        (item_get_body_armor, ":body_armor", ":item"),
        (item_get_leg_armor, ":leg_armor", ":item"),
        (try_begin),
          (gt, ":imod", 0),
          (call_script, "script_imod_effect_armor", ":imod"),
          (try_begin),
            (gt, ":head_armor", 0),
            (val_add, ":head_armor", reg0),
            (val_max, ":head_armor", 0),
          (try_end),
          (try_begin),
            (gt, ":body_armor", 0),
            (val_add, ":body_armor", reg0),
            (val_max, ":body_armor", 0),
          (try_end),
          (try_begin),
            (gt, ":leg_armor", 0),
            (val_add, ":leg_armor", reg0),
            (val_max, ":leg_armor", 0),
          (try_end),
        (try_end),
        (item_get_weight, ":weight", ":item"),
        (val_div, ":weight", 1000),
        (val_add, ":item_capability", ":head_armor"),
        (val_add, ":item_capability", ":body_armor"),
        (val_add, ":item_capability", ":leg_armor"),
        (val_mul, ":item_capability", 2),
        (val_sub, ":item_capability", ":weight"),

      (else_try),  
        (eq, ":type", itp_type_shield),
        (item_get_hit_points, ":shield_hp", ":item"),
        (item_get_body_armor, ":shield_armor", ":item"),
        (item_get_speed_rating, ":shield_speed", ":item"),
        (try_begin),
          (gt, ":imod", 0),
          (try_begin),
            (gt, ":shield_hp", 0),
            (call_script, "script_imod_effect_hp", ":imod"),
            (val_add, ":shield_hp", reg0),
            (val_max, ":shield_hp", 0),
          (try_end),
          (try_begin),
            (gt, ":shield_armor", 0),
            (call_script, "script_imod_effect_armor", ":imod"),
            (val_add, ":shield_armor", reg0),
            (val_max, ":shield_armor", 0),
          (try_end),
          (try_begin),
            (gt, ":shield_speed", 0),
            (call_script, "script_imod_effect_speed", ":imod"),
            (val_add, ":shield_speed", reg0),
            (val_max, ":shield_speed", 0),
          (try_end),
        (try_end),
        (set_fixed_point_multiplier, 1000),
        (item_get_shield_height, ":shield_height_to_bottom", ":item"),
        (val_div, ":shield_height_to_bottom", 10),
        (item_get_weapon_length, ":shield_half_width", ":item"),
        (store_add, ":shield_width", ":shield_half_width", ":shield_half_width"),
        (try_begin),
          (gt, ":shield_height_to_bottom", 0),
          (store_add, ":shield_height", ":shield_height_to_bottom", ":shield_half_width"),
        (else_try),
          (store_add, ":shield_height", ":shield_half_width", ":shield_half_width"),
        (try_end),
        (item_get_weight, ":weight", ":item"),
        (val_div, ":weight", 1000),
        (val_add, ":item_capability", ":shield_hp"),
        (val_mul, ":shield_armor", 20),
        (val_add, ":item_capability", ":shield_armor"),
        (val_add, ":item_capability", ":shield_speed"),
        (val_add, ":item_capability", ":shield_width"),
        (val_add, ":item_capability", ":shield_height"),
        (val_sub, ":item_capability", ":weight"),

      (else_try),
        (this_or_next|eq, ":type", itp_type_one_handed_wpn),
        (this_or_next|eq, ":type", itp_type_two_handed_wpn),
        (this_or_next|eq, ":type", itp_type_polearm),
        (this_or_next|eq, ":type", itp_type_bow),
        (this_or_next|eq, ":type", itp_type_crossbow),
        (this_or_next|eq, ":type", itp_type_pistol),
        (this_or_next|eq, ":type", itp_type_musket),
        (eq, ":type", itp_type_thrown),
        (item_get_swing_damage, ":swing_damage", ":item"),
        (item_get_swing_damage_type, ":swing_damage_type", ":item"),
        (item_get_thrust_damage, ":thrust_damage", ":item"),
        (item_get_thrust_damage_type, ":thrust_damage_type", ":item"),
        (item_get_speed_rating, ":item_speed", ":item"),
        (try_begin),
          (gt, ":imod", 0),
          (call_script, "script_imod_effect_damage", ":imod"),
          (try_begin),
            (gt, ":swing_damage", 0),
            (val_add, ":swing_damage", reg0),
            (val_max, ":swing_damage", 0),
          (try_end),
          (try_begin),
            (gt, ":thrust_damage", 0),
            (val_add, ":thrust_damage", reg0),
            (val_max, ":thrust_damage", 0),
          (try_end),
          (try_begin),
            (gt, ":item_speed", 0),
            (call_script, "script_imod_effect_speed", ":imod"),
            (val_add, ":item_speed", reg0),
            (val_max, ":item_speed", 0),
          (try_end),
        (try_end),
        (try_begin),
          (le, ":swing_damage", 0),
        (else_try),
          (eq, ":swing_damage_type", cut),
          (val_mul, ":swing_damage", 4),
        (else_try),
          (eq, ":swing_damage_type", pierce),
          (val_mul, ":swing_damage", 5),
        (else_try),
          (eq, ":swing_damage_type", blunt),
          (val_mul, ":swing_damage", 6),
        (try_end),
        (try_begin),
          (le, ":thrust_damage", 0),
        (else_try),
          (eq, ":thrust_damage_type", cut),
          (val_mul, ":thrust_damage", 4),
        (else_try),
          (eq, ":thrust_damage_type", pierce),
          (val_mul, ":thrust_damage", 5),
        (else_try),
          (eq, ":thrust_damage_type", blunt),
          (val_mul, ":thrust_damage", 6),
        (try_end),
        (assign, ":item_damage", ":swing_damage"),
        (val_max, ":item_damage", ":thrust_damage"),
        (item_get_weight, ":weight", ":item"),
        (val_div, ":weight", 1000),
        (try_begin),
          (this_or_next|eq, ":type", itp_type_bow),
          (this_or_next|eq, ":type", itp_type_crossbow),
          (this_or_next|eq, ":type", itp_type_pistol),
          (this_or_next|eq, ":type", itp_type_musket),
          (eq, ":type", itp_type_thrown),
          (item_get_missile_speed, ":missile_speed", ":item"),
          (val_mul, ":item_damage", 2),
          (val_add, ":item_capability", ":item_damage"),
          (val_add, ":item_capability", ":item_speed"),
          (val_add, ":item_capability", ":missile_speed"),
          (val_sub, ":item_capability", ":weight"),
          (try_begin),
            (eq, ":type", itp_type_thrown),
            (item_get_max_ammo, ":max_ammo", ":item"),
            (try_begin),
              (eq, ":imod", imod_large_bag),
              (val_add, ":max_ammo", 1),
            (try_end),
            (val_mul, ":max_ammo", 2),
            (val_add, ":item_capability", ":max_ammo"),
          (try_end),
        (else_try),
          (item_get_weapon_length, ":item_length", ":item"),
          (val_add, ":item_capability", ":item_damage"),
          (val_add, ":item_capability", ":item_speed"),
          (val_mul, ":item_length", 2),
          (val_add, ":item_capability", ":item_length"),
          (val_sub, ":item_capability", ":weight"),
        (try_end),

      (else_try),
        (this_or_next|eq, ":type", itp_type_arrows),
        (this_or_next|eq, ":type", itp_type_bolts),
        (eq, ":type", itp_type_bullets),
        (item_get_thrust_damage, ":thrust_damage", ":item"),
        (item_get_max_ammo, ":max_ammo", ":item"),
        (try_begin),
          (gt, ":imod", 0),
          (try_begin),
            (eq, ":imod", imod_large_bag),
            (val_add, ":max_ammo", 1),
          (else_try),
            (call_script, "script_imod_effect_damage", ":imod"),
            (val_add, ":thrust_damage", reg0),
          (try_end),
        (try_end),
        (val_add, ":item_capability", ":max_ammo"),
        (val_mul, ":thrust_damage", 2),
        (val_add, ":item_capability", ":thrust_damage"),
      (try_end),
      (assign, reg0, ":item_capability"),
    ])
]
