# -*- coding: cp1254 -*-
from header_common import *
from header_operations import *
from module_constants import *
from module_constants import *
from header_parties import *
from header_skills import *
from header_mission_templates import *
from header_items import *
from header_triggers import *
from header_terrain_types import *
from header_music import *
from header_map_icons import *
from ID_animations import *
from ID_strings import str_key_0
from module_factions import dplmc_factions_begin, dplmc_factions_end, dplmc_non_generic_factions_begin

spawn_bandits_scripts = [
("spawn_bandits",
    [
     (set_spawn_radius,1),

	 (try_begin),
		(eq, "$cheat_mode", 1),
		(display_message, "@{!}DEBUG : Doing spawn bandit script"),
	 (try_end),

	 (party_template_set_slot, "pt_steppe_bandits", slot_party_template_lair_type, "pt_steppe_bandit_lair"),
	 (party_template_set_slot, "pt_taiga_bandits", slot_party_template_lair_type, "pt_taiga_bandit_lair"),
	 (party_template_set_slot, "pt_mountain_bandits", slot_party_template_lair_type, "pt_mountain_bandit_lair"),
	 (party_template_set_slot, "pt_forest_bandits", slot_party_template_lair_type, "pt_forest_bandit_lair"),
	 (party_template_set_slot, "pt_sea_raiders", slot_party_template_lair_type, "pt_sea_raider_lair"),
	 (party_template_set_slot, "pt_desert_bandits", slot_party_template_lair_type, "pt_desert_bandit_lair"),

	 (party_template_set_slot, "pt_steppe_bandits", slot_party_template_lair_spawnpoint, "p_steppe_bandit_spawn_point"),
	 (party_template_set_slot, "pt_taiga_bandits", slot_party_template_lair_spawnpoint, "p_taiga_bandit_spawn_point"),
	 (party_template_set_slot, "pt_mountain_bandits", slot_party_template_lair_spawnpoint, "p_mountain_bandit_spawn_point"),
	 (party_template_set_slot, "pt_forest_bandits", slot_party_template_lair_spawnpoint, "p_forest_bandit_spawn_point"),
	 (party_template_set_slot, "pt_sea_raiders", slot_party_template_lair_spawnpoint, "p_sea_raider_spawn_point_1"),
	 (party_template_set_slot, "pt_desert_bandits", slot_party_template_lair_spawnpoint, "p_desert_bandit_spawn_point"),

     # Clean up stale lair references (party was removed but slot still holds old ID)
     (try_for_range, ":bandit_template", bandit_party_templates_begin, bandit_party_templates_end),
       (party_template_get_slot, ":lair_party", ":bandit_template", slot_party_template_lair_party),
       (gt, ":lair_party", 1),
       (try_begin),
         (neg|party_is_active, ":lair_party"),
         (party_get_slot, ":actual_type", ":lair_party", slot_party_type),
         (neq, ":actual_type", spt_bandit_lair),
         (party_template_set_slot, ":bandit_template", slot_party_template_lair_party, 0),
       (try_end),
     (try_end),

     # Mountain Bandits — respawn at lair if alive, spawn point if dead (with debuff)
     (party_template_get_slot, ":bandit_lair_party", "pt_mountain_bandits", slot_party_template_lair_party),
     (try_begin),
       (gt, ":bandit_lair_party", 1),
       (party_is_active, ":bandit_lair_party"),
       (call_script, "script_spawn_party_type_with_cooldown", "pt_mountain_bandits", ":bandit_lair_party", 1, num_max_bandit_parties_per_type),
     (else_try),
       (call_script, "script_spawn_party_type_with_cooldown", "pt_mountain_bandits", "p_mountain_bandit_spawn_point", num_mountain_bandit_spawn_points, num_max_bandit_parties_per_type),
       (neq, reg0, -1),
       (party_get_num_companion_stacks, ":stks", reg0),
       (gt, ":stks", 0),
       (party_stack_get_troop_id, ":tid", reg0, 0),
       (party_stack_get_size, ":sz", reg0, 0),
       (gt, ":sz", num_max_bandit_party_size_debuff),
       (val_sub, ":sz", num_max_bandit_party_size_debuff),
       (val_mul, ":sz", -1),
       (party_add_members, reg0, ":tid", ":sz"),
     (try_end),
     # Forest Bandits
     (party_template_get_slot, ":bandit_lair_party", "pt_forest_bandits", slot_party_template_lair_party),
     (try_begin),
       (gt, ":bandit_lair_party", 1),
       (party_is_active, ":bandit_lair_party"),
       (call_script, "script_spawn_party_type_with_cooldown", "pt_forest_bandits", ":bandit_lair_party", 1, num_max_bandit_parties_per_type),
     (else_try),
       (call_script, "script_spawn_party_type_with_cooldown", "pt_forest_bandits", "p_forest_bandit_spawn_point", num_forest_bandit_spawn_points, num_max_bandit_parties_per_type),
       (neq, reg0, -1),
       (party_get_num_companion_stacks, ":stks", reg0),
       (gt, ":stks", 0),
       (party_stack_get_troop_id, ":tid", reg0, 0),
       (party_stack_get_size, ":sz", reg0, 0),
       (gt, ":sz", num_max_bandit_party_size_debuff),
       (val_sub, ":sz", num_max_bandit_party_size_debuff),
       (val_mul, ":sz", -1),
       (party_add_members, reg0, ":tid", ":sz"),
     (try_end),
     # Sea Raiders
     (party_template_get_slot, ":bandit_lair_party", "pt_sea_raiders", slot_party_template_lair_party),
     (try_begin),
       (gt, ":bandit_lair_party", 1),
       (party_is_active, ":bandit_lair_party"),
       (call_script, "script_spawn_party_type_with_cooldown", "pt_sea_raiders", ":bandit_lair_party", 1, num_max_bandit_parties_per_type),
     (else_try),
       (call_script, "script_spawn_party_type_with_cooldown", "pt_sea_raiders", "p_sea_raider_spawn_point_1", num_sea_raider_spawn_points, num_max_bandit_parties_per_type),
       (neq, reg0, -1),
       (party_get_num_companion_stacks, ":stks", reg0),
       (gt, ":stks", 0),
       (party_stack_get_troop_id, ":tid", reg0, 0),
       (party_stack_get_size, ":sz", reg0, 0),
       (gt, ":sz", num_max_bandit_party_size_debuff),
       (val_sub, ":sz", num_max_bandit_party_size_debuff),
       (val_mul, ":sz", -1),
       (party_add_members, reg0, ":tid", ":sz"),
     (try_end),
     # Steppe Bandits
     (party_template_get_slot, ":bandit_lair_party", "pt_steppe_bandits", slot_party_template_lair_party),
     (try_begin),
       (gt, ":bandit_lair_party", 1),
       (party_is_active, ":bandit_lair_party"),
       (call_script, "script_spawn_party_type_with_cooldown", "pt_steppe_bandits", ":bandit_lair_party", 1, num_max_bandit_parties_per_type),
     (else_try),
       (call_script, "script_spawn_party_type_with_cooldown", "pt_steppe_bandits", "p_steppe_bandit_spawn_point", num_steppe_bandit_spawn_points, num_max_bandit_parties_per_type),
       (neq, reg0, -1),
       (party_get_num_companion_stacks, ":stks", reg0),
       (gt, ":stks", 0),
       (party_stack_get_troop_id, ":tid", reg0, 0),
       (party_stack_get_size, ":sz", reg0, 0),
       (gt, ":sz", num_max_bandit_party_size_debuff),
       (val_sub, ":sz", num_max_bandit_party_size_debuff),
       (val_mul, ":sz", -1),
       (party_add_members, reg0, ":tid", ":sz"),
     (try_end),
     # Taiga Bandits
     (party_template_get_slot, ":bandit_lair_party", "pt_taiga_bandits", slot_party_template_lair_party),
     (try_begin),
       (gt, ":bandit_lair_party", 1),
       (party_is_active, ":bandit_lair_party"),
       (call_script, "script_spawn_party_type_with_cooldown", "pt_taiga_bandits", ":bandit_lair_party", 1, num_max_bandit_parties_per_type),
     (else_try),
       (call_script, "script_spawn_party_type_with_cooldown", "pt_taiga_bandits", "p_taiga_bandit_spawn_point", num_taiga_bandit_spawn_points, num_max_bandit_parties_per_type),
       (neq, reg0, -1),
       (party_get_num_companion_stacks, ":stks", reg0),
       (gt, ":stks", 0),
       (party_stack_get_troop_id, ":tid", reg0, 0),
       (party_stack_get_size, ":sz", reg0, 0),
       (gt, ":sz", num_max_bandit_party_size_debuff),
       (val_sub, ":sz", num_max_bandit_party_size_debuff),
       (val_mul, ":sz", -1),
       (party_add_members, reg0, ":tid", ":sz"),
     (try_end),
     # Desert Bandits
     (party_template_get_slot, ":bandit_lair_party", "pt_desert_bandits", slot_party_template_lair_party),
     (try_begin),
       (gt, ":bandit_lair_party", 1),
       (party_is_active, ":bandit_lair_party"),
       (call_script, "script_spawn_party_type_with_cooldown", "pt_desert_bandits", ":bandit_lair_party", 1, num_max_bandit_parties_per_type),
     (else_try),
       (call_script, "script_spawn_party_type_with_cooldown", "pt_desert_bandits", "p_desert_bandit_spawn_point", num_desert_bandit_spawn_points, num_max_bandit_parties_per_type),
       (neq, reg0, -1),
       (party_get_num_companion_stacks, ":stks", reg0),
       (gt, ":stks", 0),
       (party_stack_get_troop_id, ":tid", reg0, 0),
       (party_stack_get_size, ":sz", reg0, 0),
       (gt, ":sz", num_max_bandit_party_size_debuff),
       (val_sub, ":sz", num_max_bandit_party_size_debuff),
       (val_mul, ":sz", -1),
       (party_add_members, reg0, ":tid", ":sz"),
     (try_end),
     # Looters
     (try_begin),
       (store_sub, ":num_villages", villages_end, villages_begin),
       (call_script, "script_spawn_party_type_with_cooldown", "pt_looters", villages_begin, ":num_villages", num_max_looters),
       (assign, ":spawned_party_id", reg0),
       (gt, ":spawned_party_id", 0),
       (try_begin),
         (check_quest_active, "qst_deal_with_looters"),
         (party_set_flags, ":spawned_party_id", pf_quest_party, 1),
       (else_try),
         (party_set_flags, ":spawned_party_id", pf_quest_party, 0),
       (try_end),
     (try_end),
     # Manhunters: fill to cap every cycle, spawn at random bandit respawn points
     (store_num_parties_of_template, ":num_mh", "pt_manhunters"),
     (lt, ":num_mh", num_max_manhunters),
     (store_sub, ":to_spawn", num_max_manhunters, ":num_mh"),
     (try_for_range, ":mhi", 0, ":to_spawn"),
       (store_random, ":r_bt", 6),
       (try_begin),
         (eq, ":r_bt", 0), (assign, ":sp", "p_steppe_bandit_spawn_point"),
       (else_try),
         (eq, ":r_bt", 1), (assign, ":sp", "p_taiga_bandit_spawn_point"),
       (else_try),
         (eq, ":r_bt", 2), (assign, ":sp", "p_desert_bandit_spawn_point"),
       (else_try),
         (eq, ":r_bt", 3), (assign, ":sp", "p_forest_bandit_spawn_point"),
       (else_try),
         (eq, ":r_bt", 4), (assign, ":sp", "p_mountain_bandit_spawn_point"),
       (else_try),
         (assign, ":sp", "p_sea_raider_spawn_point_1"),
       (try_end),
       (set_spawn_radius, 25),
       (spawn_around_party, ":sp", "pt_manhunters"),
     (try_end),
     (try_begin),
       (store_num_parties_of_template, ":num_parties", "pt_deserters"),
       (lt,":num_parties",15),
       (set_spawn_radius, 4),
       (try_for_range, ":troop_no", active_npcs_begin, active_npcs_end),
	     (troop_slot_eq, ":troop_no", slot_troop_occupation, slto_kingdom_hero),
         (store_random_in_range, ":random_no", 0, 100),
         (lt, ":random_no", 5),
         (troop_get_slot, ":party_no", ":troop_no", slot_troop_leaded_party),
         (store_troop_faction, ":troop_faction", ":troop_no"),
         (neq, ":troop_faction", "fac_player_supporters_faction"),
         (gt, ":party_no", 0),
         (neg|party_is_in_any_town, ":party_no"),
##         (party_get_attached_to, ":attached_party_no", ":party_no"),
##         (lt, ":attached_party_no", 0),#in wilderness
         (spawn_around_party, ":party_no", "pt_deserters"),
         (assign, ":new_party", reg0),

         ##dckplmc
         (try_begin),
          (is_between, ":troop_faction", npc_kingdoms_begin, kingdoms_end),
          (store_sub, ":fac_offset", ":troop_faction", npc_kingdoms_begin),
          (store_add, ":icon", "icon_kingdom_1_soldier_a", ":fac_offset"),
          (party_set_icon, ":new_party", ":icon"),
         (try_end),
         ##

         (store_troop_faction, ":faction_no", ":troop_no"),
         (faction_get_slot, ":tier_1_troop", ":faction_no", slot_faction_tier_1_troop),
         (store_character_level, ":level", "trp_player"),
         (store_mul, ":max_number_to_add", ":level", 2),
         (val_add, ":max_number_to_add", 11),
         (store_random_in_range, ":number_to_add", 10, ":max_number_to_add"),
         (party_add_members, ":new_party", ":tier_1_troop", ":number_to_add"),
         (store_random_in_range, ":random_no", 1, 4),
         (try_for_range, ":unused", 0, ":random_no"),
           (party_upgrade_with_xp, ":new_party", 1000000, 0),
         (try_end),
##         (str_store_party_name, s1, ":party_no"),
##         (call_script, "script_get_closest_center", ":party_no"),
##         (try_begin),
##           (gt, reg0, 0),
##           (str_store_party_name, s2, reg0),
##         (else_try),
##           (str_store_string, s2, "@unknown place"),
##         (try_end),
##         (assign, reg1, ":number_to_add"),
##         (display_message, "@{reg1} Deserters spawned from {s1}, near {s2}."),
       (try_end),
     (try_end), #deserters ends

	 # AC : Dark Hunters, Black Khergits, NPC Ships
     (try_begin),
       (eq, "$g_dark_hunters_enabled", 1),
       (store_num_parties_of_template, ":num_parties", "pt_dark_hunters"),
       (lt,":num_parties",4),
		(store_random_in_range, ":selected_town", towns_begin, towns_end),
		(set_spawn_radius, 25),
		(spawn_around_party, ":selected_town", "pt_dark_hunters"),
     (try_end),
     (try_begin),
       (eq, "$g_dark_hunters_enabled", 1),
       (store_num_parties_of_template, ":num_parties", "pt_black_khergit_raiders"),
       (lt,":num_parties",4),
       (store_random,":spawn_point",num_steppe_bandit_spawn_points),
       (val_add,":spawn_point","p_steppe_bandit_spawn_point"),
       (set_spawn_radius, 25),
       (spawn_around_party,":spawn_point","pt_black_khergit_raiders"),
     (try_end),
     # Pirate ships: 3 types, 5 per type, no cooldown (0 = fill every cycle)
     (try_begin),
      (call_script, "script_spawn_party_type_with_cooldown", "pt_sea_raiders_ship", "p_reserved_1", 1, num_max_pirate_ships),
        (neq, reg0, -1),
        (party_set_slot, reg0, slot_party_ship_type, 1),
      (try_end),
      (try_begin),
        (call_script, "script_spawn_party_type_with_cooldown", "pt_corsair_ship", "p_reserved_3", 1, num_max_pirate_ships),
        (neq, reg0, -1),
        (party_set_slot, reg0, slot_party_ship_type, 2),
      (try_end),
      (try_begin),
        (call_script, "script_spawn_party_type_with_cooldown", "pt_pirate_ship", "p_reserved_2", 1, num_max_pirate_ships),
       (neq, reg0, -1),
       (party_set_slot, reg0, slot_party_ship_type, 4),
     (try_end),
     (try_begin),
       (store_num_parties_of_template, ":num_parties", "pt_merchant_ship"),
       (lt,":num_parties",8),
       (set_spawn_radius, 1),
       (store_random_in_range, ":origin_port", "p_port_1", "p_ports_end"),
       (spawn_around_party,":origin_port","pt_merchant_ship"),
       (assign, ":party_no", reg0),
       (party_set_slot, ":party_no", slot_party_ship_type, 3),
       (party_set_flags, ":party_no", pf_default_behavior, 0),
       (party_set_ai_behavior, ":party_no", ai_bhvr_travel_to_party),
       # (party_get_slot, ":port_town", ":origin_port", slot_port_town),
       # (store_faction_of_party, ":town_faction", ":port_town"),
       # (faction_get_slot, ":reinforcements_b", ":town_faction", slot_faction_reinforcements_b),
       # (try_begin),
         # (eq, ":town_faction", "fac_player_supporters_faction"),
         # (party_get_slot, ":reinforcement_faction", ":port_town", slot_center_original_faction),
         # (faction_get_slot, ":reinforcements_b", ":reinforcement_faction", slot_faction_reinforcements_b),
       # (try_end),
       # (party_add_template, ":party_no", ":reinforcements_b"),
       # (party_add_template, ":party_no", ":reinforcements_b"),
       # (party_set_faction, ":party_no", ":town_faction"),
       (store_random_in_range, ":dest_port", "p_port_1", "p_ports_end"),
       (party_set_ai_object, ":party_no", ":dest_port"),
     (try_end),
	 #Spawn bandit lairs
	(try_for_range, ":bandit_template", bandit_party_templates_begin, bandit_party_templates_end), #SB : template range
		(party_template_get_slot, ":bandit_lair_party", ":bandit_template", slot_party_template_lair_party),
		(le, ":bandit_lair_party", 1),

        (party_template_get_slot, ":next_spawn", ":bandit_template", slot_party_template_lair_next_spawn),
        (val_max, ":next_spawn", 0),
        (store_current_hours, ":cur_hours"),
        (ge, ":cur_hours", ":next_spawn"),

		(party_template_get_slot, ":bandit_lair_template", ":bandit_template", slot_party_template_lair_type),
		(party_template_get_slot, ":bandit_lair_template_spawnpoint", ":bandit_template", slot_party_template_lair_spawnpoint),

		(set_spawn_radius, 20),

        (spawn_around_party, ":bandit_lair_template_spawnpoint", ":bandit_lair_template"),
		(assign, ":new_camp", reg0),

		(try_begin),
		  (gt, ":new_camp", 0),
		  (party_set_slot, ":new_camp", slot_party_type, spt_bandit_lair),

		(str_store_party_name, s4, ":new_camp"),

		(store_random_in_range, ":rand_sp", 0, 5),
		(init_position, pos1),
		(set_fixed_point_multiplier, 100),
		(try_begin),
			(eq, ":bandit_template", "pt_steppe_bandits"),
			(try_begin),
				(eq, ":rand_sp", 0), (position_set_x, pos1, 13000), (position_set_y, pos1, 1500),
			(else_try),
				(eq, ":rand_sp", 1), (position_set_x, pos1, 13915), (position_set_y, pos1, 1305),
			(else_try),
				(eq, ":rand_sp", 2), (position_set_x, pos1, 12877), (position_set_y, pos1, 2351),
			(else_try),
				(eq, ":rand_sp", 3), (position_set_x, pos1, 11028), (position_set_y, pos1, 975),
			(else_try),
				(position_set_x, pos1, 14000), (position_set_y, pos1, 1500),
			(try_end),
		(else_try),
			(eq, ":bandit_template", "pt_taiga_bandits"),
			(try_begin),
				(eq, ":rand_sp", 0), (position_set_x, pos1, 9500), (position_set_y, pos1, 9200),
			(else_try),
				(eq, ":rand_sp", 1), (position_set_x, pos1, 6535), (position_set_y, pos1, 8187),
			(else_try),
				(eq, ":rand_sp", 2), (position_set_x, pos1, 7958), (position_set_y, pos1, 7017),
			(else_try),
				(eq, ":rand_sp", 3), (position_set_x, pos1, 7489), (position_set_y, pos1, 9703),
			(else_try),
				(position_set_x, pos1, 7500), (position_set_y, pos1, 7800),
			(try_end),
		(else_try),
			(eq, ":bandit_template", "pt_desert_bandits"),
			(try_begin),
				(eq, ":rand_sp", 0), (position_set_x, pos1, 11522), (position_set_y, pos1, -8853),
			(else_try),
				(eq, ":rand_sp", 1), (position_set_x, pos1, 11891), (position_set_y, pos1, -8979),
			(else_try),
				(eq, ":rand_sp", 2), (position_set_x, pos1, 11254), (position_set_y, pos1, -8909),
			(else_try),
				(eq, ":rand_sp", 3), (position_set_x, pos1, 11708), (position_set_y, pos1, -8879),
			(else_try),
				(position_set_x, pos1, 11502), (position_set_y, pos1, -8999),
			(try_end),
		(else_try),
			(eq, ":bandit_template", "pt_forest_bandits"),
			(try_begin),
				(eq, ":rand_sp", 0), (position_set_x, pos1, -3578), (position_set_y, pos1, 1596),
			(else_try),
				(eq, ":rand_sp", 1), (position_set_x, pos1, -3920), (position_set_y, pos1, 3060),
			(else_try),
				(eq, ":rand_sp", 2), (position_set_x, pos1, -5000), (position_set_y, pos1, 500),
			(else_try),
				(eq, ":rand_sp", 3), (position_set_x, pos1, -4437), (position_set_y, pos1, 2150),
			(else_try),
				(position_set_x, pos1, -3031), (position_set_y, pos1, 2322),
			(try_end),
		(else_try),
			(eq, ":bandit_template", "pt_mountain_bandits"),
			(try_begin),
				(eq, ":rand_sp", 0), (position_set_x, pos1, -8500), (position_set_y, pos1, -3500),
			(else_try),
				(eq, ":rand_sp", 1), (position_set_x, pos1, -7598), (position_set_y, pos1, -2169),
			(else_try),
				(eq, ":rand_sp", 2), (position_set_x, pos1, -8894), (position_set_y, pos1, -1212),
			(else_try),
				(eq, ":rand_sp", 3), (position_set_x, pos1, -9409), (position_set_y, pos1, -4108),
			(else_try),
				(position_set_x, pos1, -11000), (position_set_y, pos1, -1200),
			(try_end),
		(else_try),
			(eq, ":bandit_template", "pt_sea_raiders"),
			(try_begin),
				(eq, ":rand_sp", 0), (position_set_x, pos1, 3000), (position_set_y, pos1, 10500),
			(else_try),
				(eq, ":rand_sp", 1), (position_set_x, pos1, -6500), (position_set_y, pos1, 7000),
			(else_try),
				(eq, ":rand_sp", 2), (position_set_x, pos1, -4000), (position_set_y, pos1, 9000),
			(else_try),
				(eq, ":rand_sp", 3), (position_set_x, pos1, -6300), (position_set_y, pos1, 6200),
			(else_try),
				(position_set_x, pos1, 5500), (position_set_y, pos1, 12000),
			(try_end),
		(try_end),
		
		(party_set_position, ":new_camp", pos1),
		(party_template_set_slot, ":bandit_template", slot_party_template_lair_party, ":new_camp"),
		(party_set_flags, ":new_camp", pf_disabled, 1),
		(party_template_set_slot, ":bandit_template", slot_party_template_lair_next_spawn, 0),
	  (try_end),
	(try_end),
      ])
]
