# -*- coding: cp1254 -*-
from header_common import *
from header_operations import *
from module_constants import *
from header_parties import *
from header_skills import *
from header_mission_templates import *
from header_items import *
from header_triggers import *
from header_terrain_types import *
from header_music import *
from header_map_icons import *
from ID_animations import *

update_order_flags_on_map_scripts = [
# script_update_agent_position_on_map
# Input: none
# Output: none
("update_order_flags_on_map",
   [(set_fixed_point_multiplier, 1000),
    (get_player_agent_no, ":player_agent"),
    (agent_get_team, ":player_team", ":player_agent"),

    (get_scene_boundaries, pos2, pos3),

    (team_get_movement_order, ":cur_order", ":player_team", grc_infantry),
    (try_begin),
      (eq, "$group0_has_troops", 1),
      (eq, ":cur_order", mordr_hold),
      (team_get_order_position, pos1, ":player_team", grc_infantry),
      (call_script, "script_convert_3d_pos_to_map_pos"),
      (overlay_set_alpha, "$g_battle_map_infantry_order_flag", 0xFF),
      (overlay_set_position, "$g_battle_map_infantry_order_flag", pos0),
    (else_try),
      (overlay_set_alpha, "$g_battle_map_infantry_order_flag", 0),
    (try_end),
    (team_get_movement_order, ":cur_order", ":player_team", grc_archers),
    (try_begin),
      (eq, "$group1_has_troops", 1),
      (eq, ":cur_order", mordr_hold),
      (team_get_order_position, pos1, ":player_team", grc_archers),
      (call_script, "script_convert_3d_pos_to_map_pos"),
      (overlay_set_alpha, "$g_battle_map_archers_order_flag", 0xFF),
      (overlay_set_position, "$g_battle_map_archers_order_flag", pos0),
    (else_try),
      (overlay_set_alpha, "$g_battle_map_archers_order_flag", 0),
    (try_end),
    (team_get_movement_order, ":cur_order", ":player_team", grc_cavalry),
    (try_begin),
      (eq, "$group2_has_troops", 1),
      (eq, ":cur_order", mordr_hold),
      (team_get_order_position, pos1, ":player_team", grc_cavalry),
      (call_script, "script_convert_3d_pos_to_map_pos"),
      (overlay_set_alpha, "$g_battle_map_cavalry_order_flag", 0xFF),
      (overlay_set_position, "$g_battle_map_cavalry_order_flag", pos0),
    (else_try),
      (overlay_set_alpha, "$g_battle_map_cavalry_order_flag", 0),
    (try_end),
    (team_get_movement_order, ":cur_order", ":player_team", 3), ######
    (try_begin),
      (eq, "$group3_has_troops", 1),
      (eq, ":cur_order", mordr_hold),
      (team_get_order_position, pos1, ":player_team", 3),
      (call_script, "script_convert_3d_pos_to_map_pos"),
      (overlay_set_alpha, "$g_battle_map_spears_order_flag", 0xFF),
      (overlay_set_position, "$g_battle_map_spears_order_flag", pos0),
    (else_try),
      (overlay_set_alpha, "$g_battle_map_spears_order_flag", 0),
    (try_end),
    (team_get_movement_order, ":cur_order", ":player_team", 4),
    (try_begin),
      (eq, "$group4_has_troops", 1),
      (eq, ":cur_order", mordr_hold),
      (team_get_order_position, pos1, ":player_team", 4),
      (call_script, "script_convert_3d_pos_to_map_pos"),
      (overlay_set_alpha, "$g_battle_map_skirmishers_order_flag", 0xFF),
      (overlay_set_position, "$g_battle_map_skirmishers_order_flag", pos0),
    (else_try),
      (overlay_set_alpha, "$g_battle_map_skirmishers_order_flag", 0),
    (try_end),
    (team_get_movement_order, ":cur_order", ":player_team", 5),
    (try_begin),
      (eq, "$group5_has_troops", 1),
      (eq, ":cur_order", mordr_hold),
      (team_get_order_position, pos1, ":player_team", 5),
      (call_script, "script_convert_3d_pos_to_map_pos"),
      (overlay_set_alpha, "$g_battle_map_horsemen_order_flag", 0xFF),
      (overlay_set_position, "$g_battle_map_horsemen_order_flag", pos0),
    (else_try),
      (overlay_set_alpha, "$g_battle_map_horsemen_order_flag", 0),
    (try_end),
    (team_get_movement_order, ":cur_order", ":player_team", 6),
    (try_begin),
      (eq, "$group6_has_troops", 1),
      (eq, ":cur_order", mordr_hold),
      (team_get_order_position, pos1, ":player_team", 6),
      (call_script, "script_convert_3d_pos_to_map_pos"),
      (overlay_set_alpha, "$g_battle_map_d7_order_flag", 0xFF),
      (overlay_set_position, "$g_battle_map_d7_order_flag", pos0),
    (else_try),
      (overlay_set_alpha, "$g_battle_map_d7_order_flag", 0),
    (try_end),
    (team_get_movement_order, ":cur_order", ":player_team", 7),
    (try_begin),
      (eq, "$group7_has_troops", 1),
      (eq, ":cur_order", mordr_hold),
      (team_get_order_position, pos1, ":player_team", 7),
      (call_script, "script_convert_3d_pos_to_map_pos"),
      (overlay_set_alpha, "$g_battle_map_d8_order_flag", 0xFF),
      (overlay_set_position, "$g_battle_map_d8_order_flag", pos0),
    (else_try),
      (overlay_set_alpha, "$g_battle_map_d8_order_flag", 0),
    (try_end),
    (team_get_movement_order, ":cur_order", ":player_team", 8),
    (try_begin),
      (eq, "$group8_has_troops", 1),
      (eq, ":cur_order", mordr_hold),
      (team_get_order_position, pos1, ":player_team", 8),
      (call_script, "script_convert_3d_pos_to_map_pos"),
      (overlay_set_alpha, "$g_battle_map_d9_order_flag", 0xFF),
      (overlay_set_position, "$g_battle_map_d9_order_flag", pos0),
    (else_try),
      (overlay_set_alpha, "$g_battle_map_d9_order_flag", 0),
    (try_end),
  ])
]
