# -*- coding: cp1254 -*-
# package initializer for captivity menus

from game_menus.captivity.mnu_captivity_avoid_wilderness import captivity_avoid_wilderness_menu
from game_menus.captivity.mnu_captivity_start_wilderness import captivity_start_wilderness_menu
from game_menus.captivity.mnu_captivity_start_wilderness_surrender import captivity_start_wilderness_surrender_menu
from game_menus.captivity.mnu_captivity_start_wilderness_defeat import captivity_start_wilderness_defeat_menu
from game_menus.captivity.mnu_captivity_start_castle_surrender import captivity_start_castle_surrender_menu
from game_menus.captivity.mnu_captivity_start_castle_defeat import captivity_start_castle_defeat_menu
from game_menus.captivity.mnu_captivity_start_under_siege_defeat import captivity_start_under_siege_defeat_menu
from game_menus.captivity.mnu_captivity_wilderness_taken_prisoner import captivity_wilderness_taken_prisoner_menu
from game_menus.captivity.mnu_captivity_wilderness_check import captivity_wilderness_check_menu
from game_menus.captivity.mnu_captivity_end_wilderness_escape import captivity_end_wilderness_escape_menu
from game_menus.captivity.mnu_captivity_castle_taken_prisoner import captivity_castle_taken_prisoner_menu
from game_menus.captivity.mnu_captivity_rescue_lord_taken_prisoner import captivity_rescue_lord_taken_prisoner_menu
from game_menus.captivity.mnu_captivity_castle_check import captivity_castle_check_menu
from game_menus.captivity.mnu_captivity_end_exchanged_with_prisoner import captivity_end_exchanged_with_prisoner_menu
from game_menus.captivity.mnu_captivity_end_propose_ransom import captivity_end_propose_ransom_menu
from game_menus.captivity.mnu_captivity_castle_remain import captivity_castle_remain_menu
from game_menus.captivity.mnu_kingdom_army_quest_report_to_army import kingdom_army_quest_report_to_army_menu
from game_menus.captivity.mnu_kingdom_army_quest_messenger import kingdom_army_quest_messenger_menu

captivity_menus = []
captivity_menus.extend(captivity_avoid_wilderness_menu)
captivity_menus.extend(captivity_start_wilderness_menu)
captivity_menus.extend(captivity_start_wilderness_surrender_menu)
captivity_menus.extend(captivity_start_wilderness_defeat_menu)
captivity_menus.extend(captivity_start_castle_surrender_menu)
captivity_menus.extend(captivity_start_castle_defeat_menu)
captivity_menus.extend(captivity_start_under_siege_defeat_menu)
captivity_menus.extend(captivity_wilderness_taken_prisoner_menu)
captivity_menus.extend(captivity_wilderness_check_menu)
captivity_menus.extend(captivity_end_wilderness_escape_menu)
captivity_menus.extend(captivity_castle_taken_prisoner_menu)
captivity_menus.extend(captivity_rescue_lord_taken_prisoner_menu)
captivity_menus.extend(captivity_castle_check_menu)
captivity_menus.extend(captivity_end_exchanged_with_prisoner_menu)
captivity_menus.extend(captivity_end_propose_ransom_menu)
captivity_menus.extend(captivity_castle_remain_menu)
captivity_menus.extend(kingdom_army_quest_report_to_army_menu)
captivity_menus.extend(kingdom_army_quest_messenger_menu)

