# -*- coding: cp1254 -*-
from header_common import *
from header_operations import *
from module_constants import *
from header_parties import *
from header_skills import *
from header_mission_templates import *
from header_items import *
from header_triggers import *
from header_terrain_types import *
from header_music import *
from header_map_icons import *
from ID_animations import *

manage_inventory_scripts = [

  ("init_item_modifier_value_multiplier",
    [
      (item_set_slot, imod_plain, slot_item_modifier_multiplier, 100),
      (item_set_slot, imod_cracked, slot_item_modifier_multiplier, 50),
      (item_set_slot, imod_rusty, slot_item_modifier_multiplier, 55),
      (item_set_slot, imod_bent, slot_item_modifier_multiplier, 65),
      (item_set_slot, imod_chipped, slot_item_modifier_multiplier, 72),
      (item_set_slot, imod_battered, slot_item_modifier_multiplier, 75),
      (item_set_slot, imod_poor, slot_item_modifier_multiplier, 80),
      (item_set_slot, imod_crude, slot_item_modifier_multiplier, 83),
      (item_set_slot, imod_old, slot_item_modifier_multiplier, 86),
      (item_set_slot, imod_cheap, slot_item_modifier_multiplier, 90),
      (item_set_slot, imod_fine, slot_item_modifier_multiplier, 190),
      (item_set_slot, imod_well_made, slot_item_modifier_multiplier, 250),
      (item_set_slot, imod_sharp, slot_item_modifier_multiplier, 160),
      (item_set_slot, imod_balanced, slot_item_modifier_multiplier, 350),
      (item_set_slot, imod_tempered, slot_item_modifier_multiplier, 670),
      (item_set_slot, imod_deadly, slot_item_modifier_multiplier, 850),
      (item_set_slot, imod_exquisite, slot_item_modifier_multiplier, 1450),
      (item_set_slot, imod_masterwork, slot_item_modifier_multiplier, 1750),
      (item_set_slot, imod_heavy, slot_item_modifier_multiplier, 190),
      (item_set_slot, imod_strong, slot_item_modifier_multiplier, 490),
      (item_set_slot, imod_powerful, slot_item_modifier_multiplier, 320),
      (item_set_slot, imod_tattered, slot_item_modifier_multiplier, 50),
      (item_set_slot, imod_ragged, slot_item_modifier_multiplier, 70),
      (item_set_slot, imod_rough, slot_item_modifier_multiplier, 60),
      (item_set_slot, imod_sturdy, slot_item_modifier_multiplier, 170),
      (item_set_slot, imod_thick, slot_item_modifier_multiplier, 260),
      (item_set_slot, imod_hardened, slot_item_modifier_multiplier, 390),
      (item_set_slot, imod_reinforced, slot_item_modifier_multiplier, 650),
      (item_set_slot, imod_superb, slot_item_modifier_multiplier, 250),
      (item_set_slot, imod_lordly, slot_item_modifier_multiplier, 1150),
      (item_set_slot, imod_lame, slot_item_modifier_multiplier, 40),
      (item_set_slot, imod_swaybacked, slot_item_modifier_multiplier, 60),
      (item_set_slot, imod_stubborn, slot_item_modifier_multiplier, 90),
      (item_set_slot, imod_timid, slot_item_modifier_multiplier, 180),
      (item_set_slot, imod_meek, slot_item_modifier_multiplier, 180),
      (item_set_slot, imod_spirited, slot_item_modifier_multiplier, 650),
      (item_set_slot, imod_champion, slot_item_modifier_multiplier, 1450),
      (item_set_slot, imod_fresh, slot_item_modifier_multiplier, 100),
      (item_set_slot, imod_day_old, slot_item_modifier_multiplier, 100),
      (item_set_slot, imod_two_day_old, slot_item_modifier_multiplier, 90),
      (item_set_slot, imod_smelling, slot_item_modifier_multiplier, 40),
      (item_set_slot, imod_rotten, slot_item_modifier_multiplier, 5),
      (item_set_slot, imod_large_bag, slot_item_modifier_multiplier, 190),
    ]),

  ("get_item_value_with_imod",
    [
      (store_script_param, ":item", 1),
      (store_script_param, ":imod", 2),
      (try_begin),
        (gt, ":item", -1),
        (store_item_value, ":score", ":item"),
        (item_get_slot, ":imod_mult", ":imod", slot_item_modifier_multiplier),
        (val_mul, ":score", ":imod_mult"),
        (val_div, ":score", 100),
      (else_try),
        (assign, ":score", 0),
      (try_end),
      (assign, reg0, ":score"),
    ]),

  ("get_item_difficulty_with_imod",
    [
      (store_script_param, ":item", 1),
      (store_script_param, ":imod", 2),

      (item_get_type, ":type", ":item"),
      (item_get_difficulty, ":difficulty", ":item"),
      (try_begin),
        (eq, ":difficulty", 0),
      (else_try),
        (eq, ":type", itp_type_horse),
        (try_begin), 
          (eq, ":imod", imod_stubborn),
          (val_add, ":difficulty", 1),
        (else_try),
          (eq, ":imod", imod_champion),
          (val_add, ":difficulty", 2),
        (else_try),
          (eq, ":imod", imod_timid),
          (val_sub, ":difficulty", 1),
        (try_end),
      (else_try),
        (this_or_next|is_between, ":type", itp_type_one_handed_wpn, itp_type_goods),
        (is_between, ":type", itp_type_head_armor, itp_type_animal),
        (try_begin),
          (eq, ":imod", imod_heavy),
          (val_add, ":difficulty", 1),
        (else_try),
          (eq, ":imod", imod_strong),
          (val_add, ":difficulty", 2),
        (else_try),
          (eq, ":imod", imod_masterwork),
          (val_add, ":difficulty", 4),
        (try_end),
      (try_end),
      (assign, reg0, ":difficulty"),
    ]),

  ("troop_can_use_item",
    [
      (store_script_param, ":troop", 1),
      (store_script_param, ":item", 2),
      (store_script_param, ":imod", 3),

      (call_script, "script_get_item_difficulty_with_imod", ":item", ":imod"),
      (assign, ":difficulty", reg0),
      (item_get_type, ":type", ":item"),
      (try_begin),
        (eq, ":type", itp_type_horse),
        (store_skill_level, ":skill", skl_riding, ":troop"),
      (else_try),
        (this_or_next|eq, ":type", itp_type_head_armor),
        (this_or_next|eq, ":type", itp_type_body_armor),
        (this_or_next|eq, ":type", itp_type_foot_armor),
        (this_or_next|eq, ":type", itp_type_hand_armor),
        (this_or_next|eq, ":type", itp_type_one_handed_wpn),
        (this_or_next|eq, ":type", itp_type_two_handed_wpn),
        (this_or_next|eq, ":type", itp_type_polearm),
        (eq, ":type", itp_type_crossbow),
        (store_attribute_level, ":skill", ":troop", ca_strength),
      (else_try),
        (eq, ":type", itp_type_bow),
        (store_skill_level, ":skill", skl_power_draw, ":troop"),
      (else_try),
        (eq, ":type", itp_type_thrown),
        (store_skill_level, ":skill", skl_power_throw, ":troop"),
      (else_try),
        (eq, ":type", itp_type_shield),
        (store_skill_level, ":skill", skl_shield, ":troop"),
      (try_end),

      (try_begin),
        (lt, ":skill", ":difficulty"),
        (assign, reg0, 0),
      (else_try),
        (assign, reg0, 1),
      (try_end),
    ]),

  ("get_inventory_slot_type",
    [
      (store_script_param, ":slot_no", 1),

      (try_begin),
        (is_between, ":slot_no", 0, ek_head),
        (assign, ":slot_type", itp_type_one_handed_wpn),
      (else_try),
        (is_between, ":slot_no", ek_head, ek_horse),
        (store_sub, ":slot_type", ":slot_no", ek_head),
        (val_add, ":slot_type", itp_type_head_armor),
      (else_try),
        (eq, ":slot_no", 8),
        (assign, ":slot_type", itp_type_horse),
      (else_try),
        (assign, ":slot_type", -1),
      (try_end),
      (assign, reg0, ":slot_type"),
    ]),

  ("exchange_two_items_of_slots",
    [
      (store_script_param, ":old_slot", 1),
      (store_script_param, ":new_slot", 2),
      (store_script_param, ":selected_troop", 3),

      (try_begin),
        (ge, ":old_slot", 10),
        (troop_get_inventory_slot, ":old_item", "trp_player", ":old_slot"),
        (troop_get_inventory_slot_modifier, ":old_imod", "trp_player", ":old_slot"),
        (troop_inventory_slot_get_item_amount, ":old_amount", "trp_player", ":old_slot"),
      (else_try),
        (troop_get_inventory_slot, ":old_item", ":selected_troop", ":old_slot"),
        (troop_get_inventory_slot_modifier, ":old_imod", ":selected_troop", ":old_slot"),
        (troop_inventory_slot_get_item_amount, ":old_amount", ":selected_troop", ":old_slot"),
      (try_end),
      (try_begin),
        (ge, ":new_slot", 10),
        (troop_get_inventory_slot, ":new_item", "trp_player", ":new_slot"),
        (troop_get_inventory_slot_modifier, ":new_imod", "trp_player", ":new_slot"),
        (troop_inventory_slot_get_item_amount, ":new_amount", "trp_player", ":new_slot"),
      (else_try),
        (troop_get_inventory_slot, ":new_item", ":selected_troop", ":new_slot"),
        (troop_get_inventory_slot_modifier, ":new_imod", ":selected_troop", ":new_slot"),
        (troop_inventory_slot_get_item_amount, ":new_amount", ":selected_troop", ":new_slot"),
      (try_end),

      (try_begin),
        (ge, ":old_slot", 10),
        (assign, ":old_troop", "trp_player"),
      (else_try),
        (assign, ":old_troop", ":selected_troop"),
      (try_end),
      (try_begin),
        (ge, ":new_slot", 10),
        (assign, ":new_troop", "trp_player"),
      (else_try),
        (assign, ":new_troop", ":selected_troop"),
      (try_end),

      (troop_set_inventory_slot, ":new_troop", ":new_slot", ":old_item"),
      (troop_set_inventory_slot_modifier, ":new_troop", ":new_slot", ":old_imod"),
      (try_begin),
        (gt, ":old_amount", 0),
        (troop_inventory_slot_set_item_amount, ":new_troop", ":new_slot", ":old_amount"),
      (try_end),
      (try_begin),
        (eq, ":new_item", -1),
        (troop_set_inventory_slot, ":old_troop", ":old_slot", -1),
      (else_try),
        (troop_set_inventory_slot, ":old_troop", ":old_slot", ":new_item"),
        (troop_set_inventory_slot_modifier, ":old_troop", ":old_slot", ":new_imod"),
        (try_begin),
          (gt, ":new_amount", 0),
          (troop_inventory_slot_set_item_amount, ":old_troop", ":old_slot", ":new_amount"),
        (try_end),
      (try_end),
    ]),

  ("imod_effect_armor", 
    [
      (store_script_param, ":imod", 1),
      (assign, ":imod_effect", 0),
      (try_begin),
        (eq, ":imod", imod_cracked),
        (assign, ":imod_effect", -4),
      (else_try),
        (eq, ":imod", imod_rusty),
        (assign, ":imod_effect", -3),
      (else_try),
        (eq, ":imod", imod_battered),
        (assign, ":imod_effect", -2),
      (else_try),
        (eq, ":imod", imod_crude),
        (assign, ":imod_effect", -1),
      (else_try),
        (eq, ":imod", imod_heavy),
        (assign, ":imod_effect", 3),
      (else_try),
        (eq, ":imod", imod_tattered),
        (assign, ":imod_effect", -3),
      (else_try),
        (eq, ":imod", imod_ragged),
        (assign, ":imod_effect", -2),
      (else_try),
        (eq, ":imod", imod_sturdy),
        (assign, ":imod_effect", 1),
      (else_try),
        (eq, ":imod", imod_thick),
        (assign, ":imod_effect", 2),
      (else_try),
        (eq, ":imod", imod_hardened),
        (assign, ":imod_effect", 3),
      (else_try),
        (eq, ":imod", imod_reinforced),
        (assign, ":imod_effect", 4),
      (else_try),
        (eq, ":imod", imod_lordly),
        (assign, ":imod_effect", 6),
      (try_end),
      (assign, reg0, ":imod_effect"),
    ]),

  ("imod_effect_hp", 
    [
      (store_script_param, ":imod", 1),
      (assign, ":imod_effect", 0),
      (try_begin),
        (eq, ":imod", imod_cracked),
        (assign, ":imod_effect", -56),
      (else_try),
        (eq, ":imod", imod_battered),
        (assign, ":imod_effect", -26),
      (else_try),
        (eq, ":imod", imod_heavy),
        (assign, ":imod_effect", 10),
      (else_try),
        (eq, ":imod", imod_thick),
        (assign, ":imod_effect", 47),
      (else_try),
        (eq, ":imod", imod_reinforced),
        (assign, ":imod_effect", 83),
      (else_try),
        (eq, ":imod", imod_lordly),
        (assign, ":imod_effect", 155),
      (else_try),
        (eq, ":imod", imod_stubborn),
        (assign, ":imod_effect", 5),
      (try_end),
      (assign, reg0, ":imod_effect"),
    ]),

  ("imod_effect_damage", 
    [
      (store_script_param, ":imod", 1),
      (assign, ":imod_effect", 0),
      (try_begin),
        (eq, ":imod", imod_cracked),
        (assign, ":imod_effect", -5),
      (else_try),
        (eq, ":imod", imod_rusty),
        (assign, ":imod_effect", -3),
      (else_try),
        (eq, ":imod", imod_bent),
        (assign, ":imod_effect", -3),
      (else_try),
        (eq, ":imod", imod_chipped),
        (assign, ":imod_effect", -1),
      (else_try),
        (eq, ":imod", imod_crude),
        (assign, ":imod_effect", -2),
      (else_try),
        (eq, ":imod", imod_fine),
        (assign, ":imod_effect", 1),
      (else_try),
        (eq, ":imod", imod_balanced),
        (assign, ":imod_effect", 3),
      (else_try),
        (eq, ":imod", imod_tempered),
        (assign, ":imod_effect", 4),
      (else_try),
        (eq, ":imod", imod_masterwork),
        (assign, ":imod_effect", 5),
      (else_try),
        (eq, ":imod", imod_heavy),
        (assign, ":imod_effect", 2),
      (else_try),
        (eq, ":imod", imod_strong),
        (assign, ":imod_effect", 3),
      (try_end),
      (assign, reg0, ":imod_effect"),
    ]),

  ("imod_effect_speed", 
    [
      (store_script_param, ":imod", 1),
      (assign, ":imod_effect", 0),
      (try_begin),
        (eq, ":imod", imod_bent),
        (assign, ":imod_effect", -3),
      (else_try),
        (eq, ":imod", imod_balanced),
        (assign, ":imod_effect", 3),
      (else_try),
        (eq, ":imod", imod_masterwork),
        (assign, ":imod_effect", 1),
      (else_try),
        (eq, ":imod", imod_heavy),
        (assign, ":imod_effect", -2),
      (else_try),
        (eq, ":imod", imod_strong),
        (assign, ":imod_effect", -3),
      (try_end),
      (assign, reg0, ":imod_effect"),
    ]),

  ("imod_effect_horse_speed", 
    [
      (store_script_param, ":imod", 1),
      (assign, ":imod_effect", 0),
      (try_begin),
        (eq, ":imod", imod_lame),
        (assign, ":imod_effect", -10),
      (else_try),
        (eq, ":imod", imod_swaybacked),
        (assign, ":imod_effect", -4),
      (else_try),
        (eq, ":imod", imod_spirited),
        (assign, ":imod_effect", 2),
      (else_try),
        (eq, ":imod", imod_champion),
        (assign, ":imod_effect", 4),
      (try_end),
      (assign, reg0, ":imod_effect"),
    ]),

  ("imod_effect_horse_maneuver", 
    [
      (store_script_param, ":imod", 1),
      (assign, ":imod_effect", 0),
      (try_begin),
        (eq, ":imod", imod_lame),
        (assign, ":imod_effect", -5),
      (else_try),
        (eq, ":imod", imod_swaybacked),
        (assign, ":imod_effect", -2),
      (else_try),
        (eq, ":imod", imod_spirited),
        (assign, ":imod_effect", 1),
      (else_try),
        (eq, ":imod", imod_champion),
        (assign, ":imod_effect", 2),
      (try_end),
      (assign, reg0, ":imod_effect"),
    ]),

  ("imod_effect_horse_charge", 
    [
      (store_script_param, ":imod", 1),
      (assign, ":imod_effect", 0),
      (try_begin),
        (eq, ":imod", imod_heavy),
        (assign, ":imod_effect", 4),
      (else_try),
        (eq, ":imod", imod_spirited),
        (assign, ":imod_effect", 1),
      (else_try),
        (eq, ":imod", imod_champion),
        (assign, ":imod_effect", 2),
      (try_end),
      (assign, reg0, ":imod_effect"),
    ]),

  ("get_item_capability_with_imod",
    [
      (store_script_param, ":item", 1),
      (store_script_param, ":imod", 2),
      
      (item_get_type, ":type", ":item"),
      (assign, ":item_capability", 0),
      (try_begin),
        (eq,  ":type", itp_type_horse),
        (item_get_hit_points, ":horse_hp", ":item"),
        (item_get_body_armor, ":horse_armor", ":item"),
        (item_get_horse_speed, ":horse_speed", ":item"),
        (item_get_horse_maneuver, ":horse_maneuver", ":item"),
        (item_get_horse_charge_damage, ":horse_charge", ":item"),
        (try_begin),
          (gt, ":imod", 0),
          (try_begin),
            (gt, ":horse_hp", 0),
            (call_script, "script_imod_effect_hp", ":imod"),
            (val_add, ":horse_hp", reg0),
            (val_max, ":horse_hp", 0),
          (try_end),
          (try_begin),
            (gt, ":horse_armor", 0),
            (call_script, "script_imod_effect_armor", ":imod"),
            (val_add, ":horse_armor", reg0),
            (val_max, ":horse_armor", 0),
          (try_end),
          (try_begin),
            (gt, ":horse_speed", 0),
            (call_script, "script_imod_effect_horse_speed", ":imod"),
            (val_add, ":horse_speed", reg0),
            (val_max, ":horse_speed", 0),
          (try_end),
          (try_begin),
            (gt, ":horse_maneuver", 0),
            (call_script, "script_imod_effect_horse_maneuver", ":imod"),
            (val_add, ":horse_maneuver", reg0),
            (val_max, ":horse_maneuver", 0),
          (try_end),
          (try_begin),
            (gt, ":horse_charge", 0),
            (call_script, "script_imod_effect_horse_charge", ":imod"),
            (val_add, ":horse_charge", reg0),
            (val_max, ":horse_charge", 0),
          (try_end),
        (try_end),
        (try_begin),
          (eq, ":imod", imod_lame),
        (else_try),
          (val_add, ":item_capability", ":horse_hp"),
          (val_mul, ":horse_armor", 3),
          (val_add, ":item_capability", ":horse_armor"),
          (val_mul, ":horse_speed", 5),
          (val_add, ":item_capability", ":horse_speed"),
          (val_mul, ":horse_maneuver", 4),
          (val_add, ":item_capability", ":horse_maneuver"),
          (val_add, ":item_capability", ":horse_charge"),
        (try_end),

      (else_try),
        (is_between, ":type", itp_type_head_armor, itp_type_hand_armor+1),
        (item_get_head_armor, ":head_armor", ":item"),
        (item_get_body_armor, ":body_armor", ":item"),
        (item_get_leg_armor, ":leg_armor", ":item"),
        (try_begin),
          (gt, ":imod", 0),
          (call_script, "script_imod_effect_armor", ":imod"),
          (try_begin),
            (gt, ":head_armor", 0),
            (val_add, ":head_armor", reg0),
            (val_max, ":head_armor", 0),
          (try_end),
          (try_begin),
            (gt, ":body_armor", 0),
            (val_add, ":body_armor", reg0),
            (val_max, ":body_armor", 0),
          (try_end),
          (try_begin),
            (gt, ":leg_armor", 0),
            (val_add, ":leg_armor", reg0),
            (val_max, ":leg_armor", 0),
          (try_end),
        (try_end),
        (item_get_weight, ":weight", ":item"),
        (val_div, ":weight", 1000),
        (val_add, ":item_capability", ":head_armor"),
        (val_add, ":item_capability", ":body_armor"),
        (val_add, ":item_capability", ":leg_armor"),
        (val_mul, ":item_capability", 2),
        (val_sub, ":item_capability", ":weight"),

      (else_try),  
        (eq, ":type", itp_type_shield),
        (item_get_hit_points, ":shield_hp", ":item"),
        (item_get_body_armor, ":shield_armor", ":item"),
        (item_get_speed_rating, ":shield_speed", ":item"),
        (try_begin),
          (gt, ":imod", 0),
          (try_begin),
            (gt, ":shield_hp", 0),
            (call_script, "script_imod_effect_hp", ":imod"),
            (val_add, ":shield_hp", reg0),
            (val_max, ":shield_hp", 0),
          (try_end),
          (try_begin),
            (gt, ":shield_armor", 0),
            (call_script, "script_imod_effect_armor", ":imod"),
            (val_add, ":shield_armor", reg0),
            (val_max, ":shield_armor", 0),
          (try_end),
          (try_begin),
            (gt, ":shield_speed", 0),
            (call_script, "script_imod_effect_speed", ":imod"),
            (val_add, ":shield_speed", reg0),
            (val_max, ":shield_speed", 0),
          (try_end),
        (try_end),
        (set_fixed_point_multiplier, 1000),
        (item_get_shield_height, ":shield_height_to_bottom", ":item"),
        (val_div, ":shield_height_to_bottom", 10),
        (item_get_weapon_length, ":shield_half_width", ":item"),
        (store_add, ":shield_width", ":shield_half_width", ":shield_half_width"),
        (try_begin),
          (gt, ":shield_height_to_bottom", 0),
          (store_add, ":shield_height", ":shield_height_to_bottom", ":shield_half_width"),
        (else_try),
          (store_add, ":shield_height", ":shield_half_width", ":shield_half_width"),
        (try_end),
        (item_get_weight, ":weight", ":item"),
        (val_div, ":weight", 1000),
        (val_add, ":item_capability", ":shield_hp"),
        (val_mul, ":shield_armor", 20),
        (val_add, ":item_capability", ":shield_armor"),
        (val_add, ":item_capability", ":shield_speed"),
        (val_add, ":item_capability", ":shield_width"),
        (val_add, ":item_capability", ":shield_height"),
        (val_sub, ":item_capability", ":weight"),

      (else_try),
        (this_or_next|eq, ":type", itp_type_one_handed_wpn),
        (this_or_next|eq, ":type", itp_type_two_handed_wpn),
        (this_or_next|eq, ":type", itp_type_polearm),
        (this_or_next|eq, ":type", itp_type_bow),
        (this_or_next|eq, ":type", itp_type_crossbow),
        (this_or_next|eq, ":type", itp_type_pistol),
        (this_or_next|eq, ":type", itp_type_musket),
        (eq, ":type", itp_type_thrown),
        (item_get_swing_damage, ":swing_damage", ":item"),
        (item_get_swing_damage_type, ":swing_damage_type", ":item"),
        (item_get_thrust_damage, ":thrust_damage", ":item"),
        (item_get_thrust_damage_type, ":thrust_damage_type", ":item"),
        (item_get_speed_rating, ":item_speed", ":item"),
        (try_begin),
          (gt, ":imod", 0),
          (call_script, "script_imod_effect_damage", ":imod"),
          (try_begin),
            (gt, ":swing_damage", 0),
            (val_add, ":swing_damage", reg0),
            (val_max, ":swing_damage", 0),
          (try_end),
          (try_begin),
            (gt, ":thrust_damage", 0),
            (val_add, ":thrust_damage", reg0),
            (val_max, ":thrust_damage", 0),
          (try_end),
          (try_begin),
            (gt, ":item_speed", 0),
            (call_script, "script_imod_effect_speed", ":imod"),
            (val_add, ":item_speed", reg0),
            (val_max, ":item_speed", 0),
          (try_end),
        (try_end),
        (try_begin),
          (le, ":swing_damage", 0),
        (else_try),
          (eq, ":swing_damage_type", cut),
          (val_mul, ":swing_damage", 4),
        (else_try),
          (eq, ":swing_damage_type", pierce),
          (val_mul, ":swing_damage", 5),
        (else_try),
          (eq, ":swing_damage_type", blunt),
          (val_mul, ":swing_damage", 6),
        (try_end),
        (try_begin),
          (le, ":thrust_damage", 0),
        (else_try),
          (eq, ":thrust_damage_type", cut),
          (val_mul, ":thrust_damage", 4),
        (else_try),
          (eq, ":thrust_damage_type", pierce),
          (val_mul, ":thrust_damage", 5),
        (else_try),
          (eq, ":thrust_damage_type", blunt),
          (val_mul, ":thrust_damage", 6),
        (try_end),
        (assign, ":item_damage", ":swing_damage"),
        (val_max, ":item_damage", ":thrust_damage"),
        (item_get_weight, ":weight", ":item"),
        (val_div, ":weight", 1000),
        (try_begin),
          (this_or_next|eq, ":type", itp_type_bow),
          (this_or_next|eq, ":type", itp_type_crossbow),
          (this_or_next|eq, ":type", itp_type_pistol),
          (this_or_next|eq, ":type", itp_type_musket),
          (eq, ":type", itp_type_thrown),
          (item_get_missile_speed, ":missile_speed", ":item"),
          (val_mul, ":item_damage", 2),
          (val_add, ":item_capability", ":item_damage"),
          (val_add, ":item_capability", ":item_speed"),
          (val_add, ":item_capability", ":missile_speed"),
          (val_sub, ":item_capability", ":weight"),
          (try_begin),
            (eq, ":type", itp_type_thrown),
            (item_get_max_ammo, ":max_ammo", ":item"),
            (try_begin),
              (eq, ":imod", imod_large_bag),
              (val_add, ":max_ammo", 1),
            (try_end),
            (val_mul, ":max_ammo", 2),
            (val_add, ":item_capability", ":max_ammo"),
          (try_end),
        (else_try),
          (item_get_weapon_length, ":item_length", ":item"),
          (val_add, ":item_capability", ":item_damage"),
          (val_add, ":item_capability", ":item_speed"),
          (val_mul, ":item_length", 2),
          (val_add, ":item_capability", ":item_length"),
          (val_sub, ":item_capability", ":weight"),
        (try_end),

      (else_try),
        (this_or_next|eq, ":type", itp_type_arrows),
        (this_or_next|eq, ":type", itp_type_bolts),
        (eq, ":type", itp_type_bullets),
        (item_get_thrust_damage, ":thrust_damage", ":item"),
        (item_get_max_ammo, ":max_ammo", ":item"),
        (try_begin),
          (gt, ":imod", 0),
          (try_begin),
            (eq, ":imod", imod_large_bag),
            (val_add, ":max_ammo", 1),
          (else_try),
            (call_script, "script_imod_effect_damage", ":imod"),
            (val_add, ":thrust_damage", reg0),
          (try_end),
        (try_end),
        (val_add, ":item_capability", ":max_ammo"),
        (val_mul, ":thrust_damage", 2),
        (val_add, ":item_capability", ":thrust_damage"),
      (try_end),
      (assign, reg0, ":item_capability"),
    ]),

  ("cf_weapons_have_the_same_important_properties", 
    [
      (store_script_param, ":item_1", 1),
      (store_script_param, ":item_2", 2),
      (assign, ":item_1_has_property_1", 0),
      (assign, ":item_1_has_property_2", 0),
      (assign, ":item_1_has_property_3", 0),
      (assign, ":item_1_has_property_4", 0),
      (try_begin),
        (item_has_property, ":item_1", itp_cant_reload_on_horseback),
        (assign, ":item_1_has_property_1", 1),
      (try_end),
      (try_begin),
        (item_has_property, ":item_1", itp_two_handed),
        (assign, ":item_1_has_property_2", 1),
      (try_end),
      (try_begin),
        (item_has_property, ":item_1", itp_cant_use_on_horseback),
        (assign, ":item_1_has_property_3", 1),
      (try_end),
      (try_begin),
        (item_has_property, ":item_1", itp_couchable),
        (assign, ":item_1_has_property_4", 1),
      (try_end),
      (assign, ":item_2_has_property_1", 0),
      (assign, ":item_2_has_property_2", 0),
      (assign, ":item_2_has_property_3", 0),
      (assign, ":item_2_has_property_4", 0),
      (try_begin),
        (item_has_property, ":item_2", itp_cant_reload_on_horseback),
        (assign, ":item_2_has_property_1", 1),
      (try_end),
      (try_begin),
        (item_has_property, ":item_2", itp_two_handed),
        (assign, ":item_2_has_property_2", 1),
      (try_end),
      (try_begin),
        (item_has_property, ":item_2", itp_cant_use_on_horseback),
        (assign, ":item_2_has_property_3", 1),
      (try_end),
      (try_begin),
        (item_has_property, ":item_2", itp_couchable),
        (assign, ":item_2_has_property_4", 1),
      (try_end),
      (eq, ":item_1_has_property_1", ":item_2_has_property_1"),
      (eq, ":item_1_has_property_2", ":item_2_has_property_2"),
      (eq, ":item_1_has_property_3", ":item_2_has_property_3"),
      (eq, ":item_1_has_property_4", ":item_2_has_property_4"),
    ]),

  ("item_is_blunt_weapon", 
    [
      (store_script_param, ":item", 1),
      (assign, ":blunt_weapon", 0),
      (try_begin),
        (gt, ":item", -1),
        (item_get_type, ":type", ":item"),
        (try_begin),
          (this_or_next|is_between, ":type", itp_type_one_handed_wpn, itp_type_arrows),
          (this_or_next|is_between, ":type", itp_type_bow, itp_type_goods),
          (is_between, ":type", itp_type_pistol, itp_type_bullets),
          (item_get_swing_damage, ":swing_damage", ":item"),
          (try_begin),
            (gt, ":swing_damage", 0),
            (item_get_swing_damage_type, ":swing_damage_type", ":item"),
            (try_begin),
              (eq, ":swing_damage_type", blunt),
              (val_add, ":blunt_weapon", 1),
            (else_try),
              (val_sub, ":blunt_weapon", 1),
            (try_end),
          (try_end),
          (item_get_thrust_damage, ":thrust_damage", ":item"),
          (try_begin),
            (gt, ":thrust_damage", 0),
            (item_get_thrust_damage_type, ":thrust_damage_type", ":item"),
            (try_begin),
              (eq, ":thrust_damage_type", blunt),
              (val_add, ":blunt_weapon", 1),
            (else_try),
              (val_sub, ":blunt_weapon", 1),
            (try_end),
          (try_end),
          (val_clamp, ":blunt_weapon", 0, 2),
        (try_end),
      (try_end),
      (assign, reg0, ":blunt_weapon"),
    ]),

  ("sort_food",
    [
      (store_script_param, ":troop_no", 1),
      (troop_get_inventory_capacity, ":inv_cap", ":troop_no"),
      (try_for_range_backwards, ":i_slot", 10, ":inv_cap"),
        (troop_get_inventory_slot, ":item", ":troop_no", ":i_slot"),
        (troop_get_inventory_slot_modifier, ":imod", ":troop_no", ":i_slot"),
        (gt, ":item", -1),
        (is_between, ":item", food_begin, food_end),
        (try_for_range_backwards, ":i_slot_2", 10, ":i_slot"),
          (troop_get_inventory_slot, ":item_2", ":troop_no", ":i_slot_2"),
          (troop_get_inventory_slot_modifier, ":imod_2", ":troop_no", ":i_slot_2"),
          (gt, ":item_2", -1),
          (eq, ":item_2", ":item"),
          (eq, ":imod_2", ":imod"),
          (troop_inventory_slot_get_item_max_amount, ":max_amount", ":troop_no", ":i_slot"),
          (troop_inventory_slot_get_item_amount, ":item_amount", ":troop_no", ":i_slot"),
          (troop_inventory_slot_get_item_amount, ":item_amount_2", ":troop_no", ":i_slot_2"),
          (store_add, ":total_amount", ":item_amount", ":item_amount_2"),
          (store_sub, ":dest_amount_i_slot_2", ":total_amount", ":max_amount"),
          (try_begin),
            (gt, ":dest_amount_i_slot_2", 0),
            (troop_inventory_slot_set_item_amount, ":troop_no", ":i_slot", ":max_amount"),
            (troop_inventory_slot_set_item_amount, ":troop_no", ":i_slot_2", ":dest_amount_i_slot_2"),
            (assign, ":i_slot_2", 0),
          (else_try),
            (troop_inventory_slot_set_item_amount, ":troop_no", ":i_slot", ":total_amount"),
            (troop_set_inventory_slot, ":troop_no", ":i_slot_2", -1),
          (try_end),
        (try_end),
      (try_end),
    ]),

  ("new_order_of_item_types",
    [
      (troop_set_slot, "trp_temp_array_sort", 0, itp_type_book),
      (troop_set_slot, "trp_temp_array_sort", 1, itp_type_horse),
      (troop_set_slot, "trp_temp_array_sort", 2, itp_type_one_handed_wpn),
      (troop_set_slot, "trp_temp_array_sort", 3, itp_type_two_handed_wpn),
      (troop_set_slot, "trp_temp_array_sort", 4, itp_type_polearm),
      (troop_set_slot, "trp_temp_array_sort", 5, itp_type_bow),
      (troop_set_slot, "trp_temp_array_sort", 6, itp_type_arrows),
      (troop_set_slot, "trp_temp_array_sort", 7, itp_type_crossbow),
      (troop_set_slot, "trp_temp_array_sort", 8, itp_type_bolts),
      (troop_set_slot, "trp_temp_array_sort", 9, itp_type_thrown),
      (troop_set_slot, "trp_temp_array_sort", 10, itp_type_pistol),
      (troop_set_slot, "trp_temp_array_sort", 11, itp_type_musket),
      (troop_set_slot, "trp_temp_array_sort", 12, itp_type_bullets),
      (troop_set_slot, "trp_temp_array_sort", 13, itp_type_shield),
      (troop_set_slot, "trp_temp_array_sort", 14, itp_type_head_armor),
      (troop_set_slot, "trp_temp_array_sort", 15, itp_type_body_armor),
      (troop_set_slot, "trp_temp_array_sort", 16, itp_type_foot_armor),
      (troop_set_slot, "trp_temp_array_sort", 17, itp_type_hand_armor),
      (troop_set_slot, "trp_temp_array_sort", 18, itp_type_goods),
      (troop_set_slot, "trp_temp_array_sort", 19, itp_type_animal),
    ]),

  ("get_num_of_item_by_type",
    [
      (store_script_param_1, ":troop_no"),
      (store_script_param_2, ":item_type"),
      (assign, ":num_of_item", 0),
      (troop_get_inventory_capacity, ":inv_cap", ":troop_no"),
      (try_for_range, ":i_slot", 10, ":inv_cap"),
        (troop_get_inventory_slot, ":item", ":troop_no", ":i_slot"),
        (gt, ":item", -1),
        (item_get_type, ":type", ":item"),
        (eq, ":type", ":item_type"),
        (val_add, ":num_of_item", 1),
      (try_end),
      (assign, reg0, ":num_of_item"),
    ]),

  ("find_best_item_slot_of_type",
    [
      (store_script_param_1, ":troop_no"),
      (store_script_param_2, ":item_type"),
      (assign, ":best_item_slot", -1),
      (assign, ":best_item_id", -1),
      (assign, ":max_value", -1),
      (assign, ":max_value_with_imod", -1),
      (troop_get_inventory_capacity, ":inv_cap", ":troop_no"),
      (try_for_range, ":i_slot", 10, ":inv_cap"),
        (troop_get_inventory_slot, ":item", ":troop_no", ":i_slot"),
        (gt, ":item", -1),
        (item_get_type, ":type", ":item"),
        (eq, ":type", ":item_type"),
        (store_item_value, ":item_value", ":item"),
        (troop_get_inventory_slot_modifier, ":imod", ":troop_no", ":i_slot"),
        (call_script, "script_get_item_value_with_imod", ":item", ":imod"),
        (assign, ":item_value_with_imod", reg0),
        (try_begin),
          (gt, ":item_value", ":max_value"),
          (assign, ":best_item_slot", ":i_slot"),
          (assign, ":best_item_id", ":item"),
          (assign, ":max_value", ":item_value"),
          (assign, ":max_value_with_imod", ":item_value_with_imod"),
        (else_try),
          (eq, ":item_value", ":max_value"),
          (lt, ":item", ":best_item_id"),
          (assign, ":best_item_slot", ":i_slot"),
          (assign, ":best_item_id", ":item"),
          (assign, ":max_value", ":item_value"),
          (assign, ":max_value_with_imod", ":item_value_with_imod"),
        (else_try),
          (eq, ":item", ":best_item_id"),
          (gt, ":item_value_with_imod", ":max_value_with_imod"),
          (assign, ":best_item_slot", ":i_slot"),
          (assign, ":max_value_with_imod", ":item_value_with_imod"),
        (try_end),
      (try_end),
      (assign, reg0, ":best_item_slot"),
    ]),

  ("sort_player_inventory_by_item_type",
    [
      (troop_get_inventory_capacity, ":inv_cap", "trp_player"),
      (troop_clear_inventory, "trp_temp_array_sort"),
      (try_for_range, ":slot_no", 10, ":inv_cap"),
        (troop_slot_eq, "trp_temp_array_lock", ":slot_no", 0),
        (troop_get_inventory_slot, ":item", "trp_player", ":slot_no"),
        (gt, ":item", -1),
        (troop_set_inventory_slot, "trp_temp_array_sort", ":slot_no", ":item"),
        (troop_get_inventory_slot_modifier, ":item_mod", "trp_player", ":slot_no"),
        (troop_set_inventory_slot_modifier, "trp_temp_array_sort", ":slot_no", ":item_mod"),
        (troop_inventory_slot_get_item_amount, ":item_amount", "trp_player", ":slot_no"),
        (try_begin),
          (gt, ":item_amount", 0),
          (troop_inventory_slot_set_item_amount, "trp_temp_array_sort", ":slot_no", ":item_amount"),
        (try_end),
        (troop_set_inventory_slot, "trp_player", ":slot_no", -1),
      (try_end),
      (call_script, "script_sort_food", "trp_temp_array_sort"),
      (assign, ":cur_item_slot", 10),
      (call_script, "script_new_order_of_item_types"),
      (try_for_range, ":slot_no", 0, 20),
        (troop_get_slot, ":item_type", "trp_temp_array_sort", ":slot_no"),
        (call_script, "script_get_num_of_item_by_type", "trp_temp_array_sort", ":item_type"),
        (assign, ":num_of_item", reg0),
        (gt, ":num_of_item", 0),
        (try_for_range, ":unused", 0, ":num_of_item"),
          (call_script, "script_find_best_item_slot_of_type", "trp_temp_array_sort", ":item_type"),
          (assign, ":best_item_slot", reg0),
          (gt, ":best_item_slot", -1),
          (troop_get_inventory_slot, ":item", "trp_temp_array_sort", ":best_item_slot"),
          (troop_get_inventory_slot_modifier, ":imod", "trp_temp_array_sort", ":best_item_slot"),
          (troop_inventory_slot_get_item_amount, ":amount", "trp_temp_array_sort", ":best_item_slot"),
          (troop_set_inventory_slot, "trp_temp_array_sort", ":best_item_slot", -1),
          (assign, ":upper_bound", ":inv_cap"),
          (assign, ":lower_bound", ":cur_item_slot"),
          (try_for_range, ":cur_slot_no", ":lower_bound", ":upper_bound"),
            (troop_slot_eq, "trp_temp_array_lock", ":cur_slot_no", 0),
            (troop_set_inventory_slot, "trp_player", ":cur_slot_no", ":item"),
            (troop_set_inventory_slot_modifier, "trp_player", ":cur_slot_no", ":imod"),
            (try_begin),
              (gt, ":amount", 0),
              (troop_inventory_slot_set_item_amount, "trp_player", ":cur_slot_no", ":amount"),
            (try_end),
            (assign, ":cur_item_slot", ":cur_slot_no"),
            (val_add, ":cur_item_slot", 1),
            (assign, ":upper_bound", 0),
          (try_end),
        (try_end),
      (try_end),
    ]),

  ("upgrade_armors_and_horse_for_troop",
    [
      (store_script_param, ":troop", 1),
      (try_for_range, ":ek_slot", ek_head, ek_horse+1),
        (troop_slot_eq, "trp_temp_array_lock", ":ek_slot", 0),
        (try_begin),
          (is_between, ":ek_slot", ek_head, ek_horse),
          (store_sub, ":dest_type", ":ek_slot", ek_head),
          (val_add, ":dest_type", itp_type_head_armor),
        (else_try),
          (eq, ":ek_slot", ek_horse),
          (assign, ":dest_type", itp_type_horse),
        (try_end),
        (assign, ":best_slot", ":ek_slot"),
        (assign, ":best_val", 0),
        (troop_get_inventory_slot, ":troop_item", ":troop", ":ek_slot"),
        (try_begin),
          (gt, ":troop_item", -1),
          (troop_get_inventory_slot_modifier, ":troop_imod", ":troop", ":ek_slot"),
          (call_script, "script_get_item_capability_with_imod", ":troop_item", ":troop_imod"),
          (assign, ":best_val", reg0),
        (try_end),
        (troop_get_inventory_capacity, ":inv_cap", "trp_player"),
        (try_for_range, ":i_slot", 10, ":inv_cap"),
          (troop_slot_eq, "trp_temp_array_lock", ":i_slot", 0),
          (troop_get_inventory_slot, ":item", "trp_player", ":i_slot"),
          (gt, ":item", -1),
          (item_get_type, ":i_type", ":item"),
          (eq, ":i_type", ":dest_type"),
          (troop_get_inventory_slot_modifier, ":imod", "trp_player", ":i_slot"),
          (call_script, "script_troop_can_use_item", ":troop", ":item", ":imod"),
          (eq, reg0, 1),
          (call_script, "script_get_item_capability_with_imod", ":item", ":imod"),
          (assign, ":item_capability", reg0),
          (gt, ":item_capability", ":best_val"),
          (assign, ":best_slot", ":i_slot"),
          (assign, ":best_val", ":item_capability"),
        (try_end),
        (ge, ":best_slot", 10),
        (troop_get_inventory_slot, ":best_item", "trp_player", ":best_slot"),
        (troop_get_inventory_slot_modifier, ":best_imod", "trp_player", ":best_slot"),
        (troop_set_inventory_slot, ":troop", ":ek_slot", ":best_item"),
        (troop_set_inventory_slot_modifier, ":troop", ":ek_slot", ":best_imod"),
        (try_begin),
          (gt, ":troop_item", -1),
          (troop_set_inventory_slot, "trp_player", ":best_slot", ":troop_item"),
          (troop_set_inventory_slot_modifier, "trp_player", ":best_slot", ":troop_imod"),
        (else_try),
          (troop_set_inventory_slot, "trp_player", ":best_slot", -1),
        (try_end),
      (try_end),
    ]),

  ("upgrade_weapons_for_troop",
    [
      (store_script_param, ":troop", 1),
      (try_for_range, ":ek_slot", ek_item_0, ek_item_3+1),
        (troop_slot_eq, "trp_temp_array_lock", ":ek_slot", 0),
        (troop_get_inventory_slot, ":troop_item", ":troop", ":ek_slot"),
        (gt, ":troop_item", -1),
        (item_get_type, ":dest_type", ":troop_item"),
        (assign, ":best_slot", ":ek_slot"),
        (assign, ":best_val", 0),
        (troop_get_inventory_slot_modifier, ":troop_imod", ":troop", ":ek_slot"),
        (call_script, "script_get_item_capability_with_imod", ":troop_item", ":troop_imod"),
        (assign, ":best_val", reg0),
        (call_script, "script_item_is_blunt_weapon", ":troop_item"),
        (assign, ":troop_item_is_blunt_weapon", reg0),
        (troop_get_inventory_capacity, ":inv_cap", "trp_player"),
        (try_for_range, ":i_slot", 10, ":inv_cap"),
          (troop_slot_eq, "trp_temp_array_lock", ":i_slot", 0),
          (troop_get_inventory_slot, ":item", "trp_player", ":i_slot"),
          (gt, ":item", -1),
          (item_get_type, ":i_type", ":item"),
          (eq, ":i_type", ":dest_type"),
          (call_script, "script_cf_weapons_have_the_same_important_properties", ":troop_item", ":item"),
          (call_script, "script_item_is_blunt_weapon", ":item"),
          (assign, ":item_is_blunt_weapon", reg0),
          (eq, ":item_is_blunt_weapon", ":troop_item_is_blunt_weapon"),
          (troop_get_inventory_slot_modifier, ":imod", "trp_player", ":i_slot"),
          (call_script, "script_troop_can_use_item", ":troop", ":item", ":imod"),
          (eq, reg0, 1),
          (call_script, "script_get_item_capability_with_imod", ":item", ":imod"),
          (assign, ":item_capability", reg0),
          (gt, ":item_capability", ":best_val"),
          (assign, ":best_slot", ":i_slot"),
          (assign, ":best_val", ":item_capability"),
        (try_end),
        (ge, ":best_slot", 10),
        (troop_get_inventory_slot, ":best_item", "trp_player", ":best_slot"),
        (troop_get_inventory_slot_modifier, ":best_imod", "trp_player", ":best_slot"),
        (troop_set_inventory_slot, ":troop", ":ek_slot", ":best_item"),
        (troop_set_inventory_slot_modifier, ":troop", ":ek_slot", ":best_imod"),
        (troop_set_inventory_slot, "trp_player", ":best_slot", ":troop_item"),
        (troop_set_inventory_slot_modifier, "trp_player", ":best_slot", ":troop_imod"),
      (try_end),
    ]),
]
