# -*- coding: cp1254 -*-
from header_common import *
from header_operations import *
from module_constants import *
from module_constants import *
from header_parties import *
from header_skills import *
from header_mission_templates import *
from header_items import *
from header_triggers import *
from header_terrain_types import *
from header_music import *
from header_map_icons import *
from ID_animations import *

####################################################################################################################
# ARENA & TOURNAMENT SCRIPTS
# 
# This file handles the logic for tournaments, arena fights, and bets.
# It manages participants, bracket setups, and prize assignments.
####################################################################################################################

arena_scripts = [
("initialize_town_arena_info",
    [
      (try_for_range, ":town_no", towns_begin, towns_end),
        (party_set_slot, ":town_no", slot_town_tournament_max_teams, 4),
        (party_set_slot, ":town_no", slot_town_tournament_max_team_size, 8),
      (try_end),
      (party_set_slot, "p_town_6", slot_town_tournament_max_team_size, 2),

      (party_set_slot,"p_town_1", slot_town_arena_melee_1_num_teams,   2),
      (party_set_slot,"p_town_1", slot_town_arena_melee_1_team_size,   1),
      (party_set_slot,"p_town_1", slot_town_arena_melee_2_num_teams,   4),
      (party_set_slot,"p_town_1", slot_town_arena_melee_2_team_size,   1),
      (party_set_slot,"p_town_1", slot_town_arena_melee_3_num_teams,   4),
      (party_set_slot,"p_town_1", slot_town_arena_melee_3_team_size,   1),

      (party_set_slot,"p_town_2", slot_town_arena_melee_1_num_teams,   4),
      (party_set_slot,"p_town_2", slot_town_arena_melee_1_team_size,   4),
      (party_set_slot,"p_town_2", slot_town_arena_melee_2_num_teams,   4),
      (party_set_slot,"p_town_2", slot_town_arena_melee_2_team_size,   6),
      (party_set_slot,"p_town_2", slot_town_arena_melee_3_num_teams,   4),
      (party_set_slot,"p_town_2", slot_town_arena_melee_3_team_size,   8),

      (party_set_slot,"p_town_3", slot_town_arena_melee_1_num_teams,   2),
      (party_set_slot,"p_town_3", slot_town_arena_melee_1_team_size,   8),
      (party_set_slot,"p_town_3", slot_town_arena_melee_2_num_teams,   2),
      (party_set_slot,"p_town_3", slot_town_arena_melee_2_team_size,   8),
      (party_set_slot,"p_town_3", slot_town_arena_melee_3_num_teams,   2),
      (party_set_slot,"p_town_3", slot_town_arena_melee_3_team_size,   8),

      (party_set_slot,"p_town_4", slot_town_arena_melee_1_num_teams,   2),
      (party_set_slot,"p_town_4", slot_town_arena_melee_1_team_size,   8),
      (party_set_slot,"p_town_4", slot_town_arena_melee_2_num_teams,   3),
      (party_set_slot,"p_town_4", slot_town_arena_melee_2_team_size,   8),
      (party_set_slot,"p_town_4", slot_town_arena_melee_3_num_teams,   2),
      (party_set_slot,"p_town_4", slot_town_arena_melee_3_team_size,   5),

      (party_set_slot,"p_town_5", slot_town_arena_melee_1_num_teams,   2),
      (party_set_slot,"p_town_5", slot_town_arena_melee_1_team_size,   3),
      (party_set_slot,"p_town_5", slot_town_arena_melee_2_num_teams,   2),
      (party_set_slot,"p_town_5", slot_town_arena_melee_2_team_size,   5),
      (party_set_slot,"p_town_5", slot_town_arena_melee_3_num_teams,   2),
      (party_set_slot,"p_town_5", slot_town_arena_melee_3_team_size,   8),

      (party_set_slot,"p_town_6", slot_town_arena_melee_1_num_teams,   2),
      (party_set_slot,"p_town_6", slot_town_arena_melee_1_team_size,   4),
      (party_set_slot,"p_town_6", slot_town_arena_melee_2_num_teams,   3),
      (party_set_slot,"p_town_6", slot_town_arena_melee_2_team_size,   4),
      (party_set_slot,"p_town_6", slot_town_arena_melee_3_num_teams,   3),
      (party_set_slot,"p_town_6", slot_town_arena_melee_3_team_size,   6),

      (party_set_slot,"p_town_7", slot_town_arena_melee_1_num_teams,   4),
      (party_set_slot,"p_town_7", slot_town_arena_melee_1_team_size,   4),
      (party_set_slot,"p_town_7", slot_town_arena_melee_2_num_teams,   4),
      (party_set_slot,"p_town_7", slot_town_arena_melee_2_team_size,   6),
      (party_set_slot,"p_town_7", slot_town_arena_melee_3_num_teams,   4),
      (party_set_slot,"p_town_7", slot_town_arena_melee_3_team_size,   8),

      (party_set_slot,"p_town_8", slot_town_arena_melee_1_num_teams,   3),
      (party_set_slot,"p_town_8", slot_town_arena_melee_1_team_size,   1),
      (party_set_slot,"p_town_8", slot_town_arena_melee_2_num_teams,   3),
      (party_set_slot,"p_town_8", slot_town_arena_melee_2_team_size,   3),
      (party_set_slot,"p_town_8", slot_town_arena_melee_3_num_teams,   3),
      (party_set_slot,"p_town_8", slot_town_arena_melee_3_team_size,   7),

      (party_set_slot,"p_town_9", slot_town_arena_melee_1_num_teams,   2),
      (party_set_slot,"p_town_9", slot_town_arena_melee_1_team_size,   2),
      (party_set_slot,"p_town_9", slot_town_arena_melee_2_num_teams,   2),
      (party_set_slot,"p_town_9", slot_town_arena_melee_2_team_size,   5),
      (party_set_slot,"p_town_9", slot_town_arena_melee_3_num_teams,   2),
      (party_set_slot,"p_town_9", slot_town_arena_melee_3_team_size,   8),

      (party_set_slot,"p_town_10", slot_town_arena_melee_1_num_teams,   2),
      (party_set_slot,"p_town_10", slot_town_arena_melee_1_team_size,   3),
      (party_set_slot,"p_town_10", slot_town_arena_melee_2_num_teams,   2),
      (party_set_slot,"p_town_10", slot_town_arena_melee_2_team_size,   5),
      (party_set_slot,"p_town_10", slot_town_arena_melee_3_num_teams,   2),
      (party_set_slot,"p_town_10", slot_town_arena_melee_3_team_size,   8),

      (party_set_slot,"p_town_11", slot_town_arena_melee_1_num_teams,   2),
      (party_set_slot,"p_town_11", slot_town_arena_melee_1_team_size,   8),
      (party_set_slot,"p_town_11", slot_town_arena_melee_2_num_teams,   3),
      (party_set_slot,"p_town_11", slot_town_arena_melee_2_team_size,   4),
      (party_set_slot,"p_town_11", slot_town_arena_melee_3_num_teams,   3),
      (party_set_slot,"p_town_11", slot_town_arena_melee_3_team_size,   6),

      (party_set_slot,"p_town_12", slot_town_arena_melee_1_num_teams,   3),
      (party_set_slot,"p_town_12", slot_town_arena_melee_1_team_size,   8),
      (party_set_slot,"p_town_12", slot_town_arena_melee_2_num_teams,   4),
      (party_set_slot,"p_town_12", slot_town_arena_melee_2_team_size,   6),
      (party_set_slot,"p_town_12", slot_town_arena_melee_3_num_teams,   4),
      (party_set_slot,"p_town_12", slot_town_arena_melee_3_team_size,   5),

      (party_set_slot,"p_town_13", slot_town_arena_melee_1_num_teams,   2),
      (party_set_slot,"p_town_13", slot_town_arena_melee_1_team_size,   8),
      (party_set_slot,"p_town_13", slot_town_arena_melee_2_num_teams,   4),
      (party_set_slot,"p_town_13", slot_town_arena_melee_2_team_size,   5),
      (party_set_slot,"p_town_13", slot_town_arena_melee_3_num_teams,   4),
      (party_set_slot,"p_town_13", slot_town_arena_melee_3_team_size,   7),

      (party_set_slot,"p_town_14", slot_town_arena_melee_1_num_teams,   2),
      (party_set_slot,"p_town_14", slot_town_arena_melee_1_team_size,   4),
      (party_set_slot,"p_town_14", slot_town_arena_melee_2_num_teams,   2),
      (party_set_slot,"p_town_14", slot_town_arena_melee_2_team_size,   5),
      (party_set_slot,"p_town_14", slot_town_arena_melee_3_num_teams,   2),
      (party_set_slot,"p_town_14", slot_town_arena_melee_3_team_size,   6),

      (party_set_slot,"p_town_15", slot_town_arena_melee_1_num_teams,   2),
      (party_set_slot,"p_town_15", slot_town_arena_melee_1_team_size,   8),
      (party_set_slot,"p_town_15", slot_town_arena_melee_2_num_teams,   3),
      (party_set_slot,"p_town_15", slot_town_arena_melee_2_team_size,   4),
      (party_set_slot,"p_town_15", slot_town_arena_melee_3_num_teams,   3),
      (party_set_slot,"p_town_15", slot_town_arena_melee_3_team_size,   6),

      (party_set_slot,"p_town_16", slot_town_arena_melee_1_num_teams,   3),
      (party_set_slot,"p_town_16", slot_town_arena_melee_1_team_size,   8),
      (party_set_slot,"p_town_16", slot_town_arena_melee_2_num_teams,   4),
      (party_set_slot,"p_town_16", slot_town_arena_melee_2_team_size,   6),
      (party_set_slot,"p_town_16", slot_town_arena_melee_3_num_teams,   4),
      (party_set_slot,"p_town_16", slot_town_arena_melee_3_team_size,   5),

      (party_set_slot,"p_town_17", slot_town_arena_melee_1_num_teams,   2),
      (party_set_slot,"p_town_17", slot_town_arena_melee_1_team_size,   8),
      (party_set_slot,"p_town_17", slot_town_arena_melee_2_num_teams,   4),
      (party_set_slot,"p_town_17", slot_town_arena_melee_2_team_size,   5),
      (party_set_slot,"p_town_17", slot_town_arena_melee_3_num_teams,   4),
      (party_set_slot,"p_town_17", slot_town_arena_melee_3_team_size,   7),

      (party_set_slot,"p_town_18", slot_town_arena_melee_1_num_teams,   2),
      (party_set_slot,"p_town_18", slot_town_arena_melee_1_team_size,   4),
      (party_set_slot,"p_town_18", slot_town_arena_melee_2_num_teams,   2),
      (party_set_slot,"p_town_18", slot_town_arena_melee_2_team_size,   5),
      (party_set_slot,"p_town_18", slot_town_arena_melee_3_num_teams,   2),
      (party_set_slot,"p_town_18", slot_town_arena_melee_3_team_size,   6),

      (party_set_slot,"p_town_19", slot_town_arena_melee_1_num_teams,   2),
      (party_set_slot,"p_town_19", slot_town_arena_melee_1_team_size,   8),
      (party_set_slot,"p_town_19", slot_town_arena_melee_2_num_teams,   4),
      (party_set_slot,"p_town_19", slot_town_arena_melee_2_team_size,   4),
      (party_set_slot,"p_town_19", slot_town_arena_melee_3_num_teams,   4),
      (party_set_slot,"p_town_19", slot_town_arena_melee_3_team_size,   6),

      (party_set_slot,"p_town_20", slot_town_arena_melee_1_num_teams,   4),
      (party_set_slot,"p_town_20", slot_town_arena_melee_1_team_size,   2),
      (party_set_slot,"p_town_20", slot_town_arena_melee_2_num_teams,   4),
      (party_set_slot,"p_town_20", slot_town_arena_melee_2_team_size,   4),
      (party_set_slot,"p_town_20", slot_town_arena_melee_3_num_teams,   4),
      (party_set_slot,"p_town_20", slot_town_arena_melee_3_team_size,   6),

      (party_set_slot,"p_town_21", slot_town_arena_melee_1_num_teams,   3),
      (party_set_slot,"p_town_21", slot_town_arena_melee_1_team_size,   3),
      (party_set_slot,"p_town_21", slot_town_arena_melee_2_num_teams,   2),
      (party_set_slot,"p_town_21", slot_town_arena_melee_2_team_size,   6),
      (party_set_slot,"p_town_21", slot_town_arena_melee_3_num_teams,   2),
      (party_set_slot,"p_town_21", slot_town_arena_melee_3_team_size,   8),

      (party_set_slot,"p_town_22", slot_town_arena_melee_1_num_teams,   4),
      (party_set_slot,"p_town_22", slot_town_arena_melee_1_team_size,   3),
      (party_set_slot,"p_town_22", slot_town_arena_melee_2_num_teams,   3),
      (party_set_slot,"p_town_22", slot_town_arena_melee_2_team_size,   4),
      (party_set_slot,"p_town_22", slot_town_arena_melee_3_num_teams,   2),
      (party_set_slot,"p_town_22", slot_town_arena_melee_3_team_size,   6),

      (party_set_slot,"p_town_23", slot_town_arena_melee_1_num_teams,   2),
      (party_set_slot,"p_town_23", slot_town_arena_melee_1_team_size,   8),
      (party_set_slot,"p_town_23", slot_town_arena_melee_2_num_teams,   3),
      (party_set_slot,"p_town_23", slot_town_arena_melee_2_team_size,   4),
      (party_set_slot,"p_town_23", slot_town_arena_melee_3_num_teams,   3),
      (party_set_slot,"p_town_23", slot_town_arena_melee_3_team_size,   6),
	]),

	  # Input: arg1 = center_no, arg2 = player_at_center
  # Output: none (fills trp_tournament_participants)
  ("fill_tournament_participants_troop",
   [
    (store_script_param, ":center_no", 1),
    (store_script_param, ":player_at_center", 2),
    (assign, ":cur_slot", 0),

      (try_begin),
        (eq, ":player_at_center", 1),
        (troop_set_slot, "trp_tournament_participants", 0, "trp_player"), #we add the player
        (val_add, ":cur_slot", 1),
        (party_get_num_companion_stacks, ":num_stacks", "p_main_party"),
        (try_begin), #add adventuring spouse
          (troop_get_slot, ":spouse", "trp_player", slot_troop_spouse),
          (ge, ":spouse", active_npcs_begin),
          (main_party_has_troop, ":spouse"),
          (neg|troop_is_wounded, ":spouse"),
          (troop_set_slot, "trp_tournament_participants", ":cur_slot", ":spouse"),
          (val_add, ":cur_slot", 1),
        (try_end),
        #SB : add in companions
        (try_for_range, ":companion_candidate", companions_begin, companions_end),

          (assign, ":continue", 0),
          (try_begin), #player pays entrance fee
            (main_party_has_troop, ":companion_candidate"),
            (assign, ":continue", 1),
          (else_try), #same conditions as below
            (troop_slot_eq, ":companion_candidate", slot_troop_cur_center, ":center_no"),
            (troop_slot_ge, ":companion_candidate", slot_troop_renown, 100),
            (assign, ":continue", 1),
          (try_end),

          (try_begin), #disqualify from health/imprisonment
            (this_or_next|troop_is_wounded, ":companion_candidate"),
            (troop_slot_ge, ":companion_candidate", slot_troop_prisoner_of_party, centers_begin),
            (assign, ":continue", 0),
          (try_end),
          (eq, ":continue", 1),

          (troop_set_slot, "trp_tournament_participants", ":cur_slot", ":companion_candidate"),
          # (call_script, "script_join_tournament", ":companion_candidate"),
          (val_add, ":cur_slot", 1),
        (try_end),

       # (try_for_range, ":stack_no", 0, ":num_stacks"),
         # (party_stack_get_troop_id, ":cur_troop", "p_main_party", ":stack_no"),
         # (troop_is_hero, ":cur_troop"),
         # (neq, ":cur_troop", "trp_kidnapped_girl"),
         # (troop_set_slot, "trp_tournament_participants", ":cur_slot", ":cur_troop"),
         # (val_add, ":cur_slot", 1),
       # (try_end),
      (else_try), #noble companions with starting renown > 100 can participate
        (eq, ":player_at_center", 0),
        (try_for_range, ":companion_candidate", companions_begin, companions_end),
          #this is handled by having their parties be in town
          (neg|troop_slot_eq, ":companion_candidate", slot_troop_occupation, slto_kingdom_hero),
          (troop_slot_eq, ":companion_candidate", slot_troop_cur_center, ":center_no"),
          (troop_slot_ge, ":companion_candidate", slot_troop_renown, 100), #rofl, alayen, etc
          (troop_set_slot, "trp_tournament_participants", ":cur_slot", ":companion_candidate"),
          (val_add, ":cur_slot", 1),
        (try_end),

      (try_end),

     #SB : add in pretender who would want renown bonus
    (try_begin),
      (is_between, "$supported_pretender", pretenders_begin, pretenders_end),
      (eq, ":player_at_center", 1),
      (main_party_has_troop, "$supported_pretender"),
      (troop_set_slot, "trp_tournament_participants", ":cur_slot", "$supported_pretender"),
      (val_add, ":cur_slot", 1),
    (try_end),
    (try_for_range, ":pretender", pretenders_begin, pretenders_end),
      # (neq, ":pretender", "$supported_pretender"),
      # (ge, "$g_dplmc_ai_changes", DPLMC_AI_CHANGES_LOW),
      (troop_slot_eq, ":pretender", slot_troop_cur_center, ":center_no"),
      (troop_set_slot, "trp_tournament_participants", ":cur_slot", ":pretender"),
      (val_add, ":cur_slot", 1),
    (try_end),
    (party_collect_attachments_to_party, ":center_no", "p_temp_party"),
    (party_get_num_companion_stacks, ":num_stacks", "p_temp_party"),
    (try_for_range, ":stack_no", 0, ":num_stacks"),
      (party_stack_get_troop_id, ":cur_troop", "p_temp_party", ":stack_no"),
      (troop_is_hero, ":cur_troop"),
      (troop_set_slot, "trp_tournament_participants", ":cur_slot", ":cur_troop"),
      (val_add, ":cur_slot", 1),
    (try_end),

     # (try_begin),
       # (store_random_in_range, ":random_no", 0, 100),
       # (lt, ":random_no", 50),
       # (troop_set_slot, "trp_tournament_participants", ":cur_slot", "trp_xerina"),
       # (val_add, ":cur_slot", 1),
     # (try_end),
     # (try_begin),
       # (store_random_in_range, ":random_no", 0, 100),
       # (lt, ":random_no", 50),
       # (troop_set_slot, "trp_tournament_participants", ":cur_slot", "trp_dranton"),
       # (val_add, ":cur_slot", 1),
     # (try_end),
     # (try_begin),
       # (store_random_in_range, ":random_no", 0, 100),
       # (lt, ":random_no", 50),
       # (troop_set_slot, "trp_tournament_participants", ":cur_slot", "trp_kradus"),
       # (val_add, ":cur_slot", 1),
     # (try_end),
    #SB : recalculate chances
    (store_add, ":heroes_limit", ":cur_slot", 5),
    (val_min, ":heroes_limit", 64),
    (try_for_range, ":hero", tournament_champions_begin, tournament_champions_end),
        # (neg|troop_is_wounded, ":hero"),
        (store_troop_health, ":health", ":hero", 0),
        (gt, ":health", 10),
        (store_random_in_range, ":random_no", 0, 6),
        (troop_set_slot, ":hero", slot_troop_cur_center, -1),
        (troop_set_slot, ":hero", slot_lady_used_tournament, -1),

        (try_begin),
            (lt, ":random_no", 2),
            (lt, ":cur_slot", ":heroes_limit"),
            (troop_set_slot, "trp_tournament_participants", ":cur_slot", ":hero"),
            # (try_begin),
                # (is_between, ":hero", quick_battle_troops_original_begin, quick_battle_troops_tournament_end),
                # (troop_set_slot, ":hero", slot_troop_cur_center, ":center_no"),
            # (try_end),
            (val_add, ":cur_slot", 1),
            #add some health too
            (val_mul, ":random_no", 10),
            (val_add, ":health", ":random_no"),
            (troop_set_health, ":hero", ":health"),
        (try_end),
    (try_end),
    ##SB : random quick-battle heroes (20% each x 11) at full health, capped to 5 per tourney to not saturate
    (try_for_range, ":hero", quick_battle_troops_begin, quick_battle_troops_end),
        (lt, ":cur_slot", ":heroes_limit"),
        (store_random_in_range, ":random_no", 0, 5),
        (try_begin),
            (eq, ":random_no", 0),
            (troop_set_slot, "trp_tournament_participants", ":cur_slot", ":hero"),
            (troop_set_health, ":hero", ":health"),
            (val_add, ":cur_slot", 1),
        (try_end),
    (try_end),
    (assign, ":begin_slot", ":cur_slot"),

    #SB : set up flavour troops (town mercenary, sword sister alternatives)
    (party_get_slot, ":town_merc", ":center_no", slot_center_mercenary_troop_type),
    (party_get_slot, ":merc_amount", ":center_no", slot_center_mercenary_troop_amount),
    (val_mul, ":merc_amount", 2),
    (val_div, ":merc_amount", 3),

    (store_faction_of_party, ":town_faction", ":center_no"),
    #alternatively check if other female heroes are present and allow sword sisters?

    #might need to test for male prejudice against hired blades?
    (try_begin),
      (call_script, "script_cf_dplmc_faction_has_bias_against_gender", ":town_faction", tf_female),
      (assign, ":sword_sister", -1),
    (else_try),
      (assign, ":sword_sister", "trp_sword_sister"),
    (try_end),
    (try_for_range, ":cur_slot", ":begin_slot", 64), #dckplmc - use faction troops unless none applicable
      (store_random_in_range, ":random_no", 0, 6),
      (store_random_in_range, ":random_no2", 0, 3), #1/3 chance of tournament fighters
      (try_begin),
        (eq, ":random_no", 0),
        (try_begin),
          (lt, ":random_no2", 2),
          (faction_get_slot, ":troop_no", ":town_faction", slot_faction_tier_3_troop),
          (gt, ":troop_no", 0),
          (troop_set_slot, "trp_tournament_participants", ":cur_slot", ":troop_no"),
        (else_try),
          (troop_set_slot, "trp_tournament_participants", ":cur_slot", "trp_regular_fighter"),
        (try_end),
      (else_try),
        (eq, ":random_no", 1),
        (try_begin),
          (lt, ":random_no2", 2),
          (faction_get_slot, ":troop_no", ":town_faction", slot_faction_tier_4_troop),
          (gt, ":troop_no", 0),
          (troop_set_slot, "trp_tournament_participants", ":cur_slot", ":troop_no"),
        (else_try),
          (troop_set_slot, "trp_tournament_participants", ":cur_slot", "trp_veteran_fighter"),
        (try_end),
      (else_try),
        (eq, ":random_no", 2),
        (try_begin),
          (lt, ":random_no2", 2),
          (faction_get_slot, ":troop_no", ":town_faction", slot_faction_tier_5_troop),
          (gt, ":troop_no", 0),
          (troop_set_slot, "trp_tournament_participants", ":cur_slot", ":troop_no"),
        (else_try),
          (troop_set_slot, "trp_tournament_participants", ":cur_slot", "trp_champion_fighter"),
        (try_end),
      (else_try),
        (eq, ":random_no", 3),
        (try_begin),
          (eq, ":sword_sister", "trp_sword_sister"),
          (eq, ":random_no2", 2),
          (troop_set_slot, "trp_tournament_participants", ":cur_slot", ":sword_sister"),
        (else_try),
          (lt, ":random_no2", 2),
          (faction_get_slot, ":troop_no", ":town_faction", slot_faction_tier_5_troop),
          (gt, ":troop_no", 0),
          (troop_set_slot, "trp_tournament_participants", ":cur_slot", ":troop_no"),
        (else_try),
          (troop_set_slot, "trp_tournament_participants", ":cur_slot", "trp_mercenary_swordsman"),
        (try_end),
      (else_try),
        (eq, ":random_no", 4),
        (try_begin),
          (lt, ":random_no2", 2),
          (faction_get_slot, ":troop_no", ":town_faction", slot_faction_tier_5_troop),
          (gt, ":troop_no", 0),
          (troop_set_slot, "trp_tournament_participants", ":cur_slot", ":troop_no"),
        (else_try),
          (troop_set_slot, "trp_tournament_participants", ":cur_slot", "trp_hired_blade"),
        (try_end),
        #(troop_set_slot, "trp_tournament_participants", ":cur_slot", "trp_hired_blade"),
      (else_try), #SB : use current town mercenary (if any remaining)
        (eq, ":random_no2", 5),
        (gt, ":merc_amount", 0),
        (val_sub, ":merc_amount", 1),
        (troop_set_slot, "trp_tournament_participants", ":cur_slot", ":town_merc"),
      (else_try), #otherwise fallback to random mercenary participant
        (store_random_in_range, ":merc", mercenary_troops_begin, mercenary_troops_end),
        (troop_set_slot, "trp_tournament_participants", ":cur_slot", ":merc"),
      (try_end),
    (try_end),
  ]),

  # script_get_num_tournament_participants
  # Input: none
  # Output: reg0 = num_participants
  ("get_num_tournament_participants",
    [(assign, ":num_participants", 0),
     (try_for_range, ":cur_slot", 0, 64),
       (troop_slot_ge, "trp_tournament_participants", ":cur_slot", 0),
       (val_add, ":num_participants", 1),
     (try_end),
     (assign, reg0, ":num_participants"),
     ]),

  # script_get_random_tournament_participant
  # Input: none
  # Output: reg0 = troop_no
  ("get_random_tournament_participant",
    [(call_script, "script_get_num_tournament_participants"),
     (assign, ":num_participants", reg0),
     (store_random_in_range, ":random_troop", 0, ":num_participants"),
     (assign, ":continue", 1),
     (try_for_range, ":cur_slot", 0, 64),
       (eq, ":continue", 1),
       (troop_slot_ge, "trp_tournament_participants", ":cur_slot", 0),
       (val_sub, ":random_troop", 1),
       (lt, ":random_troop", 0),
       (assign, ":continue", 0),
       (troop_get_slot, ":troop_no", "trp_tournament_participants", ":cur_slot"),
       (troop_set_slot, "trp_tournament_participants", ":cur_slot", -1),
     (try_end),
     (assign, reg0, ":troop_no"),
     ]),

  # script_add_tournament_participant
  # Input: arg1 = troop_no
  # Output: none
  ("add_tournament_participant",
    [(store_script_param, ":troop_no", 1),
     (assign, ":continue", 1),
     (try_for_range, ":cur_slot", 0, 64),
       (eq, ":continue", 1),
       (troop_slot_eq, "trp_tournament_participants", ":cur_slot", -1),
       (troop_set_slot, "trp_tournament_participants", ":cur_slot", ":troop_no"),
       (assign, ":continue", 0),
     (try_end),
     ]),

  # script_get_random_tournament_team_amount_and_size
  # Input: none
  # Output: reg0 = number_of_teams, reg1 = team_size
  ("get_random_tournament_team_amount_and_size",
    [
        (call_script, "script_get_num_tournament_participants"),
        (assign, ":num_participants", reg0),
        (party_get_slot, ":town_max_teams", "$current_town", slot_town_tournament_max_teams),
        (val_add, ":town_max_teams", 1),
        (party_get_slot, ":town_max_team_size", "$current_town", slot_town_tournament_max_team_size),
        (val_add, ":town_max_team_size", 1),
        (assign, ":max_teams", ":num_participants"),
        (val_min, ":max_teams", ":town_max_teams"),
        (assign, ":max_size", ":num_participants"),
        (val_min, ":max_size", ":town_max_team_size"),
        (assign, ":min_size", 1),
        (try_begin),
          (ge, ":num_participants", 32),
          (assign, ":min_size", 2),
          (val_min, ":min_size", ":town_max_team_size"),
        (try_end),
        (assign, ":end_cond", 500),
        (try_for_range, ":unused", 0, ":end_cond"),
          (store_random_in_range, ":random_teams", 2, ":max_teams"),
          (store_random_in_range, ":random_size", ":min_size", ":max_size"),
          (store_mul, ":total_men", ":random_teams", ":random_size"),
          (le, ":total_men", ":num_participants"),
          (store_sub, ":left_men", ":num_participants", ":total_men"),
          (neq, ":left_men", 1),
          (assign, ":end_cond", 0),
        (try_end),
        (try_begin),
          (gt, ":end_cond", 0),
          (assign, ":random_teams", 2),
          (assign, ":random_size", 1),
        (try_end),
        (assign, reg0, ":random_teams"),
        (assign, reg1, ":random_size"),
     ]),

  # script_get_troop_priority_point_for_tournament
  # Input: arg1 = troop_no
  # Output: reg0 = troop_point
  ("get_troop_priority_point_for_tournament",
    [(store_script_param, ":troop_no", 1),
     (assign, ":troop_point", 0),
     (try_begin),
       (ge, ":troop_no", 0),
       (val_add, ":troop_point", 40000),
       (try_begin),
         (eq, ":troop_no", "trp_player"),
         (val_add, ":troop_point", 80000),
       (try_end),
       (try_begin),
         (troop_is_hero, ":troop_no"),
         (val_add, ":troop_point", 20000),
       (try_end),
       (try_begin),
         (troop_slot_eq, ":troop_no", slot_troop_occupation, slto_player_companion),
         (val_add, ":troop_point", 10000),
       (else_try),
         (troop_slot_eq, ":troop_no", slot_troop_occupation, slto_kingdom_hero),
         (troop_get_slot, ":renown", ":troop_no", slot_troop_renown),
         (val_add, ":troop_point", ":renown"),
         (val_add, ":troop_point", 1000), #in order to make it more prior than tournament heroes with higher levels
       (else_try),
         (store_character_level, ":level", ":troop_no"),
         (val_add, ":troop_point", ":level"),
       (try_end),
     (try_end),
     (assign, reg0, ":troop_point"),
     ]),

  # script_sort_tournament_participant_troops
  # Input: none
  # Output: none (sorts trp_tournament_participants)
  ("sort_tournament_participant_troops",
    [(try_for_range, ":cur_slot", 0, 63),
       (store_add, ":cur_slot_2_begin", ":cur_slot", 1),
       (try_for_range, ":cur_slot_2", ":cur_slot_2_begin", 64),
         (troop_get_slot, ":troop_1", "trp_tournament_participants", ":cur_slot"),
         (troop_get_slot, ":troop_2", "trp_tournament_participants", ":cur_slot_2"),
         (call_script, "script_get_troop_priority_point_for_tournament", ":troop_1"),
         (assign, ":troop_1_point", reg0),
         (call_script, "script_get_troop_priority_point_for_tournament", ":troop_2"),
         (assign, ":troop_2_point", reg0),
         (gt, ":troop_2_point", ":troop_1_point"),
         (troop_set_slot, "trp_tournament_participants", ":cur_slot", ":troop_2"),
         (troop_set_slot, "trp_tournament_participants", ":cur_slot_2", ":troop_1"),
       (try_end),
     (try_end),
     ]),

  # script_remove_tournament_participants_randomly
  # Input: arg1 = number_to_be_removed
  # Output: none
  ("remove_tournament_participants_randomly",
    [(store_script_param, ":number_to_be_removed", 1),
     #SB : TODO simulate tournament fighting relationship changes
     (try_for_range, ":unused", 0, ":number_to_be_removed"),
       (assign, ":total_weight", 0),
       (try_for_range, ":cur_slot", 0, 64),
         (troop_get_slot, ":troop_no", "trp_tournament_participants", ":cur_slot"),
         (ge, ":troop_no", 0),
         (store_character_level, ":level", ":troop_no"),
         (val_min, ":level", 38),
         (store_sub, ":weight", 40, ":level"),
         (val_add, ":total_weight", ":weight"),
       (try_end),
       (store_random_in_range, ":random_weight", 0, ":total_weight"),
       (assign, ":continue", 1),
       (try_for_range, ":cur_slot", 0, 64),
         (eq, ":continue", 1),
         (troop_get_slot, ":troop_no", "trp_tournament_participants", ":cur_slot"),
         (ge, ":troop_no", 0),
         (store_character_level, ":level", ":troop_no"),
         (val_min, ":level", 38),
         (store_sub, ":weight", 40, ":level"),
         (val_sub, ":random_weight", ":weight"),
         (lt, ":random_weight", 0),
         (troop_set_slot, "trp_tournament_participants", ":cur_slot", -1),
         (assign, ":continue", 0),
       (try_end),
     (try_end),
     ]),

  # script_end_tournament_fight
  # Input: arg1 = player_team_won (1 or 0)
  # Output: none
  ("end_tournament_fight",
    [
      (store_script_param, ":player_team_won", 1),
      (call_script, "script_get_num_tournament_participants"),
      (assign, ":num_participants", reg0),
      (store_div, ":needed_to_remove_randomly", ":num_participants", 2),
      #Must remove other participants randomly earlier than adding the winners back to participants
      (call_script, "script_remove_tournament_participants_randomly", ":needed_to_remove_randomly"),

      #SB : because we've added relationship losses, we'll also add this here
      (store_div, ":relation", "$g_tournament_cur_tier", 2),
      (assign, ":num_needed", "$g_tournament_num_participants_for_fight"),
      (val_div, ":num_needed", 2),
      (get_player_agent_no, ":player_agent"),
      (agent_get_team, ":player_team", ":player_agent"),
      (try_for_agents, ":agent_no"),
        (agent_is_human, ":agent_no"),
        (agent_get_troop_id, ":troop_id", ":agent_no"),
        (neg|is_between, ":troop_id", arena_masters_begin, arena_masters_end),#omit tournament master
        (agent_get_team, ":agent_team", ":agent_no"),
        (assign, ":cur_point", 0),
        (try_begin),
          (eq, ":player_team_won", 1),
          (eq, ":agent_team", ":player_team"),
          (val_add, ":cur_point", 5000000),#Make sure that team members are chosen
          #SB : apply relationship bonus here
          (agent_is_alive, ":agent_no"),
          (troop_is_hero, ":troop_id"),
          (try_begin), #player's companions, change their morale penalty
            (troop_slot_eq, ":troop_id", slot_troop_occupation, slto_player_companion),
            (troop_get_slot, ":grievance", ":troop_id", slot_troop_personalityclash_penalties),
            (val_sub, ":grievance", "$g_tournament_cur_tier"),
            (troop_set_slot, ":troop_id", slot_troop_personalityclash_penalties, ":grievance"),
          (else_try), #friendly lords, less will have this bonus as the tiers increase
            (call_script, "script_change_player_relation_with_troop", ":troop_id", ":relation"),
          (try_end),
        (try_end),
        (agent_get_kill_count, ":kill_count", ":agent_no", 1), #everyone is knocked unconscious
        (store_mul, ":kill_point", ":kill_count", 160000),#Make sure that kill count is the second most important variable
        (val_add, ":cur_point", ":kill_point"),
        (call_script, "script_get_troop_priority_point_for_tournament", ":troop_id"),
        (val_add, ":cur_point", reg0),
        (try_begin),#reset player's point if kill count is one after the first 2 rounds, or if it is zero
         (eq, ":agent_no", ":player_agent"),
         (eq, ":player_team_won", 0),
         (assign, ":not_passed", 1),
         (try_begin),
           (ge, ":kill_count", 2),
           (assign, ":not_passed", 0),
         (else_try),
           (eq, ":kill_count", 1),
           (le, "$g_tournament_cur_tier", 1),
           (assign, ":not_passed", 0),
         (try_end),
         (eq, ":not_passed", 1),
         (assign, ":cur_point", 0),
       (try_end),
       (agent_set_slot, ":agent_no", slot_agent_tournament_point, ":cur_point"),
     (try_end),
     (try_for_range, ":unused", 0, ":num_needed"),
       (assign, ":best_point", 0),
       (assign, ":best_agent_no", -1),
       (try_for_agents, ":agent_no"),
         (agent_is_human, ":agent_no"),
         (agent_get_slot, ":point", ":agent_no", slot_agent_tournament_point),
         (gt, ":point", ":best_point"),
         (assign, ":best_agent_no", ":agent_no"),
         (assign, ":best_point", ":point"),
       (try_end),
       (agent_set_slot, ":best_agent_no", slot_agent_tournament_point, 0),#Do not select the same agent again
       (agent_get_troop_id, ":troop_id", ":best_agent_no"),
       (call_script, "script_add_tournament_participant", ":troop_id"),
     (try_end),
     (assign, "$g_tournament_player_team_won", ":player_team_won"),
     (jump_to_menu, "mnu_town_tournament"),
     ]),


  # script_get_win_amount_for_tournament_bet
  # Input: none
  # Output: reg0 = win_amount_with_100_denars
  ("get_win_amount_for_tournament_bet",
    [
        (party_get_slot, ":player_odds", "$current_town", slot_town_player_odds),
        (try_begin),
          (eq, "$g_tournament_cur_tier", 0),
          (assign, ":win_amount", 120),
        (else_try),
          (eq, "$g_tournament_cur_tier", 1),
          (assign, ":win_amount", 90),
        (else_try),
          (eq, "$g_tournament_cur_tier", 2),
          (assign, ":win_amount", 60),
        (else_try),
          (eq, "$g_tournament_cur_tier", 3),
          (assign, ":win_amount", 40),
        (else_try),
          (eq, "$g_tournament_cur_tier", 4),
          (assign, ":win_amount", 20),
        (else_try),
          (assign, ":win_amount", 8),
        (try_end),
        (val_mul, ":win_amount", ":player_odds"),
        (val_div, ":win_amount", 100),
        (val_add, ":win_amount", 100), #win amount when 100 denars is placed
        (assign, reg0, ":win_amount"),
     ]),

  # script_tournament_place_bet
  # Input: arg1 = bet_amount
  # Output: none
  ("tournament_place_bet",
    [
        (store_script_param, ":bet_amount", 1),
        (call_script, "script_get_win_amount_for_tournament_bet"),
        (assign, ":win_amount", reg0),
        (val_mul, ":win_amount", ":bet_amount"),
        (val_div, ":win_amount", 100),
        (val_sub, ":win_amount", ":bet_amount"),
        (val_add, "$g_tournament_bet_placed", ":bet_amount"),
        (val_add, "$g_tournament_bet_win_amount", ":win_amount"),
        (troop_remove_gold, "trp_player", ":bet_amount"),
        (assign, "$g_tournament_last_bet_tier", "$g_tournament_cur_tier"),
     ]),

  # script_calculate_amount_of_cattle_can_be_stolen
  # Input: arg1 = horse_chance, arg2 = lance_chance (with horse only), arg3 = sword_chance, arg4 = axe_chance, arg5 = bow_chance (without horse only), arg6 = javelin_chance (with horse only), arg7 = mounted_bow_chance (with horse only), arg8 = crossbow_sword_chance, arg9 = armor_item_begin, arg10 = helm_item_begin
  # Output: none (sets mt_arena_melee_fight items)
  ("set_items_for_tournament",
    [
      (store_script_param, ":horse_chance", 1),
      (store_script_param, ":lance_chance", 2),
      (store_script_param, ":sword_chance", 3),
      (store_script_param, ":axe_chance", 4),
      (store_script_param, ":bow_chance", 5),
      (store_script_param, ":javelin_chance", 6),
      (store_script_param, ":mounted_bow_chance", 7),
      (store_script_param, ":crossbow_sword_chance", 8),
      (store_script_param, ":armor_item_begin", 9),
      (store_script_param, ":helm_item_begin", 10),
      (store_add, ":total_chance", ":sword_chance", ":axe_chance"),
      (val_add, ":total_chance", ":crossbow_sword_chance"),


      #SB : move shield/team calculations up top, start off by one since we'll increment immediately
      (assign, ":cur_team", -1),
      (store_sub, ":cur_shield_item", "itm_arena_shield_red", 1),
      (try_begin),
        (ge, ":armor_item_begin", 0),
        (store_sub, ":cur_armor_item", ":armor_item_begin", 1),
      (else_try), #doesn't matter, we're checking parameter not this value
        (assign, ":cur_armor_item", -999),
      (try_end),
      (try_begin),
        (ge, ":helm_item_begin", 0),
        (store_sub, ":cur_helm_item", ":helm_item_begin", 1),
      (else_try),
        (assign, ":cur_helm_item", -999),
      (try_end),

      (try_for_range, ":i_ep", 0, 32),
        (mission_tpl_entry_clear_override_items, "mt_arena_melee_fight", ":i_ep"),
        (assign, ":has_horse", 0),
        # (store_div, ":cur_team", ":i_ep", 8),
        (try_begin), #SB : incrementing at same rate
          (store_mod, ":entry", ":i_ep", 8),
          (eq, ":entry", 0),
          (val_add, ":cur_team", 1),
          (val_add, ":cur_shield_item", 1),
          (val_add, ":cur_armor_item", 1),
          (val_add, ":cur_helm_item", 1),
        (try_end),
        (try_begin),
          (store_random_in_range, ":random_no", 0, 100),
          (lt, ":random_no", ":horse_chance"),
          (assign, ":has_horse", 1),
          (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_horse"),
        (try_end),
        (try_begin),
          (eq, ":has_horse", 1),
          (store_add, ":cur_total_chance", ":total_chance", ":lance_chance"),
          (val_add, ":cur_total_chance", ":javelin_chance"),
          (val_add, ":cur_total_chance", ":mounted_bow_chance"),
        (else_try),
          (store_add, ":cur_total_chance", ":total_chance", ":bow_chance"),
        (try_end),
        (store_random_in_range, ":random_no", 0, ":cur_total_chance"),
        # (store_add, ":cur_shield_item", "itm_arena_shield_red", ":cur_team"),

        #SB : deal with player entry here
        (try_begin),
          (eq, "$g_player_entry_point", ":i_ep"),
          (assign, ":continue", -1),
          (assign, ":proficiency", -1), #this checks if ranged proficiency are lower than
          #first check ranged weapon preference
          (store_proficiency_level, ":bow_prof", "trp_player", wpt_archery),
          (store_proficiency_level, ":xbow_prof", "trp_player", wpt_crossbow),
          (store_proficiency_level, ":throw_prof", "trp_player", wpt_throwing),

          #check parameters to disallow weapon types
          (try_begin),
            (le, ":bow_chance", 0),
            (le, ":mounted_bow_chance", 0),
            (assign, ":bow_prof", -1),
          (try_end),
          (try_begin),
            (this_or_next|le, ":crossbow_sword_chance", 0),
            (eq, ":has_horse", 1), #Native disallows mounted crossbow
            (assign, ":xbow_prof", -1),
          (try_end),
          (try_begin),
            (le, ":javelin_chance", 0),
            (assign, ":throw_prof", -1),
          (try_end),

          (try_begin), #do a gt check here to ensure it's not set to -1
            (gt, ":bow_prof", ":proficiency"),
            (ge, ":bow_prof", ":xbow_prof"),
            (ge, ":bow_prof", ":throw_prof"),
            (assign, ":continue", wpt_archery),
            (assign, ":proficiency", ":bow_prof"),
          (else_try),
            (gt, ":xbow_prof", ":proficiency"),
            (ge, ":xbow_prof", ":bow_prof"),
            (ge, ":xbow_prof", ":throw_prof"),
            (assign, ":continue", wpt_crossbow),
            (assign, ":proficiency", ":xbow_prof"),
          (else_try),
            (gt, ":throw_prof", ":proficiency"),
            (ge, ":throw_prof", ":bow_prof"),
            (ge, ":throw_prof", ":xbow_prof"),
            (assign, ":continue", wpt_throwing),
            (assign, ":proficiency", ":throw_prof"),
          (try_end),
          #then check melee preference
          (store_proficiency_level, ":onehands", "trp_player", wpt_one_handed_weapon),
          (store_proficiency_level, ":twohands", "trp_player", wpt_two_handed_weapon),
          (store_proficiency_level, ":polearms", "trp_player", wpt_polearm),
          (try_begin),
            (le, ":sword_chance", 0),
            (le, ":axe_chance", 0),
            (assign, ":onehands", -1),
          (try_end),
          (try_begin),
            (le, ":sword_chance", 0),
            (assign, ":twohands", -1),
          (try_end),
          (try_begin),
            (this_or_next|le, ":lance_chance", 0),
            (eq, ":has_horse", 0),
            (assign, ":polearms", -1),
          (try_end),

          (try_begin),
            (gt, ":onehands", ":proficiency"),
            (ge, ":onehands", ":twohands"),
            (ge, ":onehands", ":polearms"),
            (assign, ":continue", wpt_one_handed_weapon),
            (assign, ":proficiency", ":onehands"),
          (else_try),
            (gt, ":twohands", ":proficiency"),
            (ge, ":twohands", ":onehands"),
            (ge, ":twohands", ":polearms"),
            (assign, ":continue", wpt_two_handed_weapon),
            (assign, ":proficiency", ":twohands"),
          (else_try), #do not allow staves when dismounted
            (gt, ":polearms", ":proficiency"),
            (ge, ":polearms", ":onehands"),
            (ge, ":polearms", ":twohands"),
            (assign, ":continue", wpt_polearm),
            (assign, ":proficiency", ":polearms"),
          (try_end),

          #finally add items
          (try_begin),
            (eq, ":continue", wpt_polearm),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_lance"),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", ":cur_shield_item"),
          (else_try),
            (eq, ":continue", wpt_two_handed_weapon),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_arena_sword_two_handed"),
          (else_try),
            (eq, ":continue", wpt_one_handed_weapon),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", ":cur_shield_item"),
            (try_begin),
              (ge, ":sword_chance", ":axe_chance"),
              (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_arena_sword"),
            (else_try),
              (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_arena_axe"),
            (try_end),
          (else_try),
            (eq, ":continue", wpt_throwing),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_javelin"),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", ":cur_shield_item"),
          (else_try),
            (eq, ":continue", wpt_crossbow),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_arena_sword"), #do not replace with axe
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_crossbow"),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_bolts"),
          (else_try),
            (eq, ":continue", wpt_archery),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_bow"),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_arrows"),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_tutorial_dagger"), #keep this
          (try_end),
          #otherwise fall through to default randomization
          (neq, ":continue", -1), #no wpt chosen
          # (assign, reg1, ":continue"),
          # (assign, reg2, ":proficiency"),
          # (display_message, "@final type {reg1} at prof {reg2}"),
        (else_try),
          (try_begin),
            (val_sub, ":random_no", ":sword_chance"),
            (lt, ":random_no", 0),
            (try_begin),
              (store_random_in_range, ":sub_random_no", 0, 100),
              (lt, ":sub_random_no", 50),
              (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_arena_sword"),
              (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", ":cur_shield_item"),
#              (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_shield"),
            (else_try),
              (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_arena_sword_two_handed"),
            (try_end),
          (else_try),
            (val_sub, ":random_no", ":axe_chance"),
            (lt, ":random_no", 0),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_arena_axe"),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", ":cur_shield_item"),
#           (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_shield"),
          (else_try),
            (val_sub, ":random_no", ":crossbow_sword_chance"),
            (lt, ":random_no", 0),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_arena_sword"),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_crossbow"),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_bolts"),
          (else_try),
            (eq, ":has_horse", 0),
            (val_sub, ":random_no", ":bow_chance"),
            (lt, ":random_no", 0),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_bow"),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_arrows"),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_tutorial_dagger"),
          (else_try),
            (eq, ":has_horse", 1),
            (val_sub, ":random_no", ":lance_chance"),
            (lt, ":random_no", 0),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_lance"),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", ":cur_shield_item"),
#            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_shield"),
          (else_try),
            (eq, ":has_horse", 1),
            (val_sub, ":random_no", ":javelin_chance"),
            (lt, ":random_no", 0),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_javelin"),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", ":cur_shield_item"),
#            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_shield"),
          (else_try),
            (eq, ":has_horse", 1),
            (val_sub, ":random_no", ":mounted_bow_chance"),
            (lt, ":random_no", 0),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_bow"),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_arrows"),
            #SB : change this to a weapon that's actually usable
            (try_begin),
              (ge, ":sword_chance", ":axe_chance"),
              (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_arena_sword"),
            (else_try),
              (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_arena_axe"),
            (try_end),
            # (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_dagger"),
          (try_end),
        (try_end),
        (try_begin),
          (ge, ":armor_item_begin", 0),
          # (store_add, ":cur_armor_item", ":armor_item_begin", ":cur_team"), #SB : moved to top
          (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", ":cur_armor_item"),
          (lt, ":cur_armor_item", "itm_arena_tunic_white"),
          (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_mail_mittens"),
        (try_end),
        (try_begin),
          (ge, ":helm_item_begin", 0),
          # (store_add, ":cur_helm_item", ":helm_item_begin", ":cur_team"), #SB : moved to top
          (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", ":cur_helm_item"),
        (try_end),
      (try_end),
     ]),


  # script_custom_battle_end
  # Input: none
  # Output: reg0 = troop_no
  ("get_random_tournament_prize",
    [(store_script_param, ":party_no", 1),
     (party_get_slot, ":cur_faction", ":party_no", slot_center_original_faction),
     (assign, ":cur_merchant", "trp_salt_mine_merchant"),

     (troop_clear_inventory, ":cur_merchant"),
     (store_random_in_range, ":r", 0, 4),

     (try_begin),
         (eq, ":r", 0),
         (troop_add_merchandise_with_faction, ":cur_merchant", ":cur_faction", itp_type_body_armor, 8),
     (else_try),
         (eq, ":r", 1),
         (troop_add_merchandise_with_faction, ":cur_merchant", ":cur_faction", itp_type_head_armor, 12),
     (else_try),
         (eq, ":r", 2),
          (troop_add_merchandise_with_faction, ":cur_merchant", ":cur_faction", itp_type_one_handed_wpn, 5),
          (troop_add_merchandise_with_faction, ":cur_merchant", ":cur_faction", itp_type_two_handed_wpn, 5),
          (troop_add_merchandise_with_faction, ":cur_merchant", ":cur_faction", itp_type_polearm, 5),
          (troop_add_merchandise_with_faction, ":cur_merchant", ":cur_faction", itp_type_shield, 6),
          (troop_add_merchandise_with_faction, ":cur_merchant", ":cur_faction", itp_type_bow, 4),
          (troop_add_merchandise_with_faction, ":cur_merchant", ":cur_faction", itp_type_crossbow, 3),
     (else_try),
         (eq, ":r", 3),
         (troop_add_merchandise_with_faction,":cur_merchant", ":cur_faction",itp_type_horse,5),
     (try_end),
     (troop_sort_inventory, ":cur_merchant"),
     (troop_get_inventory_capacity, ":inv_cap", ":cur_merchant"),
     (try_for_range, ":i_slot", ek_food + 2, ":inv_cap"),
        (troop_set_inventory_slot,":cur_merchant",":i_slot",-1),
     (try_end),

     ]),
### MMC gambler ###
]
