# -*- coding: cp1254 -*-
from header_common import *
from header_operations import *
from module_constants import *
from module_constants import *
from header_parties import *
from header_skills import *
from header_mission_templates import *
from header_items import *
from header_triggers import *
from header_terrain_types import *
from header_music import *
from header_map_icons import *
from ID_animations import *

set_items_for_tournament_scripts = [
# script_calculate_amount_of_cattle_can_be_stolen
# Input: arg1 = horse_chance, arg2 = lance_chance (with horse only), arg3 = sword_chance, arg4 = axe_chance, arg5 = bow_chance (without horse only), arg6 = javelin_chance (with horse only), arg7 = mounted_bow_chance (with horse only), arg8 = crossbow_sword_chance, arg9 = armor_item_begin, arg10 = helm_item_begin
# Output: none (sets mt_arena_melee_fight items)
("set_items_for_tournament",
    [
      (store_script_param, ":horse_chance", 1),
      (store_script_param, ":lance_chance", 2),
      (store_script_param, ":sword_chance", 3),
      (store_script_param, ":axe_chance", 4),
      (store_script_param, ":bow_chance", 5),
      (store_script_param, ":javelin_chance", 6),
      (store_script_param, ":mounted_bow_chance", 7),
      (store_script_param, ":crossbow_sword_chance", 8),
      (store_script_param, ":armor_item_begin", 9),
      (store_script_param, ":helm_item_begin", 10),
      (store_add, ":total_chance", ":sword_chance", ":axe_chance"),
      (val_add, ":total_chance", ":crossbow_sword_chance"),


      #SB : move shield/team calculations up top, start off by one since we'll increment immediately
      (assign, ":cur_team", -1),
      (store_sub, ":cur_shield_item", "itm_arena_shield_red", 1),
      (try_begin),
        (ge, ":armor_item_begin", 0),
        (store_sub, ":cur_armor_item", ":armor_item_begin", 1),
      (else_try), #doesn't matter, we're checking parameter not this value
        (assign, ":cur_armor_item", -999),
      (try_end),
      (try_begin),
        (ge, ":helm_item_begin", 0),
        (store_sub, ":cur_helm_item", ":helm_item_begin", 1),
      (else_try),
        (assign, ":cur_helm_item", -999),
      (try_end),

      (try_for_range, ":i_ep", 0, 32),
        (mission_tpl_entry_clear_override_items, "mt_arena_melee_fight", ":i_ep"),
        (assign, ":has_horse", 0),
        # (store_div, ":cur_team", ":i_ep", 8),
        (try_begin), #SB : incrementing at same rate
          (store_mod, ":entry", ":i_ep", 8),
          (eq, ":entry", 0),
          (val_add, ":cur_team", 1),
          (val_add, ":cur_shield_item", 1),
          (val_add, ":cur_armor_item", 1),
          (val_add, ":cur_helm_item", 1),
        (try_end),
        (try_begin),
          (store_random_in_range, ":random_no", 0, 100),
          (lt, ":random_no", ":horse_chance"),
          (assign, ":has_horse", 1),
          (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_horse"),
        (try_end),
        (try_begin),
          (eq, ":has_horse", 1),
          (store_add, ":cur_total_chance", ":total_chance", ":lance_chance"),
          (val_add, ":cur_total_chance", ":javelin_chance"),
          (val_add, ":cur_total_chance", ":mounted_bow_chance"),
        (else_try),
          (store_add, ":cur_total_chance", ":total_chance", ":bow_chance"),
        (try_end),
        (store_random_in_range, ":random_no", 0, ":cur_total_chance"),
        # (store_add, ":cur_shield_item", "itm_arena_shield_red", ":cur_team"),

        #SB : deal with player entry here
        (try_begin),
          (eq, "$g_player_entry_point", ":i_ep"),
          (assign, ":continue", -1),
          (assign, ":proficiency", -1), #this checks if ranged proficiency are lower than
          #first check ranged weapon preference
          (store_proficiency_level, ":bow_prof", "trp_player", wpt_archery),
          (store_proficiency_level, ":xbow_prof", "trp_player", wpt_crossbow),
          (store_proficiency_level, ":throw_prof", "trp_player", wpt_throwing),

          #check parameters to disallow weapon types
          (try_begin),
            (le, ":bow_chance", 0),
            (le, ":mounted_bow_chance", 0),
            (assign, ":bow_prof", -1),
          (try_end),
          (try_begin),
            (this_or_next|le, ":crossbow_sword_chance", 0),
            (eq, ":has_horse", 1), #Native disallows mounted crossbow
            (assign, ":xbow_prof", -1),
          (try_end),
          (try_begin),
            (le, ":javelin_chance", 0),
            (assign, ":throw_prof", -1),
          (try_end),

          (try_begin), #do a gt check here to ensure it's not set to -1
            (gt, ":bow_prof", ":proficiency"),
            (ge, ":bow_prof", ":xbow_prof"),
            (ge, ":bow_prof", ":throw_prof"),
            (assign, ":continue", wpt_archery),
            (assign, ":proficiency", ":bow_prof"),
          (else_try),
            (gt, ":xbow_prof", ":proficiency"),
            (ge, ":xbow_prof", ":bow_prof"),
            (ge, ":xbow_prof", ":throw_prof"),
            (assign, ":continue", wpt_crossbow),
            (assign, ":proficiency", ":xbow_prof"),
          (else_try),
            (gt, ":throw_prof", ":proficiency"),
            (ge, ":throw_prof", ":bow_prof"),
            (ge, ":throw_prof", ":xbow_prof"),
            (assign, ":continue", wpt_throwing),
            (assign, ":proficiency", ":throw_prof"),
          (try_end),
          #then check melee preference
          (store_proficiency_level, ":onehands", "trp_player", wpt_one_handed_weapon),
          (store_proficiency_level, ":twohands", "trp_player", wpt_two_handed_weapon),
          (store_proficiency_level, ":polearms", "trp_player", wpt_polearm),
          (try_begin),
            (le, ":sword_chance", 0),
            (le, ":axe_chance", 0),
            (assign, ":onehands", -1),
          (try_end),
          (try_begin),
            (le, ":sword_chance", 0),
            (assign, ":twohands", -1),
          (try_end),
          (try_begin),
            (this_or_next|le, ":lance_chance", 0),
            (eq, ":has_horse", 0),
            (assign, ":polearms", -1),
          (try_end),

          (try_begin),
            (gt, ":onehands", ":proficiency"),
            (ge, ":onehands", ":twohands"),
            (ge, ":onehands", ":polearms"),
            (assign, ":continue", wpt_one_handed_weapon),
            (assign, ":proficiency", ":onehands"),
          (else_try),
            (gt, ":twohands", ":proficiency"),
            (ge, ":twohands", ":onehands"),
            (ge, ":twohands", ":polearms"),
            (assign, ":continue", wpt_two_handed_weapon),
            (assign, ":proficiency", ":twohands"),
          (else_try), #do not allow staves when dismounted
            (gt, ":polearms", ":proficiency"),
            (ge, ":polearms", ":onehands"),
            (ge, ":polearms", ":twohands"),
            (assign, ":continue", wpt_polearm),
            (assign, ":proficiency", ":polearms"),
          (try_end),

          #finally add items
          (try_begin),
            (eq, ":continue", wpt_polearm),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_lance"),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", ":cur_shield_item"),
          (else_try),
            (eq, ":continue", wpt_two_handed_weapon),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_arena_sword_two_handed"),
          (else_try),
            (eq, ":continue", wpt_one_handed_weapon),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", ":cur_shield_item"),
            (try_begin),
              (ge, ":sword_chance", ":axe_chance"),
              (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_arena_sword"),
            (else_try),
              (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_arena_axe"),
            (try_end),
          (else_try),
            (eq, ":continue", wpt_throwing),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_javelin"),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", ":cur_shield_item"),
          (else_try),
            (eq, ":continue", wpt_crossbow),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_arena_sword"), #do not replace with axe
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_crossbow"),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_bolts"),
          (else_try),
            (eq, ":continue", wpt_archery),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_bow"),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_arrows"),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_tutorial_dagger"), #keep this
          (try_end),
          #otherwise fall through to default randomization
          (neq, ":continue", -1), #no wpt chosen
          # (assign, reg1, ":continue"),
          # (assign, reg2, ":proficiency"),
          # (display_message, "@final type {reg1} at prof {reg2}"),
        (else_try),
          (try_begin),
            (val_sub, ":random_no", ":sword_chance"),
            (lt, ":random_no", 0),
            (try_begin),
              (store_random_in_range, ":sub_random_no", 0, 100),
              (lt, ":sub_random_no", 50),
              (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_arena_sword"),
              (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", ":cur_shield_item"),
#              (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_shield"),
            (else_try),
              (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_arena_sword_two_handed"),
            (try_end),
          (else_try),
            (val_sub, ":random_no", ":axe_chance"),
            (lt, ":random_no", 0),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_arena_axe"),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", ":cur_shield_item"),
#           (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_shield"),
          (else_try),
            (val_sub, ":random_no", ":crossbow_sword_chance"),
            (lt, ":random_no", 0),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_arena_sword"),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_crossbow"),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_bolts"),
          (else_try),
            (eq, ":has_horse", 0),
            (val_sub, ":random_no", ":bow_chance"),
            (lt, ":random_no", 0),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_bow"),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_arrows"),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_tutorial_dagger"),
          (else_try),
            (eq, ":has_horse", 1),
            (val_sub, ":random_no", ":lance_chance"),
            (lt, ":random_no", 0),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_lance"),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", ":cur_shield_item"),
#            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_shield"),
          (else_try),
            (eq, ":has_horse", 1),
            (val_sub, ":random_no", ":javelin_chance"),
            (lt, ":random_no", 0),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_javelin"),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", ":cur_shield_item"),
#            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_shield"),
          (else_try),
            (eq, ":has_horse", 1),
            (val_sub, ":random_no", ":mounted_bow_chance"),
            (lt, ":random_no", 0),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_bow"),
            (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_arrows"),
            #SB : change this to a weapon that's actually usable
            (try_begin),
              (ge, ":sword_chance", ":axe_chance"),
              (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_arena_sword"),
            (else_try),
              (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_arena_axe"),
            (try_end),
            # (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_practice_dagger"),
          (try_end),
        (try_end),
        (try_begin),
          (ge, ":armor_item_begin", 0),
          # (store_add, ":cur_armor_item", ":armor_item_begin", ":cur_team"), #SB : moved to top
          (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", ":cur_armor_item"),
          (lt, ":cur_armor_item", "itm_arena_tunic_white"),
          (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", "itm_mail_mittens"),
        (try_end),
        (try_begin),
          (ge, ":helm_item_begin", 0),
          # (store_add, ":cur_helm_item", ":helm_item_begin", ":cur_team"), #SB : moved to top
          (mission_tpl_entry_add_override_item, "mt_arena_melee_fight", ":i_ep", ":cur_helm_item"),
        (try_end),
      (try_end),
     ])
]
