# -*- coding: cp1254 -*-
from header_game_menus import *
from header_parties import *
from header_items import *
from header_mission_templates import *
from header_music import *
from header_terrain_types import *
from header_triggers import key_left_shift, key_right_shift
from module_constants import *

fucked_by_enemy_menu = [
(
    "fucked_by_enemy",0,
    "{s10}",
    "none",
    [
		 (set_background_mesh, "mesh_pic_custom_03"),
         (set_camera_follow_party, "$capturer_party"),
         (assign, "$g_player_is_captive", 1),
         (store_random_in_range, ":random_hours", 18, 30),
         (call_script, "script_event_player_captured_as_prisoner"),
         (call_script, "script_stay_captive_for_hours", ":random_hours"),
         (assign,"$auto_menu","mnu_captivity_wilderness_check"),

        (call_script, "script_change_troop_renown", "trp_player", -10),

        (troop_get_slot, ":dna", "trp_temp_array_c", 17),
        (troop_set_slot, "trp_temp_array_b", 0, -1),

		(try_begin),
		(this_or_next|eq, "$character_gender", 1),(eq, "$g_nohomo", 0),
        (troop_set_slot, "trp_temp_array_a", 0, "trp_player"),
		(try_end),


		(party_get_num_companion_stacks, ":num_stacks", "p_main_party"),
		(try_begin),
			(assign, ":fems", 0),
			(try_for_range, ":i_stack", 0, ":num_stacks"),
				(party_stack_get_troop_id, ":troop_id", "p_main_party", ":i_stack"),
				(troop_is_hero, ":troop_id"),
				(this_or_next|eq, "$g_nohomo", 0),
				(call_script, "script_cf_dplmc_troop_is_female", ":troop_id"),
				(val_add, ":fems", 1),
			(try_end),
			(store_random_in_range, ":ff", 0, ":fems"),
			(try_begin),
				(try_for_range, ":i_stack", 0, ":num_stacks"),
					(party_stack_get_troop_id, ":troop_id", "p_main_party", ":i_stack"),
					(troop_is_hero, ":troop_id"),
					(this_or_next|eq, "$g_nohomo", 0),
					(call_script, "script_cf_dplmc_troop_is_female", ":troop_id"),
					(try_begin),
						(gt, ":ff", 0),
						(val_sub, ":ff", 1),
					(else_try),
						(eq, ":ff", 0),
						(val_sub, ":ff", 1),
						(troop_set_slot, "trp_temp_array_a", 0, ":troop_id"),
						(troop_set_slot, "trp_temp_array_b", 0, -1),
						(try_begin),
							(neq, ":troop_id", "trp_player"),
							(troop_set_slot, "trp_temp_array_a", 2, "trp_player"),
							(troop_set_slot, "trp_temp_array_b", 2, -1),
							(else_try),
							(troop_set_slot, "trp_temp_array_a", 2, -1),
							(troop_set_slot, "trp_temp_array_b", 2, -1),
						(try_end),
					(try_end),
				(try_end),
			(try_end),
		(try_end),

        (troop_set_slot, "trp_temp_array_a", 1, "$g_talk_troop"),
        (troop_set_slot, "trp_temp_array_b", 1, ":dna"),
        (store_random_in_range, ":r", 0, 2),
        (assign, "$g_sex_position", ":r"),

          (party_get_current_terrain, ":terrain_type", "p_main_party"),
          (assign, ":scene_to_use", "scn_camp_scene_plain"),
          (try_begin),
            (this_or_next|eq, ":terrain_type", rt_steppe),
            (eq, ":terrain_type", rt_steppe_forest),
            (assign, ":scene_to_use", "scn_camp_scene_steppe"),
          (else_try),
            (this_or_next|eq, ":terrain_type", rt_plain),
            (eq, ":terrain_type", rt_forest),
            (assign, ":scene_to_use", "scn_camp_scene_plain"),
          (else_try),
            (this_or_next|eq, ":terrain_type", rt_snow),
            (eq, ":terrain_type", rt_snow_forest),
            (assign, ":scene_to_use", "scn_camp_scene_snow"),
          (else_try),
            (this_or_next|eq, ":terrain_type", rt_desert),
            (eq, ":terrain_type", rt_desert_forest),
            (assign, ":scene_to_use", "scn_camp_scene_desert"),
          (else_try),
            (this_or_next|eq, ":terrain_type", rt_river),
            (eq, ":terrain_type", rt_water), #figure this out later
            (assign, ":scene_to_use", "scn_sea_1"),
            (party_get_slot, ":ship_type", "$capturer_party", slot_party_ship_type),
            (try_begin),
              (eq, ":ship_type", 1),
              (assign, ":scene_to_use", "scn_sea_1"),
            (else_try),
              (eq, ":ship_type", 2),
              (assign, ":scene_to_use", "scn_sea_2"),
            (else_try),
              (eq, ":ship_type", 3),
              (assign, ":scene_to_use", "scn_sea_3"),
            (else_try),
              (eq, ":ship_type", 4),
              (assign, ":scene_to_use", "scn_sea_4"),
            (try_end),
          (else_try),
            (eq, ":terrain_type", rt_bridge),
            (try_for_parties, ":party_no"),
                (is_between, ":party_no", "p_bridge_1", "p_looter_spawn_point"),
                (store_distance_to_party_from_party, ":distance", ":party_no", "p_main_party"),
                (lt, ":distance", 2),
                (party_get_icon, ":icon", ":party_no"),
                (try_begin),
                    (eq, ":icon", "icon_bridge_snow_a"),
                    (assign, ":scene_to_use", "scn_camp_scene_snow"),
                (else_try),
                    (assign, ":scene_to_use", "scn_camp_scene_plain"),
                (try_end),
            (try_end),
          (try_end),

		(assign, "$f_temp_var", ":scene_to_use"),
		(troop_get_slot, ":girl", "trp_temp_array_a", 0),
		(str_store_troop_name,s4,":girl"),
		(try_begin),
			(eq, ":girl", 0),
			(str_store_string, s10, "@Your enemies take you prisoner, and drag you back to their camp. ^^After a few hungry glances, their leader snatches your hair and roughly pulls you into his tent where he tears your clothes away."),
			(else_try),
			(str_store_string, s10, "@Your enemies take you and your companions prisoner, leading all of you back to their camp. ^^After a few hungry glances, their leader grabs you by the arm and snatches {s4}'s hair. He roughly pulls you both into his tent and tears both your clothes away."),
		(try_end),
     ],
    [
      ("continue",[],"Continue...",
       [
	   	(try_begin),
		(troop_get_slot, ":target_char", "trp_temp_array_a", 2),
		(neq, ":target_char", "trp_player"),
		(assign, ":pos", 2),
		(else_try),
		(assign, ":pos", 3),
		(try_end),
		(call_script, "script_start_fucking", ":pos", "$f_temp_var"),
		(assign, "$f_temp_var", 0),
         ]),
      ]
  )
]
