# -*- coding: cp1254 -*-
import string
from header_common import *
from header_presentations import *
from header_mission_templates import *
from ID_meshes import *
from header_operations import *
from header_triggers import *
#SB: import skills from ID_skills import *
from module_constants import *
##diplomacy start+ Import for use with terrain advantage
from header_terrain_types import *
from module_items import *
#SB : import colors
from module_factions import *
from header_items import *
##diplomacy end
from compiler import *

redefine_keys = ("redefine_keys", prsntf_manual_end_only, mesh_cb_ui_main, [
    (ti_on_presentation_load,
      [
        (presentation_set_duration, 999999),
        (set_fixed_point_multiplier, 1000),

        (call_script, "script_init_keys_array"),

        (try_for_range, ":strings", s1, s9),
          (str_clear, ":strings"),
        (try_end),
        (try_for_range, ":cur_slot", 0, len(keys)),
          (troop_get_slot, ":key_no", "trp_temp_array_a", ":cur_slot"),
          (store_add, ":dest_string", "str_key_0", ":cur_slot"),
          (try_begin),
            (eq, ":key_no", "$g_camera_adjust_add"),
            (str_store_string, s1, ":dest_string"),
          (else_try),
            (eq, ":key_no", "$g_camera_adjust_sub"),
            (str_store_string, s2, ":dest_string"),
          (else_try),
            (eq, ":key_no", "$g_cam_tilt_left"),
            (str_store_string, s3, ":dest_string"),
          (else_try),
            (eq, ":key_no", "$g_cam_tilt_right"),
            (str_store_string, s4, ":dest_string"),
          (else_try),
            (eq, ":key_no", "$g_camera_rot_up"),
            (str_store_string, s5, ":dest_string"),
          (else_try),
            (eq, ":key_no", "$g_camera_rot_down"),
            (str_store_string, s6, ":dest_string"),
          (else_try),
            (eq, ":key_no", "$g_camera_rot_left"),
            (str_store_string, s7, ":dest_string"),
          (else_try),
            (eq, ":key_no", "$g_camera_rot_right"),
            (str_store_string, s8, ":dest_string"),
          (try_end),
        (try_end),

        (assign, "$temp", -1),
        # (store_mul, ":cur_troop", "$g_player_troop", 2),
        (create_mesh_overlay_with_tableau_material, reg0, -1, "tableau_game_party_window", "trp_player"),
        (position_set_x, pos1, 350),
        (position_set_y, pos1, 125),
        (overlay_set_position, reg0, pos1),

        ## toggle default
        (create_text_overlay, reg1, "@Default camera mode", tf_center_justify),
        (position_set_x, pos1, 500),
        (position_set_y, pos1, 650),
        (overlay_set_position, reg1, pos1),
        (position_set_x, pos1, 1500),
        (position_set_y, pos1, 1500),
        (overlay_set_size, reg1, pos1),
        (create_combo_label_overlay, "$g_dplmc_cam_activated"),
        (position_set_x, pos1, 500),
        (position_set_y, pos1, 600),
        (overlay_set_position, "$g_dplmc_cam_activated", pos1),
        # (position_set_x, pos1, 2000),
        # (position_set_y, pos1, 2000),
        # (overlay_set_size, "$g_dplmc_cam_activated", pos1),

        (overlay_add_item, "$g_dplmc_cam_activated", "@Keyboard"),
        (overlay_add_item, "$g_dplmc_cam_activated", "@Mouse"),
        (overlay_add_item, "$g_dplmc_cam_activated", "@Follower"),
        (store_sub, ":value", "$g_dplmc_cam_default", 1),
        (overlay_set_val, "$g_dplmc_cam_activated", ":value"),

        ## buttons
        (create_text_overlay, reg1, "@Raise camera", tf_center_justify),
        (position_set_x, pos1, 200),
        (position_set_y, pos1, 600),
        (overlay_set_position, reg1, pos1),
        (create_game_button_overlay, "$g_presentation_obj_1", s1),
        (position_set_x, pos1, 200),
        (position_set_y, pos1, 550),
        (overlay_set_position, "$g_presentation_obj_1", pos1),


        (create_text_overlay, reg1, "@Lower camera", tf_center_justify),
        (position_set_x, pos1, 200),
        (position_set_y, pos1, 400),
        (overlay_set_position, reg1, pos1),
        (create_game_button_overlay, "$g_presentation_obj_2", s2),
        (position_set_x, pos1, 200),
        (position_set_y, pos1, 350),
        (overlay_set_position, "$g_presentation_obj_2", pos1),

        (try_begin),
          (eq, "$g_dplmc_cam_default", camera_mouse),
          (create_text_overlay, reg1, "@Lower sensitivity", tf_center_justify),
        (else_try),
          (eq, "$g_dplmc_cam_default", camera_keyboard),
          (create_text_overlay, reg1, "@Tilt left", tf_center_justify),
        (else_try),
          (eq, "$g_dplmc_cam_default", camera_follow),
          (create_text_overlay, reg1, "@Prev troop", tf_center_justify),
        (try_end),
        (position_set_x, pos1, 100),
        (position_set_y, pos1, 500),
        (overlay_set_position, reg1, pos1),
        (create_game_button_overlay, "$g_presentation_obj_3", s3),
        (position_set_x, pos1, 100),
        (position_set_y, pos1, 450),
        (overlay_set_position, "$g_presentation_obj_3", pos1),

        (try_begin),
          (eq, "$g_dplmc_cam_default", camera_mouse),
          (create_text_overlay, reg1, "@Raise sensitivity", tf_center_justify),
        (else_try),
          (eq, "$g_dplmc_cam_default", camera_keyboard),
          (create_text_overlay, reg1, "@Tilt right", tf_center_justify),
        (else_try),
          (eq, "$g_dplmc_cam_default", camera_follow),
          (create_text_overlay, reg1, "@Next troop", tf_center_justify),
        (try_end),
        (position_set_x, pos1, 300),
        (position_set_y, pos1, 500),
        (overlay_set_position, reg1, pos1),
        (create_game_button_overlay, "$g_presentation_obj_4", s4),
        (position_set_x, pos1, 300),
        (position_set_y, pos1, 450),
        (overlay_set_position, "$g_presentation_obj_4", pos1),

        (try_begin),
          (eq, "$g_dplmc_cam_default", camera_follow),
          (create_text_overlay, reg1, "@Zoom in", tf_center_justify),
        (else_try),
          (create_text_overlay, reg1, "@Rotate up", tf_center_justify),
        (try_end),
        (position_set_x, pos1, 800),
        (position_set_y, pos1, 600),
        (overlay_set_position, reg1, pos1),
        (create_game_button_overlay, "$g_presentation_obj_11", s5),
        (position_set_x, pos1, 800),
        (position_set_y, pos1, 550),
        (overlay_set_position, "$g_presentation_obj_11", pos1),

        (try_begin),
          (eq, "$g_dplmc_cam_default", camera_follow),
          (create_text_overlay, reg1, "@Zoom out", tf_center_justify),
        (else_try),
          (create_text_overlay, reg1, "@Rotate down", tf_center_justify),
        (try_end),
        (position_set_x, pos1, 800),
        (position_set_y, pos1, 400),
        (overlay_set_position, reg1, pos1),
        (create_game_button_overlay, "$g_presentation_obj_12", s6),
        (position_set_x, pos1, 800),
        (position_set_y, pos1, 350),
        (overlay_set_position, "$g_presentation_obj_12", pos1),

        (try_begin),
          (neq, "$g_dplmc_cam_default", camera_follow),
          (create_text_overlay, reg1, "@Rotate left", tf_center_justify),
          (position_set_x, pos1, 700),
          (position_set_y, pos1, 500),
          (overlay_set_position, reg1, pos1),
        (try_end),

        (create_game_button_overlay, "$g_presentation_obj_13", s7),
        (position_set_x, pos1, 700),
        (position_set_y, pos1, 450),
        (overlay_set_position, "$g_presentation_obj_13", pos1),

        (try_begin),
          (neq, "$g_dplmc_cam_default", camera_follow),
          (create_text_overlay, reg1, "@Rotate right", tf_center_justify),
          (position_set_x, pos1, 900),
          (position_set_y, pos1, 500),
          (overlay_set_position, reg1, pos1),
        (try_end),

        (create_game_button_overlay, "$g_presentation_obj_14", s8),
        (position_set_x, pos1, 900),
        (position_set_y, pos1, 450),
        (overlay_set_position, "$g_presentation_obj_14", pos1),

        (create_text_overlay, "$g_presentation_obj_item_select_next", "@Press a key", tf_center_justify|tf_with_outline),
        (position_set_x, pos1, 500),
        (position_set_y, pos1, 450),
        (overlay_set_position, "$g_presentation_obj_item_select_next", pos1),
        (position_set_x, pos1, 2000),
        (position_set_y, pos1, 2000),
        (overlay_set_size, "$g_presentation_obj_item_select_next", pos1),
        (overlay_set_color, "$g_presentation_obj_item_select_next", 0xFFFFFF), #white since we have black bg
        (overlay_set_display, "$g_presentation_obj_item_select_next", 0),

        # done
        (create_game_button_overlay, "$g_close_equipment_selection", "str_done"),
        (position_set_x, pos1, 800),
        (position_set_y, pos1, 125),
        (overlay_set_position, "$g_close_equipment_selection", pos1),

        # reset
        (create_game_button_overlay, "$g_show_no_more_respawns_remained", "str_reset_to_default"),
        (position_set_x, pos1, 800),
        (position_set_y, pos1, 200),
        (overlay_set_position, "$g_show_no_more_respawns_remained", pos1),

        # description
        (store_sub, ":string", "$g_dplmc_cam_default", 1),
        (val_add, ":string", "str_camera_keyboard"),
        (create_text_overlay, reg1, ":string", tf_scrollable),
        (position_set_x, pos1, 40),
        (position_set_y, pos1, 60),
        (overlay_set_position, reg1, pos1),
        (position_set_x, pos1, 260),
        (position_set_y, pos1, 240),
        (overlay_set_area_size, reg1, pos1),

      ]),

    (ti_on_presentation_run,
      [
      ####### mouse fix pos system #######
      #(call_script, "script_mouse_fix_pos_run"),
      ####### mouse fix pos system #######

#When key is held down, change actual camera values?

      (try_begin),
        (gt, "$temp", -1),
        (overlay_set_display, "$g_presentation_obj_item_select_next", 1),
      (else_try),
        (overlay_set_display, "$g_presentation_obj_item_select_next", 0),
      (try_end),
      (try_for_range, ":cur_slot", 0, len(keys)),
        (troop_get_slot, ":key_no", "trp_temp_array_a", ":cur_slot"),
        (key_clicked, ":key_no"),
        (gt, "$temp", -1),
        (try_begin),
          (eq, "$temp", "$g_presentation_obj_1"),
          (assign, "$g_camera_adjust_add", ":key_no"),
        (else_try),
          (eq, "$temp", "$g_presentation_obj_2"),
          (assign, "$g_camera_adjust_sub", ":key_no"),
        (else_try),
          (eq, "$temp", "$g_presentation_obj_3"),
          (assign, "$g_cam_tilt_left", ":key_no"),
        (else_try),
          (eq, "$temp", "$g_presentation_obj_4"),
          (assign, "$g_cam_tilt_right", ":key_no"),
       (else_try),
          (eq, "$temp", "$g_presentation_obj_11"),
          (assign, "$g_camera_rot_up", ":key_no"),
        (else_try),
          (eq, "$temp", "$g_presentation_obj_12"),
          (assign, "$g_camera_rot_down", ":key_no"),
        (else_try),
          (eq, "$temp", "$g_presentation_obj_13"),
          (assign, "$g_camera_rot_left", ":key_no"),
        (else_try),
          (eq, "$temp", "$g_presentation_obj_14"),
          (assign, "$g_camera_rot_right", ":key_no"),
        (try_end),
        (store_add, ":dest_string", "str_key_0", ":cur_slot"),
        (str_store_string, s1, ":dest_string"),
        (overlay_set_text, "$temp", s1),
        (overlay_set_alpha, "$temp", 0xff),
        (assign, "$temp", -1),
      (try_end),
    ]),

    (ti_on_presentation_event_state_change,
      [
        (store_trigger_param_1, ":object"),

        (set_fixed_point_multiplier, 1000),
        (try_begin),
          (eq, ":object", "$g_show_no_more_respawns_remained"),
          (call_script, "script_setup_camera_keys"),
        (else_try), #toggling camera mode means reloading string descriptions
          (eq, ":object", "$g_dplmc_cam_activated"),
          (store_trigger_param_2, ":value"),
          (store_add, "$g_dplmc_cam_default", ":value", 1),
        (else_try),
          (eq, ":object", "$g_close_equipment_selection"),
          # provide actual exit conditions
          (assign, "$g_presentation_next_presentation", -1),
          # (try_begin),
            # (gt, "$g_presentation_next_presentation", 0),
            # (presentation_set_duration, 0),
            # (start_presentation, "$g_presentation_next_presentation"),
          # (else_try),
            # (presentation_set_duration, 0),
          # (try_end),
        (else_try),
          (gt, ":object", -1),
            #reset to black
          (overlay_set_alpha, "$g_presentation_obj_1", 0xff),
          (overlay_set_alpha, "$g_presentation_obj_2", 0xff),
          (overlay_set_alpha, "$g_presentation_obj_3", 0xff),
          (overlay_set_alpha, "$g_presentation_obj_4", 0xff),

          (overlay_set_alpha, "$g_presentation_obj_11",0xff),
          (overlay_set_alpha, "$g_presentation_obj_12",0xff),
          (overlay_set_alpha, "$g_presentation_obj_13",0xff),
          (overlay_set_alpha, "$g_presentation_obj_14",0xff),
          (assign, "$temp", ":object"),
          (overlay_set_alpha, "$temp", 0x80),
        (try_end),
        (try_begin),#done/reset
          (this_or_next|eq, ":object", "$g_show_no_more_respawns_remained"),
          (this_or_next|eq, ":object", "$g_close_equipment_selection"),
          (eq, ":object", "$g_dplmc_cam_activated"),
          (assign, "$temp", 0),
          (presentation_set_duration, 0),
        (try_end),
    ]),
  ])
