# -*- coding: cp1254 -*-
# package initializer for notifications menus

from game_menus.notifications.mnu_notification_truce_expired import notification_truce_expired_menu
from game_menus.notifications.mnu_notification_feast_quest_expired import notification_feast_quest_expired_menu
from game_menus.notifications.mnu_notification_sortie_possible import notification_sortie_possible_menu
from game_menus.notifications.mnu_notification_casus_belli_expired import notification_casus_belli_expired_menu
from game_menus.notifications.mnu_notification_lord_defects import notification_lord_defects_menu
from game_menus.notifications.mnu_notification_treason_indictment import notification_treason_indictment_menu
from game_menus.notifications.mnu_notification_border_incident import notification_border_incident_menu
from game_menus.notifications.mnu_notification_player_faction_active import notification_player_faction_active_menu
from game_menus.notifications.mnu_notification_court_lost import notification_court_lost_menu
from game_menus.notifications.mnu_notification_player_faction_deactive import notification_player_faction_deactive_menu
from game_menus.notifications.mnu_notification_player_wedding_day import notification_player_wedding_day_menu
from game_menus.notifications.mnu_notification_player_kingdom_holds_feast import notification_player_kingdom_holds_feast_menu
from game_menus.notifications.mnu_notification_center_under_siege import notification_center_under_siege_menu
from game_menus.notifications.mnu_notification_village_raided import notification_village_raided_menu
from game_menus.notifications.mnu_notification_village_raid_started import notification_village_raid_started_menu
from game_menus.notifications.mnu_notification_one_faction_left import notification_one_faction_left_menu
from game_menus.notifications.mnu_notification_oath_renounced_faction_defeated import notification_oath_renounced_faction_defeated_menu
from game_menus.notifications.mnu_notification_center_lost import notification_center_lost_menu
from game_menus.notifications.mnu_notification_troop_left_players_faction import notification_troop_left_players_faction_menu
from game_menus.notifications.mnu_notification_troop_joined_players_faction import notification_troop_joined_players_faction_menu
from game_menus.notifications.mnu_notification_war_declared import notification_war_declared_menu
from game_menus.notifications.mnu_notification_peace_declared import notification_peace_declared_menu
from game_menus.notifications.mnu_notification_faction_defeated import notification_faction_defeated_menu
from game_menus.notifications.mnu_notification_rebels_switched_to_faction import notification_rebels_switched_to_faction_menu
from game_menus.notifications.mnu_notification_player_should_consult import notification_player_should_consult_menu
from game_menus.notifications.mnu_notification_player_feast_in_progress import notification_player_feast_in_progress_menu
from game_menus.notifications.mnu_notification_lady_requests_visit import notification_lady_requests_visit_menu
from game_menus.notifications.mnu_garden import garden_menu
from game_menus.notifications.mnu_kill_local_merchant_begin import kill_local_merchant_begin_menu
from game_menus.notifications.mnu_debug_alert_from_s65 import debug_alert_from_s65_menu
from game_menus.notifications.mnu_notification_player_faction_political_issue_resolved import notification_player_faction_political_issue_resolved_menu
from game_menus.notifications.mnu_notification_player_faction_political_issue_resolved_for_player import notification_player_faction_political_issue_resolved_for_player_menu
from game_menus.notifications.mnu_notification_relieved_as_marshal import notification_relieved_as_marshal_menu
from game_menus.notifications.mnu_dplmc_manage_loot_pool import dplmc_manage_loot_pool_menu
from game_menus.notifications.mnu_dplmc_auto_loot import dplmc_auto_loot_menu

notifications_menus = []
notifications_menus.extend(notification_truce_expired_menu)
notifications_menus.extend(notification_feast_quest_expired_menu)
notifications_menus.extend(notification_sortie_possible_menu)
notifications_menus.extend(notification_casus_belli_expired_menu)
notifications_menus.extend(notification_lord_defects_menu)
notifications_menus.extend(notification_treason_indictment_menu)
notifications_menus.extend(notification_border_incident_menu)
notifications_menus.extend(notification_player_faction_active_menu)
notifications_menus.extend(notification_court_lost_menu)
notifications_menus.extend(notification_player_faction_deactive_menu)
notifications_menus.extend(notification_player_wedding_day_menu)
notifications_menus.extend(notification_player_kingdom_holds_feast_menu)
notifications_menus.extend(notification_center_under_siege_menu)
notifications_menus.extend(notification_village_raided_menu)
notifications_menus.extend(notification_village_raid_started_menu)
notifications_menus.extend(notification_one_faction_left_menu)
notifications_menus.extend(notification_oath_renounced_faction_defeated_menu)
notifications_menus.extend(notification_center_lost_menu)
notifications_menus.extend(notification_troop_left_players_faction_menu)
notifications_menus.extend(notification_troop_joined_players_faction_menu)
notifications_menus.extend(notification_war_declared_menu)
notifications_menus.extend(notification_peace_declared_menu)
notifications_menus.extend(notification_faction_defeated_menu)
notifications_menus.extend(notification_rebels_switched_to_faction_menu)
notifications_menus.extend(notification_player_should_consult_menu)
notifications_menus.extend(notification_player_feast_in_progress_menu)
notifications_menus.extend(notification_lady_requests_visit_menu)
notifications_menus.extend(garden_menu)
notifications_menus.extend(kill_local_merchant_begin_menu)
notifications_menus.extend(debug_alert_from_s65_menu)
notifications_menus.extend(notification_player_faction_political_issue_resolved_menu)
notifications_menus.extend(notification_player_faction_political_issue_resolved_for_player_menu)
notifications_menus.extend(notification_relieved_as_marshal_menu)
notifications_menus.extend(dplmc_manage_loot_pool_menu)
notifications_menus.extend(dplmc_auto_loot_menu)

