# -*- coding: cp1254 -*-
# package initializer for training menus

from game_menus.training.mnu_training_ground import training_ground_menu
from game_menus.training.mnu_training_ground_selection_details_melee_1 import training_ground_selection_details_melee_1_menu
from game_menus.training.mnu_training_ground_selection_details_melee_2 import training_ground_selection_details_melee_2_menu
from game_menus.training.mnu_training_ground_selection_details_mounted import training_ground_selection_details_mounted_menu
from game_menus.training.mnu_training_ground_selection_details_ranged_1 import training_ground_selection_details_ranged_1_menu
from game_menus.training.mnu_training_ground_selection_details_ranged_2 import training_ground_selection_details_ranged_2_menu
from game_menus.training.mnu_training_ground_description import training_ground_description_menu
from game_menus.training.mnu_training_ground_training_result import training_ground_training_result_menu

training_menus = []
training_menus.extend(training_ground_menu)
training_menus.extend(training_ground_selection_details_melee_1_menu)
training_menus.extend(training_ground_selection_details_melee_2_menu)
training_menus.extend(training_ground_selection_details_mounted_menu)
training_menus.extend(training_ground_selection_details_ranged_1_menu)
training_menus.extend(training_ground_selection_details_ranged_2_menu)
training_menus.extend(training_ground_description_menu)
training_menus.extend(training_ground_training_result_menu)

