# -*- coding: cp1254 -*-
from header_common import *
from header_operations import *
from header_parties import *
from header_items import *
from header_skills import *
from header_triggers import *
from header_troops import *
from header_music import *
from header_terrain_types import *
from module_factions import dplmc_factions_end

from module_constants import *

from compiler import *
####################################################################################################################
# Simple triggers are the alternative to old style triggers. They do not preserve state, and thus simpler to maintain.
#
#  Each simple trigger contains the following fields:
# 1) Check interval: How frequently this trigger will be checked
# 2) Operation block: This must be a valid operation block. See header_operations.py for reference.
####################################################################################################################
# Granular layout: one file per trigger block in source/simple_triggers/.

from simple_triggers.deprecated_party_encounter import deprecated_party_encounter_simple_triggers
from simple_triggers.deprecated_simulate_battle import deprecated_simulate_battle_simple_triggers
from simple_triggers.auto_besiege_renown import auto_besiege_renown_simple_triggers
from simple_triggers.captive_party_relocate import captive_party_relocate_simple_triggers
from simple_triggers.auto_menu import auto_menu_simple_triggers
from simple_triggers.auto_besiege_progress import auto_besiege_progress_simple_triggers
from simple_triggers.notification_menus import notification_menus_simple_triggers
from simple_triggers.music import music_simple_triggers
from simple_triggers.escort_caravan import escort_caravan_simple_triggers
from simple_triggers.kingdom_morale_decay import kingdom_morale_decay_simple_triggers
from simple_triggers.auto_upgrade_troops import auto_upgrade_troops_simple_triggers
from simple_triggers.locate_kingdom_ladies import locate_kingdom_ladies_simple_triggers
from simple_triggers.party_commander_error_check import party_commander_error_check_simple_triggers
from simple_triggers.kingdom_ladies_messages import kingdom_ladies_messages_simple_triggers
from simple_triggers.player_raiding_village import player_raiding_village_simple_triggers
from simple_triggers.player_raiding_distance import player_raiding_distance_simple_triggers
from simple_triggers.pay_day import pay_day_simple_triggers
from simple_triggers.mercenary_contract_expiry import mercenary_contract_expiry_simple_triggers
from simple_triggers.courtship_reset import courtship_reset_simple_triggers
from simple_triggers.reset_time_to_spare import reset_time_to_spare_simple_triggers
from simple_triggers.banner_selection_menu import banner_selection_menu_simple_triggers
from simple_triggers.party_morale import party_morale_simple_triggers
from simple_triggers.party_ai_prisoner_pruning import party_ai_prisoner_pruning_simple_triggers
from simple_triggers.hero_income import hero_income_simple_triggers
from simple_triggers.hero_wealth_hiring import hero_wealth_hiring_simple_triggers
from simple_triggers.center_prosperity_convergence import center_prosperity_convergence_simple_triggers
from simple_triggers.half_payment_resting import half_payment_resting_simple_triggers
from simple_triggers.diplomatic_indices import diplomatic_indices_simple_triggers
from simple_triggers.hero_party_xp import hero_party_xp_simple_triggers
from simple_triggers.process_sieges import process_sieges_simple_triggers
from simple_triggers.process_village_raids import process_village_raids_simple_triggers
from simple_triggers.decide_vassal_ai import decide_vassal_ai_simple_triggers
from simple_triggers.marshall_elections import marshall_elections_simple_triggers
from simple_triggers.lord_fief_relations import lord_fief_relations_simple_triggers
from simple_triggers.political_triggers import political_triggers_simple_triggers
from simple_triggers.lord_political_calculations import lord_political_calculations_simple_triggers
from simple_triggers.readiness_disabled import readiness_disabled_simple_triggers
from simple_triggers.process_vassal_ai import process_vassal_ai_simple_triggers
from simple_triggers.process_alarms import process_alarms_simple_triggers
from simple_triggers.process_siege_ai import process_siege_ai_simple_triggers
from simple_triggers.decide_faction_ais import decide_faction_ais_simple_triggers
from simple_triggers.decide_faction_ai_flag import decide_faction_ai_flag_simple_triggers
from simple_triggers.count_faction_armies import count_faction_armies_simple_triggers
from simple_triggers.reset_hero_quest_status import reset_hero_quest_status_simple_triggers
from simple_triggers.refresh_merchant_inventories import refresh_merchant_inventories_simple_triggers
from simple_triggers.refresh_village_defenders import refresh_village_defenders_simple_triggers
from simple_triggers.refresh_cattle_in_villages import refresh_cattle_in_villages_simple_triggers
from simple_triggers.offer_player_join_faction import offer_player_join_faction_simple_triggers
from simple_triggers.recalculate_lord_seeds import recalculate_lord_seeds_simple_triggers
from simple_triggers.rebellion_troop_removal import rebellion_troop_removal_simple_triggers
from simple_triggers.hero_prisoner_escape import hero_prisoner_escape_simple_triggers
from simple_triggers.captured_center_ownership import captured_center_ownership_simple_triggers
from simple_triggers.spawn_merchant_caravans import spawn_merchant_caravans_simple_triggers
from simple_triggers.trade_good_prices import trade_good_prices_simple_triggers
from simple_triggers.merchant_ai import merchant_ai_simple_triggers
from simple_triggers.zaitenko_reinforcements import zaitenko_reinforcements_simple_triggers
from simple_triggers.village_farmer_ai import village_farmer_ai_simple_triggers
from simple_triggers.increase_castle_food import increase_castle_food_simple_triggers
from simple_triggers.cache_party_strengths import cache_party_strengths_simple_triggers
from simple_triggers.center_alarms import center_alarms_simple_triggers
from simple_triggers.consume_food import consume_food_simple_triggers
from simple_triggers.item_modifiers_for_food import item_modifiers_for_food_simple_triggers
from simple_triggers.assign_lords_to_centers import assign_lords_to_centers_simple_triggers
from simple_triggers.update_player_icon import update_player_icon_simple_triggers
from simple_triggers.bandit_target_value import bandit_target_value_simple_triggers
from simple_triggers.backup_activate_player_faction import backup_activate_player_faction_simple_triggers
from simple_triggers.prisoner_join_escape import prisoner_join_escape_simple_triggers
from simple_triggers.ransom_offer import ransom_offer_simple_triggers
from simple_triggers.ransom_exchange import ransom_exchange_simple_triggers
from simple_triggers.mercenary_troops_in_towns import mercenary_troops_in_towns_simple_triggers
from simple_triggers.update_taverngoers import update_taverngoers_simple_triggers
from simple_triggers.random_walker_types import random_walker_types_simple_triggers
from simple_triggers.center_upgrades import center_upgrades_simple_triggers
from simple_triggers.tournaments_in_towns import tournaments_in_towns_simple_triggers
from simple_triggers.tournament_placement_reset import tournament_placement_reset_simple_triggers
from simple_triggers.give_center_to_player import give_center_to_player_simple_triggers
from simple_triggers.resting_denars import resting_denars_simple_triggers
from simple_triggers.spawn_bandits import spawn_bandits_simple_triggers
from simple_triggers.update_party_limits import update_party_limits_simple_triggers
from simple_triggers.faction_defeated_check import faction_defeated_check_simple_triggers
from simple_triggers.player_court_captured import player_court_captured_simple_triggers
from simple_triggers.reduce_renown import reduce_renown_simple_triggers
from simple_triggers.read_books import read_books_simple_triggers
from simple_triggers.remove_cattle_herds import remove_cattle_herds_simple_triggers
from simple_triggers.village_school_relation import village_school_relation_simple_triggers
from simple_triggers.quest_triggers import quest_triggers_simple_triggers
from simple_triggers.report_to_army_quest import report_to_army_quest_simple_triggers
from simple_triggers.army_quest_initializer import army_quest_initializer_simple_triggers
from simple_triggers.move_cattle_herd import move_cattle_herd_simple_triggers
from simple_triggers.hero_party_stop_following import hero_party_stop_following_simple_triggers
from simple_triggers.deliver_cattle import deliver_cattle_simple_triggers
from simple_triggers.train_peasants import train_peasants_simple_triggers
from simple_triggers.scout_waypoints import scout_waypoints_simple_triggers
from simple_triggers.kill_local_merchant import kill_local_merchant_simple_triggers
from simple_triggers.collect_taxes_quest import collect_taxes_quest_simple_triggers
from simple_triggers.persuade_lords_to_make_peace import persuade_lords_to_make_peace_simple_triggers
from simple_triggers.npc_changes import npc_changes_simple_triggers
from simple_triggers.hero_change_faction import hero_change_faction_simple_triggers
from simple_triggers.debug_besieging_centers import debug_besieging_centers_simple_triggers
from simple_triggers.report_control_check import report_control_check_simple_triggers
from simple_triggers.future_use_slots import future_use_slots_simple_triggers
from simple_triggers.captive_party_cleanup import captive_party_cleanup_simple_triggers
from simple_triggers.dplmc_daily_updates import dplmc_daily_updates_simple_triggers
from simple_triggers.food_bonus_reset import food_bonus_reset_simple_triggers
from simple_triggers.dummy_empty_triggers import dummy_empty_triggers_simple_triggers
from simple_triggers.dummy_96_save import dummy_96_save_simple_triggers
from simple_triggers.spouse_ai_thinking import spouse_ai_thinking_simple_triggers
from simple_triggers.recruiter_ai import recruiter_ai_simple_triggers
from simple_triggers.village_reservation import village_reservation_simple_triggers
from simple_triggers.chancellor_ai import chancellor_ai_simple_triggers
from simple_triggers.process_messengers import process_messengers_simple_triggers
from simple_triggers.constable_training import constable_training_simple_triggers
from simple_triggers.patrol_wages import patrol_wages_simple_triggers
from simple_triggers.create_ai_patrols import create_ai_patrols_simple_triggers
from simple_triggers.patrol_ai import patrol_ai_simple_triggers
from simple_triggers.scout_ai import scout_ai_simple_triggers
from simple_triggers.policy import policy_simple_triggers
from simple_triggers.affiliated_family_ai import affiliated_family_ai_simple_triggers
from simple_triggers.officer_post_demotion import officer_post_demotion_simple_triggers
from simple_triggers.kingdom_attitude_changes import kingdom_attitude_changes_simple_triggers
from simple_triggers.town_population_dynamics import town_population_dynamics_simple_triggers
from simple_triggers.debt_consequences import debt_consequences_simple_triggers
from simple_triggers.solicit_clients import solicit_clients_simple_triggers
from simple_triggers.beer_drinking import beer_drinking_simple_triggers
from simple_triggers.beer_drinking_rest import beer_drinking_rest_simple_triggers
from simple_triggers.manage_inventory_trigger import manage_inventory_trigger_simple_triggers

simple_triggers = []
simple_triggers.extend(deprecated_party_encounter_simple_triggers)
simple_triggers.extend(deprecated_simulate_battle_simple_triggers)
simple_triggers.extend(auto_besiege_renown_simple_triggers)
simple_triggers.extend(captive_party_relocate_simple_triggers)
simple_triggers.extend(auto_menu_simple_triggers)
simple_triggers.extend(auto_besiege_progress_simple_triggers)
simple_triggers.extend(notification_menus_simple_triggers)
simple_triggers.extend(music_simple_triggers)
simple_triggers.extend(escort_caravan_simple_triggers)
simple_triggers.extend(kingdom_morale_decay_simple_triggers)
simple_triggers.extend(auto_upgrade_troops_simple_triggers)
simple_triggers.extend(locate_kingdom_ladies_simple_triggers)
simple_triggers.extend(party_commander_error_check_simple_triggers)
simple_triggers.extend(kingdom_ladies_messages_simple_triggers)
simple_triggers.extend(player_raiding_village_simple_triggers)
simple_triggers.extend(player_raiding_distance_simple_triggers)
simple_triggers.extend(pay_day_simple_triggers)
simple_triggers.extend(mercenary_contract_expiry_simple_triggers)
simple_triggers.extend(courtship_reset_simple_triggers)
simple_triggers.extend(reset_time_to_spare_simple_triggers)
simple_triggers.extend(banner_selection_menu_simple_triggers)
simple_triggers.extend(party_morale_simple_triggers)
simple_triggers.extend(party_ai_prisoner_pruning_simple_triggers)
simple_triggers.extend(hero_income_simple_triggers)
simple_triggers.extend(hero_wealth_hiring_simple_triggers)
simple_triggers.extend(center_prosperity_convergence_simple_triggers)
simple_triggers.extend(half_payment_resting_simple_triggers)
simple_triggers.extend(diplomatic_indices_simple_triggers)
simple_triggers.extend(hero_party_xp_simple_triggers)
simple_triggers.extend(process_sieges_simple_triggers)
simple_triggers.extend(process_village_raids_simple_triggers)
simple_triggers.extend(decide_vassal_ai_simple_triggers)
simple_triggers.extend(marshall_elections_simple_triggers)
simple_triggers.extend(lord_fief_relations_simple_triggers)
simple_triggers.extend(political_triggers_simple_triggers)
simple_triggers.extend(lord_political_calculations_simple_triggers)
simple_triggers.extend(readiness_disabled_simple_triggers)
simple_triggers.extend(process_vassal_ai_simple_triggers)
simple_triggers.extend(process_alarms_simple_triggers)
simple_triggers.extend(process_siege_ai_simple_triggers)
simple_triggers.extend(decide_faction_ais_simple_triggers)
simple_triggers.extend(decide_faction_ai_flag_simple_triggers)
simple_triggers.extend(count_faction_armies_simple_triggers)
simple_triggers.extend(reset_hero_quest_status_simple_triggers)
simple_triggers.extend(refresh_merchant_inventories_simple_triggers)
simple_triggers.extend(refresh_village_defenders_simple_triggers)
simple_triggers.extend(refresh_cattle_in_villages_simple_triggers)
simple_triggers.extend(offer_player_join_faction_simple_triggers)
simple_triggers.extend(recalculate_lord_seeds_simple_triggers)
simple_triggers.extend(rebellion_troop_removal_simple_triggers)
simple_triggers.extend(hero_prisoner_escape_simple_triggers)
simple_triggers.extend(captured_center_ownership_simple_triggers)
simple_triggers.extend(spawn_merchant_caravans_simple_triggers)
simple_triggers.extend(trade_good_prices_simple_triggers)
simple_triggers.extend(merchant_ai_simple_triggers)
simple_triggers.extend(zaitenko_reinforcements_simple_triggers)
simple_triggers.extend(village_farmer_ai_simple_triggers)
simple_triggers.extend(increase_castle_food_simple_triggers)
simple_triggers.extend(cache_party_strengths_simple_triggers)
simple_triggers.extend(center_alarms_simple_triggers)
simple_triggers.extend(consume_food_simple_triggers)
simple_triggers.extend(item_modifiers_for_food_simple_triggers)
simple_triggers.extend(assign_lords_to_centers_simple_triggers)
simple_triggers.extend(update_player_icon_simple_triggers)
simple_triggers.extend(bandit_target_value_simple_triggers)
simple_triggers.extend(backup_activate_player_faction_simple_triggers)
simple_triggers.extend(prisoner_join_escape_simple_triggers)
simple_triggers.extend(ransom_offer_simple_triggers)
simple_triggers.extend(ransom_exchange_simple_triggers)
simple_triggers.extend(mercenary_troops_in_towns_simple_triggers)
simple_triggers.extend(update_taverngoers_simple_triggers)
simple_triggers.extend(random_walker_types_simple_triggers)
simple_triggers.extend(center_upgrades_simple_triggers)
simple_triggers.extend(tournaments_in_towns_simple_triggers)
simple_triggers.extend(tournament_placement_reset_simple_triggers)
simple_triggers.extend(give_center_to_player_simple_triggers)
simple_triggers.extend(resting_denars_simple_triggers)
simple_triggers.extend(spawn_bandits_simple_triggers)
simple_triggers.extend(update_party_limits_simple_triggers)
simple_triggers.extend(faction_defeated_check_simple_triggers)
simple_triggers.extend(player_court_captured_simple_triggers)
simple_triggers.extend(reduce_renown_simple_triggers)
simple_triggers.extend(read_books_simple_triggers)
simple_triggers.extend(remove_cattle_herds_simple_triggers)
simple_triggers.extend(village_school_relation_simple_triggers)
simple_triggers.extend(quest_triggers_simple_triggers)
simple_triggers.extend(report_to_army_quest_simple_triggers)
simple_triggers.extend(army_quest_initializer_simple_triggers)
simple_triggers.extend(move_cattle_herd_simple_triggers)
simple_triggers.extend(hero_party_stop_following_simple_triggers)
simple_triggers.extend(deliver_cattle_simple_triggers)
simple_triggers.extend(train_peasants_simple_triggers)
simple_triggers.extend(scout_waypoints_simple_triggers)
simple_triggers.extend(kill_local_merchant_simple_triggers)
simple_triggers.extend(collect_taxes_quest_simple_triggers)
simple_triggers.extend(persuade_lords_to_make_peace_simple_triggers)
simple_triggers.extend(npc_changes_simple_triggers)
simple_triggers.extend(hero_change_faction_simple_triggers)
simple_triggers.extend(debug_besieging_centers_simple_triggers)
simple_triggers.extend(report_control_check_simple_triggers)
simple_triggers.extend(future_use_slots_simple_triggers)
simple_triggers.extend(captive_party_cleanup_simple_triggers)
simple_triggers.extend(dplmc_daily_updates_simple_triggers)
simple_triggers.extend(food_bonus_reset_simple_triggers)
simple_triggers.extend(dummy_empty_triggers_simple_triggers)
simple_triggers.extend(dummy_96_save_simple_triggers)
simple_triggers.extend(spouse_ai_thinking_simple_triggers)
simple_triggers.extend(recruiter_ai_simple_triggers)
simple_triggers.extend(village_reservation_simple_triggers)
simple_triggers.extend(chancellor_ai_simple_triggers)
simple_triggers.extend(process_messengers_simple_triggers)
simple_triggers.extend(constable_training_simple_triggers)
simple_triggers.extend(patrol_wages_simple_triggers)
simple_triggers.extend(create_ai_patrols_simple_triggers)
simple_triggers.extend(patrol_ai_simple_triggers)
simple_triggers.extend(scout_ai_simple_triggers)
simple_triggers.extend(policy_simple_triggers)
simple_triggers.extend(affiliated_family_ai_simple_triggers)
simple_triggers.extend(officer_post_demotion_simple_triggers)
simple_triggers.extend(kingdom_attitude_changes_simple_triggers)
simple_triggers.extend(town_population_dynamics_simple_triggers)
simple_triggers.extend(debt_consequences_simple_triggers)
simple_triggers.extend(solicit_clients_simple_triggers)
simple_triggers.extend(beer_drinking_simple_triggers)
simple_triggers.extend(beer_drinking_rest_simple_triggers)
simple_triggers.extend(manage_inventory_trigger_simple_triggers)

# modmerger_start version=201 type=2
try:
    component_name = "simple_triggers"
    var_set = { "simple_triggers" : simple_triggers }
    from modmerger import modmerge
    modmerge(var_set)
except:
    raise
# modmerger_end
