# -*- coding: cp1254 -*-
from header_common import *
from header_presentations import *
from header_mission_templates import *
from ID_meshes import *
from header_operations import *
from header_triggers import *
from module_constants import *
from header_terrain_types import *
from module_items import *
from module_factions import *
from header_items import *
from compiler import *

from presentations.prsnt_all_items import all_items
from presentations.prsnt_arena_training import arena_training
from presentations.prsnt_auto_trade_options import auto_trade_options
from presentations.prsnt_bank import bank
from presentations.prsnt_bank_quickview import bank_quickview
from presentations.prsnt_banner_background_selection import banner_background_selection
from presentations.prsnt_banner_charge_positioning import banner_charge_positioning
from presentations.prsnt_banner_charge_selection import banner_charge_selection
from presentations.prsnt_banner_flag_map_type_selection import banner_flag_map_type_selection
from presentations.prsnt_banner_flag_type_selection import banner_flag_type_selection
from presentations.prsnt_banner_selection import banner_selection
from presentations.prsnt_battle import battle
from presentations.prsnt_battle_old import battle_excluded
from presentations.prsnt_blackjack import blackjack
from presentations.prsnt_budget_report import budget_report
from presentations.prsnt_change_color import change_color
from presentations.prsnt_color_selection import color_selection
from presentations.prsnt_companion_overview import companion_overview
from presentations.prsnt_custom_banner import custom_banner
from presentations.prsnt_customize_armor import customize_armor
from presentations.prsnt_deposit_withdraw_money import deposit_withdraw_money
from presentations.prsnt_dices_game import dices_game
from presentations.prsnt_dplmc_auto_sell_options import dplmc_auto_sell_options
from presentations.prsnt_dplmc_autoloot_upgrade_management import dplmc_autoloot_upgrade_management
from presentations.prsnt_dplmc_peace_terms import dplmc_peace_terms
from presentations.prsnt_dplmc_policy_management import dplmc_policy_management
from presentations.prsnt_dplmc_set_vassal_title import dplmc_set_vassal_title
from presentations.prsnt_dplmc_shopping_list_of_food import dplmc_shopping_list_of_food
from presentations.prsnt_food_options import food_options
from presentations.prsnt_formation_mod_option import formation_mod_option
from presentations.prsnt_game_before_quit import game_before_quit
from presentations.prsnt_game_credits import game_credits
from presentations.prsnt_game_custom_battle_designer import game_custom_battle_designer
from presentations.prsnt_game_multiplayer_admin_panel import game_multiplayer_admin_panel
from presentations.prsnt_game_profile_banner_selection import game_profile_banner_selection
from presentations.prsnt_jrider_character_relation_report import jrider_character_relation_report
from presentations.prsnt_jrider_faction_relations_report import jrider_faction_relations_report
from presentations.prsnt_manage_inventory import manage_inventory
from presentations.prsnt_marshall_selection import marshall_selection
from presentations.prsnt_mini_map import mini_map
from presentations.prsnt_mini_map_bar import mini_map_bar
from presentations.prsnt_modify_slots import modify_slots
from presentations.prsnt_multiplayer_destructible_targets_display import multiplayer_destructible_targets_display
from presentations.prsnt_multiplayer_duel_start_counter import multiplayer_duel_start_counter
from presentations.prsnt_multiplayer_escape_menu import multiplayer_escape_menu
from presentations.prsnt_multiplayer_flag_projection_display import multiplayer_flag_projection_display
from presentations.prsnt_multiplayer_flag_projection_display_bt import multiplayer_flag_projection_display_bt
from presentations.prsnt_multiplayer_item_select import multiplayer_item_select
from presentations.prsnt_multiplayer_message_1 import multiplayer_message_1
from presentations.prsnt_multiplayer_message_2 import multiplayer_message_2
from presentations.prsnt_multiplayer_message_3 import multiplayer_message_3
from presentations.prsnt_multiplayer_poll import multiplayer_poll
from presentations.prsnt_multiplayer_poll_menu import multiplayer_poll_menu
from presentations.prsnt_multiplayer_respawn_time_counter import multiplayer_respawn_time_counter
from presentations.prsnt_multiplayer_round_time_counter import multiplayer_round_time_counter
from presentations.prsnt_multiplayer_show_factions_list import multiplayer_show_factions_list
from presentations.prsnt_multiplayer_show_maps_list import multiplayer_show_maps_list
from presentations.prsnt_multiplayer_show_number_of_bots_list import multiplayer_show_number_of_bots_list
from presentations.prsnt_multiplayer_show_players_list import multiplayer_show_players_list
from presentations.prsnt_multiplayer_stats_chart import multiplayer_stats_chart
from presentations.prsnt_multiplayer_stats_chart_deathmatch import multiplayer_stats_chart_deathmatch
from presentations.prsnt_multiplayer_team_score_display import multiplayer_team_score_display
from presentations.prsnt_multiplayer_team_select import multiplayer_team_select
from presentations.prsnt_multiplayer_troop_select import multiplayer_troop_select
from presentations.prsnt_multiplayer_welcome_message import multiplayer_welcome_message
from presentations.prsnt_name_kingdom import name_kingdom
from presentations.prsnt_order_display import order_display
from presentations.prsnt_redefine_keys import redefine_keys
from presentations.prsnt_retirement import retirement
from presentations.prsnt_sliders import sliders
from presentations.prsnt_spawn_diagnostics import spawn_diagnostics
from presentations.prsnt_three_card import three_card
from presentations.prsnt_troop_ratio_bar import troop_ratio_bar
from presentations.prsnt_tutorial_show_mouse_movement import tutorial_show_mouse_movement
from presentations.prsnt_world_map import world_map
from presentations.prsnt_cc_relations_with_factions import cc_relations_with_factions
from presentations.prsnt_cc_relations_with_lords_by_faction import cc_relations_with_lords_by_faction
from presentations.prsnt_cc_color_editor import cc_color_editor

presentations = []
presentations.append(all_items)
presentations.append(arena_training)
presentations.append(auto_trade_options)
presentations.append(bank)
presentations.append(bank_quickview)
presentations.append(banner_background_selection)
presentations.append(banner_charge_positioning)
presentations.append(banner_charge_selection)
presentations.append(banner_flag_map_type_selection)
presentations.append(banner_flag_type_selection)
presentations.append(banner_selection)
presentations.append(battle)
presentations.append(battle_excluded)
presentations.append(blackjack)
presentations.append(budget_report)
presentations.append(change_color)
presentations.append(color_selection)
presentations.append(companion_overview)
presentations.append(custom_banner)
presentations.append(customize_armor)
presentations.append(deposit_withdraw_money)
presentations.append(dices_game)
presentations.append(dplmc_auto_sell_options)
presentations.append(dplmc_autoloot_upgrade_management)
presentations.append(dplmc_peace_terms)
presentations.append(dplmc_policy_management)
presentations.append(dplmc_set_vassal_title)
presentations.append(dplmc_shopping_list_of_food)
presentations.append(food_options)
presentations.append(formation_mod_option)
presentations.append(game_before_quit)
presentations.append(game_credits)
presentations.append(game_custom_battle_designer)
presentations.append(game_multiplayer_admin_panel)
presentations.append(game_profile_banner_selection)
presentations.append(jrider_character_relation_report)
presentations.append(jrider_faction_relations_report)
presentations.append(manage_inventory)
presentations.append(marshall_selection)
presentations.append(mini_map)
presentations.append(mini_map_bar)
presentations.append(modify_slots)
presentations.append(multiplayer_destructible_targets_display)
presentations.append(multiplayer_duel_start_counter)
presentations.append(multiplayer_escape_menu)
presentations.append(multiplayer_flag_projection_display)
presentations.append(multiplayer_flag_projection_display_bt)
presentations.append(multiplayer_item_select)
presentations.append(multiplayer_message_1)
presentations.append(multiplayer_message_2)
presentations.append(multiplayer_message_3)
presentations.append(multiplayer_poll)
presentations.append(multiplayer_poll_menu)
presentations.append(multiplayer_respawn_time_counter)
presentations.append(multiplayer_round_time_counter)
presentations.append(multiplayer_show_factions_list)
presentations.append(multiplayer_show_maps_list)
presentations.append(multiplayer_show_number_of_bots_list)
presentations.append(multiplayer_show_players_list)
presentations.append(multiplayer_stats_chart)
presentations.append(multiplayer_stats_chart_deathmatch)
presentations.append(multiplayer_team_score_display)
presentations.append(multiplayer_team_select)
presentations.append(multiplayer_troop_select)
presentations.append(multiplayer_welcome_message)
presentations.append(name_kingdom)
presentations.append(order_display)
presentations.append(redefine_keys)
presentations.append(retirement)
presentations.append(sliders)
presentations.append(spawn_diagnostics)
presentations.append(three_card)
presentations.append(troop_ratio_bar)
presentations.append(tutorial_show_mouse_movement)
presentations.append(world_map)
presentations.append(cc_relations_with_factions)
presentations.append(cc_relations_with_lords_by_faction)
presentations.append(cc_color_editor)

# modmerger_start version=201 type=2
try:
    component_name = "presentations"
    var_set = { "presentations" : presentations }
    from modmerger import modmerge
    modmerge(var_set)
except:
    raise
# modmerger_end

try:
    var_set = { "presentations" : presentations }
    from xgm_mod_options_presentations import modmerge
    modmerge(var_set)
except:
    raise
