# -*- coding: cp1254 -*-
# package initializer for character_creation menus

from game_menus.character_creation.mnu_start_character_4 import start_character_4_menu
from game_menus.character_creation.mnu_start_phase_4 import start_phase_4_menu
from game_menus.character_creation.mnu_start_game_3 import start_game_3_menu
from game_menus.character_creation.mnu_start_character_2 import start_character_2_menu
from game_menus.character_creation.mnu_start_character_3 import start_character_3_menu
from game_menus.character_creation.mnu_tutorial import tutorial_menu
from game_menus.character_creation.mnu_past_life_explanation import past_life_explanation_menu
from game_menus.character_creation.mnu_choose_skill import choose_skill_menu
from game_menus.character_creation.mnu_start_character_1 import start_character_1_menu
from game_menus.character_creation.mnu_export_import import export_import_menu
from game_menus.character_creation.mnu_start_phase_2 import start_phase_2_menu
from game_menus.character_creation.mnu_start_game_0 import start_game_0_menu
from game_menus.character_creation.mnu_start_game_1 import start_game_1_menu
from game_menus.character_creation.mnu_auto_return import auto_return_menu
from game_menus.character_creation.mnu_start_phase_2_5 import start_phase_2_5_menu
from game_menus.character_creation.mnu_start_phase_3 import start_phase_3_menu

character_creation_menus = []
character_creation_menus.extend(start_character_4_menu)
character_creation_menus.extend(start_phase_4_menu)
character_creation_menus.extend(start_game_3_menu)
character_creation_menus.extend(start_character_2_menu)
character_creation_menus.extend(start_character_3_menu)
character_creation_menus.extend(tutorial_menu)
character_creation_menus.extend(past_life_explanation_menu)
character_creation_menus.extend(choose_skill_menu)
character_creation_menus.extend(start_character_1_menu)
character_creation_menus.extend(export_import_menu)
character_creation_menus.extend(start_phase_2_menu)
character_creation_menus.extend(start_game_0_menu)
character_creation_menus.extend(start_game_1_menu)
character_creation_menus.extend(auto_return_menu)
character_creation_menus.extend(start_phase_2_5_menu)
character_creation_menus.extend(start_phase_3_menu)

