# -*- coding: cp1254 -*-
from header_game_menus import *
from header_parties import *
from header_items import *
from header_mission_templates import *
from header_music import *
from header_terrain_types import *
from header_triggers import key_left_shift, key_right_shift
from module_constants import *

choose_skill_menu = [
(
    "choose_skill",mnf_disable_all_keys,
    "Only you know exactly what caused you to give up your old life and become an adventurer. {s13}",
    "none",
    [(assign,"$current_string_reg",10),
	 (assign, ":difficulty", 0),

	 (try_begin),
		(eq, "$character_gender", tf_female),
		(str_store_string, s14, "str_woman"),
		(val_add, ":difficulty", 1),
	 (else_try),
		(str_store_string, s14, "str_man"),
	 (try_end),

	 (try_begin),
        (eq,"$background_type",cb_noble),
		(str_store_string, s15, "str_noble"),
		(val_sub, ":difficulty", 1),
	 (else_try),
		(str_store_string, s15, "str_common"),
	 (try_end),

	 (try_begin),
		(eq, ":difficulty", -1),
		(str_store_string, s16, "str_may_find_that_you_are_able_to_take_your_place_among_calradias_great_lords_relatively_quickly"),
	 (else_try),
		(eq, ":difficulty", 0),
		(str_store_string, s16, "str_may_face_some_difficulties_establishing_yourself_as_an_equal_among_calradias_great_lords"),
	 (else_try),
		(eq, ":difficulty", 1),
		(str_store_string, s16, "str_may_face_great_difficulties_establishing_yourself_as_an_equal_among_calradias_great_lords"),
	 (try_end),
	],
    [
##      ("start_swordsman",[],"Swordsmanship.",[
##        (assign, "$starting_skill", 1),
##        (str_store_string, s14, "@You are particularly talented at swordsmanship."),
##        (jump_to_menu,"mnu_past_life_explanation"),
##        ]),
##      ("start_archer",[],"Archery.",[
##        (assign, "$starting_skill", 2),
##        (str_store_string, s14, "@You are particularly talented at archery."),
##        (jump_to_menu,"mnu_past_life_explanation"),
##        ]),
##      ("start_medicine",[],"Medicine.",[
##        (assign, "$starting_skill", 3),
##        (str_store_string, s14, "@You are particularly talented at medicine."),
##        (jump_to_menu,"mnu_past_life_explanation"),
##        ]),
      ("begin_adventuring",[],"Become an adventurer and ride to your destiny.",[
           (set_show_messages, 0),
           (try_begin),
             (eq, "$character_gender", tf_male),
             (troop_raise_attribute, "trp_player",ca_strength,1),
             (troop_raise_attribute, "trp_player",ca_charisma,1),
           (else_try),
             (troop_raise_attribute, "trp_player",ca_agility,1),
             (troop_raise_attribute, "trp_player",ca_intelligence,1),
           (try_end),

           (troop_raise_attribute, "trp_player",ca_strength,1),
           (troop_raise_attribute, "trp_player",ca_agility,1),
           (troop_raise_attribute, "trp_player",ca_charisma,1),

           (troop_raise_skill, "trp_player","skl_leadership",1),
           (troop_raise_skill, "trp_player","skl_riding",1),
##           (try_begin),
##             (eq, "$starting_skill", 1),
##             (troop_raise_attribute, "trp_player",ca_agility,1),
##             (troop_raise_attribute, "trp_player",ca_strength,1),
##             (troop_raise_skill, "trp_player",skl_power_strike,2),
##             (troop_raise_proficiency, "trp_player",0,30),
##             (troop_raise_proficiency, "trp_player",1,20),
##           (else_try),
##             (eq, "$starting_skill", 2),
##             (troop_raise_attribute, "trp_player",ca_strength,2),
##             (troop_raise_skill, "trp_player",skl_power_draw,2),
##             (troop_raise_proficiency, "trp_player",3,50),
##           (else_try),
##             (troop_raise_attribute, "trp_player",ca_intelligence,1),
##             (troop_raise_attribute, "trp_player",ca_charisma,1),
##             (troop_raise_skill, "trp_player",skl_first_aid,1),
##             (troop_raise_skill, "trp_player",skl_wound_treatment,1),
##             (troop_add_item, "trp_player","itm_winged_mace",0),
##             (troop_raise_proficiency, "trp_player",0,15),
##             (troop_raise_proficiency, "trp_player",1,15),
##             (troop_raise_proficiency, "trp_player",2,15),
##           (try_end),


      (try_begin),
        (eq,"$background_type",cb_noble),
        (eq,"$character_gender",tf_male),
        (troop_raise_attribute, "trp_player",ca_intelligence,1),
        (troop_raise_attribute, "trp_player",ca_charisma,2),
        (troop_raise_skill, "trp_player",skl_weapon_master,1),
        (troop_raise_skill, "trp_player",skl_power_strike,1),
        (troop_raise_skill, "trp_player",skl_riding,1),
        (troop_raise_skill, "trp_player",skl_tactics,1),
        (troop_raise_skill, "trp_player",skl_leadership,1),
        (troop_raise_proficiency, "trp_player",wpt_one_handed_weapon,10),
        (troop_raise_proficiency, "trp_player",wpt_two_handed_weapon,10),
        (troop_raise_proficiency, "trp_player",wpt_polearm,10),

        (troop_add_item, "trp_player","itm_tab_shield_round_a",imod_battered),
        (troop_set_slot, "trp_player", slot_troop_renown, 100),
        (call_script, "script_change_player_honor", 3),


##        (troop_add_item, "trp_player","itm_red_gambeson",imod_plain),
##        (troop_add_item, "trp_player","itm_sword",imod_plain),
##        (troop_add_item, "trp_player","itm_dagger",imod_balanced),
##        (troop_add_item, "trp_player","itm_woolen_hose",0),
##        (troop_add_item, "trp_player","itm_dried_meat",0),
##        (troop_add_item, "trp_player","itm_saddle_horse",imod_plain),
        (troop_add_gold, "trp_player", 100),
      (else_try),
        (eq,"$background_type",cb_noble),
        (eq,"$character_gender",tf_female),
        (troop_raise_attribute, "trp_player",ca_intelligence,2),
        (troop_raise_attribute, "trp_player",ca_charisma,1),
        (troop_raise_skill, "trp_player",skl_wound_treatment,1),
        (troop_raise_skill, "trp_player",skl_riding,2),
        (troop_raise_skill, "trp_player",skl_first_aid,1),
        (troop_raise_skill, "trp_player",skl_leadership,1),
        (troop_raise_proficiency, "trp_player",wpt_one_handed_weapon,20),

        (troop_set_slot, "trp_player", slot_troop_renown, 50),
        (troop_add_item, "trp_player","itm_tab_shield_round_a",imod_battered),

##        (troop_add_item, "trp_player","itm_dress",imod_sturdy),
##        (troop_add_item, "trp_player","itm_dagger",imod_watered_steel),
##        (troop_add_item, "trp_player","itm_woolen_hose",0),
##        (troop_add_item, "trp_player","itm_hunting_crossbow",0),
##        (troop_add_item, "trp_player","itm_bolts",0),
##        (troop_add_item, "trp_player","itm_smoked_fish",0),
##        (troop_add_item, "trp_player","itm_courser",imod_spirited),
        (troop_add_gold, "trp_player", 100),
      (else_try),
        (eq,"$background_type",cb_merchant),
        (troop_raise_attribute, "trp_player",ca_intelligence,2),
        (troop_raise_attribute, "trp_player",ca_charisma,1),
        (troop_raise_skill, "trp_player",skl_riding,1),
        (troop_raise_skill, "trp_player",skl_leadership,1),
        (troop_raise_skill, "trp_player",skl_trade,2),
        (troop_raise_skill, "trp_player",skl_inventory_management,1),
        (troop_raise_proficiency, "trp_player",wpt_two_handed_weapon,10),

##        (troop_add_item, "trp_player","itm_leather_jacket",0),
##        (troop_add_item, "trp_player","itm_leather_boots",0),
##        (troop_add_item, "trp_player","itm_fur_hat",0),
##        (troop_add_item, "trp_player","itm_dagger",0),
##        (troop_add_item, "trp_player","itm_hunting_crossbow",0),
##        (troop_add_item, "trp_player","itm_bolts",0),
##        (troop_add_item, "trp_player","itm_smoked_fish",0),
##        (troop_add_item, "trp_player","itm_saddle_horse",0),
##        (troop_add_item, "trp_player","itm_sumpter_horse",0),
##        (troop_add_item, "trp_player","itm_salt",0),
##        (troop_add_item, "trp_player","itm_salt",0),
##        (troop_add_item, "trp_player","itm_salt",0),
##        (troop_add_item, "trp_player","itm_pottery",0),
##        (troop_add_item, "trp_player","itm_pottery",0),

        (troop_add_gold, "trp_player", 250),
        (troop_set_slot, "trp_player", slot_troop_renown, 20),
      (else_try),
        (eq,"$background_type",cb_guard),
        (troop_raise_attribute, "trp_player",ca_strength,1),
        (troop_raise_attribute, "trp_player",ca_agility,1),
        (troop_raise_attribute, "trp_player",ca_charisma,1),
        (troop_raise_skill, "trp_player","skl_ironflesh",1),
        (troop_raise_skill, "trp_player","skl_power_strike",1),
        (troop_raise_skill, "trp_player","skl_weapon_master",1),
        (troop_raise_skill, "trp_player","skl_leadership",1),
        (troop_raise_skill, "trp_player","skl_trainer",1),
        (troop_raise_proficiency, "trp_player",wpt_one_handed_weapon,10),
        (troop_raise_proficiency, "trp_player",wpt_two_handed_weapon,15),
        (troop_raise_proficiency, "trp_player",wpt_polearm,20),
        (troop_raise_proficiency, "trp_player",wpt_throwing,10),
        (troop_add_item, "trp_player","itm_tab_shield_kite_b",imod_battered),

##        (troop_add_item, "trp_player","itm_leather_jerkin",imod_ragged),
##        (troop_add_item, "trp_player","itm_skullcap",imod_rusty),
##        (troop_add_item, "trp_player","itm_spear",0),
##        (troop_add_item, "trp_player","itm_arming_sword",imod_chipped),
##        (troop_add_item, "trp_player","itm_hunting_crossbow",0),
##        (troop_add_item, "trp_player","itm_hunter_boots",0),
##        (troop_add_item, "trp_player","itm_leather_gloves",imod_ragged),
##        (troop_add_item, "trp_player","itm_bolts",0),
##        (troop_add_item, "trp_player","itm_smoked_fish",0),
##        (troop_add_item, "trp_player","itm_saddle_horse",imod_swaybacked),
        (troop_add_gold, "trp_player", 50),
        (troop_set_slot, "trp_player", slot_troop_renown, 10),
      (else_try),
        (eq,"$background_type",cb_forester),
        (troop_raise_attribute, "trp_player",ca_strength,1),
        (troop_raise_attribute, "trp_player",ca_agility,2),
        (troop_raise_skill, "trp_player","skl_power_draw",1),
        (troop_raise_skill, "trp_player","skl_tracking",1),
        (troop_raise_skill, "trp_player","skl_pathfinding",1),
        (troop_raise_skill, "trp_player","skl_spotting",1),
        (troop_raise_skill, "trp_player","skl_athletics",1),
        (troop_raise_proficiency, "trp_player",wpt_two_handed_weapon,10),
        (troop_raise_proficiency, "trp_player",wpt_archery,30),
##        (troop_add_item, "trp_player","itm_short_bow",imod_bent),
##        (troop_add_item, "trp_player","itm_arrows",0),
##        (troop_add_item, "trp_player","itm_axe",imod_chipped),
##        (troop_add_item, "trp_player","itm_rawhide_coat",0),
##        (troop_add_item, "trp_player","itm_hide_boots",0),
##        (troop_add_item, "trp_player","itm_dried_meat",0),
##        (troop_add_item, "trp_player","itm_sumpter_horse",imod_heavy),
##        (troop_add_item, "trp_player","itm_furs",0),
        (troop_add_gold, "trp_player", 30),
      (else_try),
        (eq,"$background_type",cb_nomad),
        (eq,"$character_gender",tf_male),
        (troop_raise_attribute, "trp_player",ca_strength,1),
        (troop_raise_attribute, "trp_player",ca_agility,1),
        (troop_raise_attribute, "trp_player",ca_intelligence,1),
        (troop_raise_skill, "trp_player","skl_power_draw",1),
        (troop_raise_skill, "trp_player","skl_horse_archery",1),
        (troop_raise_skill, "trp_player","skl_pathfinding",1),
        (troop_raise_skill, "trp_player","skl_riding",2),
        (troop_raise_proficiency, "trp_player",wpt_one_handed_weapon,10),
        (troop_raise_proficiency, "trp_player",wpt_archery,30),
        (troop_raise_proficiency, "trp_player",wpt_throwing,10),
        (troop_add_item, "trp_player","itm_tab_shield_small_round_a",imod_battered),
##        (troop_add_item, "trp_player","itm_javelin",imod_bent),
##        (troop_add_item, "trp_player","itm_sword_khergit_1",imod_rusty),
##        (troop_add_item, "trp_player","itm_nomad_armor",0),
##        (troop_add_item, "trp_player","itm_hide_boots",0),
##        (troop_add_item, "trp_player","itm_horse_meat",0),
##        (troop_add_item, "trp_player","itm_steppe_horse",0),
        (troop_add_gold, "trp_player", 15),
        (troop_set_slot, "trp_player", slot_troop_renown, 10),
      (else_try),
        (eq,"$background_type",cb_nomad),
        (eq,"$character_gender",tf_female),
        (troop_raise_attribute, "trp_player",ca_strength,1),
        (troop_raise_attribute, "trp_player",ca_agility,1),
        (troop_raise_attribute, "trp_player",ca_intelligence,1),
        (troop_raise_skill, "trp_player","skl_wound_treatment",1),
        (troop_raise_skill, "trp_player","skl_first_aid",1),
        (troop_raise_skill, "trp_player","skl_pathfinding",1),
        (troop_raise_skill, "trp_player","skl_riding",2),
        (troop_raise_proficiency, "trp_player",wpt_one_handed_weapon,5),
        (troop_raise_proficiency, "trp_player",wpt_archery,20),
        (troop_raise_proficiency, "trp_player",wpt_throwing,5),
        (troop_add_item, "trp_player","itm_tab_shield_small_round_a",imod_battered),
##        (troop_add_item, "trp_player","itm_javelin",imod_bent),
##        (troop_add_item, "trp_player","itm_sickle",imod_plain),
##        (troop_add_item, "trp_player","itm_nomad_armor",0),
##        (troop_add_item, "trp_player","itm_hide_boots",0),
##        (troop_add_item, "trp_player","itm_steppe_horse",0),
##        (troop_add_item, "trp_player","itm_grain",0),
        (troop_add_gold, "trp_player", 20),
      (else_try),
        (eq,"$background_type",cb_thief),
        (troop_raise_attribute, "trp_player",ca_agility,3),
        (troop_raise_skill, "trp_player","skl_athletics",2),
        (troop_raise_skill, "trp_player","skl_power_throw",1),
        (troop_raise_skill, "trp_player","skl_inventory_management",1),
        (troop_raise_skill, "trp_player","skl_looting",1),
        (troop_raise_proficiency, "trp_player",wpt_one_handed_weapon,20),
        (troop_raise_proficiency, "trp_player",wpt_throwing,20),
        (troop_add_item, "trp_player","itm_throwing_knives",0),
##        (troop_add_item, "trp_player","itm_stones",0),
##        (troop_add_item, "trp_player","itm_cudgel",imod_plain),
##        (troop_add_item, "trp_player","itm_dagger",imod_rusty),
##        (troop_add_item, "trp_player","itm_shirt",imod_tattered),
##        (troop_add_item, "trp_player","itm_black_hood",imod_tattered),
##        (troop_add_item, "trp_player","itm_wrapping_boots",imod_ragged),
        (troop_add_gold, "trp_player", 25),
     (else_try), #SB : re-enable priests
       (eq,"$background_type",cb_priest),
       (troop_raise_attribute, "trp_player",ca_strength,1),
       (troop_raise_attribute, "trp_player",ca_intelligence,2),
       (troop_raise_attribute, "trp_player",ca_charisma,1),
       (troop_raise_skill, "trp_player","skl_wound_treatment",1),
       (troop_raise_skill, "trp_player","skl_leadership",1),
       (troop_raise_skill, "trp_player","skl_prisoner_management",1),
       (troop_raise_proficiency, "trp_player", wpt_one_handed_weapon, 10),
       (troop_add_item, "trp_player","itm_robe",0),
       # (troop_add_item, "trp_player","itm_wrapping_boots",0), #SB : remove most of these, cb3 adds equipment
       # (troop_add_item, "trp_player","itm_club",0),
       (troop_add_item, "trp_player","itm_grain",imod_large_bag),
       # (troop_add_item, "trp_player","itm_sumpter_horse",0), #SB: I guess it's a donkey or something
       (troop_add_gold, "trp_player", 10),
       (troop_set_slot, "trp_player", slot_troop_renown, 10),
      (try_end),

    (try_begin),
        (eq,"$background_answer_2",cb2_page),
        (troop_raise_attribute, "trp_player",ca_charisma,1),
        (troop_raise_attribute, "trp_player",ca_strength,1),
        (troop_raise_skill, "trp_player","skl_power_strike",1),
        (troop_raise_skill, "trp_player","skl_persuasion",1),
        (troop_raise_proficiency, "trp_player",wpt_one_handed_weapon,15),
        (troop_raise_proficiency, "trp_player",wpt_polearm,5),
    (else_try),
        (eq,"$background_answer_2",cb2_apprentice),
        (troop_raise_attribute, "trp_player",ca_intelligence,1),
        (troop_raise_attribute, "trp_player",ca_strength,1),
        (troop_raise_skill, "trp_player","skl_engineer",1),
        (troop_raise_skill, "trp_player","skl_trade",1),
    (else_try),
        (eq,"$background_answer_2",cb2_urchin),
        (troop_raise_attribute, "trp_player",ca_agility,1),
        (troop_raise_attribute, "trp_player",ca_intelligence,1),
        (troop_raise_skill, "trp_player","skl_spotting",1),
        (troop_raise_skill, "trp_player","skl_looting",1),
        (troop_raise_proficiency, "trp_player",wpt_one_handed_weapon,15),
        (troop_raise_proficiency, "trp_player",wpt_throwing,5),
    (else_try),
        (eq,"$background_answer_2",cb2_steppe_child),
        (troop_raise_attribute, "trp_player",ca_strength,1),
        (troop_raise_attribute, "trp_player",ca_agility,1),
        (troop_raise_skill, "trp_player","skl_horse_archery",1),
        (troop_raise_skill, "trp_player","skl_power_throw",1),
        (troop_raise_proficiency, "trp_player",wpt_archery,15),
        (call_script,"script_change_troop_renown", "trp_player", 5),
    (else_try),
        (eq,"$background_answer_2",cb2_merchants_helper),
        (troop_raise_attribute, "trp_player",ca_intelligence,1),
        (troop_raise_attribute, "trp_player",ca_charisma,1),
        (troop_raise_skill, "trp_player","skl_inventory_management",1),
        (troop_raise_skill, "trp_player","skl_trade",1),
	(else_try),
       (eq,"$background_answer_2",dplmc_cb2_mummer),
       (troop_raise_attribute, "trp_player",ca_intelligence,1),
       (troop_raise_attribute, "trp_player",ca_charisma,1),
       # (troop_raise_skill, "trp_player",skl_leadership,1), #SB : +2 attr, +2 skill
       (troop_raise_skill, "trp_player",skl_athletics,1),
       (troop_raise_skill, "trp_player",skl_riding,1),
       (troop_raise_proficiency, "trp_player",wpt_two_handed_weapon,5),
       (troop_raise_proficiency, "trp_player",wpt_polearm,5),
       (call_script,"script_change_troop_renown", "trp_player", 15),
	(else_try),
       (eq,"$background_answer_2",dplmc_cb2_courtier),
       (troop_raise_attribute, "trp_player",ca_charisma,2), #SB : lower to +2
       (troop_raise_attribute, "trp_player",ca_agility,1),
       (troop_raise_skill, "trp_player","skl_weapon_master",1),
       (troop_raise_skill, "trp_player","skl_persuasion",1), #add this I guess from page
       (troop_raise_proficiency, "trp_player",wpt_one_handed_weapon,15),
       # (troop_raise_proficiency, "trp_player",wpt_polearm,10), #this is way too much wpt for a courtier
       (troop_raise_proficiency, "trp_player",wpt_crossbow, 5),
       (call_script,"script_change_troop_renown", "trp_player", 20),
	(else_try),
       (eq,"$background_answer_2",dplmc_cb2_noble),
       (troop_raise_attribute, "trp_player",ca_intelligence,1),
       (troop_raise_attribute, "trp_player",ca_charisma,2),
       (troop_raise_skill, "trp_player","skl_leadership",1),
       (troop_raise_skill, "trp_player","skl_tactics",1),
       (troop_raise_proficiency, "trp_player",wpt_one_handed_weapon,10),
       (troop_raise_proficiency, "trp_player",wpt_two_handed_weapon,10),
       (call_script,"script_change_troop_renown", "trp_player", 15),
       #SB : add background renown/honor/rtr
       (val_add, "$player_right_to_rule", 1),
	(else_try),
       (eq,"$background_answer_2",dplmc_cb2_acolyte),
       (troop_raise_attribute, "trp_player",ca_agility,1),
       (troop_raise_attribute, "trp_player",ca_intelligence,1),
       (troop_raise_attribute, "trp_player",ca_charisma,1),
       (troop_raise_skill, "trp_player",skl_leadership,1),
       (troop_raise_skill, "trp_player",skl_surgery,1),
       (troop_raise_skill, "trp_player",skl_first_aid,1),
       (troop_raise_proficiency, "trp_player",wpt_polearm,10),
       (call_script,"script_change_troop_renown", "trp_player", 5),
	(try_end),

	(try_begin), #SB :re-enable 3x cb3 options, adding 1x body armor and weapon + food
       (eq,"$background_answer_3",dplmc_cb3_bravo),
       (troop_raise_attribute, "trp_player",ca_strength,1),
       (troop_raise_skill, "trp_player","skl_power_strike",1),
       (troop_raise_skill, "trp_player","skl_shield",1),
       (troop_add_gold, "trp_player", 10),
       # (try_begin),
       # (this_or_next|player_has_item,"itm_sword"),
       # (troop_has_item_equipped,"trp_player","itm_sword"),
       # (troop_remove_item, "trp_player","itm_sword"),
       # (try_end),
       # (try_begin),
       # (this_or_next|player_has_item,"itm_arming_sword"),
       # (troop_has_item_equipped,"trp_player","itm_arming_sword"),
       # (troop_remove_item, "trp_player","itm_arming_sword"),
       # (try_end),
       # (troop_add_item, "trp_player","itm_short_sword",0),
       # (troop_add_item, "trp_player","itm_wooden_shield",imod_battered),
       (store_random_in_range, ":shield_item", "itm_norman_shield_1", "itm_tab_shield_round_a"),
       (troop_add_item, "trp_player",":shield_item",imod_heavy),
       (store_random_in_range, ":armor_item", "itm_gambeson", "itm_tribal_warrior_outfit"),
       (store_random_in_range, ":armor_imod", imod_tattered, imod_reinforced),
       (troop_add_item, "trp_player",":armor_item",":armor_imod"),
       (troop_add_item, "trp_player", "itm_ankle_boots", 0),
       #store a random sword
       (store_random_in_range, ":weapon_item", "itm_long_voulge", "itm_mace_1"),
       (try_begin), #2+4 offset for scimitar + sarranid swords
         (lt, ":weapon_item", "itm_sword_medieval_a"),
         (val_sub, ":weapon_item", "itm_long_voulge"),
         (val_add, ":weapon_item", "itm_scimitar"),
       (try_end),
       (troop_add_item, "trp_player",":weapon_item"),
       (store_random_in_range, ":food_item", "itm_dried_meat", "itm_grain"),
       (troop_add_item, "trp_player",":food_item"),
       (troop_raise_proficiency, "trp_player",wpt_one_handed_weapon,10),
       (troop_raise_proficiency, "trp_player",wpt_crossbow,10),
   (else_try),
       (eq,"$background_answer_3",dplmc_cb3_merc),
       (troop_raise_attribute, "trp_player",ca_agility,1),
       (troop_raise_skill, "trp_player",skl_weapon_master,1),
       (troop_raise_skill, "trp_player",skl_shield,1),
       # (try_begin),
       # (this_or_next|player_has_item,"itm_hide_boots"),
       # (troop_has_item_equipped,"trp_player","itm_hide_boots"),
       # (troop_remove_item, "trp_player","itm_hide_boots"),
       # (try_end),
       #store crap gear here, this depends on Native's item ordering
       (store_random_in_range, ":helmet_item", "itm_byzantion_helmet_a", "itm_tunic_with_green_cape"),
       (store_random_in_range, ":weapon_item", "itm_sword_medieval_a", "itm_club_with_spike_head"),
       (store_random_in_range, ":armor_item", "itm_leather_jerkin", "itm_lamellar_vest"),
       (store_random_in_range, ":boots_item", "itm_hunter_boots", "itm_splinted_greaves"),
       (store_random_in_range, ":helmet_imod", imod_tattered, imod_reinforced),
       (store_random_in_range, ":weapon_imod", imod_crude, imod_deadly),
       (store_random_in_range, ":armor_imod", imod_tattered, imod_reinforced),

       #SB : pick 1 set for each faction
       (store_random_in_range, ":faction_no", npc_kingdoms_begin, npc_kingdoms_end),
       (try_begin),
         (eq, ":faction_no", "fac_kingdom_1"),
         (store_random_in_range, ":helmet_item", "itm_norman_helmet", "itm_kettle_hat"),
         (store_random_in_range, ":weapon_item", "itm_awlpike", "itm_bec_de_corbin_a"),
       (else_try),
         (eq, ":faction_no", "fac_kingdom_2"),
         (store_random_in_range, ":helmet_item", "itm_vaegir_fur_cap", "itm_vaegir_lamellar_helmet"),
       (else_try),
         (eq, ":faction_no", "fac_kingdom_3"), #original items
         (assign, ":helmet_item", "itm_khergit_guard_helmet"),
         (store_random_in_range, ":weapon_item", "itm_sword_khergit_1", "itm_sword_khergit_4"),
         (assign, ":boots_item","itm_mail_chausses"),
         (assign, ":helmet_imod", imod_crude),
       (else_try),
         (eq, ":faction_no", "fac_kingdom_4"), #pick axes, some are fairly expensive
         (store_random_in_range, ":weapon_item","itm_one_handed_war_axe_a", "itm_bardiche"),
         (assign, ":helmet_item", 0),
       (else_try),
         (eq, ":faction_no", "fac_kingdom_5"), #pick from the blunt range
         (store_random_in_range, ":weapon_item","itm_military_hammer", "itm_sickle"),
       (else_try),
         (eq, ":faction_no", "fac_kingdom_6"), #a fairly complete set of gear
         (troop_add_item, "trp_player","itm_sarranid_warrior_cap",imod_hardened),
         (store_random_in_range, ":boots_item", "itm_sarranid_boots_a", "itm_sarranid_boots_d"),
         (store_random_in_range, ":helmet_item", "itm_sarranid_felt_hat", "itm_sarranid_horseman_helmet"),
         # (assign, ":weapon_item","itm_sarranid_two_handed_mace_1"),
       (try_end),
       (try_begin),
         (gt, ":helmet_item", 0),
         (troop_add_item, "trp_player", ":helmet_item", ":helmet_imod"),
       (try_end),
       (try_begin),
         (gt, ":weapon_item", 0),
         (try_begin),
           (call_script, "script_dplmc_troop_can_use_item", "trp_player", ":weapon_item", ":weapon_imod"),
           (eq, reg0, 1),
           (troop_add_item, "trp_player", ":weapon_item", ":weapon_imod"),
         (else_try), #use a low-requirement common spear, or highest wpt_proficiency I guess
           (store_random_in_range, ":weapon_item", "itm_shortened_spear", "itm_light_lance"),
           (troop_add_item, "trp_player", ":weapon_item", ":weapon_imod"),
         (try_end),
       (try_end),
       (try_begin),
         (gt, ":armor_item", 0),
         (try_begin),
           (call_script, "script_dplmc_troop_can_use_item", "trp_player", ":armor_item", ":armor_imod"),
           (eq, reg0, 1),
           (troop_add_item, "trp_player", ":armor_item", ":armor_imod"),
         (else_try), #use a low-requirement gambeson
           (store_random_in_range, ":armor_item", "itm_blue_gambeson", "itm_nomad_vest"),
           (troop_add_item, "trp_player", ":armor_item", ":armor_imod"),
         (try_end),
       (try_end),
       (try_begin),
         (gt, ":boots_item", 0),
         (troop_add_item, "trp_player", ":boots_item", 0),
       (try_end),

       (store_random_in_range, ":food_item", "itm_cattle_meat", "itm_siege_supply"),
       (troop_add_item, "trp_player",":food_item"),
       # (troop_add_gold, "trp_player", 20),
       # (troop_raise_proficiency, "trp_player",wpt_polearm,20),
       (try_for_range, ":unused", 0, 4),
         (store_random_in_range, ":wpt", wpt_one_handed_weapon, wpt_firearm),
         (troop_raise_proficiency, "trp_player",":wpt",5), #"taught you how to wield any weapon you desired"
       (try_end),
   (else_try),
        (eq,"$background_answer_3",cb3_poacher),
        (troop_raise_attribute, "trp_player",ca_strength,1),
        (troop_raise_attribute, "trp_player",ca_agility,1),
        (troop_raise_skill, "trp_player","skl_power_draw",1),
        (troop_raise_skill, "trp_player","skl_tracking",1),
        (troop_raise_skill, "trp_player","skl_spotting",1),
        (troop_raise_skill, "trp_player","skl_athletics",1),
        (troop_add_gold, "trp_player", 10),
        (troop_raise_proficiency, "trp_player",wpt_polearm,10),
        (troop_raise_proficiency, "trp_player",wpt_archery,35),

        (troop_add_item, "trp_player","itm_axe",imod_chipped),
        (troop_add_item, "trp_player","itm_rawhide_coat",0),
        (troop_add_item, "trp_player","itm_hide_boots",0),
        (troop_add_item, "trp_player","itm_hunting_bow",0),
        (troop_add_item, "trp_player","itm_barbed_arrows",0),
        (troop_add_item, "trp_player","itm_sumpter_horse",imod_heavy),
        (troop_add_item, "trp_player","itm_dried_meat",0),
        (troop_add_item, "trp_player","itm_dried_meat",0),
        (troop_add_item, "trp_player","itm_furs",0),
        (troop_add_item, "trp_player","itm_furs",0),
    (else_try),
        (eq,"$background_answer_3",cb3_craftsman),
        (troop_raise_attribute, "trp_player",ca_strength,1),
        (troop_raise_attribute, "trp_player",ca_intelligence,1),

        (troop_raise_skill, "trp_player","skl_weapon_master",1),
        (troop_raise_skill, "trp_player","skl_engineer",1),
        (troop_raise_skill, "trp_player","skl_tactics",1),
        (troop_raise_skill, "trp_player","skl_trade",1),

        (troop_raise_proficiency, "trp_player",wpt_one_handed_weapon,15),
        (troop_add_gold, "trp_player", 100),


        (troop_add_item, "trp_player","itm_leather_boots",imod_ragged),
        (troop_add_item, "trp_player","itm_coarse_tunic",0),

        (troop_add_item, "trp_player","itm_sword_medieval_b", imod_balanced),
        (troop_add_item, "trp_player","itm_hunting_crossbow",0),
        (troop_add_item, "trp_player","itm_bolts",0),

        (troop_add_item, "trp_player","itm_tools",0),
        (troop_add_item, "trp_player","itm_saddle_horse",0),
        (troop_add_item, "trp_player","itm_smoked_fish",0),
    (else_try),
        (eq,"$background_answer_3",cb3_peddler),
        (troop_raise_attribute, "trp_player",ca_charisma,1),
        (troop_raise_attribute, "trp_player",ca_intelligence,1),
        (troop_raise_skill, "trp_player","skl_riding",1),
        (troop_raise_skill, "trp_player","skl_trade",1),
        (troop_raise_skill, "trp_player","skl_pathfinding",1),
        (troop_raise_skill, "trp_player","skl_inventory_management",1),

        (troop_add_item, "trp_player","itm_leather_gloves",imod_plain),
        (troop_add_gold, "trp_player", 90),
        (troop_raise_proficiency, "trp_player",wpt_polearm,15),

        (troop_add_item, "trp_player","itm_leather_jacket",0),
        (troop_add_item, "trp_player","itm_leather_boots",imod_ragged),
        (troop_add_item, "trp_player","itm_fur_hat",0),
        (troop_add_item, "trp_player","itm_staff",0),
        (troop_add_item, "trp_player","itm_hunting_crossbow",0),
        (troop_add_item, "trp_player","itm_bolts",0),
        (troop_add_item, "trp_player","itm_saddle_horse",0),
        (troop_add_item, "trp_player","itm_sumpter_horse",0),

        (troop_add_item, "trp_player","itm_linen",0),
        (troop_add_item, "trp_player","itm_pottery",0),
        (troop_add_item, "trp_player","itm_wool",0),
        (troop_add_item, "trp_player","itm_wool",0),
        (troop_add_item, "trp_player","itm_smoked_fish",0),
   (else_try),
       (eq,"$background_answer_3",dplmc_cb3_preacher),
       (troop_raise_attribute, "trp_player",ca_strength,1),
       (troop_raise_attribute, "trp_player",ca_charisma,1),
       (troop_raise_skill, "trp_player","skl_shield",1),
       (troop_raise_skill, "trp_player","skl_wound_treatment",1),
       (troop_raise_skill, "trp_player","skl_first_aid",1),
       (troop_raise_skill, "trp_player","skl_surgery",1),
       (troop_add_item, "trp_player","itm_leather_gloves",imod_ragged),
       (troop_add_item, "trp_player","itm_quarter_staff",imod_heavy),
       #remove monk stuff, add pilgrim stuff
       (troop_remove_item, "trp_player", "itm_robe"),
       # (troop_remove_item, "trp_player", "itm_black_hood"),
       (troop_add_item, "trp_player", "itm_pilgrim_disguise"),
       (troop_add_item, "trp_player", "itm_pilgrim_hood"),
       (troop_add_item, "trp_player", "itm_wrapping_boots"),
       (troop_add_item, "trp_player", "itm_cheese"), #add 1x food
       (troop_add_gold, "trp_player", 10),
       (troop_raise_proficiency, "trp_player",wpt_polearm,20),
    (else_try),
        (eq,"$background_answer_3",cb3_troubadour),
        (troop_raise_attribute, "trp_player",ca_charisma,2),

        (troop_raise_skill, "trp_player","skl_weapon_master",1),
        (troop_raise_skill, "trp_player","skl_persuasion",1),
        (troop_raise_skill, "trp_player","skl_leadership",1),
        (troop_raise_skill, "trp_player","skl_pathfinding",1),

        (troop_add_gold, "trp_player", 80),
        (troop_raise_proficiency, "trp_player",wpt_one_handed_weapon,25),
        (troop_raise_proficiency, "trp_player",wpt_crossbow,10),

        (troop_add_item, "trp_player","itm_tabard",imod_sturdy),
        (troop_add_item, "trp_player","itm_leather_boots",imod_ragged),
        (troop_add_item, "trp_player","itm_sword_medieval_a", imod_rusty),
        (troop_add_item, "trp_player","itm_hunting_crossbow", 0),
        (troop_add_item, "trp_player","itm_bolts", 0),
        (troop_add_item, "trp_player","itm_saddle_horse",imod_swaybacked),
        (troop_add_item, "trp_player","itm_smoked_fish",0),
    (else_try),
        (eq,"$background_answer_3",cb3_squire),
        (troop_raise_attribute, "trp_player",ca_strength,1),
        (troop_raise_attribute, "trp_player",ca_agility,1),
        (troop_raise_skill, "trp_player","skl_riding",1),
        (troop_raise_skill, "trp_player","skl_weapon_master",1),
        (troop_raise_skill, "trp_player","skl_power_strike",1),
        (troop_raise_skill, "trp_player","skl_leadership",1),

        (troop_add_gold, "trp_player", 20),
        (troop_raise_proficiency, "trp_player",wpt_one_handed_weapon,30),
        (troop_raise_proficiency, "trp_player",wpt_two_handed_weapon,30),
        (troop_raise_proficiency, "trp_player",wpt_polearm,30),
        (troop_raise_proficiency, "trp_player",wpt_archery,10),
        (troop_raise_proficiency, "trp_player",wpt_crossbow,10),
        (troop_raise_proficiency, "trp_player",wpt_throwing,10),

        (troop_add_item, "trp_player","itm_leather_jerkin",imod_ragged),
        (troop_add_item, "trp_player","itm_leather_boots",imod_tattered),

        (troop_add_item, "trp_player","itm_sword_medieval_a", imod_rusty),
        (troop_add_item, "trp_player","itm_hunting_crossbow",0),
        (troop_add_item, "trp_player","itm_bolts",0),
        (troop_add_item, "trp_player","itm_saddle_horse",imod_swaybacked),
        (troop_add_item, "trp_player","itm_smoked_fish",0),
    (else_try),
        (eq,"$background_answer_3",cb3_lady_in_waiting),
        (eq,"$character_gender",tf_female),
        (troop_raise_attribute, "trp_player",ca_intelligence,1),
        (troop_raise_attribute, "trp_player",ca_charisma,1),

        (troop_raise_skill, "trp_player","skl_persuasion",2),
        (troop_raise_skill, "trp_player","skl_riding",1),
        (troop_raise_skill, "trp_player","skl_wound_treatment",1),

        (troop_add_item, "trp_player","itm_dagger", 0),
        (troop_add_item, "trp_player","itm_hunting_crossbow",0),
        (troop_add_item, "trp_player","itm_bolts",0),
        (troop_add_item, "trp_player","itm_courser", imod_spirited),
        (troop_add_item, "trp_player","itm_woolen_hood",imod_sturdy),
        (troop_add_item, "trp_player","itm_woolen_dress",imod_sturdy),
        (troop_add_gold, "trp_player", 100),
        (troop_raise_proficiency, "trp_player",wpt_one_handed_weapon,10),
        (troop_raise_proficiency, "trp_player",wpt_crossbow,15),
        (troop_add_item, "trp_player","itm_smoked_fish",0),
    (else_try),
        (eq,"$background_answer_3",cb3_student),
        (troop_raise_attribute, "trp_player",ca_intelligence,2),

        (troop_raise_skill, "trp_player","skl_weapon_master",1),
        (troop_raise_skill, "trp_player","skl_surgery",1),
        (troop_raise_skill, "trp_player","skl_wound_treatment",1),
        (troop_raise_skill, "trp_player","skl_persuasion",1),

        (troop_add_gold, "trp_player", 80),
        (troop_raise_proficiency, "trp_player",wpt_one_handed_weapon,20),
        (troop_raise_proficiency, "trp_player",wpt_crossbow,20),

        (troop_add_item, "trp_player","itm_linen_tunic",imod_sturdy),
        (troop_add_item, "trp_player","itm_woolen_hose",0),
        (troop_add_item, "trp_player","itm_sword_medieval_a", imod_rusty),
        (troop_add_item, "trp_player","itm_hunting_crossbow", 0),
        (troop_add_item, "trp_player","itm_bolts", 0),
        (troop_add_item, "trp_player","itm_saddle_horse",imod_swaybacked),
        (troop_add_item, "trp_player","itm_smoked_fish",0),
        (store_random_in_range, ":book_no", books_begin, books_end),
        (troop_add_item, "trp_player",":book_no",0),
    (try_end),

      (try_begin),
        (eq,"$background_answer_4",cb4_revenge),
        (troop_raise_attribute, "trp_player",ca_strength,2),
        (troop_raise_skill, "trp_player","skl_power_strike",1),
      (else_try),
        (eq,"$background_answer_4",cb4_loss),
        (troop_raise_attribute, "trp_player",ca_charisma,2),
        (troop_raise_skill, "trp_player","skl_ironflesh",1),
      (else_try),
        (eq,"$background_answer_4",cb4_wanderlust),
        (troop_raise_attribute, "trp_player",ca_agility,2),
        (troop_raise_skill, "trp_player","skl_pathfinding",1),
      (else_try),
        (eq,"$background_answer_4",dplmc_cb4_fervor),
        (troop_raise_attribute, "trp_player",ca_charisma,1),
        (troop_raise_skill, "trp_player",skl_wound_treatment,1),
        (troop_raise_proficiency, "trp_player",wpt_throwing,10), #wait what
      (else_try),
        (eq,"$background_answer_4",cb4_disown),
        (troop_raise_attribute, "trp_player",ca_strength,1),
        (troop_raise_attribute, "trp_player",ca_intelligence,1),
        (troop_raise_skill, "trp_player","skl_weapon_master",1),
      (else_try),
        (eq,"$background_answer_4",cb4_greed),
        (troop_raise_attribute, "trp_player",ca_agility,1),
        (troop_raise_attribute, "trp_player",ca_intelligence,1),
        (troop_raise_skill, "trp_player","skl_looting",1),
      (try_end),

      #SB : pre-allocate disguises
      (try_begin),
        (assign, ":disguise", disguise_pilgrim), #always available
        #farmer, acquired from not picking inappropriate noble/priestly options
        (try_begin),
          (neq, "$background_type", cb_noble),
          (neq, "$background_type", cb_priest),
          (neq, "$background_answer_2", cb2_page),
          (neq, "$background_answer_2", dplmc_cb2_courtier),
          (neq, "$background_answer_2", dplmc_cb2_noble),
          (neq, "$background_answer_2", dplmc_cb2_acolyte),
          (is_between, "$background_answer_3", cb3_poacher, dplmc_cb3_preacher),
          (val_add, ":disguise", disguise_farmer),
        (try_end),
        (try_begin),
          (this_or_next|eq, "$background_type", cb_forester),
          (this_or_next|eq, "$background_answer_2", cb2_steppe_child),
          (eq, "$background_answer_3", cb3_poacher),
          (val_add, ":disguise", disguise_hunter),
        (try_end),
        (try_begin),
          (this_or_next|eq, "$background_type", cb_merchant),
          (this_or_next|eq, "$background_answer_2", cb2_merchants_helper),
          (eq, "$background_answer_3", cb3_peddler),
          (val_add, ":disguise", disguise_merchant),
        (try_end),
        (try_begin),
          (this_or_next|eq, "$background_type", cb_guard),
          (this_or_next|eq, "$background_answer_3", dplmc_cb3_bravo),
          (this_or_next|eq, "$background_answer_3", dplmc_cb3_merc),
          (eq, "$background_answer_3", cb3_squire),
          (val_add, ":disguise", disguise_guard),
        (try_end),
        (try_begin),
          (this_or_next|eq, "$background_answer_2", dplmc_cb2_mummer),
          (eq, "$background_answer_3", cb3_troubadour),
          (val_add, ":disguise", disguise_bard),
        (try_end),
      (try_end),
      (troop_set_slot, "trp_player", slot_troop_player_disguise_sets, ":disguise"),

           (try_begin),
             (eq, "$background_type", cb_noble),
             (jump_to_menu, "mnu_auto_return"),
#normal_banner_begin
#             (start_presentation, "prsnt_banner_selection"),
#custom_banner_begin
#             (start_presentation, "prsnt_custom_banner"),
              (assign, "$g_edit_banner_troop", "trp_player"),
              (jump_to_menu, "mnu_choose_banner"),
           (else_try),
             (change_screen_return, 0),
           (try_end),
           (set_show_messages, 1),
        ]),
      ("go_back_dot",[],"Go back.",[
        (jump_to_menu,"mnu_start_character_4"),
        ]),
    ]
  )
]
