# -*- coding: cp1254 -*-
# package initializer for diplomacy menus

from game_menus.diplomacy.mnu_dplmc_notification_riot import dplmc_notification_riot_menu
from game_menus.diplomacy.mnu_dplmc_scout import dplmc_scout_menu
from game_menus.diplomacy.mnu_dplmc_dictate_terms import dplmc_dictate_terms_menu
from game_menus.diplomacy.mnu_dplmc_notification_defensive_expired import dplmc_notification_defensive_expired_menu
from game_menus.diplomacy.mnu_dplmc_question_nonaggression_offer import dplmc_question_nonaggression_offer_menu
from game_menus.diplomacy.mnu_dplmc_constable_confirm import dplmc_constable_confirm_menu
from game_menus.diplomacy.mnu_dplmc_notification_appoint_chamberlain import dplmc_notification_appoint_chamberlain_menu
from game_menus.diplomacy.mnu_dplmc_affiliate_end import dplmc_affiliate_end_menu
from game_menus.diplomacy.mnu_dplmc_start_select_prejudice import dplmc_start_select_prejudice_menu
from game_menus.diplomacy.mnu_give_center_to_player import give_center_to_player_menu
from game_menus.diplomacy.mnu_dplmc_chancellor_confirm import dplmc_chancellor_confirm_menu
from game_menus.diplomacy.mnu_leave_faction import leave_faction_menu
from game_menus.diplomacy.mnu_dplmc_notification_appoint_constable import dplmc_notification_appoint_constable_menu
from game_menus.diplomacy.mnu_dickplo_town_manage import dickplo_town_manage_menu
from game_menus.diplomacy.mnu_dplmc_notification_defensive_declared import dplmc_notification_defensive_declared_menu
from game_menus.diplomacy.mnu_dplmc_deserters import dplmc_deserters_menu
from game_menus.diplomacy.mnu_dplmc_chamberlain_confirm import dplmc_chamberlain_confirm_menu
from game_menus.diplomacy.mnu_dplmc_economic_report import dplmc_economic_report_menu
from game_menus.diplomacy.mnu_dplmc_auto_loot import dplmc_auto_loot_menu
from game_menus.diplomacy.mnu_dplmc_riot_negotiate import dplmc_riot_negotiate_menu
from game_menus.diplomacy.mnu_dplmc_manage_loot_pool import dplmc_manage_loot_pool_menu
from game_menus.diplomacy.mnu_dplmc_negotiate_besieger import dplmc_negotiate_besieger_menu
from game_menus.diplomacy.mnu_dplmc_affiliated_family_report import dplmc_affiliated_family_report_menu
from game_menus.diplomacy.mnu_dplmc_notification_appoint_chancellor import dplmc_notification_appoint_chancellor_menu
from game_menus.diplomacy.mnu_dplmc_domestic_policy import dplmc_domestic_policy_menu
from game_menus.diplomacy.mnu_dplmc_notification_alliance_declared import dplmc_notification_alliance_declared_menu
from game_menus.diplomacy.mnu_dplmc_trade_auto_buy_food_begin import dplmc_trade_auto_buy_food_begin_menu
from game_menus.diplomacy.mnu_dplmc_deny_terms import dplmc_deny_terms_menu
from game_menus.diplomacy.mnu_dplmc_notification_trade_declared import dplmc_notification_trade_declared_menu
from game_menus.diplomacy.mnu_dplmc_village_riot_result import dplmc_village_riot_result_menu
from game_menus.diplomacy.mnu_dplmc_question_trade_offer import dplmc_question_trade_offer_menu
from game_menus.diplomacy.mnu_dplmc_notification_trade_expired import dplmc_notification_trade_expired_menu
from game_menus.diplomacy.mnu_dplmc_village_riot_removed import dplmc_village_riot_removed_menu
from game_menus.diplomacy.mnu_dplmc_messenger import dplmc_messenger_menu
from game_menus.diplomacy.mnu_dplmc_preferences import dplmc_preferences_menu
from game_menus.diplomacy.mnu_dplmc_notification_nonaggression_declared import dplmc_notification_nonaggression_declared_menu
from game_menus.diplomacy.mnu_dplmc_town_riot_removed import dplmc_town_riot_removed_menu
from game_menus.diplomacy.mnu_dplmc_question_defensive_offer import dplmc_question_defensive_offer_menu
from game_menus.diplomacy.mnu_dplmc_notification_alliance_expired import dplmc_notification_alliance_expired_menu
from game_menus.diplomacy.mnu_give_center_to_player_2 import give_center_to_player_2_menu
from game_menus.diplomacy.mnu_dplmc_choose_disguise import dplmc_choose_disguise_menu
from game_menus.diplomacy.mnu_oath_fulfilled import oath_fulfilled_menu
from game_menus.diplomacy.mnu_dplmc_trade_auto_sell_begin import dplmc_trade_auto_sell_begin_menu
from game_menus.diplomacy.mnu_dplmc_question_alliance_offer import dplmc_question_alliance_offer_menu

diplomacy_menus = []
diplomacy_menus.extend(dplmc_notification_riot_menu)
diplomacy_menus.extend(dplmc_scout_menu)
diplomacy_menus.extend(dplmc_dictate_terms_menu)
diplomacy_menus.extend(dplmc_notification_defensive_expired_menu)
diplomacy_menus.extend(dplmc_question_nonaggression_offer_menu)
diplomacy_menus.extend(dplmc_constable_confirm_menu)
diplomacy_menus.extend(dplmc_notification_appoint_chamberlain_menu)
diplomacy_menus.extend(dplmc_affiliate_end_menu)
diplomacy_menus.extend(dplmc_start_select_prejudice_menu)
diplomacy_menus.extend(give_center_to_player_menu)
diplomacy_menus.extend(dplmc_chancellor_confirm_menu)
diplomacy_menus.extend(leave_faction_menu)
diplomacy_menus.extend(dplmc_notification_appoint_constable_menu)
diplomacy_menus.extend(dickplo_town_manage_menu)
diplomacy_menus.extend(dplmc_notification_defensive_declared_menu)
diplomacy_menus.extend(dplmc_deserters_menu)
diplomacy_menus.extend(dplmc_chamberlain_confirm_menu)
diplomacy_menus.extend(dplmc_economic_report_menu)
diplomacy_menus.extend(dplmc_auto_loot_menu)
diplomacy_menus.extend(dplmc_riot_negotiate_menu)
diplomacy_menus.extend(dplmc_manage_loot_pool_menu)
diplomacy_menus.extend(dplmc_negotiate_besieger_menu)
diplomacy_menus.extend(dplmc_affiliated_family_report_menu)
diplomacy_menus.extend(dplmc_notification_appoint_chancellor_menu)
diplomacy_menus.extend(dplmc_domestic_policy_menu)
diplomacy_menus.extend(dplmc_notification_alliance_declared_menu)
diplomacy_menus.extend(dplmc_trade_auto_buy_food_begin_menu)
diplomacy_menus.extend(dplmc_deny_terms_menu)
diplomacy_menus.extend(dplmc_notification_trade_declared_menu)
diplomacy_menus.extend(dplmc_village_riot_result_menu)
diplomacy_menus.extend(dplmc_question_trade_offer_menu)
diplomacy_menus.extend(dplmc_notification_trade_expired_menu)
diplomacy_menus.extend(dplmc_village_riot_removed_menu)
diplomacy_menus.extend(dplmc_messenger_menu)
diplomacy_menus.extend(dplmc_preferences_menu)
diplomacy_menus.extend(dplmc_notification_nonaggression_declared_menu)
diplomacy_menus.extend(dplmc_town_riot_removed_menu)
diplomacy_menus.extend(dplmc_question_defensive_offer_menu)
diplomacy_menus.extend(dplmc_notification_alliance_expired_menu)
diplomacy_menus.extend(give_center_to_player_2_menu)
diplomacy_menus.extend(dplmc_choose_disguise_menu)
diplomacy_menus.extend(oath_fulfilled_menu)
diplomacy_menus.extend(dplmc_trade_auto_sell_begin_menu)
diplomacy_menus.extend(dplmc_question_alliance_offer_menu)

